import typing, abc
from Avalonia.Layout import Layoutable, HorizontalAlignment, VerticalAlignment
from Avalonia.Styling import ThemeVariant, Styles, ControlTheme
from Avalonia import Rect, Size, Thickness, StyledElement, RelativePoint, AvaloniaObject, AvaloniaProperty
from Avalonia.Controls import Classes, IResourceDictionary
from Avalonia.Media import Geometry, IEffect, FlowDirection, IBrush, ITransform
from Avalonia.Animation import Transitions
from System import EventHandler_1, Delegate, IObservable_1, ValueTuple_2, IDisposable, Action_2, EventArgs
from Avalonia.Data import IndexerDescriptor, IBinding

class Interactive(Layoutable):
    def __init__(self) -> None: ...
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DesiredSize(self) -> Size: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    def RaiseEvent(self, e: RoutedEventArgs) -> None: ...
    # Skipped AddHandler due to it being static, abstract and generic.

    AddHandler : AddHandler_MethodGroup
    class AddHandler_MethodGroup:
        def __getitem__(self, t:typing.Type[AddHandler_1_T1]) -> AddHandler_1[AddHandler_1_T1]: ...

        AddHandler_1_T1 = typing.TypeVar('AddHandler_1_T1')
        class AddHandler_1(typing.Generic[AddHandler_1_T1]):
            AddHandler_1_TEventArgs = Interactive.AddHandler_MethodGroup.AddHandler_1_T1
            def __call__(self, routedEvent: RoutedEvent_1[AddHandler_1_TEventArgs], handler: EventHandler_1[AddHandler_1_TEventArgs], routes: RoutingStrategies = ..., handledEventsToo: bool = ...) -> None:...

        def __call__(self, routedEvent: RoutedEvent, handler: Delegate, routes: RoutingStrategies = ..., handledEventsToo: bool = ...) -> None:...

    # Skipped RemoveHandler due to it being static, abstract and generic.

    RemoveHandler : RemoveHandler_MethodGroup
    class RemoveHandler_MethodGroup:
        def __getitem__(self, t:typing.Type[RemoveHandler_1_T1]) -> RemoveHandler_1[RemoveHandler_1_T1]: ...

        RemoveHandler_1_T1 = typing.TypeVar('RemoveHandler_1_T1')
        class RemoveHandler_1(typing.Generic[RemoveHandler_1_T1]):
            RemoveHandler_1_TEventArgs = Interactive.RemoveHandler_MethodGroup.RemoveHandler_1_T1
            def __call__(self, routedEvent: RoutedEvent_1[RemoveHandler_1_TEventArgs], handler: EventHandler_1[RemoveHandler_1_TEventArgs]) -> None:...

        def __call__(self, routedEvent: RoutedEvent, handler: Delegate) -> None:...

    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class RoutedEvent_GenericClasses(abc.ABCMeta):
    Generic_RoutedEvent_GenericClasses_RoutedEvent_1_TEventArgs = typing.TypeVar('Generic_RoutedEvent_GenericClasses_RoutedEvent_1_TEventArgs')
    def __getitem__(self, types : typing.Type[Generic_RoutedEvent_GenericClasses_RoutedEvent_1_TEventArgs]) -> typing.Type[RoutedEvent_1[Generic_RoutedEvent_GenericClasses_RoutedEvent_1_TEventArgs]]: ...

class RoutedEvent(RoutedEvent_0, metaclass =RoutedEvent_GenericClasses): ...

class RoutedEvent_0:
    def __init__(self, name: str, routingStrategies: RoutingStrategies, eventArgsType: typing.Type[typing.Any], ownerType: typing.Type[typing.Any]) -> None: ...
    @property
    def EventArgsType(self) -> typing.Type[typing.Any]: ...
    @property
    def HasRaisedSubscriptions(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def OwnerType(self) -> typing.Type[typing.Any]: ...
    @property
    def Raised(self) -> IObservable_1[ValueTuple_2[typing.Any, RoutedEventArgs]]: ...
    @property
    def RouteFinished(self) -> IObservable_1[RoutedEventArgs]: ...
    @property
    def RoutingStrategies(self) -> RoutingStrategies: ...
    def AddClassHandler(self, targetType: typing.Type[typing.Any], handler: EventHandler_1[RoutedEventArgs], routes: RoutingStrategies = ..., handledEventsToo: bool = ...) -> IDisposable: ...
    # Skipped Register due to it being static, abstract and generic.

    Register : Register_MethodGroup
    class Register_MethodGroup:
        @typing.overload
        def __getitem__(self, t:typing.Tuple[typing.Type[Register_2_T1], typing.Type[Register_2_T2]]) -> Register_2[Register_2_T1, Register_2_T2]: ...

        Register_2_T1 = typing.TypeVar('Register_2_T1')
        Register_2_T2 = typing.TypeVar('Register_2_T2')
        class Register_2(typing.Generic[Register_2_T1, Register_2_T2]):
            Register_2_TOwner = RoutedEvent_0.Register_MethodGroup.Register_2_T1
            Register_2_TEventArgs = RoutedEvent_0.Register_MethodGroup.Register_2_T2
            def __call__(self, name: str, routingStrategy: RoutingStrategies) -> RoutedEvent_1[Register_2_TEventArgs]:...

        @typing.overload
        def __getitem__(self, t:typing.Type[Register_1_T1]) -> Register_1[Register_1_T1]: ...

        Register_1_T1 = typing.TypeVar('Register_1_T1')
        class Register_1(typing.Generic[Register_1_T1]):
            Register_1_TEventArgs = RoutedEvent_0.Register_MethodGroup.Register_1_T1
            def __call__(self, name: str, routingStrategy: RoutingStrategies, ownerType: typing.Type[typing.Any]) -> RoutedEvent_1[Register_1_TEventArgs]:...




RoutedEvent_1_TEventArgs = typing.TypeVar('RoutedEvent_1_TEventArgs')
class RoutedEvent_1(typing.Generic[RoutedEvent_1_TEventArgs], RoutedEvent_0):
    def __init__(self, name: str, routingStrategies: RoutingStrategies, ownerType: typing.Type[typing.Any]) -> None: ...
    @property
    def EventArgsType(self) -> typing.Type[typing.Any]: ...
    @property
    def HasRaisedSubscriptions(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def OwnerType(self) -> typing.Type[typing.Any]: ...
    @property
    def Raised(self) -> IObservable_1[ValueTuple_2[typing.Any, RoutedEventArgs]]: ...
    @property
    def RouteFinished(self) -> IObservable_1[RoutedEventArgs]: ...
    @property
    def RoutingStrategies(self) -> RoutingStrategies: ...
    # Skipped AddClassHandler due to it being static, abstract and generic.

    AddClassHandler : AddClassHandler_MethodGroup[RoutedEvent_1_TEventArgs]
    AddClassHandler_MethodGroup_RoutedEvent_1_TEventArgs = typing.TypeVar('AddClassHandler_MethodGroup_RoutedEvent_1_TEventArgs')
    class AddClassHandler_MethodGroup(typing.Generic[AddClassHandler_MethodGroup_RoutedEvent_1_TEventArgs]):
        AddClassHandler_MethodGroup_RoutedEvent_1_TEventArgs = RoutedEvent_1.AddClassHandler_MethodGroup_RoutedEvent_1_TEventArgs
        def __getitem__(self, t:typing.Type[AddClassHandler_1_T1]) -> AddClassHandler_1[AddClassHandler_MethodGroup_RoutedEvent_1_TEventArgs, AddClassHandler_1_T1]: ...

        AddClassHandler_1_RoutedEvent_1_TEventArgs = typing.TypeVar('AddClassHandler_1_RoutedEvent_1_TEventArgs')
        AddClassHandler_1_T1 = typing.TypeVar('AddClassHandler_1_T1')
        class AddClassHandler_1(typing.Generic[AddClassHandler_1_RoutedEvent_1_TEventArgs, AddClassHandler_1_T1]):
            AddClassHandler_1_RoutedEvent_1_TEventArgs = RoutedEvent_1.AddClassHandler_MethodGroup.AddClassHandler_1_RoutedEvent_1_TEventArgs
            AddClassHandler_1_TTarget = RoutedEvent_1.AddClassHandler_MethodGroup.AddClassHandler_1_T1
            def __call__(self, handler: Action_2[AddClassHandler_1_TTarget, AddClassHandler_1_RoutedEvent_1_TEventArgs], routes: RoutingStrategies = ..., handledEventsToo: bool = ...) -> IDisposable:...




class RoutedEventArgs(EventArgs):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, routedEvent: RoutedEvent) -> None: ...
    @typing.overload
    def __init__(self, routedEvent: RoutedEvent, source: typing.Any) -> None: ...
    @property
    def Handled(self) -> bool: ...
    @Handled.setter
    def Handled(self, value: bool) -> bool: ...
    @property
    def Route(self) -> RoutingStrategies: ...
    @Route.setter
    def Route(self, value: RoutingStrategies) -> RoutingStrategies: ...
    @property
    def RoutedEvent(self) -> RoutedEvent: ...
    @RoutedEvent.setter
    def RoutedEvent(self, value: RoutedEvent) -> RoutedEvent: ...
    @property
    def Source(self) -> typing.Any: ...
    @Source.setter
    def Source(self, value: typing.Any) -> typing.Any: ...


class RoutingStrategies(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Direct : RoutingStrategies # 1
    Tunnel : RoutingStrategies # 2
    Bubble : RoutingStrategies # 4

