import typing
from System.Collections.Generic import IReadOnlyList_1
from Avalonia.Utilities import ImmutableReadOnlyListStructEnumerator_1
from System import Uri

class FamilyNameCollection(IReadOnlyList_1[str]):
    def __init__(self, familyNames: str) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def HasFallbacks(self) -> bool: ...
    @property
    def PrimaryFamilyName(self) -> str: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetEnumerator(self) -> ImmutableReadOnlyListStructEnumerator_1[str]: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, a: FamilyNameCollection, b: FamilyNameCollection) -> bool: ...
    def __ne__(self, a: FamilyNameCollection, b: FamilyNameCollection) -> bool: ...
    def ToString(self) -> str: ...
    def __getitem__(self, index: int) -> str: ...


class FontFamilyKey:
    def __init__(self, source: Uri, baseUri: Uri = ...) -> None: ...
    @property
    def BaseUri(self) -> Uri: ...
    @property
    def Source(self) -> Uri: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, a: FontFamilyKey, b: FontFamilyKey) -> bool: ...
    def __ne__(self, a: FontFamilyKey, b: FontFamilyKey) -> bool: ...
    def ToString(self) -> str: ...

