"""
This type stub file was generated by pyright.
"""


""" Classes and metaclasses for easier ``__slots__`` handling.  """
__version__ = ...
__all__ = ["Slots", "SlotsMeta", "SlotsPlusDict", "SlotsPlusDictMeta"]
def assignments_to_self(method) -> set:
    """Given a method, collect all the attribute names for assignments
    to "self"."""
    ...

class SlotsMeta(type):
    def __new__(mcs, name, bases, ns): # -> Self:
        ...



class Slots(metaclass=SlotsMeta):
    ...


def super_has_dict(cls): # -> bool:
    ...

class SlotsPlusDictMeta(SlotsMeta):
    def __new__(mcs, name, bases, ns): # -> Self:
        ...



class SlotsPlusDict(metaclass=SlotsPlusDictMeta):
    ...


