import typing, clr, abc
from System.Collections.Generic import List_1
from JAStudio.Core.Note import KanjiNote, VocabNote, SentenceNote, NoteServices
from JAStudio.Core.TaskRunners import TaskRunner
from System import IEquatable_1

class AllNotesData:
    def __init__(self, kanji: List_1[KanjiNote], vocab: List_1[VocabNote], sentences: List_1[SentenceNote]) -> None: ...
    @property
    def Kanji(self) -> List_1[KanjiNote]: ...
    @property
    def Sentences(self) -> List_1[SentenceNote]: ...
    @property
    def Vocab(self) -> List_1[VocabNote]: ...


class FileSystemNoteRepository(INoteRepository):
    def __init__(self, serializer: NoteSerializer, taskRunner: TaskRunner, rootDir: str) -> None: ...
    @property
    def Serializer(self) -> NoteSerializer: ...
    def LoadAll(self) -> AllNotesData: ...
    def LoadAllSingleFile(self) -> AllNotesData: ...
    def SaveAll(self, data: AllNotesData) -> None: ...
    def SaveAllSingleFile(self, data: AllNotesData) -> None: ...
    def ScanFiles(self) -> FileSystemNoteRepository.NoteFilesByType: ...
    # Skipped Save due to it being static, abstract and generic.

    Save : Save_MethodGroup
    class Save_MethodGroup:
        @typing.overload
        def __call__(self, note: KanjiNote) -> None:...
        @typing.overload
        def __call__(self, note: VocabNote) -> None:...
        @typing.overload
        def __call__(self, note: SentenceNote) -> None:...


    class NoteFilesByType(IEquatable_1[FileSystemNoteRepository.NoteFilesByType]):
        def __init__(self, Kanji: List_1[str], Vocab: List_1[str], Sentences: List_1[str]) -> None: ...
        @property
        def Kanji(self) -> List_1[str]: ...
        @Kanji.setter
        def Kanji(self, value: List_1[str]) -> List_1[str]: ...
        @property
        def Sentences(self) -> List_1[str]: ...
        @Sentences.setter
        def Sentences(self, value: List_1[str]) -> List_1[str]: ...
        @property
        def Vocab(self) -> List_1[str]: ...
        @Vocab.setter
        def Vocab(self, value: List_1[str]) -> List_1[str]: ...
        def Deconstruct(self, Kanji: clr.Reference[List_1[str]], Vocab: clr.Reference[List_1[str]], Sentences: clr.Reference[List_1[str]]) -> None: ...
        def GetHashCode(self) -> int: ...
        def __eq__(self, left: FileSystemNoteRepository.NoteFilesByType, right: FileSystemNoteRepository.NoteFilesByType) -> bool: ...
        def __ne__(self, left: FileSystemNoteRepository.NoteFilesByType, right: FileSystemNoteRepository.NoteFilesByType) -> bool: ...
        def ToString(self) -> str: ...
        # Skipped Equals due to it being static, abstract and generic.

        Equals : Equals_MethodGroup
        class Equals_MethodGroup:
            @typing.overload
            def __call__(self, other: FileSystemNoteRepository.NoteFilesByType) -> bool:...
            @typing.overload
            def __call__(self, obj: typing.Any) -> bool:...




class InMemoryNoteRepository(INoteRepository):
    def __init__(self) -> None: ...
    def LoadAll(self) -> AllNotesData: ...
    # Skipped Save due to it being static, abstract and generic.

    Save : Save_MethodGroup
    class Save_MethodGroup:
        @typing.overload
        def __call__(self, note: KanjiNote) -> None:...
        @typing.overload
        def __call__(self, note: VocabNote) -> None:...
        @typing.overload
        def __call__(self, note: SentenceNote) -> None:...



class INoteRepository(typing.Protocol):
    @abc.abstractmethod
    def LoadAll(self) -> AllNotesData: ...
    # Skipped Save due to it being static, abstract and generic.

    Save : Save_MethodGroup
    class Save_MethodGroup:
        @typing.overload
        def __call__(self, note: KanjiNote) -> None:...
        @typing.overload
        def __call__(self, note: VocabNote) -> None:...
        @typing.overload
        def __call__(self, note: SentenceNote) -> None:...



class NoteSerializer:
    def __init__(self, noteServices: NoteServices) -> None: ...
    def DeserializeAll(self, json: str) -> AllNotesData: ...
    def DeserializeKanji(self, json: str) -> KanjiNote: ...
    def DeserializeSentence(self, json: str) -> SentenceNote: ...
    def DeserializeVocab(self, json: str) -> VocabNote: ...
    # Skipped Serialize due to it being static, abstract and generic.

    Serialize : Serialize_MethodGroup
    class Serialize_MethodGroup:
        @typing.overload
        def __call__(self, note: KanjiNote) -> str:...
        @typing.overload
        def __call__(self, note: VocabNote) -> str:...
        @typing.overload
        def __call__(self, note: SentenceNote) -> str:...
        @typing.overload
        def __call__(self, data: AllNotesData) -> str:...


