import typing
from System.Collections.Generic import List_1
from JAStudio.Core.Note import KanjiNote, VocabNote, SentenceNote, NoteId, NoteServices

class AllNotesData:
    def __init__(self, kanji: List_1[KanjiNote], vocab: List_1[VocabNote], sentences: List_1[SentenceNote]) -> None: ...
    @property
    def Kanji(self) -> List_1[KanjiNote]: ...
    @property
    def Sentences(self) -> List_1[SentenceNote]: ...
    @property
    def Vocab(self) -> List_1[VocabNote]: ...


class FileSystemNoteRepository:
    def __init__(self, serializer: NoteSerializer, rootDir: str) -> None: ...
    def LoadAll(self) -> AllNotesData: ...
    def LoadAllSingleFile(self) -> AllNotesData: ...
    def LoadKanji(self, id: NoteId) -> KanjiNote: ...
    def LoadSentence(self, id: NoteId) -> SentenceNote: ...
    def LoadVocab(self, id: NoteId) -> VocabNote: ...
    def SaveAll(self, data: AllNotesData) -> None: ...
    def SaveAllSingleFile(self, data: AllNotesData) -> None: ...
    def SaveKanji(self, note: KanjiNote) -> None: ...
    def SaveSentence(self, note: SentenceNote) -> None: ...
    def SaveVocab(self, note: VocabNote) -> None: ...


class NoteSerializer:
    def __init__(self, noteServices: NoteServices) -> None: ...
    def DeserializeAll(self, json: str) -> AllNotesData: ...
    def DeserializeKanji(self, json: str) -> KanjiNote: ...
    def DeserializeSentence(self, json: str) -> SentenceNote: ...
    def DeserializeVocab(self, json: str) -> VocabNote: ...
    # Skipped Serialize due to it being static, abstract and generic.

    Serialize : Serialize_MethodGroup
    class Serialize_MethodGroup:
        @typing.overload
        def __call__(self, note: KanjiNote) -> str:...
        @typing.overload
        def __call__(self, note: VocabNote) -> str:...
        @typing.overload
        def __call__(self, note: SentenceNote) -> str:...
        @typing.overload
        def __call__(self, data: AllNotesData) -> str:...


