import typing, clr, abc
from System.Collections.Generic import List_1
from JAStudio.Core.Note import KanjiNote, NoteServices
from JAStudio.Core.Note.Vocabulary import VocabNote
from JAStudio.Core.Note.Sentences import SentenceNote
from JAStudio.Core.TaskRunners import TaskRunner, BackgroundTaskManager
from JAStudio.Core import IEnvironmentPaths
from System import Guid, IEquatable_1, DateTime
from System.Text.Json import JsonSerializerOptions

class AllNotesData:
    def __init__(self, kanji: List_1[KanjiNote], vocab: List_1[VocabNote], sentences: List_1[SentenceNote]) -> None: ...
    @property
    def Kanji(self) -> List_1[KanjiNote]: ...
    @property
    def Sentences(self) -> List_1[SentenceNote]: ...
    @property
    def Vocab(self) -> List_1[VocabNote]: ...


class FileSystemNoteRepository(INoteRepository):
    @typing.overload
    def __init__(self, serializer: NoteSerializer, taskRunner: TaskRunner, backgroundTaskManager: BackgroundTaskManager, paths: IEnvironmentPaths) -> None: ...
    @typing.overload
    def __init__(self, serializer: NoteSerializer, taskRunner: TaskRunner, backgroundTaskManager: BackgroundTaskManager, rootDir: str) -> None: ...
    def LoadAll(self) -> AllNotesData: ...
    def LoadSnapshot(self) -> AllNotesData: ...
    def SaveAll(self, data: AllNotesData) -> None: ...
    def SaveSnapshot(self, data: AllNotesData) -> None: ...
    # Skipped Save due to it being static, abstract and generic.

    Save : Save_MethodGroup
    class Save_MethodGroup:
        @typing.overload
        def __call__(self, note: KanjiNote) -> None:...
        @typing.overload
        def __call__(self, note: VocabNote) -> None:...
        @typing.overload
        def __call__(self, note: SentenceNote) -> None:...



class IIdentifiableByGuid(typing.Protocol):
    @property
    def Id(self) -> Guid: ...


class INoteRepository(typing.Protocol):
    @abc.abstractmethod
    def LoadAll(self) -> AllNotesData: ...
    # Skipped Save due to it being static, abstract and generic.

    Save : Save_MethodGroup
    class Save_MethodGroup:
        @typing.overload
        def __call__(self, note: KanjiNote) -> None:...
        @typing.overload
        def __call__(self, note: VocabNote) -> None:...
        @typing.overload
        def __call__(self, note: SentenceNote) -> None:...



class JsonFilesystemObjectRepository_GenericClasses(abc.ABCMeta):
    Generic_JsonFilesystemObjectRepository_GenericClasses_JsonFilesystemObjectRepository_1_TData = typing.TypeVar('Generic_JsonFilesystemObjectRepository_GenericClasses_JsonFilesystemObjectRepository_1_TData')
    def __getitem__(self, types : typing.Type[Generic_JsonFilesystemObjectRepository_GenericClasses_JsonFilesystemObjectRepository_1_TData]) -> typing.Type[JsonFilesystemObjectRepository_1[Generic_JsonFilesystemObjectRepository_GenericClasses_JsonFilesystemObjectRepository_1_TData]]: ...

JsonFilesystemObjectRepository : JsonFilesystemObjectRepository_GenericClasses

JsonFilesystemObjectRepository_1_TData = typing.TypeVar('JsonFilesystemObjectRepository_1_TData')
class JsonFilesystemObjectRepository_1(typing.Generic[JsonFilesystemObjectRepository_1_TData]):
    def __init__(self, directory: str, jsonOptions: JsonSerializerOptions) -> None: ...
    def LoadAll(self) -> List_1[JsonFilesystemObjectRepository_1_TData]: ...
    def LoadSnapshot(self) -> List_1[JsonFilesystemObjectRepository_1_TData]: ...
    def Save(self, data: JsonFilesystemObjectRepository_1_TData) -> None: ...
    def SaveSnapshot(self, data: List_1[JsonFilesystemObjectRepository_1_TData]) -> None: ...
    def ScanFiles(self) -> List_1[JsonFilesystemObjectRepository_1.ScannedFile_1[JsonFilesystemObjectRepository_1_TData]]: ...

    ScannedFile_GenericClasses_JsonFilesystemObjectRepository_1_TData = typing.TypeVar('ScannedFile_GenericClasses_JsonFilesystemObjectRepository_1_TData')
    class ScannedFile_GenericClasses(typing.Generic[ScannedFile_GenericClasses_JsonFilesystemObjectRepository_1_TData], abc.ABCMeta):
        ScannedFile_GenericClasses_JsonFilesystemObjectRepository_1_TData = JsonFilesystemObjectRepository_1.ScannedFile_GenericClasses_JsonFilesystemObjectRepository_1_TData
        def __call__(self) -> JsonFilesystemObjectRepository_1.ScannedFile_1[ScannedFile_GenericClasses_JsonFilesystemObjectRepository_1_TData]: ...

    ScannedFile : ScannedFile_GenericClasses[JsonFilesystemObjectRepository_1_TData]

    ScannedFile_1_TData = typing.TypeVar('ScannedFile_1_TData')
    class ScannedFile_1(typing.Generic[ScannedFile_1_TData], IEquatable_1[JsonFilesystemObjectRepository_1.ScannedFile_1[ScannedFile_1_TData]]):
        ScannedFile_1_TData = JsonFilesystemObjectRepository_1.ScannedFile_1_TData
        def __init__(self, Path: str, Id: Guid, LastWriteUtc: DateTime) -> None: ...
        @property
        def Id(self) -> Guid: ...
        @Id.setter
        def Id(self, value: Guid) -> Guid: ...
        @property
        def LastWriteUtc(self) -> DateTime: ...
        @LastWriteUtc.setter
        def LastWriteUtc(self, value: DateTime) -> DateTime: ...
        @property
        def Path(self) -> str: ...
        @Path.setter
        def Path(self, value: str) -> str: ...
        def Deconstruct(self, Path: clr.Reference[str], Id: clr.Reference[Guid], LastWriteUtc: clr.Reference[DateTime]) -> None: ...
        def GetHashCode(self) -> int: ...
        def __eq__(self, left: JsonFilesystemObjectRepository_1.ScannedFile_1[ScannedFile_1_TData], right: JsonFilesystemObjectRepository_1.ScannedFile_1[ScannedFile_1_TData]) -> bool: ...
        def __ne__(self, left: JsonFilesystemObjectRepository_1.ScannedFile_1[ScannedFile_1_TData], right: JsonFilesystemObjectRepository_1.ScannedFile_1[ScannedFile_1_TData]) -> bool: ...
        def ToString(self) -> str: ...
        # Skipped Equals due to it being static, abstract and generic.

        Equals : Equals_MethodGroup[ScannedFile_1_TData]
        Equals_MethodGroup_ScannedFile_1_TData = typing.TypeVar('Equals_MethodGroup_ScannedFile_1_TData')
        class Equals_MethodGroup(typing.Generic[Equals_MethodGroup_ScannedFile_1_TData]):
            Equals_MethodGroup_ScannedFile_1_TData = JsonFilesystemObjectRepository_1.ScannedFile_1.Equals_MethodGroup_ScannedFile_1_TData
            @typing.overload
            def __call__(self, other: JsonFilesystemObjectRepository_1.ScannedFile_1[Equals_MethodGroup_ScannedFile_1_TData]) -> bool:...
            @typing.overload
            def __call__(self, obj: typing.Any) -> bool:...




class NoteSerializer:
    def __init__(self, noteServices: NoteServices) -> None: ...
    def DeserializeAll(self, json: str) -> AllNotesData: ...
    def DeserializeKanji(self, json: str) -> KanjiNote: ...
    def DeserializeSentence(self, json: str) -> SentenceNote: ...
    def DeserializeVocab(self, json: str) -> VocabNote: ...
    # Skipped Serialize due to it being static, abstract and generic.

    Serialize : Serialize_MethodGroup
    class Serialize_MethodGroup:
        @typing.overload
        def __call__(self, note: KanjiNote) -> str:...
        @typing.overload
        def __call__(self, note: VocabNote) -> str:...
        @typing.overload
        def __call__(self, note: SentenceNote) -> str:...
        @typing.overload
        def __call__(self, data: AllNotesData) -> str:...


