import abc
from System.Collections.Generic import List_1

class AnkiFacade(abc.ABC):
    @staticmethod
    def ConvertImmersionKitSentences() -> None: ...
    @staticmethod
    def ExecuteLookup(query: str) -> None: ...
    @staticmethod
    def ExecuteLookupAndShowPreviewer(query: str) -> None: ...
    @staticmethod
    def GetNoteIdFromCardId(cardId: int) -> int: ...
    @staticmethod
    def PrioritizeCards(cardIds: List_1[int]) -> None: ...
    @staticmethod
    def Refresh() -> None: ...
    @staticmethod
    def ShowTooltip(message: str, periodMs: int = ...) -> None: ...
    @staticmethod
    def SpreadCardsOverDays(cardIds: List_1[int], startDay: int, daysApart: int) -> None: ...
    @staticmethod
    def SuspendAllCardsForNote(noteId: int) -> None: ...
    @staticmethod
    def UnsuspendAllCardsForNote(noteId: int) -> None: ...

