import abc

class AnkiFacade(abc.ABC):
    @staticmethod
    def ConvertImmersionKitSentences() -> None: ...
    @staticmethod
    def ExecuteLookup(query: str) -> None: ...
    @staticmethod
    def Refresh() -> None: ...
    @staticmethod
    def ShowTooltip(message: str, periodMs: int = ...) -> None: ...

