import typing, abc
from System.Threading.Tasks import Task, Task_1
from System import Array_1
from Avalonia.Input import IDataObject, KeyModifiers, KeyGesture
from System.Collections.Generic import List_1

class IClipboard(typing.Protocol):
    @abc.abstractmethod
    def ClearAsync(self) -> Task: ...
    @abc.abstractmethod
    def GetDataAsync(self, format: str) -> Task_1[typing.Any]: ...
    @abc.abstractmethod
    def GetFormatsAsync(self) -> Task_1[Array_1[str]]: ...
    @abc.abstractmethod
    def GetTextAsync(self) -> Task_1[str]: ...
    @abc.abstractmethod
    def SetDataObjectAsync(self, data: IDataObject) -> Task: ...
    @abc.abstractmethod
    def SetTextAsync(self, text: str) -> Task: ...


class PlatformHotkeyConfiguration:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, commandModifiers: KeyModifiers, selectionModifiers: KeyModifiers = ..., wholeWordTextActionModifiers: KeyModifiers = ...) -> None: ...
    @property
    def Back(self) -> List_1[KeyGesture]: ...
    @Back.setter
    def Back(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def CommandModifiers(self) -> KeyModifiers: ...
    @CommandModifiers.setter
    def CommandModifiers(self, value: KeyModifiers) -> KeyModifiers: ...
    @property
    def Copy(self) -> List_1[KeyGesture]: ...
    @Copy.setter
    def Copy(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def Cut(self) -> List_1[KeyGesture]: ...
    @Cut.setter
    def Cut(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def MoveCursorToTheEndOfDocument(self) -> List_1[KeyGesture]: ...
    @MoveCursorToTheEndOfDocument.setter
    def MoveCursorToTheEndOfDocument(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def MoveCursorToTheEndOfDocumentWithSelection(self) -> List_1[KeyGesture]: ...
    @MoveCursorToTheEndOfDocumentWithSelection.setter
    def MoveCursorToTheEndOfDocumentWithSelection(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def MoveCursorToTheEndOfLine(self) -> List_1[KeyGesture]: ...
    @MoveCursorToTheEndOfLine.setter
    def MoveCursorToTheEndOfLine(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def MoveCursorToTheEndOfLineWithSelection(self) -> List_1[KeyGesture]: ...
    @MoveCursorToTheEndOfLineWithSelection.setter
    def MoveCursorToTheEndOfLineWithSelection(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def MoveCursorToTheStartOfDocument(self) -> List_1[KeyGesture]: ...
    @MoveCursorToTheStartOfDocument.setter
    def MoveCursorToTheStartOfDocument(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def MoveCursorToTheStartOfDocumentWithSelection(self) -> List_1[KeyGesture]: ...
    @MoveCursorToTheStartOfDocumentWithSelection.setter
    def MoveCursorToTheStartOfDocumentWithSelection(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def MoveCursorToTheStartOfLine(self) -> List_1[KeyGesture]: ...
    @MoveCursorToTheStartOfLine.setter
    def MoveCursorToTheStartOfLine(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def MoveCursorToTheStartOfLineWithSelection(self) -> List_1[KeyGesture]: ...
    @MoveCursorToTheStartOfLineWithSelection.setter
    def MoveCursorToTheStartOfLineWithSelection(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def OpenContextMenu(self) -> List_1[KeyGesture]: ...
    @OpenContextMenu.setter
    def OpenContextMenu(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def PageDown(self) -> List_1[KeyGesture]: ...
    @PageDown.setter
    def PageDown(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def PageLeft(self) -> List_1[KeyGesture]: ...
    @PageLeft.setter
    def PageLeft(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def PageRight(self) -> List_1[KeyGesture]: ...
    @PageRight.setter
    def PageRight(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def PageUp(self) -> List_1[KeyGesture]: ...
    @PageUp.setter
    def PageUp(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def Paste(self) -> List_1[KeyGesture]: ...
    @Paste.setter
    def Paste(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def Redo(self) -> List_1[KeyGesture]: ...
    @Redo.setter
    def Redo(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def SelectAll(self) -> List_1[KeyGesture]: ...
    @SelectAll.setter
    def SelectAll(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def SelectionModifiers(self) -> KeyModifiers: ...
    @SelectionModifiers.setter
    def SelectionModifiers(self, value: KeyModifiers) -> KeyModifiers: ...
    @property
    def Undo(self) -> List_1[KeyGesture]: ...
    @Undo.setter
    def Undo(self, value: List_1[KeyGesture]) -> List_1[KeyGesture]: ...
    @property
    def WholeWordTextActionModifiers(self) -> KeyModifiers: ...
    @WholeWordTextActionModifiers.setter
    def WholeWordTextActionModifiers(self, value: KeyModifiers) -> KeyModifiers: ...

