import typing, abc
from System.Collections import IList
from System.Collections.Generic import IEnumerable_1, IEnumerator_1, List_1, IList_1, IReadOnlyList_1
from System import Array_1, Action_1
from System.ComponentModel import INotifyPropertyChanged
from System.Collections.Specialized import INotifyCollectionChanged

class AvaloniaList_GenericClasses(abc.ABCMeta):
    Generic_AvaloniaList_GenericClasses_AvaloniaList_1_T = typing.TypeVar('Generic_AvaloniaList_GenericClasses_AvaloniaList_1_T')
    def __getitem__(self, types : typing.Type[Generic_AvaloniaList_GenericClasses_AvaloniaList_1_T]) -> typing.Type[AvaloniaList_1[Generic_AvaloniaList_GenericClasses_AvaloniaList_1_T]]: ...

AvaloniaList : AvaloniaList_GenericClasses

AvaloniaList_1_T = typing.TypeVar('AvaloniaList_1_T')
class AvaloniaList_1(typing.Generic[AvaloniaList_1_T], IAvaloniaList_1[AvaloniaList_1_T], IList):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, capacity: int) -> None: ...
    @typing.overload
    def __init__(self, items: IEnumerable_1[AvaloniaList_1_T]) -> None: ...
    @typing.overload
    def __init__(self, items: Array_1[AvaloniaList_1_T]) -> None: ...
    @property
    def Capacity(self) -> int: ...
    @Capacity.setter
    def Capacity(self, value: int) -> int: ...
    @property
    def Count(self) -> int: ...
    @property
    def ResetBehavior(self) -> ResetBehavior: ...
    @ResetBehavior.setter
    def ResetBehavior(self, value: ResetBehavior) -> ResetBehavior: ...
    @property
    def Validate(self) -> Action_1[AvaloniaList_1_T]: ...
    @Validate.setter
    def Validate(self, value: Action_1[AvaloniaList_1_T]) -> Action_1[AvaloniaList_1_T]: ...
    def Add(self, item: AvaloniaList_1_T) -> None: ...
    def AddRange(self, items: IEnumerable_1[AvaloniaList_1_T]) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, item: AvaloniaList_1_T) -> bool: ...
    def CopyTo(self, array: Array_1[AvaloniaList_1_T], arrayIndex: int) -> None: ...
    def EnsureCapacity(self, capacity: int) -> None: ...
    def GetEnumerator(self) -> AvaloniaList_1.Enumerator_1[AvaloniaList_1_T]: ...
    def GetRange(self, index: int, count: int) -> IEnumerable_1[AvaloniaList_1_T]: ...
    def IndexOf(self, item: AvaloniaList_1_T) -> int: ...
    def Insert(self, index: int, item: AvaloniaList_1_T) -> None: ...
    def InsertRange(self, index: int, items: IEnumerable_1[AvaloniaList_1_T]) -> None: ...
    def Move(self, oldIndex: int, newIndex: int) -> None: ...
    def MoveRange(self, oldIndex: int, count: int, newIndex: int) -> None: ...
    def Remove(self, item: AvaloniaList_1_T) -> bool: ...
    def RemoveAll(self, items: IEnumerable_1[AvaloniaList_1_T]) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def RemoveRange(self, index: int, count: int) -> None: ...

    Enumerator_GenericClasses_AvaloniaList_1_T = typing.TypeVar('Enumerator_GenericClasses_AvaloniaList_1_T')
    class Enumerator_GenericClasses(typing.Generic[Enumerator_GenericClasses_AvaloniaList_1_T], abc.ABCMeta):
        Enumerator_GenericClasses_AvaloniaList_1_T = AvaloniaList_1.Enumerator_GenericClasses_AvaloniaList_1_T
        def __call__(self) -> AvaloniaList_1.Enumerator_1[Enumerator_GenericClasses_AvaloniaList_1_T]: ...

    Enumerator : Enumerator_GenericClasses[AvaloniaList_1_T]

    Enumerator_1_T = typing.TypeVar('Enumerator_1_T')
    class Enumerator_1(typing.Generic[Enumerator_1_T], IEnumerator_1[Enumerator_1_T]):
        Enumerator_1_T = AvaloniaList_1.Enumerator_1_T
        def __init__(self, inner: List_1[Enumerator_1_T]) -> None: ...
        @property
        def Current(self) -> Enumerator_1_T: ...
        def Dispose(self) -> None: ...
        def MoveNext(self) -> bool: ...

    def __getitem__(self, index: int) -> AvaloniaList_1_T: ...
    def __setitem__(self, index: int, value: AvaloniaList_1_T) -> None: ...


class IAvaloniaList_GenericClasses(abc.ABCMeta):
    Generic_IAvaloniaList_GenericClasses_IAvaloniaList_1_T = typing.TypeVar('Generic_IAvaloniaList_GenericClasses_IAvaloniaList_1_T')
    def __getitem__(self, types : typing.Type[Generic_IAvaloniaList_GenericClasses_IAvaloniaList_1_T]) -> typing.Type[IAvaloniaList_1[Generic_IAvaloniaList_GenericClasses_IAvaloniaList_1_T]]: ...

IAvaloniaList : IAvaloniaList_GenericClasses

IAvaloniaList_1_T = typing.TypeVar('IAvaloniaList_1_T')
class IAvaloniaList_1(typing.Generic[IAvaloniaList_1_T], IAvaloniaReadOnlyList_1[IAvaloniaList_1_T], IList_1[IAvaloniaList_1_T], typing.Protocol):
    @property
    def Count(self) -> int: ...
    @abc.abstractmethod
    def AddRange(self, items: IEnumerable_1[IAvaloniaList_1_T]) -> None: ...
    @abc.abstractmethod
    def InsertRange(self, index: int, items: IEnumerable_1[IAvaloniaList_1_T]) -> None: ...
    @abc.abstractmethod
    def Move(self, oldIndex: int, newIndex: int) -> None: ...
    @abc.abstractmethod
    def MoveRange(self, oldIndex: int, count: int, newIndex: int) -> None: ...
    @abc.abstractmethod
    def RemoveAll(self, items: IEnumerable_1[IAvaloniaList_1_T]) -> None: ...
    @abc.abstractmethod
    def RemoveRange(self, index: int, count: int) -> None: ...
    def __getitem__(self, index: int) -> IAvaloniaList_1_T: ...
    def __setitem__(self, index: int, value: IAvaloniaList_1_T) -> None: ...


class IAvaloniaReadOnlyList_GenericClasses(abc.ABCMeta):
    Generic_IAvaloniaReadOnlyList_GenericClasses_IAvaloniaReadOnlyList_1_T = typing.TypeVar('Generic_IAvaloniaReadOnlyList_GenericClasses_IAvaloniaReadOnlyList_1_T')
    def __getitem__(self, types : typing.Type[Generic_IAvaloniaReadOnlyList_GenericClasses_IAvaloniaReadOnlyList_1_T]) -> typing.Type[IAvaloniaReadOnlyList_1[Generic_IAvaloniaReadOnlyList_GenericClasses_IAvaloniaReadOnlyList_1_T]]: ...

IAvaloniaReadOnlyList : IAvaloniaReadOnlyList_GenericClasses

IAvaloniaReadOnlyList_1_T = typing.TypeVar('IAvaloniaReadOnlyList_1_T', covariant=True)
class IAvaloniaReadOnlyList_1(typing.Generic[IAvaloniaReadOnlyList_1_T], IReadOnlyList_1[IAvaloniaReadOnlyList_1_T], INotifyPropertyChanged, INotifyCollectionChanged, typing.Protocol):
    pass


class ResetBehavior(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Reset : ResetBehavior # 0
    Remove : ResetBehavior # 1

