from System.Collections.Generic import List_1
from JAStudio.Core.Note import KanjiNote

class KanjiListViewModel:
    def __init__(self, kanjiList: List_1[KanjiViewModel]) -> None: ...
    @property
    def KanjiList(self) -> List_1[KanjiViewModel]: ...
    def ToString(self) -> str: ...


class KanjiViewModel:
    def __init__(self, kanji: KanjiNote) -> None: ...
    @property
    def Kanji(self) -> KanjiNote: ...
    def Answer(self) -> str: ...
    def Mnemonic(self) -> str: ...
    def Question(self) -> str: ...
    def Readings(self) -> str: ...
    def ToString(self) -> str: ...


class SentenceKanjiListViewModel:
    @staticmethod
    def Create(kanji: List_1[str]) -> KanjiListViewModel: ...

