from CommunityToolkit.Mvvm.ComponentModel import ObservableObject
from JAStudio.Core.Note.NoteFields import RequireForbidFlagField
from System import Action_1
from CommunityToolkit.Mvvm.Input import IRelayCommand, IAsyncRelayCommand
from System.Collections.Generic import HashSet_1
from Avalonia.Controls import Window
from System.Collections.ObjectModel import ObservableCollection_1

class RequireForbidControlViewModel(ObservableObject):
    def __init__(self, field: RequireForbidFlagField, label: str, reparseTrigger: bool = ...) -> None: ...
    @property
    def GroupName(self) -> str: ...
    @property
    def IsForbidden(self) -> bool: ...
    @IsForbidden.setter
    def IsForbidden(self, value: bool) -> bool: ...
    @property
    def IsRequired(self) -> bool: ...
    @IsRequired.setter
    def IsRequired(self, value: bool) -> bool: ...
    @property
    def IsUnset(self) -> bool: ...
    @IsUnset.setter
    def IsUnset(self, value: bool) -> bool: ...
    @property
    def RepraiseTrigger(self) -> bool: ...
    def HasChanged(self) -> bool: ...


class StringChipViewModel(ObservableObject):
    def __init__(self, value: str, onRemove: Action_1[str]) -> None: ...
    @property
    def RemoveCommand(self) -> IRelayCommand: ...
    @property
    def Value(self) -> str: ...


class StringSetControlViewModel(ObservableObject):
    def __init__(self, backingSet: HashSet_1[str], title: str, parentWindow: Window = ...) -> None: ...
    @property
    def AddCommand(self) -> IAsyncRelayCommand: ...
    @property
    def Items(self) -> ObservableCollection_1[StringChipViewModel]: ...
    @Items.setter
    def Items(self, value: ObservableCollection_1[StringChipViewModel]) -> ObservableCollection_1[StringChipViewModel]: ...
    @property
    def Title(self) -> str: ...
    def HasChanges(self) -> bool: ...

