import typing, abc
from JAStudio.UI.Menus.UIAgnosticMenuStructure import SpecMenuItem
from JAStudio.UI.Menus import JapaneseMainMenu, NoteContextMenu
from JAStudio.Anki import QueryBuilder, AnkiLifecycleEvent
from JAStudio.Core import TemporaryServiceCollection
from System import Action_1, Action
from System.Collections.Generic import IEnumerable_1
from Avalonia.Controls import MenuItem, IResourceDictionary
from Avalonia import Application, AvaloniaProperty
from Avalonia.Styling import ThemeVariant, Styles
from Avalonia.Controls.ApplicationLifetimes import IApplicationLifetime
from Avalonia.Controls.Templates import DataTemplates
from Avalonia.Platform import IPlatformSettings
from Avalonia.Data import IndexerDescriptor, IBinding

class AnkiDialogs:
    def ToggleEnglishWordSearchDialog(self) -> None: ...
    def ToggleNoteSearchDialog(self) -> None: ...


class AnkiMenus:
    def BuildBrowserMenuSpec(self, selectedCardIds: typing.Any, selectedNoteIds: typing.Any) -> SpecMenuItem: ...
    def CreateJapaneseMainMenu(self) -> JapaneseMainMenu: ...
    def CreateNoteContextMenu(self) -> NoteContextMenu: ...
    def ShowContextMenuPopup(self, clipboardContent: str, selectionContent: str, x: int, y: int) -> None: ...


class AnkiServiceExtensions(abc.ABC):
    @staticmethod
    def QueryBuilder(services: TemporaryServiceCollection) -> QueryBuilder: ...


class JAStudioAppRoot:
    @property
    def Dialogs(self) -> AnkiDialogs: ...
    @property
    def Menus(self) -> AnkiMenus: ...
    @property
    def Services(self) -> TemporaryServiceCollection: ...
    def HandleAnkiLifecycleEvent(self, lifecycleEvent: AnkiLifecycleEvent) -> None: ...
    @staticmethod
    def Initialize(configJson: str, configUpdateCallback: Action_1[str]) -> JAStudioAppRoot: ...
    def RunOnUIThread(self, action: Action) -> None: ...
    def Shutdown(self) -> None: ...
    def ShutDown(self) -> None: ...


class PopupMenuHost(abc.ABC):
    @staticmethod
    def ShowAt(menuItems: IEnumerable_1[MenuItem], x: int, y: int) -> None: ...


class UIApp(Application):
    def __init__(self) -> None: ...
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def ApplicationLifetime(self) -> IApplicationLifetime: ...
    @ApplicationLifetime.setter
    def ApplicationLifetime(self, value: IApplicationLifetime) -> IApplicationLifetime: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def PlatformSettings(self) -> IPlatformSettings: ...
    @property
    def RequestedThemeVariant(self) -> ThemeVariant: ...
    @RequestedThemeVariant.setter
    def RequestedThemeVariant(self, value: ThemeVariant) -> ThemeVariant: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def Styles(self) -> Styles: ...
    def Initialize(self) -> None: ...
    def OnFrameworkInitializationCompleted(self) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...

