import typing, abc
from JAStudio.Core import CoreApp, TemporaryServiceCollection
from JAStudio.UI.Menus.UIAgnosticMenuStructure import SpecMenuItem
from System.Collections.Generic import IReadOnlyList_1, IEnumerable_1
from JAStudio.UI.Menus import JapaneseMainMenu, NoteContextMenu
from Avalonia.Controls import MenuItem, IResourceDictionary
from Avalonia import Application, AvaloniaProperty
from Avalonia.Styling import ThemeVariant, Styles
from Avalonia.Controls.ApplicationLifetimes import IApplicationLifetime
from Avalonia.Controls.Templates import DataTemplates
from Avalonia.Platform import IPlatformSettings
from System import TimeSpan
from Avalonia.Data import IndexerDescriptor, IBinding

class AnkiDialogs:
    def __init__(self, coreApp: CoreApp) -> None: ...
    def ToggleEnglishWordSearchDialog(self) -> None: ...
    def ToggleNoteSearchDialog(self) -> None: ...


class AnkiMenus:
    def __init__(self, services: TemporaryServiceCollection) -> None: ...
    def BuildBrowserMenuSpec(self, selectedCardIds: IReadOnlyList_1[int], selectedNoteIds: IReadOnlyList_1[int]) -> SpecMenuItem: ...
    def CreateJapaneseMainMenu(self) -> JapaneseMainMenu: ...
    def CreateNoteContextMenu(self) -> NoteContextMenu: ...
    def ShowContextMenuPopup(self, clipboardContent: str, selectionContent: str, x: int, y: int) -> None: ...


class PopupMenuHost(abc.ABC):
    @staticmethod
    def ShowAt(menuItems: IEnumerable_1[MenuItem], x: int, y: int) -> None: ...


class UIApp(Application):
    def __init__(self) -> None: ...
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def ApplicationLifetime(self) -> IApplicationLifetime: ...
    @ApplicationLifetime.setter
    def ApplicationLifetime(self, value: IApplicationLifetime) -> IApplicationLifetime: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def PlatformSettings(self) -> IPlatformSettings: ...
    @property
    def RequestedThemeVariant(self) -> ThemeVariant: ...
    @RequestedThemeVariant.setter
    def RequestedThemeVariant(self, value: ThemeVariant) -> ThemeVariant: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def Styles(self) -> Styles: ...
    def Initialize(self) -> None: ...
    def OnFrameworkInitializationCompleted(self) -> None: ...
    @staticmethod
    def WaitForInitialization(timeout: TimeSpan) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...

