import typing, abc
from Avalonia import Application, AvaloniaProperty
from Avalonia.Styling import ThemeVariant, Styles
from Avalonia.Controls.ApplicationLifetimes import IApplicationLifetime
from Avalonia.Controls.Templates import DataTemplates
from Avalonia.Platform import IPlatformSettings
from Avalonia.Controls import IResourceDictionary
from Avalonia.Data import IndexerDescriptor, IBinding
from System import Action
from JAStudio.Core.Note import VocabNote

class App(Application):
    def __init__(self) -> None: ...
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def ApplicationLifetime(self) -> IApplicationLifetime: ...
    @ApplicationLifetime.setter
    def ApplicationLifetime(self, value: IApplicationLifetime) -> IApplicationLifetime: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def PlatformSettings(self) -> IPlatformSettings: ...
    @property
    def RequestedThemeVariant(self) -> ThemeVariant: ...
    @RequestedThemeVariant.setter
    def RequestedThemeVariant(self, value: ThemeVariant) -> ThemeVariant: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def Styles(self) -> Styles: ...
    def Initialize(self) -> None: ...
    def OnFrameworkInitializationCompleted(self) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class DialogHost(abc.ABC):
    @staticmethod
    def Initialize() -> None: ...
    @staticmethod
    def RunOnUIThread(action: Action) -> None: ...
    @staticmethod
    def ShowAboutDialog() -> None: ...
    @staticmethod
    def ShowContextMenuPopup(clipboardContent: str, selectionContent: str, x: int, y: int) -> None: ...
    @staticmethod
    def ShowVocabFlagsDialog(vocab: VocabNote) -> None: ...
    @staticmethod
    def Shutdown() -> None: ...
    # Skipped ShowDialog due to it being static, abstract and generic.

    ShowDialog : ShowDialog_MethodGroup
    class ShowDialog_MethodGroup:
        def __getitem__(self, t:typing.Type[ShowDialog_1_T1]) -> ShowDialog_1[ShowDialog_1_T1]: ...

        ShowDialog_1_T1 = typing.TypeVar('ShowDialog_1_T1')
        class ShowDialog_1(typing.Generic[ShowDialog_1_T1]):
            ShowDialog_1_T = DialogHost.ShowDialog_MethodGroup.ShowDialog_1_T1
            def __call__(self) -> None:...



