python -m unidic2ud download kindai
python -m unidic2ud download gendai
python -m unidic2ud download spoken
python -m unidic2ud download kinsei
python -m unidic2ud download novel
python -m unidic2ud download qkana
python -m unidic2ud download kyogen
python -m unidic2ud download wakan
python -m unidic2ud download wabun
python -m unidic2ud download manyo