[tool.ruff]
#int.select = ["E", "F", "TCH"]  # Enable TCH rules along with basic error checking
lint.select = ["E", "F", "B", "I", "TCH"] #

lint.ignore = ["E701"] #E701 multiple statements on one line


line-length = 250