[tool.ruff]
extend-exclude = [
    "_lib",
    "_lib_patched"
]
line-length = 9999
target-version = "py39"

[tool.ruff.lint]

select = [
    "E", # pycodestyle
    "F",# Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I",# isort sorts imports etc
    "TC", # TODO
    "ANN"
]

#select = ["ALL"]

ignore = [
    "E701", #E701 multiple statements on one line,
    "D102", # Missing docstring in public method
    "TC006",# [*] Add quotes to type expression in `typing.cast()`
    "UP007",# Use `X | Y` for type annotations

    #ANN
    #"ANN204", #Missing return type annotation for special method `__init__`" thousands of these. It's just not worth it

    #below here is only needed when ALL is the select value
#    "Q", # rules on how quotes are use...
#    "D", #Docstring rules
#    "W292", # [*] No newline at end of file
]

