[tool.ruff]
extend-exclude = [
    "_lib",
    "_lib_patched"
]
line-length = 9999

[tool.ruff.lint]


select = [
    "E", # pycodestyle
    "F",# Pyflakes
#    "UP", # pyupgrade
#    "B", # flake8-bugbear
#    "SIM", # flake8-simplify
    "I",# isort sorts imports etc
    "TCH" # TODO
]

#lint.select = ["ALL"]

ignore = [
    "E701", #E701 multiple statements on one line,
    "D102", # Missing docstring in public method
    "TC006",# [*] Add quotes to type expression in `typing.cast()`
]

