import typing, abc
from System import Action_1, Func_2, ValueTuple_2, Action
from System.Collections.Generic import List_1, Dictionary_2

class ConfigurationValue_GenericClasses(abc.ABCMeta):
    Generic_ConfigurationValue_GenericClasses_ConfigurationValue_1_T = typing.TypeVar('Generic_ConfigurationValue_GenericClasses_ConfigurationValue_1_T')
    def __getitem__(self, types : typing.Type[Generic_ConfigurationValue_GenericClasses_ConfigurationValue_1_T]) -> typing.Type[ConfigurationValue_1[Generic_ConfigurationValue_GenericClasses_ConfigurationValue_1_T]]: ...

class ConfigurationValue(ConfigurationValue_0, metaclass =ConfigurationValue_GenericClasses): ...

class ConfigurationValue_0(abc.ABC):
    @staticmethod
    def Config() -> JapaneseConfig: ...
    @staticmethod
    def InitJson(json: str, updateCallback: Action_1[str]) -> None: ...
    @staticmethod
    def InitPreviewForTesting() -> None: ...


ConfigurationValue_1_T = typing.TypeVar('ConfigurationValue_1_T')
class ConfigurationValue_1(typing.Generic[ConfigurationValue_1_T]):
    def __init__(self, name: str, title: str, defaultValue: ConfigurationValue_1_T, converter: Func_2[typing.Any, ConfigurationValue_1_T], featureToggler: Action_1[ConfigurationValue_1_T] = ...) -> None: ...
    @property
    def FeatureToggler(self) -> Action_1[ConfigurationValue_1_T]: ...
    @property
    def Name(self) -> str: ...
    @property
    def Title(self) -> str: ...
    def GetValue(self) -> ConfigurationValue_1_T: ...
    def OnChange(self, callback: Action_1[ConfigurationValue_1_T]) -> None: ...
    def SetValue(self, value: ConfigurationValue_1_T) -> None: ...
    def ToggleFeature(self) -> None: ...


class JapaneseConfig:
    def __init__(self) -> None: ...
    @property
    def AnkiInternalFsrsSetEnableFsrsShortTermWithSteps(self) -> ConfigurationValue_1[bool]: ...
    @property
    def AutoadvanceSentenceHiraganaSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceSentenceKanjiSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceSentenceKatakanaSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceSentenceStartingSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceVocabHiraganaSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceVocabKanjiSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceVocabKatakanaSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceVocabStartingSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutomaticallyYieldLastTokenInCausativeVerbCompoundsToOverlappingCompound(self) -> ConfigurationValue_1[bool]: ...
    @property
    def AutomaticallyYieldLastTokenInPassiveVerbCompoundsToOverlappingCompound(self) -> ConfigurationValue_1[bool]: ...
    @property
    def AutomaticallyYieldLastTokenInSuruVerbCompoundsToOverlappingCompound(self) -> ConfigurationValue_1[bool]: ...
    @property
    def BoostFailedCardAllowedTime(self) -> ConfigurationValue_1[bool]: ...
    @property
    def BoostFailedCardAllowedTimeByFactor(self) -> ConfigurationValue_1[float]: ...
    @property
    def DecreaseFailedCardIntervals(self) -> ConfigurationValue_1[bool]: ...
    @property
    def DecreaseFailedCardIntervalsInterval(self) -> ConfigurationValue_1[int]: ...
    @property
    def DeveloperOnlyToggles(self) -> List_1[ConfigurationValue_1[bool]]: ...
    @property
    def DisableAllAutomaticGarbageCollection(self) -> ConfigurationValue_1[bool]: ...
    @property
    def EnableAutomaticGarbageCollection(self) -> ConfigurationValue_1[bool]: ...
    @property
    def EnableAutoStringInterning(self) -> ConfigurationValue_1[bool]: ...
    @property
    def EnableGarbageCollectionDuringBatches(self) -> ConfigurationValue_1[bool]: ...
    @property
    def EnableTraceMalloc(self) -> ConfigurationValue_1[bool]: ...
    @property
    def FeatureToggles(self) -> List_1[ValueTuple_2[str, List_1[ConfigurationValue_1[bool]]]]: ...
    @property
    def HideAllCompounds(self) -> ConfigurationValue_1[bool]: ...
    @property
    def HideCompositionallyTransparentCompounds(self) -> ConfigurationValue_1[bool]: ...
    @property
    def LoadJamdictDbIntoMemory(self) -> ConfigurationValue_1[bool]: ...
    @property
    def LoadStudioInForeground(self) -> ConfigurationValue_1[bool]: ...
    @property
    def LogWhenFlushingNotes(self) -> ConfigurationValue_1[bool]: ...
    @property
    def MinimumTimeViewingAnswer(self) -> ConfigurationValue_1[float]: ...
    @property
    def MinimumTimeViewingQuestion(self) -> ConfigurationValue_1[float]: ...
    @property
    def MiscToggles(self) -> List_1[ConfigurationValue_1[bool]]: ...
    @property
    def PerformanceAndMemoryToggles(self) -> List_1[ConfigurationValue_1[bool]]: ...
    @property
    def PreCacheCardStudyingStatus(self) -> ConfigurationValue_1[bool]: ...
    @property
    def PreferDefaultMnemonicsToSourceMnemonics(self) -> ConfigurationValue_1[bool]: ...
    @property
    def PreventAnkiFromGarbageCollectingEveryTimeAWindowCloses(self) -> ConfigurationValue_1[bool]: ...
    @property
    def PreventDoubleClicks(self) -> ConfigurationValue_1[bool]: ...
    @property
    def ReadingsMappingsDict(self) -> Dictionary_2[str, str]: ...
    @ReadingsMappingsDict.setter
    def ReadingsMappingsDict(self, value: Dictionary_2[str, str]) -> Dictionary_2[str, str]: ...
    @property
    def SentenceViewToggles(self) -> List_1[ConfigurationValue_1[bool]]: ...
    @property
    def ShowCompoundPartsInSentenceBreakdown(self) -> ConfigurationValue_1[bool]: ...
    @property
    def ShowKanjiInSentenceBreakdown(self) -> ConfigurationValue_1[bool]: ...
    @property
    def ShowKanjiMnemonicsInSentenceBreakdown(self) -> ConfigurationValue_1[bool]: ...
    @property
    def ShowSentenceBreakdownInEditMode(self) -> ConfigurationValue_1[bool]: ...
    @property
    def TimeboxKanjiRead(self) -> ConfigurationValue_1[int]: ...
    @property
    def TimeboxSentenceListen(self) -> ConfigurationValue_1[int]: ...
    @property
    def TimeboxSentenceRead(self) -> ConfigurationValue_1[int]: ...
    @property
    def TimeboxVocabListen(self) -> ConfigurationValue_1[int]: ...
    @property
    def TimeboxVocabRead(self) -> ConfigurationValue_1[int]: ...
    @property
    def TrackInstancesInMemory(self) -> ConfigurationValue_1[bool]: ...
    @property
    def YomitanIntegrationCopyAnswerToClipboard(self) -> ConfigurationValue_1[bool]: ...
    def OnChange(self, callback: Action) -> None: ...
    @staticmethod
    def ReadReadingsMappingsFile() -> str: ...
    def SaveMappings(self, mappings: str) -> None: ...
    def SetReadingsMappingsForTesting(self, mappings: str) -> None: ...
    def ToggleAllSentenceDisplayAutoYieldFlags(self, value: typing.Optional[bool] = ...) -> None: ...


class Settings:
    @staticmethod
    def AutomaticallyYieldLastTokenInCausativeVerbCompoundsToOverlappingCompound() -> bool: ...
    @staticmethod
    def AutomaticallyYieldLastTokenInPassiveVerbCompoundsToOverlappingCompound() -> bool: ...
    @staticmethod
    def AutomaticallyYieldLastTokenInSuruVerbCompoundsToOverlappingCompound() -> bool: ...
    @staticmethod
    def HideAllCompounds() -> bool: ...
    @staticmethod
    def HideTransparentCompounds() -> bool: ...
    @staticmethod
    def LogWhenFlushingNotes() -> bool: ...
    @staticmethod
    def ShowBreakdownInEditMode() -> bool: ...
    @staticmethod
    def ShowCompoundPartsInSentenceBreakdown() -> bool: ...
    @staticmethod
    def ShowKanjiInSentenceBreakdown() -> bool: ...
    @staticmethod
    def ShowKanjiMnemonicsInSentenceBreakdown() -> bool: ...

