import typing, abc
from System import Action_1, Func_2, ValueTuple_2, Action
from System.Collections.Generic import Dictionary_2, List_1

class AnkiConfigDictSource(IConfigDictSource):
    def __init__(self, json: str, updateCallback: Action_1[str]) -> None: ...
    def Load(self) -> Dictionary_2[str, typing.Any]: ...
    def Persist(self, json: str) -> None: ...


class ConfigurationStore:
    def Config(self) -> JapaneseConfig: ...
    def GetReadingsMappings(self) -> Dictionary_2[str, str]: ...
    def ReadReadingsMappingsFile(self) -> str: ...
    def SaveMappings(self, mappings: str) -> None: ...


class ConfigurationValue_GenericClasses(abc.ABCMeta):
    Generic_ConfigurationValue_GenericClasses_ConfigurationValue_1_T = typing.TypeVar('Generic_ConfigurationValue_GenericClasses_ConfigurationValue_1_T')
    def __getitem__(self, types : typing.Type[Generic_ConfigurationValue_GenericClasses_ConfigurationValue_1_T]) -> typing.Type[ConfigurationValue_1[Generic_ConfigurationValue_GenericClasses_ConfigurationValue_1_T]]: ...

ConfigurationValue : ConfigurationValue_GenericClasses

ConfigurationValue_1_T = typing.TypeVar('ConfigurationValue_1_T')
class ConfigurationValue_1(typing.Generic[ConfigurationValue_1_T]):
    def __init__(self, name: str, title: str, defaultValue: ConfigurationValue_1_T, converter: Func_2[typing.Any, ConfigurationValue_1_T], configDict: Dictionary_2[str, typing.Any]) -> None: ...
    @property
    def Name(self) -> str: ...
    @property
    def Title(self) -> str: ...
    @property
    def Value(self) -> ConfigurationValue_1_T: ...
    @Value.setter
    def Value(self, value: ConfigurationValue_1_T) -> ConfigurationValue_1_T: ...
    def OnChange(self, callback: Action_1[ConfigurationValue_1_T]) -> None: ...


class IConfigDictSource(typing.Protocol):
    @abc.abstractmethod
    def Load(self) -> Dictionary_2[str, typing.Any]: ...
    @abc.abstractmethod
    def Persist(self, json: str) -> None: ...


class IReadingsMappingsSource(typing.Protocol):
    @abc.abstractmethod
    def GetMappings(self) -> Dictionary_2[str, str]: ...
    @abc.abstractmethod
    def ReadRawMappings(self) -> str: ...
    @abc.abstractmethod
    def SaveMappings(self, mappings: str) -> None: ...


class JapaneseConfig:
    def __init__(self, store: ConfigurationStore) -> None: ...
    @property
    def AnkiInternalFsrsSetEnableFsrsShortTermWithSteps(self) -> ConfigurationValue_1[bool]: ...
    @property
    def AutoadvanceSentenceHiraganaSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceSentenceKanjiSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceSentenceKatakanaSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceSentenceStartingSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceVocabHiraganaSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceVocabKanjiSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceVocabKatakanaSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutoadvanceVocabStartingSeconds(self) -> ConfigurationValue_1[float]: ...
    @property
    def AutomaticallyYieldLastTokenInCausativeVerbCompoundsToOverlappingCompound(self) -> ConfigurationValue_1[bool]: ...
    @property
    def AutomaticallyYieldLastTokenInPassiveVerbCompoundsToOverlappingCompound(self) -> ConfigurationValue_1[bool]: ...
    @property
    def AutomaticallyYieldLastTokenInSuruVerbCompoundsToOverlappingCompound(self) -> ConfigurationValue_1[bool]: ...
    @property
    def BoostFailedCardAllowedTime(self) -> ConfigurationValue_1[bool]: ...
    @property
    def BoostFailedCardAllowedTimeByFactor(self) -> ConfigurationValue_1[float]: ...
    @property
    def DecreaseFailedCardIntervals(self) -> ConfigurationValue_1[bool]: ...
    @property
    def DecreaseFailedCardIntervalsInterval(self) -> ConfigurationValue_1[int]: ...
    @property
    def DeveloperOnlyToggles(self) -> List_1[ConfigurationValue_1[bool]]: ...
    @property
    def DisableAllAutomaticGarbageCollection(self) -> ConfigurationValue_1[bool]: ...
    @property
    def EnableAutomaticGarbageCollection(self) -> ConfigurationValue_1[bool]: ...
    @property
    def EnableGarbageCollectionDuringBatches(self) -> ConfigurationValue_1[bool]: ...
    @property
    def EnableTraceMalloc(self) -> ConfigurationValue_1[bool]: ...
    @property
    def FeatureToggles(self) -> List_1[ValueTuple_2[str, List_1[ConfigurationValue_1[bool]]]]: ...
    @property
    def HideAllCompounds(self) -> ConfigurationValue_1[bool]: ...
    @property
    def HideCompositionallyTransparentCompounds(self) -> ConfigurationValue_1[bool]: ...
    @property
    def LoadJamdictDbIntoMemory(self) -> ConfigurationValue_1[bool]: ...
    @property
    def LoadStudioInForeground(self) -> ConfigurationValue_1[bool]: ...
    @property
    def LogWhenFlushingNotes(self) -> ConfigurationValue_1[bool]: ...
    @property
    def MinimumTimeViewingAnswer(self) -> ConfigurationValue_1[float]: ...
    @property
    def MinimumTimeViewingQuestion(self) -> ConfigurationValue_1[float]: ...
    @property
    def MiscToggles(self) -> List_1[ConfigurationValue_1[bool]]: ...
    @property
    def PerformanceAndMemoryToggles(self) -> List_1[ConfigurationValue_1[bool]]: ...
    @property
    def PreCacheCardStudyingStatus(self) -> ConfigurationValue_1[bool]: ...
    @property
    def PreferDefaultMnemonicsToSourceMnemonics(self) -> ConfigurationValue_1[bool]: ...
    @property
    def PreventAnkiFromGarbageCollectingEveryTimeAWindowCloses(self) -> ConfigurationValue_1[bool]: ...
    @property
    def PreventDoubleClicks(self) -> ConfigurationValue_1[bool]: ...
    @property
    def ReadingsMappingsDict(self) -> Dictionary_2[str, str]: ...
    @ReadingsMappingsDict.setter
    def ReadingsMappingsDict(self, value: Dictionary_2[str, str]) -> Dictionary_2[str, str]: ...
    @property
    def ReanalysisThreads(self) -> ConfigurationValue_1[int]: ...
    @property
    def SentenceViewToggles(self) -> List_1[ConfigurationValue_1[bool]]: ...
    @property
    def ShowCompoundPartsInSentenceBreakdown(self) -> ConfigurationValue_1[bool]: ...
    @property
    def ShowKanjiInSentenceBreakdown(self) -> ConfigurationValue_1[bool]: ...
    @property
    def ShowKanjiMnemonicsInSentenceBreakdown(self) -> ConfigurationValue_1[bool]: ...
    @property
    def ShowSentenceBreakdownInEditMode(self) -> ConfigurationValue_1[bool]: ...
    @property
    def TimeboxKanjiRead(self) -> ConfigurationValue_1[int]: ...
    @property
    def TimeboxSentenceListen(self) -> ConfigurationValue_1[int]: ...
    @property
    def TimeboxSentenceRead(self) -> ConfigurationValue_1[int]: ...
    @property
    def TimeboxVocabListen(self) -> ConfigurationValue_1[int]: ...
    @property
    def TimeboxVocabRead(self) -> ConfigurationValue_1[int]: ...
    @property
    def TrackInstancesInMemory(self) -> ConfigurationValue_1[bool]: ...
    @property
    def YomitanIntegrationCopyAnswerToClipboard(self) -> ConfigurationValue_1[bool]: ...
    def OnChange(self, callback: Action) -> None: ...
    def ReadReadingsMappingsFile(self) -> str: ...
    def SaveMappings(self, mappings: str) -> None: ...
    def ToggleAllSentenceDisplayAutoYieldFlags(self, value: typing.Optional[bool] = ...) -> None: ...


class Settings:
    def AutomaticallyYieldLastTokenInCausativeVerbCompoundsToOverlappingCompound(self) -> bool: ...
    def AutomaticallyYieldLastTokenInPassiveVerbCompoundsToOverlappingCompound(self) -> bool: ...
    def AutomaticallyYieldLastTokenInSuruVerbCompoundsToOverlappingCompound(self) -> bool: ...
    def HideAllCompounds(self) -> bool: ...
    def HideTransparentCompounds(self) -> bool: ...
    def LogWhenFlushingNotes(self) -> bool: ...
    def ShowBreakdownInEditMode(self) -> bool: ...
    def ShowCompoundPartsInSentenceBreakdown(self) -> bool: ...
    def ShowKanjiInSentenceBreakdown(self) -> bool: ...
    def ShowKanjiMnemonicsInSentenceBreakdown(self) -> bool: ...

