
class PykakasiWrapper:
    def __init__(self) -> None: ...
    def Romanize(self, text: str) -> str: ...


class RomkanWrapper:
    def __init__(self) -> None: ...
    def ToHiragana(self, romaji: str) -> str: ...
    def ToKatakana(self, romaji: str) -> str: ...

