from JAStudio.Core.Note import KanjiNote
from System.Collections.Generic import List_1
from JAStudio.Core.Note.Sentences import SentenceNote
from JAStudio.Core.Note.Vocabulary import VocabNote

class LocalNoteUpdater:
    def CreateMissingVocabWithDictionaryEntries(self) -> None: ...
    def ForceFlushAllNotes(self) -> None: ...
    def FullRebuild(self) -> None: ...
    def ReadingInVocabReading(self, kanji: KanjiNote, kanjiReading: str, vocabReading: str, vocabForm: str) -> bool: ...
    def RegenerateJamdictVocabAnswers(self) -> None: ...
    def ReparseAllSentences(self) -> None: ...
    def ReparseMatchingSentences(self, questionSubstring: str) -> None: ...
    def ReparseSentences(self, sentences: List_1[SentenceNote]) -> None: ...
    def ReparseSentencesForVocab(self, vocab: VocabNote) -> None: ...
    def TagKanjiMetadata(self) -> None: ...
    def TagNoteMetadata(self) -> None: ...
    def TagSentenceMetadata(self) -> None: ...
    def TagVocabMetadata(self) -> None: ...
    def UpdateAll(self) -> None: ...
    def UpdateKanji(self) -> None: ...
    def UpdateSentences(self) -> None: ...
    def UpdateVocab(self) -> None: ...
    def WriteFileSystemRepository(self) -> None: ...

