import abc
from JAStudio.Core.Note import KanjiNote, SentenceNote, VocabNote
from System.Collections.Generic import List_1

class LocalNoteUpdater(abc.ABC):
    @staticmethod
    def CreateMissingVocabWithDictionaryEntries() -> None: ...
    @staticmethod
    def FullRebuild() -> None: ...
    @staticmethod
    def ReadingInVocabReading(kanji: KanjiNote, kanjiReading: str, vocabReading: str, vocabForm: str) -> bool: ...
    @staticmethod
    def RegenerateJamdictVocabAnswers() -> None: ...
    @staticmethod
    def ReparseAllSentences() -> None: ...
    @staticmethod
    def ReparseMatchingSentences(questionSubstring: str) -> None: ...
    @staticmethod
    def ReparseSentences(sentences: List_1[SentenceNote], runGcDuringBatch: bool = ...) -> None: ...
    @staticmethod
    def ReparseSentencesForVocab(vocab: VocabNote) -> None: ...
    @staticmethod
    def TagKanjiMetadata() -> None: ...
    @staticmethod
    def TagNoteMetadata() -> None: ...
    @staticmethod
    def TagSentenceMetadata() -> None: ...
    @staticmethod
    def TagVocabMetadata() -> None: ...
    @staticmethod
    def UpdateAll() -> None: ...
    @staticmethod
    def UpdateKanji() -> None: ...
    @staticmethod
    def UpdateSentences() -> None: ...
    @staticmethod
    def UpdateVocab() -> None: ...

