import typing, abc
from System import IDisposable, Action, Func_2
from JAStudio.Core.Note.Collection import JPCollection, CardStudyingStatus
from JAStudio.Core.Configuration import JapaneseConfig, ConfigurationStore
from JAStudio.Core.Note import IBackendNoteCreator, NoteServices, NoteId, AnkiCardOperations, AnkiNoteIdMap
from JAStudio.Core.Storage import INoteRepository
from System.Collections.Generic import Dictionary_2, List_1
from JAStudio.Core.TaskRunners import TaskRunner
from JAStudio.Core.UI.Web.Kanji import KanjiNoteRenderer
from JAStudio.Core.UI.Web.Sentence import SentenceNoteRenderer
from JAStudio.Core.UI.Web.Vocab import VocabNoteRenderer
from JAStudio.Core.Batches import LocalNoteUpdater
from JAStudio.Core.AnkiUtils import QueryBuilder
from Compze.Utilities.DependencyInjection.Abstractions import IServiceLocator
from JAStudio.Core.Note.Vocabulary import VocabNoteFactory

class App(IDisposable):
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def Config(self) -> JapaneseConfig: ...
    @classmethod
    @property
    def IsTesting(cls) -> bool: ...
    @property
    def Services(self) -> TemporaryServiceCollection: ...
    def AddInitHook(self, hook: Action) -> None: ...
    @staticmethod
    def Bootstrap(backendNoteCreator: IBackendNoteCreator = ..., backendDataLoader: IBackendDataLoader = ..., environmentPaths: IEnvironmentPaths = ..., alternateRepositoryFactory: Func_2[NoteServices, INoteRepository] = ...) -> App: ...
    def Dispose(self) -> None: ...


class BackendData:
    def __init__(self, idMappings: Dictionary_2[int, NoteId], studyingStatuses: List_1[CardStudyingStatus]) -> None: ...
    @property
    def IdMappings(self) -> Dictionary_2[int, NoteId]: ...
    @property
    def StudyingStatuses(self) -> List_1[CardStudyingStatus]: ...


class IBackendDataLoader(typing.Protocol):
    @abc.abstractmethod
    def Load(self, taskRunner: TaskRunner) -> BackendData: ...


class IEnvironmentPaths(typing.Protocol):
    @property
    def AddonRootDir(self) -> str: ...


class Renderers:
    @property
    def KanjiNoteRenderer(self) -> KanjiNoteRenderer: ...
    @property
    def SentenceNoteRenderer(self) -> SentenceNoteRenderer: ...
    @property
    def VocabNoteRenderer(self) -> VocabNoteRenderer: ...


class StringExtensions(abc.ABC):
    InvisibleSpace : str
    @staticmethod
    def ExtractCommaSeparatedValues(input: str) -> List_1[str]: ...
    @staticmethod
    def FirstNumber(input: str) -> str: ...
    @staticmethod
    def PadToLength(value: str, targetLength: int, spaceScaling: float = ...) -> str: ...
    @staticmethod
    def ReplaceWord(word: str, replacement: str, text: str) -> str: ...
    @staticmethod
    def StripHtmlMarkup(input: str) -> str: ...


class TemporaryServiceCollection(IDisposable):
    @property
    def AnkiCardOperations(self) -> AnkiCardOperations: ...
    @property
    def AnkiNoteIdMap(self) -> AnkiNoteIdMap: ...
    @property
    def App(self) -> App: ...
    @property
    def ConfigurationStore(self) -> ConfigurationStore: ...
    @classmethod
    @property
    def Instance(cls) -> TemporaryServiceCollection: ...
    @classmethod
    @Instance.setter
    def Instance(cls, value: TemporaryServiceCollection) -> TemporaryServiceCollection: ...
    @property
    def LocalNoteUpdater(self) -> LocalNoteUpdater: ...
    @property
    def NoteServices(self) -> NoteServices: ...
    @property
    def QueryBuilder(self) -> QueryBuilder: ...
    @property
    def Renderers(self) -> Renderers: ...
    @property
    def ServiceLocator(self) -> IServiceLocator: ...
    @property
    def TaskRunner(self) -> TaskRunner: ...
    @property
    def VocabNoteFactory(self) -> VocabNoteFactory: ...
    def Dispose(self) -> None: ...

