import typing, abc
from JAStudio.Core.UI.Web.Kanji import KanjiNoteRenderer
from JAStudio.Core.UI.Web.Sentence import SentenceNoteRenderer
from JAStudio.Core.UI.Web.Vocab import VocabNoteRenderer
from System.Collections.Generic import Dictionary_2, List_1
from JAStudio.Core.Note import NoteId, IBackendNoteCreator, ExternalNoteIdMap, ICardOperations, NoteServices
from JAStudio.Core.Note.Collection import CardStudyingStatus, JPCollection
from System import IDisposable, Func_2
from JAStudio.Core.Configuration import JapaneseConfig, IConfigDictSource, IReadingsMappingsSource, ConfigurationStore
from JAStudio.Core.TaskRunners import TaskRunner, IFatalErrorHandler, ITaskProgressUI, BackgroundTaskManager
from JAStudio.Core.Batches import LocalNoteUpdater
from Compze.Utilities.DependencyInjection.Abstractions import IServiceLocator
from JAStudio.Core.Note.Vocabulary import VocabNoteFactory

class AnkiHTMLRenderers:
    @property
    def KanjiNoteRenderer(self) -> KanjiNoteRenderer: ...
    @property
    def SentenceNoteRenderer(self) -> SentenceNoteRenderer: ...
    @property
    def VocabNoteRenderer(self) -> VocabNoteRenderer: ...


class AppBootstrapper(abc.ABC):
    @staticmethod
    def BootstrapForTests() -> CoreApp: ...
    @staticmethod
    def BootstrapProduction(deps: IBootstrapDependencies) -> CoreApp: ...


class BackendData:
    def __init__(self, idMappings: Dictionary_2[int, NoteId], studyingStatuses: List_1[CardStudyingStatus]) -> None: ...
    @property
    def IdMappings(self) -> Dictionary_2[int, NoteId]: ...
    @property
    def StudyingStatuses(self) -> List_1[CardStudyingStatus]: ...


class CoreApp(IDisposable):
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def Config(self) -> JapaneseConfig: ...
    @classmethod
    @property
    def IsTesting(cls) -> bool: ...
    @property
    def Paths(self) -> IEnvironmentPaths: ...
    @property
    def Services(self) -> TemporaryServiceCollection: ...
    def Dispose(self) -> None: ...


class IBackendDataLoader(typing.Protocol):
    @abc.abstractmethod
    def Load(self, taskRunner: TaskRunner) -> BackendData: ...


class IBootstrapDependencies(typing.Protocol):
    @property
    def BackendDataLoader(self) -> IBackendDataLoader: ...
    @property
    def BackendNoteCreator(self) -> IBackendNoteCreator: ...
    @property
    def CardOperationsFactory(self) -> Func_2[ExternalNoteIdMap, ICardOperations]: ...
    @property
    def ConfigDictSource(self) -> IConfigDictSource: ...
    @property
    def EnvironmentPaths(self) -> IEnvironmentPaths: ...
    @property
    def FatalErrorHandler(self) -> IFatalErrorHandler: ...
    @property
    def ReadingsMappingsSource(self) -> IReadingsMappingsSource: ...
    @property
    def TaskProgressUI(self) -> ITaskProgressUI: ...


class IEnvironmentPaths(typing.Protocol):
    @property
    def AddonRootDir(self) -> str: ...
    @property
    def AnkiMediaDir(self) -> str: ...
    @property
    def DatabaseDir(self) -> str: ...
    @property
    def MediaDir(self) -> str: ...
    @property
    def MetadataDir(self) -> str: ...
    @property
    def UserFilesDir(self) -> str: ...


class StringExtensions(abc.ABC):
    InvisibleSpace : str
    @staticmethod
    def ExtractCommaSeparatedValues(input: str) -> List_1[str]: ...
    @staticmethod
    def FirstNumber(input: str) -> str: ...
    @staticmethod
    def PadToLength(value: str, targetLength: int, spaceScaling: float = ...) -> str: ...
    @staticmethod
    def ReplaceWord(word: str, replacement: str, text: str) -> str: ...
    @staticmethod
    def StripHtmlMarkup(input: str) -> str: ...


class TemporaryServiceCollection(IDisposable):
    @property
    def AnkiHTMLRenderers(self) -> AnkiHTMLRenderers: ...
    @property
    def BackgroundTaskManager(self) -> BackgroundTaskManager: ...
    @property
    def ConfigurationStore(self) -> ConfigurationStore: ...
    @property
    def CoreApp(self) -> CoreApp: ...
    @property
    def ExternalNoteIdMap(self) -> ExternalNoteIdMap: ...
    @classmethod
    @property
    def Instance(cls) -> TemporaryServiceCollection: ...
    @classmethod
    @Instance.setter
    def Instance(cls, value: TemporaryServiceCollection) -> TemporaryServiceCollection: ...
    @property
    def LocalNoteUpdater(self) -> LocalNoteUpdater: ...
    @property
    def NoteServices(self) -> NoteServices: ...
    @property
    def ServiceLocator(self) -> IServiceLocator: ...
    @property
    def TaskRunner(self) -> TaskRunner: ...
    @property
    def VocabNoteFactory(self) -> VocabNoteFactory: ...
    def Dispose(self) -> None: ...

