import typing, abc
from System import Action
from JAStudio.Core.Note.Collection import JPCollection
from JAStudio.Core.Configuration import JapaneseConfig
from JAStudio.Core.Note import IBackendNoteCreator
from Compze.Utilities.SystemCE import LazyCE_1
from System.Collections.Generic import List_1

class App(abc.ABC):
    @classmethod
    @property
    def IsTesting(cls) -> bool: ...
    @classmethod
    @property
    def UserFilesDir(cls) -> str: ...
    @staticmethod
    def AddInitHook(hook: Action) -> None: ...
    @staticmethod
    def Col() -> JPCollection: ...
    @staticmethod
    def Config() -> JapaneseConfig: ...
    @staticmethod
    def Reset(backendNoteCreator: IBackendNoteCreator) -> None: ...


class ConsoleLogger(ILogger):
    def __init__(self) -> None: ...
    def Debug(self, message: str) -> None: ...
    def Error(self, message: str) -> None: ...
    def Info(self, message: str) -> None: ...
    def Warning(self, message: str) -> None: ...


class ILogger(typing.Protocol):
    @abc.abstractmethod
    def Debug(self, message: str) -> None: ...
    @abc.abstractmethod
    def Error(self, message: str) -> None: ...
    @abc.abstractmethod
    def Info(self, message: str) -> None: ...
    @abc.abstractmethod
    def Warning(self, message: str) -> None: ...


class MyLog(abc.ABC):
    @staticmethod
    def Debug(msg: str) -> None: ...
    @staticmethod
    def Error(msg: str) -> None: ...
    @staticmethod
    def Info(msg: str) -> None: ...
    @staticmethod
    def SetLoggerFactory(logger: LazyCE_1[ILogger]) -> None: ...
    @staticmethod
    def Warning(msg: str) -> None: ...


class StringExtensions(abc.ABC):
    InvisibleSpace : str
    @staticmethod
    def ExtractCommaSeparatedValues(input: str) -> List_1[str]: ...
    @staticmethod
    def FirstNumber(input: str) -> str: ...
    @staticmethod
    def PadToLength(value: str, targetLength: int, spaceScaling: float = ...) -> str: ...
    @staticmethod
    def ReplaceWord(word: str, replacement: str, text: str) -> str: ...
    @staticmethod
    def StripHtmlMarkup(input: str) -> str: ...

