import typing, abc
from System.Collections.Generic import List_1, Dictionary_2
from JAStudio.Core.Note import NoteData, NoteId
from System import IDisposable
from Microsoft.Data.Sqlite import SqliteConnection
from JAStudio.Core.Note.Collection import CardStudyingStatus

class AnkiBulkLoadResult:
    def __init__(self, notes: List_1[NoteData], ankiIdMap: Dictionary_2[int, NoteId]) -> None: ...
    @property
    def AnkiIdMap(self) -> Dictionary_2[int, NoteId]: ...
    @property
    def Notes(self) -> List_1[NoteData]: ...


class AnkiCardOperations:
    def SetImplementation(self, implementation: IAnkiCardOperations) -> None: ...
    def SuspendAllCardsForNote(self, noteId: NoteId) -> None: ...
    def UnsuspendAllCardsForNote(self, noteId: NoteId) -> None: ...


class AnkiCardOperationsImpl(IAnkiCardOperations):
    def __init__(self, idMap: AnkiNoteIdMap) -> None: ...
    def SuspendAllCardsForNote(self, noteId: NoteId) -> None: ...
    def UnsuspendAllCardsForNote(self, noteId: NoteId) -> None: ...


class AnkiDatabase(IDisposable):
    @property
    def Connection(self) -> SqliteConnection: ...
    def Dispose(self) -> None: ...
    @staticmethod
    def OpenReadOnly(dbFilePath: str) -> AnkiDatabase: ...


class AnkiFacade(abc.ABC):
    @staticmethod
    def GetNoteIdFromCardId(cardId: int) -> int: ...

    class Batches(abc.ABC):
        @staticmethod
        def ConvertImmersionKitSentences() -> None: ...


    class Browser(abc.ABC):
        @staticmethod
        def ExecuteLookup(query: str) -> None: ...
        @staticmethod
        def ExecuteLookupAndShowPreviewer(query: str) -> None: ...

        class MenuActions(abc.ABC):
            @staticmethod
            def PrioritizeCards(cardIds: List_1[int]) -> None: ...
            @staticmethod
            def SpreadCardsOverDays(cardIds: List_1[int], startDay: int, daysApart: int) -> None: ...



    class Col(abc.ABC):
        @staticmethod
        def DbFilePath() -> str: ...


    class NoteEx(abc.ABC):
        @staticmethod
        def SuspendAllCardsForNote(noteId: int) -> None: ...
        @staticmethod
        def UnsuspendAllCardsForNote(noteId: int) -> None: ...


    class UIUtils(abc.ABC):
        @staticmethod
        def Refresh() -> None: ...
        @staticmethod
        def ShowTooltip(message: str, periodMs: int = ...) -> None: ...



class AnkiNoteIdMap:
    def __init__(self) -> None: ...
    def FromAnkiId(self, ankiId: int) -> NoteId: ...
    def Register(self, ankiId: int, noteId: NoteId) -> None: ...
    def RequireAnkiId(self, noteId: NoteId) -> int: ...
    def ToAnkiId(self, noteId: NoteId) -> typing.Optional[int]: ...


class CardStudyingStatusLoader(abc.ABC):
    @staticmethod
    def FetchAll(dbFilePath: str) -> List_1[CardStudyingStatus]: ...


class IAnkiCardOperations(typing.Protocol):
    @abc.abstractmethod
    def SuspendAllCardsForNote(self, noteId: NoteId) -> None: ...
    @abc.abstractmethod
    def UnsuspendAllCardsForNote(self, noteId: NoteId) -> None: ...


class NoteBulkLoader(abc.ABC):
    @staticmethod
    def LoadAllNotesOfType(dbFilePath: str, noteTypeName: str) -> AnkiBulkLoadResult: ...

