import typing, abc

class AnkiCardOperations:
    def SetImplementation(self, implementation: IAnkiCardOperations) -> None: ...
    def SuspendAllCardsForNote(self, noteId: int) -> None: ...
    def UnsuspendAllCardsForNote(self, noteId: int) -> None: ...


class IAnkiCardOperations(typing.Protocol):
    @abc.abstractmethod
    def SuspendAllCardsForNote(self, noteId: int) -> None: ...
    @abc.abstractmethod
    def UnsuspendAllCardsForNote(self, noteId: int) -> None: ...

