import typing, abc
from System import Action
from System.Collections.Generic import IReadOnlyList_1

class SpecMenuItem(abc.ABC):
    @property
    def AcceleratorKey(self) -> typing.Optional[str]: ...
    @property
    def Action(self) -> Action: ...
    @property
    def Children(self) -> IReadOnlyList_1[SpecMenuItem]: ...
    @property
    def HasVisibleChildren(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def KeyboardShortcut(self) -> str: ...
    @property
    def Kind(self) -> SpecMenuItemKind: ...
    @property
    def Name(self) -> str: ...
    @staticmethod
    def Command(name: str, action: Action, acceleratorKey: typing.Optional[str] = ..., shortcut: str = ..., enabled: bool = ...) -> SpecMenuItem: ...
    @staticmethod
    def Separator() -> SpecMenuItem: ...
    @staticmethod
    def Submenu(name: str, children: IReadOnlyList_1[SpecMenuItem], acceleratorKey: typing.Optional[str] = ...) -> SpecMenuItem: ...


class SpecMenuItemKind(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Command : SpecMenuItemKind # 0
    Submenu : SpecMenuItemKind # 1
    Separator : SpecMenuItemKind # 2

