import typing, abc
import Avalonia.Controls
from System.Collections.Generic import IEnumerable_1, IReadOnlyList_1
from System import Action

class AvaloniaMenuAdapter(abc.ABC):
    @staticmethod
    def ToAvalonia(spec: MenuItem) -> Avalonia.Controls.MenuItem: ...
    @staticmethod
    def ToAvaloniaList(specs: IEnumerable_1[MenuItem]) -> IEnumerable_1[typing.Any]: ...


class MenuItem:
    def __init__(self) -> None: ...
    @property
    def AcceleratorKey(self) -> typing.Optional[str]: ...
    @AcceleratorKey.setter
    def AcceleratorKey(self, value: typing.Optional[str]) -> typing.Optional[str]: ...
    @property
    def Action(self) -> Action: ...
    @Action.setter
    def Action(self, value: Action) -> Action: ...
    @property
    def Children(self) -> IReadOnlyList_1[MenuItem]: ...
    @Children.setter
    def Children(self, value: IReadOnlyList_1[MenuItem]) -> IReadOnlyList_1[MenuItem]: ...
    @property
    def IsCommand(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsSeparator(self) -> bool: ...
    @IsSeparator.setter
    def IsSeparator(self, value: bool) -> bool: ...
    @property
    def IsSubmenu(self) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def KeyboardShortcut(self) -> str: ...
    @KeyboardShortcut.setter
    def KeyboardShortcut(self, value: str) -> str: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @staticmethod
    def Command(name: str, action: Action, acceleratorKey: typing.Optional[str] = ..., shortcut: str = ..., enabled: bool = ...) -> MenuItem: ...
    @staticmethod
    def Separator() -> MenuItem: ...
    @staticmethod
    def Submenu(name: str, children: IReadOnlyList_1[MenuItem], acceleratorKey: typing.Optional[str] = ...) -> MenuItem: ...

