import typing, abc
from JAStudio.Core.Note.NoteFields import TagFlagField, RequireForbidFlagField, WritableStringValue, WritableImageValue, MediaReference, IObjectSerializer_1
from JAStudio.Core.Note import Tag, JPNote, NoteServices, NoteGuard, NoteFlushGuard, NoteTags
from System.Collections.Generic import HashSet_1, List_1, IEnumerable_1
from System.Collections.Frozen import FrozenSet_1
from System import Func_1, Func_3, Array_1, Action_1
from JAStudio.Core.Note.CorpusData import VocabData, CorpusDataBase, VocabMatchingRulesSubData
from JAStudio.Core.Note.Collection import JPCollection
from JAStudio.Core.Note.Vocabulary.RelatedVocab import RelatedVocab
from JAStudio.Core.Note.Sentences import SentenceNote

class IsInflectingWord(TagFlagField):
    def __init__(self, vocab: VocabNote) -> None: ...
    Tag : Tag
    @property
    def IsActive(self) -> bool: ...
    def ToString(self) -> str: ...


class POS(abc.ABC):
    Abbreviation : str
    Adverb : str
    Adverbial : str
    AdverbialNoun : str
    AllVerbPoses : HashSet_1[str]
    Auxiliary : str
    Conjunction : str
    Copula : str
    Counter : str
    Expression : str
    GodanVerb : str
    IAdjective : str
    IchidanVerb : str
    IndependentNoun : str
    Interjection : str
    Intransitive : str
    Irregular : str
    KuruVerb : str
    MasuSuffix : str
    NaAdjective : str
    NidanVerb : str
    NoAdjective : str
    Noun : str
    Numeral : str
    Numeric : str
    NuVerb : str
    Particle : str
    Prefix : str
    Prenominal : str
    PreNounAdjectival : str
    Pronoun : str
    ProperNoun : str
    SpecialClass : str
    SpecialClassAru : str
    Suffix : str
    SuruVerb : str
    SuVerb : str
    TaruAdjective : str
    ToAdverb : str
    Transitive : str
    Unknown : str
    YodanVerb : str
    ZuruVerb : str


class POSSetManager:
    def __init__(self) -> None: ...
    @staticmethod
    def Get(pos: str) -> FrozenSet_1[str]: ...
    @staticmethod
    def InternAndHarmonize(pos: str) -> str: ...
    @staticmethod
    def InternAndHarmonizeFromList(posList: List_1[str]) -> FrozenSet_1[str]: ...
    @staticmethod
    def IsIntransitiveVerb(posSet: FrozenSet_1[str]) -> bool: ...
    @staticmethod
    def IsTransitiveVerb(posSet: FrozenSet_1[str]) -> bool: ...
    @staticmethod
    def IsVerb(posSet: FrozenSet_1[str]) -> bool: ...


class SentenceCounts:
    def __init__(self, parent: Func_1[VocabNoteSentences]) -> None: ...
    @property
    def StudyingListening(self) -> int: ...
    @property
    def StudyingReading(self) -> int: ...
    @property
    def Total(self) -> int: ...


class VocabCloner:
    def __init__(self, note: VocabNote) -> None: ...
    def Clone(self) -> VocabNote: ...
    def CloneToDerivedForm(self, formSuffix: str, createFormRoot: Func_3[VocabNote, str, str]) -> VocabNote: ...
    def CloneToForm(self, form: str) -> VocabNote: ...
    def CreateBaForm(self) -> VocabNote: ...
    def CreateCausativeForm(self) -> VocabNote: ...
    def CreateImperative(self) -> VocabNote: ...
    def CreateKaSuffixedWord(self) -> VocabNote: ...
    def CreateKuForm(self) -> VocabNote: ...
    def CreateMasuForm(self) -> VocabNote: ...
    def CreateNaAdjective(self) -> VocabNote: ...
    def CreateNaiForm(self) -> VocabNote: ...
    def CreateNiAdverb(self) -> VocabNote: ...
    def CreateNoAdjective(self) -> VocabNote: ...
    def CreateNSuffixedWord(self) -> VocabNote: ...
    def CreateOPrefixedWord(self) -> VocabNote: ...
    def CreatePotentialGodan(self) -> VocabNote: ...
    def CreateReceptiveForm(self) -> VocabNote: ...
    def CreateSaForm(self) -> VocabNote: ...
    def CreateShimasuVerb(self) -> VocabNote: ...
    def CreateSuffixVersion(self, suffix: str, speechType: str = ..., setCompounds: bool = ..., truncateCharacters: int = ...) -> VocabNote: ...
    def CreateSuruVerb(self, shimasu: bool = ...) -> VocabNote: ...
    def CreateTaForm(self) -> VocabNote: ...
    def CreateTeForm(self) -> VocabNote: ...
    def CreateTePrefixedWord(self) -> VocabNote: ...
    def CreateToAdverb(self) -> VocabNote: ...
    def PrefixToChopped(self, prefix: str, chopCharacters: int) -> VocabNote: ...
    def PrefixToChoppedPreview(self, formPrefix: str, chopCharacters: int) -> str: ...
    def PrefixToDictionaryForm(self, prefix: str, speechType: str = ...) -> VocabNote: ...
    def SuffixToAStem(self, formSuffix: str) -> VocabNote: ...
    def SuffixToAStemPreview(self, formSuffix: str) -> str: ...
    def SuffixToChopped(self, formSuffix: str, chopCharacters: int) -> VocabNote: ...
    def SuffixToChoppedPreview(self, formSuffix: str, chopCharacters: int) -> str: ...
    def SuffixToEStem(self, formSuffix: str) -> VocabNote: ...
    def SuffixToEStemPreview(self, formSuffix: str) -> str: ...
    def SuffixToIStem(self, formSuffix: str) -> VocabNote: ...
    def SuffixToIStemPreview(self, formSuffix: str) -> str: ...
    def SuffixToTeStem(self, formSuffix: str) -> VocabNote: ...
    def SuffixToTeStemPreview(self, formSuffix: str) -> str: ...


class VocabMatchingRulesConfigurationBoolFlags:
    def __init__(self, vocab: VocabNote) -> None: ...
    @property
    def IsCompositionallyTransparentCompound(self) -> TagFlagField: ...
    @property
    def IsInflectingWord(self) -> IsInflectingWord: ...
    @property
    def IsPoisonWord(self) -> TagFlagField: ...
    @property
    def MatchWithPrecedingVowel(self) -> TagFlagField: ...
    @property
    def QuestionOverridesForm(self) -> TagFlagField: ...


class VocabMatchingRulesConfigurationRequiresForbidsFlags:
    def __init__(self, vocab: VocabNote) -> None: ...
    @property
    def AllFlags(self) -> IEnumerable_1[RequireForbidFlagField]: ...
    @property
    def DictionaryFormPrefix(self) -> RequireForbidFlagField: ...
    @property
    def DictionaryFormStem(self) -> RequireForbidFlagField: ...
    @property
    def Godan(self) -> RequireForbidFlagField: ...
    @property
    def GodanImperative(self) -> RequireForbidFlagField: ...
    @property
    def GodanImperativePrefix(self) -> RequireForbidFlagField: ...
    @property
    def GodanPotential(self) -> RequireForbidFlagField: ...
    @property
    def Ichidan(self) -> RequireForbidFlagField: ...
    @property
    def IchidanImperative(self) -> RequireForbidFlagField: ...
    @property
    def Irrealis(self) -> RequireForbidFlagField: ...
    @property
    def MasuStem(self) -> RequireForbidFlagField: ...
    @property
    def MatchWeight(self) -> int: ...
    @property
    def PastTenseStem(self) -> RequireForbidFlagField: ...
    @property
    def PrecedingAdverb(self) -> RequireForbidFlagField: ...
    @property
    def SentenceEnd(self) -> RequireForbidFlagField: ...
    @property
    def SentenceStart(self) -> RequireForbidFlagField: ...
    @property
    def SingleToken(self) -> RequireForbidFlagField: ...
    @property
    def Surface(self) -> RequireForbidFlagField: ...
    @property
    def TeFormPrefix(self) -> RequireForbidFlagField: ...
    @property
    def TeFormStem(self) -> RequireForbidFlagField: ...
    @property
    def YieldLastToken(self) -> YieldLastTokenToOverlappingCompound: ...


class VocabMetaTag:
    def __init__(self, name: str, display: str, tooltip: str) -> None: ...
    @property
    def Display(self) -> str: ...
    @Display.setter
    def Display(self, value: str) -> str: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Tooltip(self) -> str: ...
    @Tooltip.setter
    def Tooltip(self, value: str) -> str: ...


class VocabNote(JPNote):
    def __init__(self, services: NoteServices, data: VocabData = ...) -> None: ...
    @property
    def ActiveAnswer(self) -> WritableStringValue: ...
    @property
    def Audio(self) -> VocabNoteAudio: ...
    @property
    def Cloner(self) -> VocabCloner: ...
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def CompoundParts(self) -> VocabNoteUserCompoundParts: ...
    @property
    def Conjugator(self) -> VocabNoteConjugator: ...
    @property
    def Forms(self) -> VocabNoteForms: ...
    @property
    def Guard(self) -> NoteGuard: ...
    @property
    def Image(self) -> WritableImageValue: ...
    @property
    def IsFlushing(self) -> bool: ...
    @property
    def Kanji(self) -> VocabNoteKanji: ...
    @property
    def MatchingConfiguration(self) -> VocabNoteMatchingConfiguration: ...
    @MatchingConfiguration.setter
    def MatchingConfiguration(self, value: VocabNoteMatchingConfiguration) -> VocabNoteMatchingConfiguration: ...
    @property
    def MetaData(self) -> VocabNoteMetaData: ...
    @property
    def PartsOfSpeech(self) -> VocabNotePartsOfSpeech: ...
    @property
    def Question(self) -> VocabNoteQuestion: ...
    @Question.setter
    def Question(self, value: VocabNoteQuestion) -> VocabNoteQuestion: ...
    @property
    def RecursiveFlushGuard(self) -> NoteFlushGuard: ...
    @property
    def References(self) -> WritableStringValue: ...
    @property
    def Register(self) -> VocabNoteRegister: ...
    @property
    def RelatedNotes(self) -> RelatedVocab: ...
    @property
    def Sentences(self) -> VocabNoteSentences: ...
    @property
    def Services(self) -> NoteServices: ...
    @property
    def SourceAnswer(self) -> WritableStringValue: ...
    @property
    def SourceMnemonic(self) -> WritableStringValue: ...
    @property
    def SourceReadingMnemonic(self) -> WritableStringValue: ...
    @property
    def Tags(self) -> NoteTags: ...
    @property
    def TechnicalNotes(self) -> WritableStringValue: ...
    @property
    def User(self) -> VocabNoteUserFields: ...
    @property
    def UserImage(self) -> WritableImageValue: ...
    def GenerateAndSetAnswer(self) -> None: ...
    def GetAnswer(self) -> str: ...
    def GetDirectDependencies(self) -> HashSet_1[JPNote]: ...
    def GetMediaReferences(self) -> List_1[MediaReference]: ...
    def GetQuestion(self) -> str: ...
    def GetReadings(self) -> List_1[str]: ...
    def OnTagsUpdated(self) -> None: ...
    def SetReadings(self, readings: List_1[str]) -> None: ...
    def ToCorpusData(self) -> CorpusDataBase: ...
    def UpdateGeneratedData(self) -> None: ...
    def UpdateInCache(self) -> None: ...
    # Skipped Create due to it being static, abstract and generic.

    Create : Create_MethodGroup
    class Create_MethodGroup:
        @typing.overload
        def __call__(self, services: NoteServices, question: str, answer: str, readings: Array_1[str]) -> VocabNote:...
        @typing.overload
        def __call__(self, services: NoteServices, question: str, answer: str, readings: List_1[str], forms: List_1[str]) -> VocabNote:...



class VocabNoteAudio:
    def __init__(self, data: VocabData, guard: NoteGuard) -> None: ...
    @property
    def First(self) -> WritableAudioValue: ...
    @property
    def PrimaryAudio(self) -> str: ...
    @property
    def PrimaryAudioPath(self) -> str: ...
    @property
    def Second(self) -> WritableAudioValue: ...
    @property
    def Tts(self) -> WritableAudioValue: ...
    def ToString(self) -> str: ...


class VocabNoteConjugator:
    def __init__(self, vocab: VocabNote) -> None: ...
    def GetStemsForAllForms(self) -> List_1[str]: ...
    def GetStemsForPrimaryForm(self) -> List_1[str]: ...


class VocabNoteFactory:
    def Create(self, question: str, answer: str, readings: List_1[str], initializer: Action_1[VocabNote] = ...) -> VocabNote: ...
    def CreateFromUserData(self, question: str, answer: str, readings: List_1[str], initializer: Action_1[VocabNote] = ...) -> VocabNote: ...
    def CreateWithDictionary(self, question: str) -> VocabNote: ...


class VocabNoteForms:
    def __init__(self, vocab: VocabNote, data: VocabData, guard: NoteGuard) -> None: ...
    def Add(self, add: str) -> None: ...
    def AllList(self) -> List_1[str]: ...
    def AllListNotes(self) -> List_1[VocabNote]: ...
    def AllListNotesBySentenceCount(self) -> List_1[VocabNote]: ...
    def AllRawList(self) -> List_1[str]: ...
    def AllRawString(self) -> str: ...
    def AllSet(self) -> HashSet_1[str]: ...
    def IsOwnedForm(self, form: str) -> bool: ...
    def NotOwnedByOtherVocab(self) -> HashSet_1[str]: ...
    def OwnedForms(self) -> HashSet_1[str]: ...
    def Remove(self, remove: str) -> None: ...
    def SetList(self, forms: List_1[str]) -> None: ...
    def SetSet(self, forms: HashSet_1[str]) -> None: ...
    def ToString(self) -> str: ...
    def WithoutNoiseCharacters(self) -> List_1[str]: ...


class VocabNoteGeneratedData:
    def UpdateGeneratedData(self, vocab: VocabNote) -> None: ...


class VocabNoteKanji:
    def __init__(self, vocab: VocabNote) -> None: ...
    def ExtractAllKanji(self) -> HashSet_1[str]: ...
    def ExtractMainFormKanji(self) -> List_1[str]: ...
    def ToString(self) -> str: ...


class VocabNoteMatchingConfiguration:
    def __init__(self, vocab: VocabNote, data: VocabData, guard: NoteGuard) -> None: ...
    @property
    def BoolFlags(self) -> VocabMatchingRulesConfigurationBoolFlags: ...
    @BoolFlags.setter
    def BoolFlags(self, value: VocabMatchingRulesConfigurationBoolFlags) -> VocabMatchingRulesConfigurationBoolFlags: ...
    @property
    def ConfigurableRules(self) -> VocabNoteMatchingRules: ...
    @property
    def CustomRequirementsWeight(self) -> int: ...
    @property
    def RequiresForbids(self) -> VocabMatchingRulesConfigurationRequiresForbidsFlags: ...
    @RequiresForbids.setter
    def RequiresForbids(self, value: VocabMatchingRulesConfigurationRequiresForbidsFlags) -> VocabMatchingRulesConfigurationRequiresForbidsFlags: ...
    def RefreshTagBasedFlags(self) -> None: ...


class VocabNoteMatchingRules:
    def __init__(self, vocab: VocabNote, subData: VocabMatchingRulesSubData, guard: NoteGuard) -> None: ...
    @property
    def MatchWeight(self) -> int: ...
    @property
    def PrefixIsNot(self) -> HashSet_1[str]: ...
    @property
    def RequiredPrefix(self) -> HashSet_1[str]: ...
    @property
    def SuffixIsNot(self) -> HashSet_1[str]: ...
    @property
    def SurfaceIsNot(self) -> HashSet_1[str]: ...
    @property
    def YieldToSurface(self) -> HashSet_1[str]: ...
    def OverwriteWith(self, other: VocabNoteMatchingRules) -> None: ...
    def Save(self) -> None: ...


class VocabNoteMatchingRulesData:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, surfaceIsNot: HashSet_1[str], prefixIsNot: HashSet_1[str], suffixIsNot: HashSet_1[str], requiredPrefix: HashSet_1[str], yieldToSurface: HashSet_1[str]) -> None: ...
    @property
    def PrefixIsNot(self) -> HashSet_1[str]: ...
    @PrefixIsNot.setter
    def PrefixIsNot(self, value: HashSet_1[str]) -> HashSet_1[str]: ...
    @property
    def RequiredPrefix(self) -> HashSet_1[str]: ...
    @RequiredPrefix.setter
    def RequiredPrefix(self, value: HashSet_1[str]) -> HashSet_1[str]: ...
    @property
    def SuffixIsNot(self) -> HashSet_1[str]: ...
    @SuffixIsNot.setter
    def SuffixIsNot(self, value: HashSet_1[str]) -> HashSet_1[str]: ...
    @property
    def SurfaceIsNot(self) -> HashSet_1[str]: ...
    @SurfaceIsNot.setter
    def SurfaceIsNot(self, value: HashSet_1[str]) -> HashSet_1[str]: ...
    @property
    def YieldToSurface(self) -> HashSet_1[str]: ...
    @YieldToSurface.setter
    def YieldToSurface(self, value: HashSet_1[str]) -> HashSet_1[str]: ...


class VocabNoteMatchingRulesSerializer(IObjectSerializer_1[VocabNoteMatchingRulesData]):
    def __init__(self) -> None: ...
    def Deserialize(self, serialized: str) -> VocabNoteMatchingRulesData: ...
    def Serialize(self, instance: VocabNoteMatchingRulesData) -> str: ...


class VocabNoteMetaData:
    def __init__(self, vocab: VocabNote, data: VocabData, guard: NoteGuard) -> None: ...
    @property
    def SentenceCount(self) -> int: ...
    def MetaTagsHtml(self, displayExtendedSentenceStatistics: bool = ..., noSentenceStatistics: bool = ...) -> str: ...
    def SetSentenceCount(self, value: int) -> None: ...


class VocabNoteMetaTagFormatter(abc.ABC):
    @staticmethod
    def GetMetaTagsHtml(vocab: VocabNote, displayExtendedSentenceStatistics: bool = ..., noSentenceStatistics: bool = ...) -> str: ...


class VocabNotePartsOfSpeech:
    def __init__(self, vocab: VocabNote, data: VocabData, guard: NoteGuard) -> None: ...
    def Get(self) -> HashSet_1[str]: ...
    def IsCausativeVerbCompound(self) -> bool: ...
    def IsCompleteNaAdjective(self) -> bool: ...
    def IsGodan(self) -> bool: ...
    def IsIchidan(self) -> bool: ...
    def IsInflectingWordType(self) -> bool: ...
    def IsIntransitive(self) -> bool: ...
    def IsNiSuruGaSuruKuSuruCompound(self) -> bool: ...
    def IsPassiveVerbCompound(self) -> bool: ...
    def IsSuruVerbIncluded(self) -> bool: ...
    def IsTransitive(self) -> bool: ...
    def IsUk(self) -> bool: ...
    def RawStringValue(self) -> str: ...
    def Set(self, value: IEnumerable_1[str]) -> None: ...
    def SetAutomaticallyFromDictionary(self) -> None: ...
    def SetRawStringValue(self, value: str) -> None: ...
    def ToString(self) -> str: ...


class VocabNoteQuestion:
    def __init__(self, vocab: VocabNote, data: VocabData, guard: NoteGuard) -> None: ...
    DisambiguationMarker : str
    InvalidQuestionMessage : str
    @property
    def DisambiguationName(self) -> str: ...
    @DisambiguationName.setter
    def DisambiguationName(self, value: str) -> str: ...
    @property
    def IsDisambiguated(self) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def Raw(self) -> str: ...
    @Raw.setter
    def Raw(self, value: str) -> str: ...
    @property
    def WithoutNoiseCharacters(self) -> str: ...
    def Set(self, value: str) -> None: ...
    def Stems(self) -> VocabStems: ...
    def ToString(self) -> str: ...


class VocabNoteRegister:
    def __init__(self, vocab: VocabNote) -> None: ...
    @property
    def Archaic(self) -> TagFlagField: ...
    @property
    def Childish(self) -> TagFlagField: ...
    @property
    def Derogatory(self) -> TagFlagField: ...
    @property
    def Formal(self) -> TagFlagField: ...
    @property
    def Honorific(self) -> TagFlagField: ...
    @property
    def Humble(self) -> TagFlagField: ...
    @property
    def Informal(self) -> TagFlagField: ...
    @property
    def Literary(self) -> TagFlagField: ...
    @property
    def Polite(self) -> TagFlagField: ...
    @property
    def RoughMasculine(self) -> TagFlagField: ...
    @property
    def Sensitive(self) -> TagFlagField: ...
    @property
    def Slang(self) -> TagFlagField: ...
    @property
    def SoftFeminine(self) -> TagFlagField: ...
    @property
    def Vulgar(self) -> TagFlagField: ...


class VocabNoteSentences:
    def __init__(self, vocab: VocabNote) -> None: ...
    def All(self) -> List_1[SentenceNote]: ...
    def Counts(self) -> SentenceCounts: ...
    def InvalidIn(self) -> List_1[SentenceNote]: ...
    def Studying(self) -> List_1[SentenceNote]: ...
    def UserHighlighted(self) -> List_1[SentenceNote]: ...
    def WithOwnedForm(self) -> List_1[SentenceNote]: ...
    def WithPrimaryForm(self) -> List_1[SentenceNote]: ...


class VocabNoteSorting(abc.ABC):
    @staticmethod
    def SortVocabListByStudyingStatus(vocabs: IEnumerable_1[VocabNote], primaryVoc: List_1[str] = ..., preferredKanji: str = ...) -> List_1[VocabNote]: ...


class VocabNoteUserCompoundParts:
    def __init__(self, vocab: VocabNote, data: VocabData, guard: NoteGuard) -> None: ...
    def All(self) -> List_1[str]: ...
    def AllNotes(self) -> HashSet_1[VocabNote]: ...
    def AllRaw(self) -> List_1[str]: ...
    def AutoGenerate(self) -> None: ...
    def Primary(self) -> List_1[str]: ...
    def PrimaryPartsNotes(self) -> List_1[VocabNote]: ...
    def Set(self, value: List_1[str]) -> None: ...
    def ToString(self) -> str: ...


class VocabNoteUserFields:
    def __init__(self, data: VocabData, guard: NoteGuard) -> None: ...
    @property
    def Answer(self) -> WritableStringValue: ...
    @property
    def Explanation(self) -> WritableStringValue: ...
    @property
    def ExplanationLong(self) -> WritableStringValue: ...
    @property
    def Mnemonic(self) -> WritableStringValue: ...
    def ToString(self) -> str: ...


class VocabStems:
    def __init__(self, vocab: VocabNote) -> None: ...
    def MasuStem(self) -> str: ...


class WritableAudioValue:
    def __init__(self, initialValue: str, guard: NoteGuard) -> None: ...
    def AudioFilesPaths(self) -> List_1[str]: ...
    def FirstAudioFilePath(self) -> str: ...
    def GetMediaReferences(self) -> List_1[MediaReference]: ...
    def HasAudio(self) -> bool: ...
    def RawValue(self) -> str: ...
    def SetRawValue(self, value: str) -> None: ...
    def ToString(self) -> str: ...


class YieldLastTokenToOverlappingCompound(RequireForbidFlagField):
    def __init__(self, vocab: VocabNote) -> None: ...
    @property
    def ForbiddenWeight(self) -> int: ...
    @property
    def IsActive(self) -> bool: ...
    @property
    def IsConfiguredForbidden(self) -> bool: ...
    @property
    def IsConfiguredRequired(self) -> bool: ...
    @property
    def IsForbidden(self) -> bool: ...
    @property
    def IsRequired(self) -> bool: ...
    @property
    def MatchWeight(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def RequiredWeight(self) -> int: ...
    def ToString(self) -> str: ...

