import typing
from Avalonia import Size, Visual, DirectProperty_2, StyledProperty_1, Thickness, Rect, StyledElement, RelativePoint, AvaloniaObject, AvaloniaProperty
from Avalonia.Styling import ThemeVariant, Styles, ControlTheme
from Avalonia.Controls import Classes, IResourceDictionary
from Avalonia.Media import Geometry, IEffect, FlowDirection, IBrush, ITransform
from Avalonia.Animation import Transitions
from Avalonia.Data import IndexerDescriptor, IBinding

class HorizontalAlignment(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Stretch : HorizontalAlignment # 0
    Left : HorizontalAlignment # 1
    Center : HorizontalAlignment # 2
    Right : HorizontalAlignment # 3


class ILayoutRoot(typing.Protocol):
    @property
    def ClientSize(self) -> Size: ...
    @property
    def LayoutScaling(self) -> float: ...


class Layoutable(Visual):
    def __init__(self) -> None: ...
    DesiredSizeProperty : DirectProperty_2[Layoutable, Size]
    HeightProperty : StyledProperty_1[float]
    HorizontalAlignmentProperty : StyledProperty_1[HorizontalAlignment]
    MarginProperty : StyledProperty_1[Thickness]
    MaxHeightProperty : StyledProperty_1[float]
    MaxWidthProperty : StyledProperty_1[float]
    MinHeightProperty : StyledProperty_1[float]
    MinWidthProperty : StyledProperty_1[float]
    UseLayoutRoundingProperty : StyledProperty_1[bool]
    VerticalAlignmentProperty : StyledProperty_1[VerticalAlignment]
    WidthProperty : StyledProperty_1[float]
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DesiredSize(self) -> Size: ...
    @DesiredSize.setter
    def DesiredSize(self, value: Size) -> Size: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @IsArrangeValid.setter
    def IsArrangeValid(self, value: bool) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @IsMeasureValid.setter
    def IsMeasureValid(self, value: bool) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    def ApplyTemplate(self) -> None: ...
    def Arrange(self, rect: Rect) -> None: ...
    def InvalidateArrange(self) -> None: ...
    def InvalidateMeasure(self) -> None: ...
    def Measure(self, availableSize: Size) -> None: ...
    def UpdateLayout(self) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class VerticalAlignment(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Stretch : VerticalAlignment # 0
    Top : VerticalAlignment # 1
    Center : VerticalAlignment # 2
    Bottom : VerticalAlignment # 3

