import abc
from System import Action, Action_1, Func_1
from System.Collections.Generic import List_1
from Avalonia.Controls import MenuItem

class JapaneseMainMenu:
    def __init__(self, refreshCallback: Action, executeLookup: Action_1[str], searchText: str) -> None: ...
    def BuildMenu(self) -> List_1[MenuItem]: ...


class NoteContextMenu:
    def __init__(self, refreshCallback: Action, executeLookup: Action_1[str]) -> None: ...
    def BuildGenericContextMenu(self, selection: str, clipboard: str) -> List_1[MenuItem]: ...
    def BuildKanjiContextMenu(self, kanjiId: int, selection: str, clipboard: str) -> List_1[MenuItem]: ...
    def BuildSentenceContextMenu(self, sentenceId: int, selection: str, clipboard: str) -> List_1[MenuItem]: ...
    def BuildVocabContextMenu(self, vocabId: int, selection: str, clipboard: str) -> List_1[MenuItem]: ...


class OpenInAnkiMenus(abc.ABC):
    @staticmethod
    def BuildOpenInAnkiMenu(getSearchText: Func_1[str], executeLookup: Action_1[str]) -> MenuItem: ...


class WebSearchMenus(abc.ABC):
    @staticmethod
    def BuildWebSearchMenu(getSearchText: Func_1[str], openUrl: Action_1[str]) -> MenuItem: ...

