import abc
from JAStudio.Core import TemporaryServiceCollection
from JAStudio.UI.Menus.UIAgnosticMenuStructure import SpecMenuItem
from System.Collections.Generic import IReadOnlyList_1, List_1
from System import Func_1
from Avalonia.Controls import MenuItem
from JAStudio.Core.Note import NoteId

class BrowserMenus:
    def __init__(self, services: TemporaryServiceCollection) -> None: ...
    def BuildBrowserMenuSpec(self, selectedCardIds: IReadOnlyList_1[int], selectedNoteIds: IReadOnlyList_1[int]) -> SpecMenuItem: ...


class JapaneseMainMenu:
    def __init__(self, services: TemporaryServiceCollection) -> None: ...
    def BuildMenuSpec(self, getClipboardContent: Func_1[str]) -> List_1[SpecMenuItem]: ...


class NoteContextMenu:
    def __init__(self, services: TemporaryServiceCollection) -> None: ...
    def BuildGenericContextMenu(self, selection: str, clipboard: str) -> List_1[MenuItem]: ...
    def BuildGenericContextMenuSpec(self, selection: str, clipboard: str) -> List_1[SpecMenuItem]: ...
    def BuildKanjiContextMenu(self, kanjiId: int, selection: str, clipboard: str) -> List_1[MenuItem]: ...
    def BuildKanjiContextMenuSpec(self, kanjiId: NoteId, selection: str, clipboard: str) -> List_1[SpecMenuItem]: ...
    def BuildSentenceContextMenu(self, sentenceId: int, selection: str, clipboard: str) -> List_1[MenuItem]: ...
    def BuildSentenceContextMenuSpec(self, sentenceId: NoteId, selection: str, clipboard: str) -> List_1[SpecMenuItem]: ...
    def BuildVocabContextMenu(self, vocabId: int, selection: str, clipboard: str) -> List_1[MenuItem]: ...
    def BuildVocabContextMenuSpec(self, vocabId: NoteId, selection: str, clipboard: str) -> List_1[SpecMenuItem]: ...


class OpenInAnkiMenus:
    def __init__(self, services: TemporaryServiceCollection) -> None: ...
    def BuildOpenInAnkiMenu(self, getSearchText: Func_1[str]) -> MenuItem: ...
    def BuildOpenInAnkiMenuSpec(self, getSearchText: Func_1[str]) -> SpecMenuItem: ...


class WebSearchMenus(abc.ABC):
    @staticmethod
    def BuildWebSearchMenu(getSearchText: Func_1[str]) -> MenuItem: ...
    @staticmethod
    def BuildWebSearchMenuSpec(getSearchText: Func_1[str]) -> SpecMenuItem: ...

