from typing import Any

class SentenceSpec:
    def __init__(self, question: str, answer: str):
        self.question = question
        self.answer = answer

    def __repr__(self) -> str:
        return f"""SentenceSpec("{self.question}", "{self.answer}")"""

    def __hash__(self) -> int: return hash(self.question)

    def __eq__(self, other: Any) -> bool:
        return (isinstance(other, SentenceSpec)
                and other.question == self.question
                and other.answer == self.answer)

#Generated by test_create_sample_data()
test_sentence_list = [
    SentenceSpec("な…何をそんなに一生懸命探しているんですか", "Wh-What are you searching for so desperately?"),
    SentenceSpec("ついに素晴らしい女性に逢えた。", "I was finally able to meet a wonderful woman."),
    SentenceSpec("昨夜恐ろしい夢を見た。", "I had a terrible dream last night.恐ろしい -- terrible, awful"),
    SentenceSpec("一度夢を見た", "Once, [I] had a dream."),
    SentenceSpec("言われるまで気づかなかった", "[I] didn't notice, until [it] was said."),
    SentenceSpec("それなのに先生に当てられてもちゃんと答えられるし", "And yet, when the teacher calls on him, he can answer correctly."),
    SentenceSpec("一度失敗して泣いたり逃げたりすると", "If you fail once, cry, run away, and so on&nbsp; ..."),
    SentenceSpec("私に日記を書くように言ったのも自分が楽をするためでした", "He only told me I should keep a diary to make things easier on himself."),
    SentenceSpec("私に日記を書くように言ったのも自分が楽をするためでした", "He only told me I should keep a diary to make things easier on himself."),
    SentenceSpec("自分のことを知ってもらえてない人に話しかけたりするのって", "Talking to people who don't know you."),
    SentenceSpec("ううん　俺で良かったらいくらでも付き合うから", "no | if-I-will-do | as-much-as-you-want | accompany | so..."),
    SentenceSpec("そんなに気になるなら あの時俺も友達だって言えばよかったじゃん", "If it bothers you that much, you should have said you were her friend, too."),
    SentenceSpec("そんなに気になるなら あの時俺も友達だって言えばよかったじゃん", "If it bothers you that much, you should have said you were her friend, too."),
    SentenceSpec("話したいことって ひょっとしたら ヨリ戻そうってのかもなあ", "Something she wants to say, huh? It could be that she wants to get back together."),
    SentenceSpec("問題があるとしたら 大谷のほうや", "Otani is the problem."),
    SentenceSpec("ほんで どうツッコんだろかなって いろいろ考えながら— 米 取ろうとしたら 頭がフラーッとして", "So then I was thinking I'd take the rice off while making a joke, when I suddenly got dizzy..."),
    SentenceSpec("（大谷） ほんで どうツッコんだろかなって いろいろ考えながら 米 取ろうとしたら 頭がフラーッとして", "So then I was thinking I'd take this rice off while making a joke, when I suddenly got dizzy..."),
    SentenceSpec("（信子）ごめんな せっかくもろたのに ばあちゃんが “親からもろた体に—” “傷付けることしたらあかん” 言うねん", "I'm sorry. I know you went to a lot of trouble to get these, ...but my grandma would be upset if I poked holes in my body."),
    SentenceSpec("長谷くんは　友達と遊びに行くとしたら　どこ行くの", "Hase-kun, when you go out with your friends, where do you go?"),
    SentenceSpec("やばいな　寝ちゃいそう 単位落としたらどうしよう", "Man, I hope I don't doze off. What'll I do if I fail?"),
    SentenceSpec("まあ　でも　それが本当の藤宮なんだとしたら 藤宮にとってお前は特別な存在ってことだよな", "Umm... However, if we assume that that's the real Fujimiya, then you must be special to her, right?&nbsp;"),
    SentenceSpec("だとしたら　今のままでいいんじゃねぇの", "If that's true, then aren't things fine as they are?"),
    SentenceSpec("あいつが話の中に出てくるのが…", "But when that guy comes up in our conversation...")
]
