import typing, abc
from Avalonia import AvaloniaObject, AttachedProperty_1, DirectProperty_2, AvaloniaProperty, Size, Rect, Visual, Vector, StyledProperty_1, Thickness, CornerRadius, StyledElement, RelativePoint
from Avalonia.Controls import Control, ItemsControl, SelectionChangedEventArgs, Classes, ContextMenu, ITemplate_1, ItemCollection, Panel, ItemsSourceView, IResourceDictionary, INameScope
from Avalonia.Data import IndexerDescriptor, IBinding
from Avalonia.Input import NavigationDirection, IFocusScope, Cursor, KeyBinding
from System import EventArgs, IDisposable
from Avalonia.Controls.Presenters import ContentPresenter, ItemsPresenter
from Avalonia.Media import Transform, IBrush, BackgroundSizing, Geometry, IEffect, FlowDirection, FontFamily, FontFeatureCollection, FontStretch, FontStyle, FontWeight, ITransform
from Avalonia.Controls.Primitives.PopupPositioning import PopupPositionRequest
from Avalonia.Interactivity import RoutedEvent_1, RoutedEventArgs, RoutingStrategies, RoutedEvent
from Avalonia.Styling import ThemeVariant, ControlTheme, Styles
from Avalonia.Controls.Templates import DataTemplates, IDataTemplate, IControlTemplate
from Avalonia.Input.GestureRecognizers import GestureRecognizerCollection
from Avalonia.Layout import HorizontalAlignment, VerticalAlignment
from Avalonia.Controls.Generators import ItemContainerGenerator
from System.Collections import IEnumerable
from System.Collections.Generic import List_1
from Avalonia.Animation import Transitions

class FlyoutBase(AvaloniaObject, abc.ABC):
    AttachedFlyoutProperty : AttachedProperty_1[FlyoutBase]
    IsOpenProperty : DirectProperty_2[FlyoutBase, bool]
    TargetProperty : DirectProperty_2[FlyoutBase, Control]
    @property
    def IsOpen(self) -> bool: ...
    @IsOpen.setter
    def IsOpen(self, value: bool) -> bool: ...
    @property
    def Target(self) -> Control: ...
    @Target.setter
    def Target(self, value: Control) -> Control: ...
    @staticmethod
    def GetAttachedFlyout(element: Control) -> FlyoutBase: ...
    @abc.abstractmethod
    def Hide(self) -> None: ...
    @staticmethod
    def SetAttachedFlyout(element: Control, value: FlyoutBase) -> None: ...
    @abc.abstractmethod
    def ShowAt(self, placementTarget: Control) -> None: ...
    @staticmethod
    def ShowAttachedFlyout(flyoutOwner: Control) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class ILogicalScrollable(IScrollable, typing.Protocol):
    @property
    def CanHorizontallyScroll(self) -> bool: ...
    @CanHorizontallyScroll.setter
    def CanHorizontallyScroll(self, value: bool) -> bool: ...
    @property
    def CanVerticallyScroll(self) -> bool: ...
    @CanVerticallyScroll.setter
    def CanVerticallyScroll(self, value: bool) -> bool: ...
    @property
    def IsLogicalScrollEnabled(self) -> bool: ...
    @property
    def PageScrollSize(self) -> Size: ...
    @property
    def ScrollSize(self) -> Size: ...
    @abc.abstractmethod
    def BringIntoView(self, target: Control, targetRect: Rect) -> bool: ...
    @abc.abstractmethod
    def GetControlInDirection(self, direction: NavigationDirection, from_: Control) -> Control: ...
    @abc.abstractmethod
    def RaiseScrollInvalidated(self, e: EventArgs) -> None: ...


class IPopupHost(IFocusScope, IDisposable, typing.Protocol):
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HostedVisualTreeRoot(self) -> Visual: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Presenter(self) -> ContentPresenter: ...
    @property
    def Topmost(self) -> bool: ...
    @Topmost.setter
    def Topmost(self, value: bool) -> bool: ...
    @property
    def Transform(self) -> Transform: ...
    @Transform.setter
    def Transform(self, value: Transform) -> Transform: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @abc.abstractmethod
    def ConfigurePosition(self, positionRequest: PopupPositionRequest) -> None: ...
    @abc.abstractmethod
    def Hide(self) -> None: ...
    @abc.abstractmethod
    def SetChild(self, control: Control) -> None: ...
    @abc.abstractmethod
    def Show(self) -> None: ...
    @abc.abstractmethod
    def TakeFocus(self) -> None: ...


class IScrollable(typing.Protocol):
    @property
    def Extent(self) -> Size: ...
    @property
    def Offset(self) -> Vector: ...
    @Offset.setter
    def Offset(self, value: Vector) -> Vector: ...
    @property
    def Viewport(self) -> Size: ...


class SelectingItemsControl(ItemsControl):
    def __init__(self) -> None: ...
    AutoScrollToSelectedItemProperty : StyledProperty_1[bool]
    IsSelectedChangedEvent : RoutedEvent_1[RoutedEventArgs]
    IsSelectedProperty : StyledProperty_1[bool]
    IsTextSearchEnabledProperty : StyledProperty_1[bool]
    SelectedIndexProperty : DirectProperty_2[SelectingItemsControl, int]
    SelectedItemProperty : DirectProperty_2[SelectingItemsControl, typing.Any]
    SelectedValueBindingProperty : StyledProperty_1[IBinding]
    SelectedValueProperty : StyledProperty_1[typing.Any]
    SelectionChangedEvent : RoutedEvent_1[SelectionChangedEventArgs]
    WrapSelectionProperty : StyledProperty_1[bool]
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def AutoScrollToSelectedItem(self) -> bool: ...
    @AutoScrollToSelectedItem.setter
    def AutoScrollToSelectedItem(self, value: bool) -> bool: ...
    @property
    def Background(self) -> IBrush: ...
    @Background.setter
    def Background(self, value: IBrush) -> IBrush: ...
    @property
    def BackgroundSizing(self) -> BackgroundSizing: ...
    @BackgroundSizing.setter
    def BackgroundSizing(self, value: BackgroundSizing) -> BackgroundSizing: ...
    @property
    def BorderBrush(self) -> IBrush: ...
    @BorderBrush.setter
    def BorderBrush(self, value: IBrush) -> IBrush: ...
    @property
    def BorderThickness(self) -> Thickness: ...
    @BorderThickness.setter
    def BorderThickness(self, value: Thickness) -> Thickness: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def ContextFlyout(self) -> FlyoutBase: ...
    @ContextFlyout.setter
    def ContextFlyout(self, value: FlyoutBase) -> FlyoutBase: ...
    @property
    def ContextMenu(self) -> ContextMenu: ...
    @ContextMenu.setter
    def ContextMenu(self, value: ContextMenu) -> ContextMenu: ...
    @property
    def CornerRadius(self) -> CornerRadius: ...
    @CornerRadius.setter
    def CornerRadius(self, value: CornerRadius) -> CornerRadius: ...
    @property
    def Cursor(self) -> Cursor: ...
    @Cursor.setter
    def Cursor(self, value: Cursor) -> Cursor: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def DesiredSize(self) -> Size: ...
    @property
    def DisplayMemberBinding(self) -> IBinding: ...
    @DisplayMemberBinding.setter
    def DisplayMemberBinding(self, value: IBinding) -> IBinding: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def Focusable(self) -> bool: ...
    @Focusable.setter
    def Focusable(self, value: bool) -> bool: ...
    @property
    def FocusAdorner(self) -> ITemplate_1[Control]: ...
    @FocusAdorner.setter
    def FocusAdorner(self, value: ITemplate_1[Control]) -> ITemplate_1[Control]: ...
    @property
    def FontFamily(self) -> FontFamily: ...
    @FontFamily.setter
    def FontFamily(self, value: FontFamily) -> FontFamily: ...
    @property
    def FontFeatures(self) -> FontFeatureCollection: ...
    @FontFeatures.setter
    def FontFeatures(self, value: FontFeatureCollection) -> FontFeatureCollection: ...
    @property
    def FontSize(self) -> float: ...
    @FontSize.setter
    def FontSize(self, value: float) -> float: ...
    @property
    def FontStretch(self) -> FontStretch: ...
    @FontStretch.setter
    def FontStretch(self, value: FontStretch) -> FontStretch: ...
    @property
    def FontStyle(self) -> FontStyle: ...
    @FontStyle.setter
    def FontStyle(self, value: FontStyle) -> FontStyle: ...
    @property
    def FontWeight(self) -> FontWeight: ...
    @FontWeight.setter
    def FontWeight(self, value: FontWeight) -> FontWeight: ...
    @property
    def Foreground(self) -> IBrush: ...
    @Foreground.setter
    def Foreground(self, value: IBrush) -> IBrush: ...
    @property
    def GestureRecognizers(self) -> GestureRecognizerCollection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @property
    def IsEffectivelyEnabled(self) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsFocused(self) -> bool: ...
    @property
    def IsHitTestVisible(self) -> bool: ...
    @IsHitTestVisible.setter
    def IsHitTestVisible(self, value: bool) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsKeyboardFocusWithin(self) -> bool: ...
    @IsKeyboardFocusWithin.setter
    def IsKeyboardFocusWithin(self, value: bool) -> bool: ...
    @property
    def IsLoaded(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @property
    def IsPointerOver(self) -> bool: ...
    @IsPointerOver.setter
    def IsPointerOver(self, value: bool) -> bool: ...
    @property
    def IsTabStop(self) -> bool: ...
    @IsTabStop.setter
    def IsTabStop(self, value: bool) -> bool: ...
    @property
    def IsTextSearchEnabled(self) -> bool: ...
    @IsTextSearchEnabled.setter
    def IsTextSearchEnabled(self, value: bool) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def ItemContainerGenerator(self) -> ItemContainerGenerator: ...
    @property
    def ItemContainerTheme(self) -> ControlTheme: ...
    @ItemContainerTheme.setter
    def ItemContainerTheme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def ItemCount(self) -> int: ...
    @property
    def Items(self) -> ItemCollection: ...
    @property
    def ItemsPanel(self) -> ITemplate_1[Panel]: ...
    @ItemsPanel.setter
    def ItemsPanel(self, value: ITemplate_1[Panel]) -> ITemplate_1[Panel]: ...
    @property
    def ItemsPanelRoot(self) -> Panel: ...
    @property
    def ItemsSource(self) -> IEnumerable: ...
    @ItemsSource.setter
    def ItemsSource(self, value: IEnumerable) -> IEnumerable: ...
    @property
    def ItemsView(self) -> ItemsSourceView: ...
    @property
    def ItemTemplate(self) -> IDataTemplate: ...
    @ItemTemplate.setter
    def ItemTemplate(self, value: IDataTemplate) -> IDataTemplate: ...
    @property
    def KeyBindings(self) -> List_1[KeyBinding]: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Padding(self) -> Thickness: ...
    @Padding.setter
    def Padding(self, value: Thickness) -> Thickness: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def Presenter(self) -> ItemsPresenter: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def SelectedIndex(self) -> int: ...
    @SelectedIndex.setter
    def SelectedIndex(self, value: int) -> int: ...
    @property
    def SelectedItem(self) -> typing.Any: ...
    @SelectedItem.setter
    def SelectedItem(self, value: typing.Any) -> typing.Any: ...
    @property
    def SelectedValue(self) -> typing.Any: ...
    @SelectedValue.setter
    def SelectedValue(self, value: typing.Any) -> typing.Any: ...
    @property
    def SelectedValueBinding(self) -> IBinding: ...
    @SelectedValueBinding.setter
    def SelectedValueBinding(self, value: IBinding) -> IBinding: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def TabIndex(self) -> int: ...
    @TabIndex.setter
    def TabIndex(self, value: int) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Template(self) -> IControlTemplate: ...
    @Template.setter
    def Template(self, value: IControlTemplate) -> IControlTemplate: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def WrapSelection(self) -> bool: ...
    @WrapSelection.setter
    def WrapSelection(self, value: bool) -> bool: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    def BeginInit(self) -> None: ...
    def EndInit(self) -> None: ...
    @staticmethod
    def GetIsSelected(control: Control) -> bool: ...
    @staticmethod
    def SetIsSelected(control: Control, value: bool) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class TemplateAppliedEventArgs(RoutedEventArgs):
    def __init__(self, nameScope: INameScope) -> None: ...
    @property
    def Handled(self) -> bool: ...
    @Handled.setter
    def Handled(self, value: bool) -> bool: ...
    @property
    def NameScope(self) -> INameScope: ...
    @property
    def Route(self) -> RoutingStrategies: ...
    @Route.setter
    def Route(self, value: RoutingStrategies) -> RoutingStrategies: ...
    @property
    def RoutedEvent(self) -> RoutedEvent: ...
    @RoutedEvent.setter
    def RoutedEvent(self, value: RoutedEvent) -> RoutedEvent: ...
    @property
    def Source(self) -> typing.Any: ...
    @Source.setter
    def Source(self, value: typing.Any) -> typing.Any: ...


class TemplatedControl(Control):
    def __init__(self) -> None: ...
    BackgroundProperty : StyledProperty_1[IBrush]
    BackgroundSizingProperty : StyledProperty_1[BackgroundSizing]
    BorderBrushProperty : StyledProperty_1[IBrush]
    BorderThicknessProperty : StyledProperty_1[Thickness]
    CornerRadiusProperty : StyledProperty_1[CornerRadius]
    FontFamilyProperty : StyledProperty_1[FontFamily]
    FontFeaturesProperty : StyledProperty_1[FontFeatureCollection]
    FontSizeProperty : StyledProperty_1[float]
    FontStretchProperty : StyledProperty_1[FontStretch]
    FontStyleProperty : StyledProperty_1[FontStyle]
    FontWeightProperty : StyledProperty_1[FontWeight]
    ForegroundProperty : StyledProperty_1[IBrush]
    IsTemplateFocusTargetProperty : AttachedProperty_1[bool]
    PaddingProperty : StyledProperty_1[Thickness]
    TemplateAppliedEvent : RoutedEvent_1[TemplateAppliedEventArgs]
    TemplateProperty : StyledProperty_1[IControlTemplate]
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def Background(self) -> IBrush: ...
    @Background.setter
    def Background(self, value: IBrush) -> IBrush: ...
    @property
    def BackgroundSizing(self) -> BackgroundSizing: ...
    @BackgroundSizing.setter
    def BackgroundSizing(self, value: BackgroundSizing) -> BackgroundSizing: ...
    @property
    def BorderBrush(self) -> IBrush: ...
    @BorderBrush.setter
    def BorderBrush(self, value: IBrush) -> IBrush: ...
    @property
    def BorderThickness(self) -> Thickness: ...
    @BorderThickness.setter
    def BorderThickness(self, value: Thickness) -> Thickness: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def ContextFlyout(self) -> FlyoutBase: ...
    @ContextFlyout.setter
    def ContextFlyout(self, value: FlyoutBase) -> FlyoutBase: ...
    @property
    def ContextMenu(self) -> ContextMenu: ...
    @ContextMenu.setter
    def ContextMenu(self, value: ContextMenu) -> ContextMenu: ...
    @property
    def CornerRadius(self) -> CornerRadius: ...
    @CornerRadius.setter
    def CornerRadius(self, value: CornerRadius) -> CornerRadius: ...
    @property
    def Cursor(self) -> Cursor: ...
    @Cursor.setter
    def Cursor(self, value: Cursor) -> Cursor: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def DesiredSize(self) -> Size: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def Focusable(self) -> bool: ...
    @Focusable.setter
    def Focusable(self, value: bool) -> bool: ...
    @property
    def FocusAdorner(self) -> ITemplate_1[Control]: ...
    @FocusAdorner.setter
    def FocusAdorner(self, value: ITemplate_1[Control]) -> ITemplate_1[Control]: ...
    @property
    def FontFamily(self) -> FontFamily: ...
    @FontFamily.setter
    def FontFamily(self, value: FontFamily) -> FontFamily: ...
    @property
    def FontFeatures(self) -> FontFeatureCollection: ...
    @FontFeatures.setter
    def FontFeatures(self, value: FontFeatureCollection) -> FontFeatureCollection: ...
    @property
    def FontSize(self) -> float: ...
    @FontSize.setter
    def FontSize(self, value: float) -> float: ...
    @property
    def FontStretch(self) -> FontStretch: ...
    @FontStretch.setter
    def FontStretch(self, value: FontStretch) -> FontStretch: ...
    @property
    def FontStyle(self) -> FontStyle: ...
    @FontStyle.setter
    def FontStyle(self, value: FontStyle) -> FontStyle: ...
    @property
    def FontWeight(self) -> FontWeight: ...
    @FontWeight.setter
    def FontWeight(self, value: FontWeight) -> FontWeight: ...
    @property
    def Foreground(self) -> IBrush: ...
    @Foreground.setter
    def Foreground(self, value: IBrush) -> IBrush: ...
    @property
    def GestureRecognizers(self) -> GestureRecognizerCollection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @property
    def IsEffectivelyEnabled(self) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsFocused(self) -> bool: ...
    @property
    def IsHitTestVisible(self) -> bool: ...
    @IsHitTestVisible.setter
    def IsHitTestVisible(self, value: bool) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsKeyboardFocusWithin(self) -> bool: ...
    @IsKeyboardFocusWithin.setter
    def IsKeyboardFocusWithin(self, value: bool) -> bool: ...
    @property
    def IsLoaded(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @property
    def IsPointerOver(self) -> bool: ...
    @IsPointerOver.setter
    def IsPointerOver(self, value: bool) -> bool: ...
    @property
    def IsTabStop(self) -> bool: ...
    @IsTabStop.setter
    def IsTabStop(self, value: bool) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def KeyBindings(self) -> List_1[KeyBinding]: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Padding(self) -> Thickness: ...
    @Padding.setter
    def Padding(self, value: Thickness) -> Thickness: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def TabIndex(self) -> int: ...
    @TabIndex.setter
    def TabIndex(self, value: int) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Template(self) -> IControlTemplate: ...
    @Template.setter
    def Template(self, value: IControlTemplate) -> IControlTemplate: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    def ApplyTemplate(self) -> None: ...
    @staticmethod
    def GetIsTemplateFocusTarget(control: Control) -> bool: ...
    @staticmethod
    def SetIsTemplateFocusTarget(control: Control, value: bool) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...

