import typing, clr
from System import IEquatable_1, Guid
from System.Collections.Generic import IReadOnlyCollection_1, List_1, IReadOnlyList_1

class MediaFileId(IEquatable_1[MediaFileId]):
    def __init__(self, Value: Guid) -> None: ...
    @property
    def IsEmpty(self) -> bool: ...
    @property
    def Value(self) -> Guid: ...
    @Value.setter
    def Value(self, value: Guid) -> Guid: ...
    def Deconstruct(self, Value: clr.Reference[Guid]) -> None: ...
    def GetHashCode(self) -> int: ...
    @staticmethod
    def New() -> MediaFileId: ...
    def __eq__(self, left: MediaFileId, right: MediaFileId) -> bool: ...
    def __ne__(self, left: MediaFileId, right: MediaFileId) -> bool: ...
    @staticmethod
    def Parse(value: str) -> MediaFileId: ...
    def ToString(self) -> str: ...
    @staticmethod
    def TryParse(value: str, result: clr.Reference[MediaFileId]) -> bool: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: MediaFileId) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class MediaFileIndex:
    def __init__(self, mediaRoot: str) -> None: ...
    @property
    def All(self) -> IReadOnlyCollection_1[MediaFileInfo]: ...
    @property
    def Count(self) -> int: ...
    def Build(self) -> None: ...
    def Contains(self, id: MediaFileId) -> bool: ...
    def TryGetInfo(self, id: MediaFileId) -> MediaFileInfo: ...
    def TryResolve(self, id: MediaFileId) -> str: ...


class MediaFileInfo(IEquatable_1[MediaFileInfo]):
    def __init__(self, Id: MediaFileId, FullPath: str, OriginalFileName: str, Extension: str) -> None: ...
    @property
    def Extension(self) -> str: ...
    @Extension.setter
    def Extension(self, value: str) -> str: ...
    @property
    def FullPath(self) -> str: ...
    @FullPath.setter
    def FullPath(self, value: str) -> str: ...
    @property
    def Id(self) -> MediaFileId: ...
    @Id.setter
    def Id(self, value: MediaFileId) -> MediaFileId: ...
    @property
    def OriginalFileName(self) -> str: ...
    @OriginalFileName.setter
    def OriginalFileName(self, value: str) -> str: ...
    def Deconstruct(self, Id: clr.Reference[MediaFileId], FullPath: clr.Reference[str], OriginalFileName: clr.Reference[str], Extension: clr.Reference[str]) -> None: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: MediaFileInfo, right: MediaFileInfo) -> bool: ...
    def __ne__(self, left: MediaFileInfo, right: MediaFileInfo) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: MediaFileInfo) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class MediaRoutingConfig:
    def __init__(self, rules: List_1[MediaRoutingRule], defaultDirectory: str) -> None: ...
    @property
    def DefaultDirectory(self) -> str: ...
    @property
    def Rules(self) -> IReadOnlyList_1[MediaRoutingRule]: ...
    @staticmethod
    def Default() -> MediaRoutingConfig: ...
    def ResolveDirectory(self, sourceTag: str) -> str: ...


class MediaRoutingRule(IEquatable_1[MediaRoutingRule]):
    def __init__(self, SourceTagPrefix: str, TargetDirectory: str) -> None: ...
    @property
    def SourceTagPrefix(self) -> str: ...
    @SourceTagPrefix.setter
    def SourceTagPrefix(self, value: str) -> str: ...
    @property
    def TargetDirectory(self) -> str: ...
    @TargetDirectory.setter
    def TargetDirectory(self, value: str) -> str: ...
    def Deconstruct(self, SourceTagPrefix: clr.Reference[str], TargetDirectory: clr.Reference[str]) -> None: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: MediaRoutingRule, right: MediaRoutingRule) -> bool: ...
    def __ne__(self, left: MediaRoutingRule, right: MediaRoutingRule) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: MediaRoutingRule) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class MediaStorageService:
    def __init__(self, mediaRoot: str, index: MediaFileIndex, routingConfig: MediaRoutingConfig) -> None: ...
    def Exists(self, id: MediaFileId) -> bool: ...
    def StoreFile(self, sourceFilePath: str, sourceTag: str, originalFileName: str) -> MediaFileId: ...
    def StoreFileWithId(self, id: MediaFileId, sourceFilePath: str, sourceTag: str, originalFileName: str) -> None: ...
    def TryResolve(self, id: MediaFileId) -> str: ...

