import typing, clr, abc
from JAStudio.Core.Note import JPNote
from System import IEquatable_1
from System.Collections.Generic import List_1

class IMediaSyncService(typing.Protocol):
    @abc.abstractmethod
    def SyncMedia(self, note: JPNote) -> None: ...


class MediaReference(IEquatable_1[MediaReference]):
    def __init__(self, FileName: str, Type: MediaType) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> str: ...
    @property
    def Type(self) -> MediaType: ...
    @Type.setter
    def Type(self, value: MediaType) -> MediaType: ...
    def Deconstruct(self, FileName: clr.Reference[str], Type: clr.Reference[MediaType]) -> None: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: MediaReference, right: MediaReference) -> bool: ...
    def __ne__(self, left: MediaReference, right: MediaReference) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: MediaReference) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class MediaReferenceExtractor(abc.ABC):
    @staticmethod
    def ExtractAll(note: JPNote) -> List_1[MediaReference]: ...


class MediaSyncService(IMediaSyncService):
    def __init__(self, ankiMediaDir: str, databaseDir: str) -> None: ...
    def SyncMedia(self, note: JPNote) -> None: ...


class MediaType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Audio : MediaType # 0
    Image : MediaType # 1


class NullMediaSyncService(IMediaSyncService):
    def __init__(self) -> None: ...
    def SyncMedia(self, note: JPNote) -> None: ...

