import typing, clr
from Avalonia.Rendering.Composition import CompositionObject, Compositor
from Avalonia.Media import Color
from System.Numerics import Matrix3x2, Matrix4x4, Quaternion, Vector2, Vector3, Vector4
from System.Collections.Generic import IDictionary_2, IEnumerator_1, KeyValuePair_2, IReadOnlyDictionary_2
from System import TimeSpan
from Avalonia.Animation import PlaybackDirection
from Avalonia.Animation.Easings import Easing

class AnimationDelayBehavior(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    SetInitialValueAfterDelay : AnimationDelayBehavior # 0
    SetInitialValueBeforeDelay : AnimationDelayBehavior # 1


class AnimationIterationBehavior(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Count : AnimationIterationBehavior # 0
    Forever : AnimationIterationBehavior # 1


class AnimationStopBehavior(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    LeaveCurrentValue : AnimationStopBehavior # 0
    SetToInitialValue : AnimationStopBehavior # 1
    SetToFinalValue : AnimationStopBehavior # 2


class CompositionAnimation(CompositionObject, ICompositionAnimationBase):
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    def ClearAllParameters(self) -> None: ...
    def ClearParameter(self, key: str) -> None: ...
    def SetColorParameter(self, key: str, value: Color) -> None: ...
    def SetMatrix3x2Parameter(self, key: str, value: Matrix3x2) -> None: ...
    def SetMatrix4x4Parameter(self, key: str, value: Matrix4x4) -> None: ...
    def SetQuaternionParameter(self, key: str, value: Quaternion) -> None: ...
    def SetReferenceParameter(self, key: str, compositionObject: CompositionObject) -> None: ...
    def SetScalarParameter(self, key: str, value: float) -> None: ...
    def SetVector2Parameter(self, key: str, value: Vector2) -> None: ...
    def SetVector3Parameter(self, key: str, value: Vector3) -> None: ...
    def SetVector4Parameter(self, key: str, value: Vector4) -> None: ...


class CompositionAnimationGroup(CompositionObject, ICompositionAnimationBase):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    def Add(self, value: CompositionAnimation) -> None: ...
    def Remove(self, value: CompositionAnimation) -> None: ...
    def RemoveAll(self) -> None: ...


class ExpressionAnimation(CompositionAnimation):
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def Expression(self) -> str: ...
    @Expression.setter
    def Expression(self, value: str) -> str: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...


class ICompositionAnimationBase(typing.Protocol):
    pass


class ImplicitAnimationCollection(CompositionObject, IDictionary_2[str, ICompositionAnimationBase]):
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def Count(self) -> int: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Size(self) -> int: ...
    def Add(self, key: str, value: ICompositionAnimationBase) -> None: ...
    def Clear(self) -> None: ...
    def ContainsKey(self, key: str) -> bool: ...
    def GetEnumerator(self) -> IEnumerator_1[KeyValuePair_2[str, ICompositionAnimationBase]]: ...
    def GetView(self) -> IReadOnlyDictionary_2[str, ICompositionAnimationBase]: ...
    def HasKey(self, key: str) -> bool: ...
    def Insert(self, key: str, animation: ICompositionAnimationBase) -> None: ...
    def Lookup(self, key: str) -> ICompositionAnimationBase: ...
    def Remove(self, key: str) -> bool: ...
    def TryGetValue(self, key: str, value: clr.Reference[ICompositionAnimationBase]) -> bool: ...
    def __getitem__(self, key: str) -> ICompositionAnimationBase: ...
    def __setitem__(self, key: str, value: ICompositionAnimationBase) -> None: ...


class KeyFrameAnimation(CompositionAnimation):
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    def InsertExpressionKeyFrame(self, normalizedProgressKey: float, value: str, easingFunction: Easing = ...) -> None: ...

