import typing, clr
from Avalonia.Controls import Control

class ItemContainerGenerator:
    def ClearItemContainer(self, container: Control) -> None: ...
    def ContainerFromIndex(self, index: int) -> Control: ...
    def CreateContainer(self, item: typing.Any, index: int, recycleKey: typing.Any) -> Control: ...
    def IndexFromContainer(self, container: Control) -> int: ...
    def ItemContainerIndexChanged(self, container: Control, oldIndex: int, newIndex: int) -> None: ...
    def ItemContainerPrepared(self, container: Control, item: typing.Any, index: int) -> None: ...
    def NeedsContainer(self, item: typing.Any, index: int, recycleKey: clr.Reference[typing.Any]) -> bool: ...
    def PrepareItemContainer(self, container: Control, item: typing.Any, index: int) -> None: ...

