import typing, abc
from System.Collections.Generic import List_1, HashSet_1, Dictionary_2, IEnumerable_1, IEnumerator_1, IReadOnlyList_1
from System import Action, Guid, IDisposable, Func_2
from JAStudio.Core.Note.Sentences import SentenceNote
from JAStudio.Core.Note.Vocabulary import VocabNote, WritableAudioValue, VocabNoteFactory, VocabNoteGeneratedData
from JAStudio.Core.Note.Collection import JPCollection, CardStudyingStatus
from JAStudio.Core.Storage.Media import NoteMedia
from JAStudio.Core.Note.NoteFields import MediaReference, WritableStringValue, WritableImageValue
from JAStudio.Core.Note.CorpusData import CorpusObjectData, KanjiData
from Compze.Core.Public import EntityId
from JAStudio.Core.Configuration import JapaneseConfig, Settings
from JAStudio.Core.LanguageServices.JamdictEx import DictLookup
from JAStudio.Core.TaskRunners import TaskRunner

class Builtin(abc.ABC):
    Card : str
    Deck : str
    Note : str
    Tag : str


class CardOperations:
    def SetImplementation(self, implementation: ICardOperations) -> None: ...
    def SuspendAllCardsForNote(self, noteId: NoteId) -> None: ...
    def UnsuspendAllCardsForNote(self, noteId: NoteId) -> None: ...


class CardTypes(abc.ABC):
    Listening : str
    Reading : str


class DifficultyCalculator:
    def __init__(self, startingSeconds: float, hiraganaSeconds: float, katakataSeconds: float, kanjiSeconds: float) -> None: ...
    def AllowedSeconds(self, text: str) -> float: ...
    @staticmethod
    def IsOtherCharacter(ch: str) -> bool: ...


class ExternalNoteIdMap:
    def __init__(self) -> None: ...
    def AllExternalIds(self) -> List_1[int]: ...
    def Clear(self) -> None: ...
    def FromExternalId(self, externalId: int) -> NoteId: ...
    def Register(self, externalId: int, noteId: NoteId) -> None: ...
    def RequireExternalId(self, noteId: NoteId) -> int: ...
    def ToExternalId(self, noteId: NoteId) -> typing.Optional[int]: ...
    def Unregister(self, externalId: int) -> None: ...


class IBackendNoteCreator(typing.Protocol):
    @abc.abstractmethod
    def CreateKanji(self, note: KanjiNote, callback: Action) -> None: ...
    @abc.abstractmethod
    def CreateSentence(self, note: SentenceNote, callback: Action) -> None: ...
    @abc.abstractmethod
    def CreateVocab(self, note: VocabNote, callback: Action) -> None: ...


class ICardOperations(typing.Protocol):
    @abc.abstractmethod
    def SuspendAllCardsForNote(self, noteId: NoteId) -> None: ...
    @abc.abstractmethod
    def UnsuspendAllCardsForNote(self, noteId: NoteId) -> None: ...


class JPNote(abc.ABC):
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def Guard(self) -> NoteGuard: ...
    @property
    def IsFlushing(self) -> bool: ...
    @property
    def Media(self) -> NoteMedia: ...
    @Media.setter
    def Media(self, value: NoteMedia) -> NoteMedia: ...
    @property
    def MediaReferences(self) -> List_1[MediaReference]: ...
    @property
    def RecursiveFlushGuard(self) -> NoteFlushGuard: ...
    @property
    def Services(self) -> NoteServices: ...
    @property
    def Tags(self) -> NoteTags: ...
    def CopyStudyingStatusFrom(self, other: JPNote) -> None: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def Flush(self) -> None: ...
    @abc.abstractmethod
    def GetAnswer(self) -> str: ...
    def GetData(self) -> NoteData: ...
    def GetHashCode(self) -> int: ...
    def GetId(self) -> NoteId: ...
    def GetMetaTags(self) -> HashSet_1[str]: ...
    @abc.abstractmethod
    def GetQuestion(self) -> str: ...
    def GetSourceTag(self) -> str: ...
    def HasActiveCards(self) -> bool: ...
    def HasSuspendedCards(self) -> bool: ...
    def IsStudying(self, cardType: str = ...) -> bool: ...
    def IsStudyingListening(self) -> bool: ...
    def IsStudyingRead(self) -> bool: ...
    def OnTagsUpdated(self) -> None: ...
    def PriorityTagValue(self) -> int: ...
    def SetStudyingStatus(self, status: CardStudyingStatus) -> None: ...
    def SuspendAllCards(self) -> None: ...
    @abc.abstractmethod
    def ToCorpusData(self) -> CorpusObjectData: ...
    def ToString(self) -> str: ...
    def UnsuspendAllCards(self) -> None: ...
    def UpdateGeneratedData(self) -> None: ...
    @abc.abstractmethod
    def UpdateInCache(self) -> None: ...


class KanjiId(NoteId):
    def __init__(self, id: Guid) -> None: ...
    @property
    def Value(self) -> Guid: ...
    @staticmethod
    def New() -> KanjiId: ...


class KanjiNote(JPNote):
    def __init__(self, services: NoteServices, data: KanjiData = ...) -> None: ...
    @property
    def ActiveAnswer(self) -> WritableStringValue: ...
    @property
    def ActiveMnemonic(self) -> str: ...
    @property
    def AllRadicals(self) -> List_1[str]: ...
    @property
    def AnswerText(self) -> str: ...
    @property
    def Audio(self) -> WritableAudioValue: ...
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def Guard(self) -> NoteGuard: ...
    @property
    def Image(self) -> WritableImageValue: ...
    @property
    def IsFlushing(self) -> bool: ...
    @property
    def KanjiReferences(self) -> WritableStringValue: ...
    @property
    def MeaningInfo(self) -> WritableStringValue: ...
    @property
    def Media(self) -> NoteMedia: ...
    @Media.setter
    def Media(self, value: NoteMedia) -> NoteMedia: ...
    @property
    def MediaReferences(self) -> List_1[MediaReference]: ...
    @property
    def PrimaryMeaning(self) -> str: ...
    @property
    def PrimaryRadicalMeaning(self) -> str: ...
    @property
    def PrimaryReadings(self) -> List_1[str]: ...
    @property
    def PrimaryReadingsKun(self) -> List_1[str]: ...
    @property
    def PrimaryReadingsNan(self) -> List_1[str]: ...
    @property
    def PrimaryReadingsOn(self) -> List_1[str]: ...
    @property
    def PrimaryReadingsTtsAudio(self) -> WritableStringValue: ...
    @property
    def PrimaryVocab(self) -> List_1[str]: ...
    @PrimaryVocab.setter
    def PrimaryVocab(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def PrimaryVocabsOrDefaults(self) -> List_1[str]: ...
    @property
    def Radicals(self) -> List_1[str]: ...
    @property
    def ReadingInfo(self) -> WritableStringValue: ...
    @property
    def ReadingKunHtml(self) -> WritableStringValue: ...
    @property
    def ReadingKunListHtml(self) -> List_1[str]: ...
    @property
    def ReadingMnemonic(self) -> WritableStringValue: ...
    @property
    def ReadingNanHtml(self) -> WritableStringValue: ...
    @property
    def ReadingNanListHtml(self) -> List_1[str]: ...
    @property
    def ReadingOnHtml(self) -> WritableStringValue: ...
    @property
    def ReadingOnListHtml(self) -> List_1[str]: ...
    @property
    def ReadingsClean(self) -> List_1[str]: ...
    @property
    def ReadingsKun(self) -> List_1[str]: ...
    @property
    def ReadingsOn(self) -> List_1[str]: ...
    @property
    def RecursiveFlushGuard(self) -> NoteFlushGuard: ...
    @property
    def RelatedConfusedWith(self) -> List_1[str]: ...
    @property
    def RelatedConfusedWithRaw(self) -> str: ...
    @RelatedConfusedWithRaw.setter
    def RelatedConfusedWithRaw(self, value: str) -> str: ...
    @property
    def Services(self) -> NoteServices: ...
    @property
    def SourceAnswer(self) -> WritableStringValue: ...
    @property
    def SourceMeaningMnemonic(self) -> WritableStringValue: ...
    @property
    def Tags(self) -> NoteTags: ...
    @property
    def UserAnswer(self) -> WritableStringValue: ...
    @property
    def UserMnemonic(self) -> WritableStringValue: ...
    @property
    def UserSimilarMeaning(self) -> List_1[str]: ...
    @property
    def UserSimilarMeaningRaw(self) -> str: ...
    @UserSimilarMeaningRaw.setter
    def UserSimilarMeaningRaw(self, value: str) -> str: ...
    def AddPrimaryKunReading(self, reading: str) -> None: ...
    def AddPrimaryOnReading(self, reading: str) -> None: ...
    def AddRelatedConfusedWith(self, newConfusedWith: str) -> None: ...
    def AddUserSimilarMeaning(self, newSynonymQuestion: str, isRecursiveCall: bool = ...) -> None: ...
    def BootstrapMnemonicFromRadicals(self) -> None: ...
    @staticmethod
    def Create(services: NoteServices, question: str, answer: str, onReadings: str, kunReading: str) -> KanjiNote: ...
    def GenerateDefaultPrimaryVocab(self) -> List_1[str]: ...
    def GetAnswer(self) -> str: ...
    def GetQuestion(self) -> str: ...
    def GetRadicalsNotes(self) -> List_1[KanjiNote]: ...
    def GetVocabNotes(self) -> List_1[VocabNote]: ...
    def GetVocabNotesSorted(self) -> List_1[VocabNote]: ...
    def PopulateRadicalsFromMnemonicTags(self) -> None: ...
    def PositionPrimaryVocab(self, vocab: str, newIndex: int = ...) -> None: ...
    def ReadingInVocabReading(self, kanjiReading: str, vocabReading: str, vocabForm: str) -> bool: ...
    def RemovePrimaryKunReading(self, reading: str) -> None: ...
    def RemovePrimaryOnReading(self, reading: str) -> None: ...
    def RemovePrimaryVocab(self, vocab: str) -> None: ...
    def SetQuestion(self, value: str) -> None: ...
    def SetRadicals(self, value: str) -> None: ...
    def TagVocabReadings(self, vocab: VocabNote) -> List_1[str]: ...
    def ToCorpusData(self) -> CorpusObjectData: ...
    def UpdateGeneratedData(self) -> None: ...
    def UpdateInCache(self) -> None: ...


class KanjiNoteMnemonicMaker:
    def CreateDefaultMnemonic(self, kanjiNote: KanjiNote) -> str: ...


class Mine(abc.ABC):
    AppName : str
    AppStillLoadingMessage : str
    VocabPrefixSuffixMarker : str


class NoteData:
    def __init__(self, id: NoteId, fields: Dictionary_2[str, str], tags: List_1[str]) -> None: ...
    @property
    def Fields(self) -> Dictionary_2[str, str]: ...
    @Fields.setter
    def Fields(self, value: Dictionary_2[str, str]) -> Dictionary_2[str, str]: ...
    @property
    def Id(self) -> NoteId: ...
    @Id.setter
    def Id(self, value: NoteId) -> NoteId: ...
    @property
    def Tags(self) -> List_1[str]: ...
    @Tags.setter
    def Tags(self, value: List_1[str]) -> List_1[str]: ...


class NoteFlushGuard:
    def __init__(self, note: JPNote) -> None: ...
    @property
    def IsFlushing(self) -> bool: ...
    def Flush(self) -> None: ...
    def PauseFlushing(self) -> IDisposable: ...


class NoteGuard:
    def __init__(self, flush: Action) -> None: ...
    def Update(self, mutation: Action) -> None: ...


class NoteId(EntityId):
    def __init__(self, id: Guid) -> None: ...
    @property
    def Value(self) -> Guid: ...
    @staticmethod
    def Parse(value: str) -> NoteId: ...


class NoteServices:
    @property
    def CardOperations(self) -> ICardOperations: ...
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def Config(self) -> JapaneseConfig: ...
    @property
    def DictLookup(self) -> DictLookup: ...
    @property
    def ExternalNoteIdMap(self) -> ExternalNoteIdMap: ...
    @property
    def KanjiNoteMnemonicMaker(self) -> KanjiNoteMnemonicMaker: ...
    @property
    def Settings(self) -> Settings: ...
    @property
    def TaskRunner(self) -> TaskRunner: ...
    @property
    def VocabNoteFactory(self) -> VocabNoteFactory: ...
    @property
    def VocabNoteGeneratedData(self) -> VocabNoteGeneratedData: ...


class NoteTags(IEnumerable_1[Tag]):
    def __init__(self, note: JPNote, tags: List_1[str] = ...) -> None: ...
    def Contains(self, value: Tag) -> bool: ...
    def GetEnumerator(self) -> IEnumerator_1[Tag]: ...
    def Set(self, tag: Tag) -> None: ...
    def Toggle(self, tag: Tag, on: bool) -> None: ...
    def ToStringList(self) -> List_1[str]: ...
    def Unset(self, tag: Tag) -> None: ...


class NoteTypes(abc.ABC):
    All : HashSet_1[str]
    AllList : IReadOnlyList_1[str]
    ImmersionKit : str
    Kanji : str
    Sentence : str
    Vocab : str
    @staticmethod
    def IdFactoryFromName(noteTypeName: str) -> Func_2[Guid, NoteId]: ...


class SentenceId(NoteId):
    def __init__(self, id: Guid) -> None: ...
    @property
    def Value(self) -> Guid: ...
    @staticmethod
    def New() -> SentenceId: ...


class Tag:
    @property
    def Bit(self) -> int: ...
    @property
    def Id(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @staticmethod
    def FromId(id: int) -> Tag: ...
    @staticmethod
    def FromName(name: str) -> Tag: ...


class Tags(abc.ABC):
    DisableKanaOnly : Tag
    PriorityFolder : str
    TTSAudio : Tag
    UsuallyKanaOnly : Tag

    class Kanji(abc.ABC):
        HasNonPrimaryOnReadingVocab : Tag
        HasNonPrimaryOnReadingVocabWithOnlyKnownKanji : Tag
        HasPrimaryReadingWithNoStudyingVocab : Tag
        HasStudyingVocabForEachPrimaryReading : Tag
        HasStudyingVocabWithNoMatchingPrimaryReading : Tag
        InAnyVocabForm : Tag
        InVocabMainForm : Tag
        IsRadical : Tag
        IsRadicalPurely : Tag
        IsRadicalSilent : Tag
        WithNoPrimaryOnReadings : Tag
        WithNoPrimaryReadings : Tag
        WithSingleKanjiVocab : Tag
        WithSingleKanjiVocabWithDifferentReading : Tag
        WithStudyingSingleKanjiVocabWithDifferentReading : Tag
        WithStudyingVocab : Tag
        WithStudyingVocabWithPrimaryOnReading : Tag
        WithVocabWithPrimaryOnReading : Tag


    class Sentence(abc.ABC):

        class Uses(abc.ABC):
            HiddenMatches : Tag
            IncorrectMatches : Tag



    class Source(abc.ABC):
        Folder : str
        ImmersionKit : Tag
        Jamdict : Tag


    class Vocab(abc.ABC):
        HasNoStudyingSentences : Tag
        IsCompositionallyTransparentCompound : Tag
        IsIchidanHidingGodanPotential : Tag
        QuestionOverridesForm : Tag
        Root : str

        class Matching(abc.ABC):
            IsInflectingWord : Tag
            IsPoisonWord : Tag
            YieldLastTokenToOverlappingCompound : Tag

            class Forbids(abc.ABC):
                AutoYielding : Tag
                DictionaryFormPrefix : Tag
                DictionaryFormStem : Tag
                Godan : Tag
                GodanImperative : Tag
                GodanImperativePrefix : Tag
                GodanPotential : Tag
                Ichidan : Tag
                IchidanImperative : Tag
                Irrealis : Tag
                MasuStem : Tag
                PastTenseStem : Tag
                PrecedingAdverb : Tag
                SentenceEnd : Tag
                SentenceStart : Tag
                Surface : Tag
                TeFormPrefix : Tag
                TeFormStem : Tag


            class Requires(abc.ABC):
                Compound : Tag
                DictionaryFormPrefix : Tag
                DictionaryFormStem : Tag
                FolderName : str
                Godan : Tag
                GodanImperative : Tag
                GodanImperativePrefix : Tag
                GodanPotential : Tag
                Ichidan : Tag
                IchidanImperative : Tag
                Irrealis : Tag
                MasuStem : Tag
                PastTenseStem : Tag
                PrecedingAdverb : Tag
                SentenceEnd : Tag
                SentenceStart : Tag
                SingleToken : Tag
                Surface : Tag
                TeFormPrefix : Tag
                TeFormStem : Tag


            class Todo(abc.ABC):
                WithPrecedingVowel : Tag


            class Uses(abc.ABC):
                PrefixIsNot : Tag
                RequiredPrefix : Tag
                SuffixIsNot : Tag
                SurfaceIsNot : Tag



        class Register(abc.ABC):
            Archaic : Tag
            Childish : Tag
            Derogatory : Tag
            Formal : Tag
            Honorific : Tag
            Humble : Tag
            Informal : Tag
            Literary : Tag
            Polite : Tag
            RoughMasculine : Tag
            Sensitive : Tag
            Slang : Tag
            SoftFeminine : Tag
            Vulgar : Tag




class VocabId(NoteId):
    def __init__(self, id: Guid) -> None: ...
    @property
    def Value(self) -> Guid: ...
    @staticmethod
    def New() -> VocabId: ...

