import typing, abc
from System import Action, IDisposable, Array_1
from JAStudio.Core.Note.Collection import JPCollection, CardStudyingStatus
from System.Collections.Generic import HashSet_1, List_1, Dictionary_2, IReadOnlyList_1, IEnumerable_1, IEnumerator_1
from JAStudio.Core.Anki import AnkiCardOperations
from JAStudio.Core.Configuration import JapaneseConfig, Settings
from JAStudio.Core.LanguageServices.JamdictEx import DictLookup
from JAStudio.Core.TaskRunners import TaskRunner
from JAStudio.Core.Note.Vocabulary import VocabNoteFactory, VocabNoteGeneratedData, VocabNoteAudio, VocabCloner, VocabNoteUserCompoundParts, VocabNoteConjugator, VocabNoteForms, VocabNoteKanji, VocabNoteMatchingConfiguration, VocabNoteMetaData, VocabNotePartsOfSpeech, VocabNoteQuestion, VocabNoteRegister, VocabNoteSentences, VocabNoteUserFields
from JAStudio.Core.Note.NoteFields import MutableStringField, StripHtmlOnReadFallbackStringField, WritableAudioField, MutableSerializedObjectField_1, SentenceQuestionField, MutableCommaSeparatedStringsListField
from JAStudio.Core.LanguageServices.JanomeEx import AnalysisServices
from JAStudio.Core.Note.Sentences import CachingSentenceConfigurationField, ParsingResult, SentenceUserFields
from JAStudio.Core.LanguageServices.JanomeEx.WordExtraction import TextAnalysis
from JAStudio.Core.Note.Vocabulary.RelatedVocab import RelatedVocab

class Builtin(abc.ABC):
    Card : str
    Deck : str
    Note : str
    Tag : str


class CardTypes(abc.ABC):
    Listening : str
    Reading : str


class DifficultyCalculator:
    def __init__(self, startingSeconds: float, hiraganaSeconds: float, katakataSeconds: float, kanjiSeconds: float) -> None: ...
    def AllowedSeconds(self, text: str) -> float: ...
    @staticmethod
    def IsOtherCharacter(ch: str) -> bool: ...


class IBackendNoteCreator(typing.Protocol):
    @abc.abstractmethod
    def CreateKanji(self, note: KanjiNote, callback: Action) -> None: ...
    @abc.abstractmethod
    def CreateSentence(self, note: SentenceNote, callback: Action) -> None: ...
    @abc.abstractmethod
    def CreateVocab(self, note: VocabNote, callback: Action) -> None: ...


class ImmersionKitSentenceNoteFields(abc.ABC):
    Answer : str
    Audio : str
    Id : str
    Question : str
    Reading : str
    Screenshot : str


class JPNote(abc.ABC):
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def IsFlushing(self) -> bool: ...
    @property
    def RecursiveFlushGuard(self) -> NoteFlushGuard: ...
    @property
    def Services(self) -> NoteServices: ...
    @property
    def Tags(self) -> NoteTags: ...
    def CopyStudyingStatusFrom(self, other: JPNote) -> None: ...
    def Equals(self, obj: typing.Any) -> bool: ...
    def Flush(self) -> None: ...
    def GetAnswer(self) -> str: ...
    def GetData(self) -> NoteData: ...
    def GetDependenciesRecursive(self) -> HashSet_1[JPNote]: ...
    def GetDirectDependencies(self) -> HashSet_1[JPNote]: ...
    def GetField(self, fieldName: str) -> str: ...
    def GetHashCode(self) -> int: ...
    def GetId(self) -> int: ...
    def GetMetaTags(self) -> HashSet_1[str]: ...
    def GetQuestion(self) -> str: ...
    def GetSourceTag(self) -> str: ...
    def HasActiveCards(self) -> bool: ...
    def HasSuspendedCards(self) -> bool: ...
    def IsStudying(self, cardType: str = ...) -> bool: ...
    def IsStudyingListening(self) -> bool: ...
    def IsStudyingRead(self) -> bool: ...
    def OnTagsUpdated(self) -> None: ...
    def PriorityTagValue(self) -> int: ...
    def SetField(self, fieldName: str, value: str) -> None: ...
    def SetId(self, id: int) -> None: ...
    def SetStudyingStatus(self, status: CardStudyingStatus) -> None: ...
    def SuspendAllCards(self) -> None: ...
    def ToString(self) -> str: ...
    def UnsuspendAllCards(self) -> None: ...
    def UpdateGeneratedData(self) -> None: ...
    @abc.abstractmethod
    def UpdateInCache(self) -> None: ...


class KanjiNote(JPNote):
    def __init__(self, services: NoteServices, data: NoteData = ...) -> None: ...
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def IsFlushing(self) -> bool: ...
    @property
    def RecursiveFlushGuard(self) -> NoteFlushGuard: ...
    @property
    def Services(self) -> NoteServices: ...
    @property
    def Tags(self) -> NoteTags: ...
    def AddPrimaryKunReading(self, reading: str) -> None: ...
    def AddPrimaryOnReading(self, reading: str) -> None: ...
    def AddRelatedConfusedWith(self, newConfusedWith: str) -> None: ...
    def AddUserSimilarMeaning(self, newSynonymQuestion: str, isRecursiveCall: bool = ...) -> None: ...
    def BootstrapMnemonicFromRadicals(self) -> None: ...
    @staticmethod
    def Create(services: NoteServices, question: str, answer: str, onReadings: str, kunReading: str) -> KanjiNote: ...
    def GenerateDefaultPrimaryVocab(self) -> List_1[str]: ...
    def GetActiveMnemonic(self) -> str: ...
    def GetAnswer(self) -> str: ...
    def GetAnswerText(self) -> str: ...
    def GetDirectDependencies(self) -> HashSet_1[JPNote]: ...
    def GetPrimaryMeaning(self) -> str: ...
    def GetPrimaryRadicalMeaning(self) -> str: ...
    def GetPrimaryReadings(self) -> List_1[str]: ...
    def GetPrimaryReadingsKun(self) -> List_1[str]: ...
    def GetPrimaryReadingsNan(self) -> List_1[str]: ...
    def GetPrimaryReadingsOn(self) -> List_1[str]: ...
    def GetPrimaryVocab(self) -> List_1[str]: ...
    def GetPrimaryVocabsOrDefaults(self) -> List_1[str]: ...
    def GetQuestion(self) -> str: ...
    def GetRadicals(self) -> List_1[str]: ...
    def GetRadicalsNotes(self) -> List_1[KanjiNote]: ...
    def GetReadingKunHtml(self) -> str: ...
    def GetReadingKunListHtml(self) -> List_1[str]: ...
    def GetReadingNanHtml(self) -> str: ...
    def GetReadingNanListHtml(self) -> List_1[str]: ...
    def GetReadingOnHtml(self) -> str: ...
    def GetReadingOnListHtml(self) -> List_1[str]: ...
    def GetReadingsClean(self) -> List_1[str]: ...
    def GetReadingsKun(self) -> List_1[str]: ...
    def GetReadingsOn(self) -> List_1[str]: ...
    def GetRelatedConfusedWith(self) -> List_1[str]: ...
    def GetSourceMeaningMnemonic(self) -> str: ...
    def GetUserAnswer(self) -> str: ...
    def GetUserMnemonic(self) -> str: ...
    def GetUserSimilarMeaning(self) -> List_1[str]: ...
    def GetVocabNotes(self) -> List_1[VocabNote]: ...
    def GetVocabNotesSorted(self) -> List_1[VocabNote]: ...
    def PopulateRadicalsFromMnemonicTags(self) -> None: ...
    def PositionPrimaryVocab(self, vocab: str, newIndex: int = ...) -> None: ...
    def ReadingInVocabReading(self, kanjiReading: str, vocabReading: str, vocabForm: str) -> bool: ...
    def RemovePrimaryKunReading(self, reading: str) -> None: ...
    def RemovePrimaryOnReading(self, reading: str) -> None: ...
    def RemovePrimaryVocab(self, vocab: str) -> None: ...
    def SetPrimaryVocab(self, value: List_1[str]) -> None: ...
    def SetQuestion(self, value: str) -> None: ...
    def SetRadicals(self, value: str) -> None: ...
    def SetReadingKun(self, value: str) -> None: ...
    def SetReadingOn(self, value: str) -> None: ...
    def SetUserAnswer(self, value: str) -> None: ...
    def SetUserMnemonic(self, value: str) -> None: ...
    def TagVocabReadings(self, vocab: VocabNote) -> List_1[str]: ...
    def UpdateGeneratedData(self) -> None: ...
    def UpdateInCache(self) -> None: ...


class KanjiNoteMnemonicMaker:
    def CreateDefaultMnemonic(self, kanjiNote: KanjiNote) -> str: ...


class Mine(abc.ABC):
    AppName : str
    AppStillLoadingMessage : str
    VocabPrefixSuffixMarker : str


class MyNoteFields(abc.ABC):
    Answer : str
    Question : str


class NoteData:
    def __init__(self, id: int, fields: Dictionary_2[str, str], tags: List_1[str]) -> None: ...
    @property
    def Fields(self) -> Dictionary_2[str, str]: ...
    @Fields.setter
    def Fields(self, value: Dictionary_2[str, str]) -> Dictionary_2[str, str]: ...
    @property
    def Id(self) -> int: ...
    @Id.setter
    def Id(self, value: int) -> int: ...
    @property
    def Tags(self) -> List_1[str]: ...
    @Tags.setter
    def Tags(self, value: List_1[str]) -> List_1[str]: ...
    @staticmethod
    def FromPythonListOfNoteData(pythonList: typing.Any) -> IReadOnlyList_1[NoteData]: ...
    @staticmethod
    def FromPythonNoteData(item: typing.Any) -> NoteData: ...


class NoteFieldsConstants(abc.ABC):
    NoteId : str

    class Kanji(abc.ABC):
        ActiveAnswer : str
        Audio : str
        MeaningInfo : str
        PrimaryVocab : str
        Question : str
        Radicals : str
        ReadingInfo : str
        ReadingKun : str
        ReadingMnemonic : str
        ReadingNan : str
        ReadingOn : str
        RelatedConfusedWith : str
        SourceAnswer : str
        SourceMeaningMnemonic : str
        UserAnswer : str
        UserMnemonic : str
        UserSimilarMeaning : str


    class SentencesNoteType(abc.ABC):

        class Card(abc.ABC):
            Listening : str
            Reading : str



    class Vocab(abc.ABC):
        ActiveAnswer : str
        AudioB : str
        AudioG : str
        AudioTTS : str
        Forms : str
        Homophones : str
        Kanji : str
        MatchingRules : str
        ParsedTypeOfSpeech : str
        PartsOfSpeech : str
        Question : str
        Reading : str
        RelatedVocab : str
        SentenceCount : str
        SourceAnswer : str
        SourceMnemonic : str
        SourceReadingMnemonic : str
        UserAnswer : str
        UserCompounds : str
        UserExplanation : str
        UserExplanationLong : str
        UserMnemonic : str


    class VocabNoteType(abc.ABC):

        class Card(abc.ABC):
            Listening : str
            Reading : str




class NoteFlushGuard:
    def __init__(self, note: JPNote) -> None: ...
    @property
    def IsFlushing(self) -> bool: ...
    def Flush(self) -> None: ...
    def PauseFlushing(self) -> IDisposable: ...


class NoteServices:
    @property
    def AnkiCardOperations(self) -> AnkiCardOperations: ...
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def Config(self) -> JapaneseConfig: ...
    @property
    def DictLookup(self) -> DictLookup: ...
    @property
    def KanjiNoteMnemonicMaker(self) -> KanjiNoteMnemonicMaker: ...
    @property
    def Settings(self) -> Settings: ...
    @property
    def TaskRunner(self) -> TaskRunner: ...
    @property
    def VocabNoteFactory(self) -> VocabNoteFactory: ...
    @property
    def VocabNoteGeneratedData(self) -> VocabNoteGeneratedData: ...


class NoteTags(IEnumerable_1[Tag]):
    def __init__(self, note: JPNote, data: NoteData = ...) -> None: ...
    def Contains(self, value: Tag) -> bool: ...
    def GetEnumerator(self) -> IEnumerator_1[Tag]: ...
    def Set(self, tag: Tag) -> None: ...
    def Toggle(self, tag: Tag, on: bool) -> None: ...
    def ToInternedStringList(self) -> List_1[str]: ...
    def Unset(self, tag: Tag) -> None: ...


class NoteTypes(abc.ABC):
    All : HashSet_1[str]
    AllList : IReadOnlyList_1[str]
    ImmersionKit : str
    Kanji : str
    Sentence : str
    Vocab : str
    @staticmethod
    def FromType(noteType: typing.Type[typing.Any]) -> str: ...


class SentenceNote(JPNote):
    def __init__(self, services: NoteServices, data: NoteData = ...) -> None: ...
    @property
    def ActiveAnswer(self) -> MutableStringField: ...
    @property
    def ActiveQuestion(self) -> MutableStringField: ...
    @property
    def AnalysisServices(self) -> AnalysisServices: ...
    @property
    def Answer(self) -> StripHtmlOnReadFallbackStringField: ...
    @property
    def Audio(self) -> WritableAudioField: ...
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def Configuration(self) -> CachingSentenceConfigurationField: ...
    @Configuration.setter
    def Configuration(self, value: CachingSentenceConfigurationField) -> CachingSentenceConfigurationField: ...
    @property
    def Id(self) -> MutableStringField: ...
    @property
    def IsFlushing(self) -> bool: ...
    @property
    def JanomeTokens(self) -> MutableStringField: ...
    @property
    def ParsingResult(self) -> MutableSerializedObjectField_1[ParsingResult]: ...
    @property
    def Question(self) -> SentenceQuestionField: ...
    @property
    def Reading(self) -> MutableStringField: ...
    @property
    def RecursiveFlushGuard(self) -> NoteFlushGuard: ...
    @property
    def Services(self) -> NoteServices: ...
    @property
    def SourceComments(self) -> MutableStringField: ...
    @property
    def SourceQuestion(self) -> MutableStringField: ...
    @property
    def Tags(self) -> NoteTags: ...
    @property
    def User(self) -> SentenceUserFields: ...
    @staticmethod
    def AddSentence(services: NoteServices, question: str, answer: str, audio: str = ..., screenshot: str = ..., highlightedVocab: HashSet_1[str] = ..., tags: HashSet_1[Tag] = ...) -> SentenceNote: ...
    @staticmethod
    def Create(services: NoteServices, question: str) -> SentenceNote: ...
    def CreateAnalysis(self, forUI: bool = ...) -> TextAnalysis: ...
    @staticmethod
    def CreateTestNote(services: NoteServices, question: str, answer: str) -> SentenceNote: ...
    def ExtractKanji(self) -> List_1[str]: ...
    def GetAnswer(self) -> str: ...
    def GetDirectDependencies(self) -> HashSet_1[JPNote]: ...
    def GetQuestion(self) -> str: ...
    def GetWords(self) -> List_1[str]: ...
    def UpdateGeneratedData(self) -> None: ...
    def UpdateInCache(self) -> None: ...
    def UpdateParsedWords(self, force: bool = ...) -> None: ...


class SentenceNoteFields(abc.ABC):
    ActiveAnswer : str
    ActiveQuestion : str
    Audio : str
    Configuration : str
    Id : str
    JanomeTokens : str
    ParsingResult : str
    Reading : str
    Screenshot : str
    SourceAnswer : str
    SourceComments : str
    SourceQuestion : str
    UserAnswer : str
    UserComments : str
    UserQuestion : str


class Tag:
    @property
    def Bit(self) -> int: ...
    @property
    def Id(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @staticmethod
    def FromId(id: int) -> Tag: ...
    @staticmethod
    def FromName(name: str) -> Tag: ...


class Tags(abc.ABC):
    DisableKanaOnly : Tag
    PriorityFolder : str
    TTSAudio : Tag
    UsuallyKanaOnly : Tag

    class Kanji(abc.ABC):
        HasNonPrimaryOnReadingVocab : Tag
        HasNonPrimaryOnReadingVocabWithOnlyKnownKanji : Tag
        HasPrimaryReadingWithNoStudyingVocab : Tag
        HasStudyingVocabForEachPrimaryReading : Tag
        HasStudyingVocabWithNoMatchingPrimaryReading : Tag
        InAnyVocabForm : Tag
        InVocabMainForm : Tag
        IsRadical : Tag
        IsRadicalPurely : Tag
        IsRadicalSilent : Tag
        WithNoPrimaryOnReadings : Tag
        WithNoPrimaryReadings : Tag
        WithSingleKanjiVocab : Tag
        WithSingleKanjiVocabWithDifferentReading : Tag
        WithStudyingSingleKanjiVocabWithDifferentReading : Tag
        WithStudyingVocab : Tag
        WithStudyingVocabWithPrimaryOnReading : Tag
        WithVocabWithPrimaryOnReading : Tag


    class Sentence(abc.ABC):

        class Uses(abc.ABC):
            HiddenMatches : Tag
            IncorrectMatches : Tag



    class Source(abc.ABC):
        Folder : str
        ImmersionKit : Tag
        Jamdict : Tag


    class Vocab(abc.ABC):
        HasNoStudyingSentences : Tag
        IsCompositionallyTransparentCompound : Tag
        IsIchidanHidingGodanPotential : Tag
        QuestionOverridesForm : Tag
        Root : str

        class Matching(abc.ABC):
            IsInflectingWord : Tag
            IsPoisonWord : Tag
            YieldLastTokenToOverlappingCompound : Tag

            class Forbids(abc.ABC):
                AutoYielding : Tag
                DictionaryFormPrefix : Tag
                DictionaryFormStem : Tag
                Godan : Tag
                GodanImperative : Tag
                GodanImperativePrefix : Tag
                GodanPotential : Tag
                Ichidan : Tag
                IchidanImperative : Tag
                Irrealis : Tag
                MasuStem : Tag
                PastTenseStem : Tag
                PrecedingAdverb : Tag
                SentenceEnd : Tag
                SentenceStart : Tag
                Surface : Tag
                TeFormPrefix : Tag
                TeFormStem : Tag


            class Requires(abc.ABC):
                Compound : Tag
                DictionaryFormPrefix : Tag
                DictionaryFormStem : Tag
                FolderName : str
                Godan : Tag
                GodanImperative : Tag
                GodanImperativePrefix : Tag
                GodanPotential : Tag
                Ichidan : Tag
                IchidanImperative : Tag
                Irrealis : Tag
                MasuStem : Tag
                PastTenseStem : Tag
                PrecedingAdverb : Tag
                SentenceEnd : Tag
                SentenceStart : Tag
                SingleToken : Tag
                Surface : Tag
                TeFormPrefix : Tag
                TeFormStem : Tag


            class Todo(abc.ABC):
                WithPrecedingVowel : Tag


            class Uses(abc.ABC):
                PrefixIsNot : Tag
                RequiredPrefix : Tag
                SuffixIsNot : Tag
                SurfaceIsNot : Tag



        class Register(abc.ABC):
            Archaic : Tag
            Childish : Tag
            Derogatory : Tag
            Formal : Tag
            Honorific : Tag
            Humble : Tag
            Informal : Tag
            Literary : Tag
            Polite : Tag
            RoughMasculine : Tag
            Sensitive : Tag
            Slang : Tag
            SoftFeminine : Tag
            Vulgar : Tag




class TestingBackendNoteCreator(IBackendNoteCreator):
    def __init__(self) -> None: ...
    def CreateKanji(self, note: KanjiNote, callback: Action) -> None: ...
    def CreateSentence(self, note: SentenceNote, callback: Action) -> None: ...
    def CreateVocab(self, note: VocabNote, callback: Action) -> None: ...


class VocabNote(JPNote):
    def __init__(self, services: NoteServices, data: NoteData = ...) -> None: ...
    @property
    def ActiveAnswer(self) -> MutableStringField: ...
    @property
    def Audio(self) -> VocabNoteAudio: ...
    @property
    def Cloner(self) -> VocabCloner: ...
    @property
    def Collection(self) -> JPCollection: ...
    @property
    def CompoundParts(self) -> VocabNoteUserCompoundParts: ...
    @property
    def Conjugator(self) -> VocabNoteConjugator: ...
    @property
    def Forms(self) -> VocabNoteForms: ...
    @property
    def IsFlushing(self) -> bool: ...
    @property
    def Kanji(self) -> VocabNoteKanji: ...
    @property
    def MatchingConfiguration(self) -> VocabNoteMatchingConfiguration: ...
    @MatchingConfiguration.setter
    def MatchingConfiguration(self, value: VocabNoteMatchingConfiguration) -> VocabNoteMatchingConfiguration: ...
    @property
    def MetaData(self) -> VocabNoteMetaData: ...
    @property
    def PartsOfSpeech(self) -> VocabNotePartsOfSpeech: ...
    @property
    def Question(self) -> VocabNoteQuestion: ...
    @Question.setter
    def Question(self, value: VocabNoteQuestion) -> VocabNoteQuestion: ...
    @property
    def Readings(self) -> MutableCommaSeparatedStringsListField: ...
    @property
    def RecursiveFlushGuard(self) -> NoteFlushGuard: ...
    @property
    def Register(self) -> VocabNoteRegister: ...
    @property
    def RelatedNotes(self) -> RelatedVocab: ...
    @property
    def Sentences(self) -> VocabNoteSentences: ...
    @property
    def Services(self) -> NoteServices: ...
    @property
    def SourceAnswer(self) -> MutableStringField: ...
    @property
    def Tags(self) -> NoteTags: ...
    @property
    def User(self) -> VocabNoteUserFields: ...
    def GenerateAndSetAnswer(self) -> None: ...
    def GetAnswer(self) -> str: ...
    def GetDirectDependencies(self) -> HashSet_1[JPNote]: ...
    def GetQuestion(self) -> str: ...
    def GetReadings(self) -> List_1[str]: ...
    def OnTagsUpdated(self) -> None: ...
    def SetReadings(self, readings: List_1[str]) -> None: ...
    def UpdateGeneratedData(self) -> None: ...
    def UpdateInCache(self) -> None: ...
    # Skipped Create due to it being static, abstract and generic.

    Create : Create_MethodGroup
    class Create_MethodGroup:
        @typing.overload
        def __call__(self, services: NoteServices, question: str, answer: str, readings: Array_1[str]) -> VocabNote:...
        @typing.overload
        def __call__(self, services: NoteServices, question: str, answer: str, readings: List_1[str], forms: List_1[str]) -> VocabNote:...


