import abc
from JAStudio.Core.LanguageServices.JanomeEx.WordExtraction import CandidateWordVariant, CandidateWord, WordExclusion
from JAStudio.Core.LanguageServices.JamdictEx import DictEntry
from System.Collections.Generic import List_1
from JAStudio.Core.LanguageServices.JanomeEx.WordExtraction.Matches.Requirements import MatchInspector, VocabMatchInspector
from JAStudio.Core.Note import VocabNote
from JAStudio.Core.Note.Vocabulary import VocabNoteMatchingConfiguration, VocabMatchingRulesConfigurationRequiresForbidsFlags, VocabNoteMatchingRules

class DictionaryMatch(Match):
    def __init__(self, wordVariant: CandidateWordVariant, dictionaryEntry: DictEntry) -> None: ...
    @property
    def Answer(self) -> str: ...
    @property
    def DictionaryEntry(self) -> DictEntry: ...
    @property
    def ExclusionForm(self) -> str: ...
    @property
    def FailureReasons(self) -> List_1[str]: ...
    @property
    def HidingReasons(self) -> List_1[str]: ...
    @property
    def Inspector(self) -> MatchInspector: ...
    @property
    def IsDisplayed(self) -> bool: ...
    @property
    def IsEmergencyDisplayed(self) -> bool: ...
    @property
    def IsHighlighted(self) -> bool: ...
    @property
    def IsPrimarilyValidProperty(self) -> bool: ...
    @property
    def IsShadowed(self) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def IsValidForDisplay(self) -> bool: ...
    @property
    def MatchForm(self) -> str: ...
    @property
    def ParsedForm(self) -> str: ...
    @property
    def Readings(self) -> List_1[str]: ...
    @property
    def StartIndex(self) -> int: ...
    @property
    def StaticDisplayRequirementsFulfilled(self) -> bool: ...
    @property
    def TokenizedForm(self) -> str: ...
    @property
    def Variant(self) -> CandidateWordVariant: ...
    @property
    def Word(self) -> CandidateWord: ...


class Match(abc.ABC):
    @property
    def Answer(self) -> str: ...
    @property
    def ExclusionForm(self) -> str: ...
    @property
    def FailureReasons(self) -> List_1[str]: ...
    @property
    def HidingReasons(self) -> List_1[str]: ...
    @property
    def Inspector(self) -> MatchInspector: ...
    @property
    def IsDisplayed(self) -> bool: ...
    @property
    def IsEmergencyDisplayed(self) -> bool: ...
    @property
    def IsHighlighted(self) -> bool: ...
    @property
    def IsPrimarilyValidProperty(self) -> bool: ...
    @property
    def IsShadowed(self) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def IsValidForDisplay(self) -> bool: ...
    @property
    def MatchForm(self) -> str: ...
    @property
    def ParsedForm(self) -> str: ...
    @property
    def Readings(self) -> List_1[str]: ...
    @property
    def StartIndex(self) -> int: ...
    @property
    def StaticDisplayRequirementsFulfilled(self) -> bool: ...
    @property
    def TokenizedForm(self) -> str: ...
    @property
    def Variant(self) -> CandidateWordVariant: ...
    @property
    def Word(self) -> CandidateWord: ...
    def ToExclusion(self) -> WordExclusion: ...
    def ToString(self) -> str: ...


class MissingMatch(Match):
    def __init__(self, wordVariant: CandidateWordVariant) -> None: ...
    @property
    def Answer(self) -> str: ...
    @property
    def ExclusionForm(self) -> str: ...
    @property
    def FailureReasons(self) -> List_1[str]: ...
    @property
    def HidingReasons(self) -> List_1[str]: ...
    @property
    def Inspector(self) -> MatchInspector: ...
    @property
    def IsDisplayed(self) -> bool: ...
    @property
    def IsEmergencyDisplayed(self) -> bool: ...
    @property
    def IsHighlighted(self) -> bool: ...
    @property
    def IsPrimarilyValidProperty(self) -> bool: ...
    @property
    def IsShadowed(self) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def IsValidForDisplay(self) -> bool: ...
    @property
    def MatchForm(self) -> str: ...
    @property
    def ParsedForm(self) -> str: ...
    @property
    def Readings(self) -> List_1[str]: ...
    @property
    def StartIndex(self) -> int: ...
    @property
    def StaticDisplayRequirementsFulfilled(self) -> bool: ...
    @property
    def TokenizedForm(self) -> str: ...
    @property
    def Variant(self) -> CandidateWordVariant: ...
    @property
    def Word(self) -> CandidateWord: ...


class VocabMatch(Match):
    def __init__(self, wordVariant: CandidateWordVariant, vocab: VocabNote) -> None: ...
    @property
    def AnotherMatchIsHigherPriority(self) -> bool: ...
    @property
    def Answer(self) -> str: ...
    @property
    def ExclusionForm(self) -> str: ...
    @property
    def FailureReasons(self) -> List_1[str]: ...
    @property
    def HidingReasons(self) -> List_1[str]: ...
    @property
    def Inspector(self) -> MatchInspector: ...
    @property
    def IsDisplayed(self) -> bool: ...
    @property
    def IsEmergencyDisplayed(self) -> bool: ...
    @property
    def IsHighlighted(self) -> bool: ...
    @property
    def IsPrimarilyValidProperty(self) -> bool: ...
    @property
    def IsShadowed(self) -> bool: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def IsValidForDisplay(self) -> bool: ...
    @property
    def MatchForm(self) -> str: ...
    @property
    def MatchingConfiguration(self) -> VocabNoteMatchingConfiguration: ...
    @property
    def ParsedForm(self) -> str: ...
    @property
    def Readings(self) -> List_1[str]: ...
    @property
    def RequiresForbids(self) -> VocabMatchingRulesConfigurationRequiresForbidsFlags: ...
    @property
    def Rules(self) -> VocabNoteMatchingRules: ...
    @property
    def StartIndex(self) -> int: ...
    @property
    def StaticDisplayRequirementsFulfilled(self) -> bool: ...
    @property
    def TokenizedForm(self) -> str: ...
    @property
    def Variant(self) -> CandidateWordVariant: ...
    @property
    def Vocab(self) -> VocabNote: ...
    @property
    def VocabInspector(self) -> VocabMatchInspector: ...
    @property
    def Word(self) -> CandidateWord: ...
    def ToString(self) -> str: ...

