from System import IDisposable
from JAStudio.Core import IEnvironmentPaths

class TestEnvironmentPaths(IDisposable, IEnvironmentPaths):
    def __init__(self) -> None: ...
    @property
    def AddonRootDir(self) -> str: ...
    @property
    def AnkiMediaDir(self) -> str: ...
    @property
    def DatabaseDir(self) -> str: ...
    @property
    def MediaDir(self) -> str: ...
    @property
    def MetadataDir(self) -> str: ...
    @property
    def UserFilesDir(self) -> str: ...
    def Dispose(self) -> None: ...

