import abc
from JAStudio.Core import CoreApp, IEnvironmentPaths
from System import IDisposable

class TestCoreApp(abc.ABC):
    @staticmethod
    def Reset() -> CoreApp: ...


class TestEnvironmentPaths(IDisposable, IEnvironmentPaths):
    def __init__(self) -> None: ...
    @property
    def AddonRootDir(self) -> str: ...
    @property
    def AnkiMediaDir(self) -> str: ...
    @property
    def DatabaseDir(self) -> str: ...
    @property
    def MediaDir(self) -> str: ...
    @property
    def MetadataDir(self) -> str: ...
    @property
    def UserFilesDir(self) -> str: ...
    def Dispose(self) -> None: ...

