from JAStudio.Core.LanguageServices.JanomeEx.WordExtraction import CandidateWordVariant, TextAnalysis
from JAStudio.Core.Configuration import Settings
from JAStudio.Core.Note.Collection import VocabCollection
from System.Collections.Generic import List_1, HashSet_1
from JAStudio.Core.Note.Vocabulary import VocabNote
from JAStudio.Core.Note.Sentences import SentenceConfiguration, SentenceNote
from JAStudio.Core.Note import NoteId
from JAStudio.Core.LanguageServices.JanomeEx.WordExtraction.Matches import Match, VocabMatch
from JAStudio.Core.UI.Web import PreRenderingContentRenderer_1

class CandidateWordVariantViewModel:
    def __init__(self, variant: CandidateWordVariant, settings: Settings, vocab: VocabCollection) -> None: ...
    @property
    def CandidateWord(self) -> CandidateWordVariant: ...
    @property
    def DisplayMatches(self) -> List_1[MatchViewModel]: ...
    @property
    def HasPerfectMatch(self) -> bool: ...
    @property
    def IsDisplayWord(self) -> bool: ...
    @property
    def Matches(self) -> List_1[MatchViewModel]: ...
    @property
    def PrimaryDisplayForms(self) -> List_1[MatchViewModel]: ...
    def ToString(self) -> str: ...


class CompoundPartViewModel:
    def __init__(self, vocabNote: VocabNote, depth: int, config: SentenceConfiguration) -> None: ...
    @property
    def Answer(self) -> str: ...
    @property
    def AudioPath(self) -> str: ...
    @property
    def Depth(self) -> int: ...
    @property
    def DisplayReadings(self) -> bool: ...
    @property
    def IsHighlighted(self) -> bool: ...
    @property
    def MetaTagsHtml(self) -> str: ...
    @property
    def MetaTagsString(self) -> str: ...
    @property
    def Question(self) -> str: ...
    @property
    def Readings(self) -> str: ...
    @property
    def VocabNote(self) -> VocabNote: ...
    @staticmethod
    def GetCompoundPartsRecursive(matchViewModel: MatchViewModel, vocabNote: VocabNote, config: SentenceConfiguration, settings: Settings, vocab: VocabCollection, depth: int = ..., visited: HashSet_1[NoteId] = ...) -> List_1[CompoundPartViewModel]: ...


class MatchViewModel:
    def __init__(self, wordVariantVm: CandidateWordVariantViewModel, match: Match, settings: Settings, vocab: VocabCollection) -> None: ...
    @property
    def Answer(self) -> str: ...
    @property
    def AudioPath(self) -> str: ...
    @property
    def CompoundParts(self) -> List_1[CompoundPartViewModel]: ...
    @property
    def DisplayReadings(self) -> bool: ...
    @property
    def DisplayVocabForm(self) -> bool: ...
    @property
    def HidingReasons(self) -> List_1[str]: ...
    @property
    def IncorrectReasons(self) -> List_1[str]: ...
    @property
    def IsDisplayed(self) -> bool: ...
    @property
    def IsDisplayWord(self) -> bool: ...
    @property
    def IsHighlighted(self) -> bool: ...
    @property
    def Kanji(self) -> List_1[str]: ...
    @property
    def Match(self) -> Match: ...
    @property
    def MatchIsDisplayed(self) -> bool: ...
    @property
    def MatchOwnsForm(self) -> bool: ...
    @property
    def MetaTagsHtml(self) -> str: ...
    @property
    def MetaTagsList(self) -> List_1[str]: ...
    @property
    def MetaTagsString(self) -> str: ...
    @property
    def ParsedForm(self) -> str: ...
    @property
    def Readings(self) -> str: ...
    @property
    def ShowCompoundParts(self) -> bool: ...
    @property
    def ShowKanji(self) -> bool: ...
    @property
    def ShowKanjiMnemonics(self) -> bool: ...
    @property
    def VocabForm(self) -> str: ...
    @property
    def VocabMatch(self) -> VocabMatch: ...
    @property
    def WordVariantVm(self) -> CandidateWordVariantViewModel: ...
    def ToString(self) -> str: ...


class SentenceNoteRenderer:
    def CreateRenderer(self) -> PreRenderingContentRenderer_1[SentenceNote]: ...


class SentenceViewModel:
    def __init__(self, sentence: SentenceNote, settings: Settings, vocab: VocabCollection) -> None: ...
    @property
    def Analysis(self) -> TextAnalysisViewModel: ...
    @property
    def DisplayedMatches(self) -> List_1[MatchViewModel]: ...
    @property
    def Sentence(self) -> SentenceNote: ...


class TextAnalysisViewModel:
    def __init__(self, textAnalysis: TextAnalysis, settings: Settings, vocab: VocabCollection) -> None: ...
    @property
    def Analysis(self) -> TextAnalysis: ...
    @property
    def CandidateWords(self) -> List_1[CandidateWordVariantViewModel]: ...
    @property
    def DisplayedMatches(self) -> List_1[MatchViewModel]: ...

