from __future__ import annotations


class POS:
    """Canonical POS (Part of Speech) value constants."""
    ABBREVIATION: str = "abbreviation"
    ADVERBIAL_NOUN: str = "adverbial noun"
    ADVERBIAL: str = "adverbial"
    NUMERAL: str = "numeral"
    INDEPENDENT_NOUN: str = "independent noun"
    TRANSITIVE: str = "transitive"
    INTRANSITIVE: str = "intransitive"
    GODAN_VERB: str = "godan verb"
    ICHIDAN_VERB: str = "ichidan verb"
    SURU_VERB: str = "suru verb"
    KURU_VERB: str = "kuru verb"
    NU_VERB: str = "nu verb"
    SU_VERB: str = "su verb"
    YODAN_VERB: str = "yodan verb"
    NIDAN_VERB: str = "nidan verb"
    NOUN: str = "noun"
    PROPER_NOUN: str = "proper noun"
    NA_ADJECTIVE: str = "na-adjective"
    I_ADJECTIVE: str = "i-adjective"
    TARU_ADJECTIVE: str = "taru-adjective"
    ADVERB: str = "adverb"
    TO_ADVERB: str = "to-adverb"
    EXPRESSION: str = "expression"
    AUXILIARY: str = "auxiliary"
    CONJUNCTION: str = "conjunction"
    COPULA: str = "copula"
    INTERJECTION: str = "interjection"
    PARTICLE: str = "particle"
    PREFIX: str = "prefix"
    SUFFIX: str = "suffix"
    PRONOUN: str = "pronoun"
    COUNTER: str = "counter"
    NUMERIC: str = "numeric"
    PRENOMINAL: str = "prenominal"
    PRE_NOUN_ADJECTIVAL: str = "pre-noun-adjectival"
    NO_ADJECTIVE: str = "no-adjective"
    SPECIAL_CLASS: str = "special-class"
    SPECIAL_CLASS_ARU: str = "special-class-aru"
    ZURU_VERB: str = "zuru verb"
    IRREGULAR: str = "irregular"
    UNKNOWN: str = "Unknown"
    MASU_SUFFIX: str = "masu-suffix"  # non-standard, follows the 連用形/masu-stem form of a verb

    ALL_VERB_POSES: frozenset[str] = frozenset([GODAN_VERB, ICHIDAN_VERB, SURU_VERB, KURU_VERB, NU_VERB, SU_VERB, YODAN_VERB, NIDAN_VERB])
