import abc
from System import Array_1, TimeSpan, IDisposable

class ExStr(abc.ABC):
    @staticmethod
    def StripHtmlAndBracketMarkupAndNoiseCharacters(input: str) -> str: ...


class JAAssert(abc.ABC):
    @staticmethod
    def That(condition: bool, message: str = ...) -> None: ...


class KanaUtils(abc.ABC):
    FullWidthSpace : str
    @staticmethod
    def AnythingToHiragana(text: str) -> str: ...
    @staticmethod
    def CharacterIsHiragana(ch: str) -> bool: ...
    @staticmethod
    def CharacterIsKana(ch: str) -> bool: ...
    @staticmethod
    def CharacterIsKanji(ch: str) -> bool: ...
    @staticmethod
    def CharacterIsKatakana(ch: str) -> bool: ...
    @staticmethod
    def ExtractKanji(text: str) -> Array_1[str]: ...
    @staticmethod
    def HiraganaToKatakana(hiragana: str) -> str: ...
    @staticmethod
    def IsOnlyHiragana(text: str) -> bool: ...
    @staticmethod
    def IsOnlyKana(text: str) -> bool: ...
    @staticmethod
    def IsOnlyKatakana(text: str) -> bool: ...
    @staticmethod
    def KatakanaToHiragana(katakana: str) -> str: ...
    @staticmethod
    def PadToLength(value: str, targetLength: int) -> str: ...
    @staticmethod
    def RomajiToHiragana(romaji: str) -> str: ...
    @staticmethod
    def RomajiToKatakana(romaji: str) -> str: ...
    @staticmethod
    def Romanize(text: str) -> str: ...


class StopWatch:
    def __init__(self) -> None: ...
    def Elapsed(self) -> TimeSpan: ...
    def ElapsedFormatted(self) -> str: ...
    def ElapsedSeconds(self) -> float: ...
    @staticmethod
    def LogWarningIfSlowerThan(warnIfSlowerThanSeconds: float, message: str = ...) -> IDisposable: ...

