import abc
from System import TimeSpan, IDisposable

class ExStr(abc.ABC):
    @staticmethod
    def StripHtmlAndBracketMarkupAndNoiseCharacters(input: str) -> str: ...


class JAAssert(abc.ABC):
    @staticmethod
    def That(condition: bool, message: str = ...) -> None: ...


class StopWatch:
    def __init__(self) -> None: ...
    def Elapsed(self) -> TimeSpan: ...
    def ElapsedFormatted(self) -> str: ...
    def ElapsedSeconds(self) -> float: ...
    @staticmethod
    def LogWarningIfSlowerThan(warnIfSlowerThanSeconds: float, message: str = ...) -> IDisposable: ...

