import typing, abc
from System.Collections.Generic import IEnumerator_1, IReadOnlyList_1
from System import IEquatable_1, Action
from System.Runtime.CompilerServices import INotifyCompletion

class ImmutableReadOnlyListStructEnumerator_GenericClasses(abc.ABCMeta):
    Generic_ImmutableReadOnlyListStructEnumerator_GenericClasses_ImmutableReadOnlyListStructEnumerator_1_T = typing.TypeVar('Generic_ImmutableReadOnlyListStructEnumerator_GenericClasses_ImmutableReadOnlyListStructEnumerator_1_T')
    def __getitem__(self, types : typing.Type[Generic_ImmutableReadOnlyListStructEnumerator_GenericClasses_ImmutableReadOnlyListStructEnumerator_1_T]) -> typing.Type[ImmutableReadOnlyListStructEnumerator_1[Generic_ImmutableReadOnlyListStructEnumerator_GenericClasses_ImmutableReadOnlyListStructEnumerator_1_T]]: ...

ImmutableReadOnlyListStructEnumerator : ImmutableReadOnlyListStructEnumerator_GenericClasses

ImmutableReadOnlyListStructEnumerator_1_T = typing.TypeVar('ImmutableReadOnlyListStructEnumerator_1_T')
class ImmutableReadOnlyListStructEnumerator_1(typing.Generic[ImmutableReadOnlyListStructEnumerator_1_T], IEnumerator_1[ImmutableReadOnlyListStructEnumerator_1_T]):
    def __init__(self, readOnlyList: IReadOnlyList_1[ImmutableReadOnlyListStructEnumerator_1_T]) -> None: ...
    @property
    def Current(self) -> ImmutableReadOnlyListStructEnumerator_1_T: ...
    def Dispose(self) -> None: ...
    def MoveNext(self) -> bool: ...
    def Reset(self) -> None: ...


class SynchronousCompletionAsyncResult_GenericClasses(abc.ABCMeta):
    Generic_SynchronousCompletionAsyncResult_GenericClasses_SynchronousCompletionAsyncResult_1_T = typing.TypeVar('Generic_SynchronousCompletionAsyncResult_GenericClasses_SynchronousCompletionAsyncResult_1_T')
    def __getitem__(self, types : typing.Type[Generic_SynchronousCompletionAsyncResult_GenericClasses_SynchronousCompletionAsyncResult_1_T]) -> typing.Type[SynchronousCompletionAsyncResult_1[Generic_SynchronousCompletionAsyncResult_GenericClasses_SynchronousCompletionAsyncResult_1_T]]: ...

SynchronousCompletionAsyncResult : SynchronousCompletionAsyncResult_GenericClasses

SynchronousCompletionAsyncResult_1_T = typing.TypeVar('SynchronousCompletionAsyncResult_1_T')
class SynchronousCompletionAsyncResult_1(typing.Generic[SynchronousCompletionAsyncResult_1_T], IEquatable_1[SynchronousCompletionAsyncResult_1[SynchronousCompletionAsyncResult_1_T]], INotifyCompletion):
    def __init__(self, result: SynchronousCompletionAsyncResult_1_T) -> None: ...
    @property
    def IsCompleted(self) -> bool: ...
    def GetAwaiter(self) -> SynchronousCompletionAsyncResult_1[SynchronousCompletionAsyncResult_1_T]: ...
    def GetHashCode(self) -> int: ...
    def GetResult(self) -> SynchronousCompletionAsyncResult_1_T: ...
    def OnCompleted(self, continuation: Action) -> None: ...
    def __eq__(self, left: SynchronousCompletionAsyncResult_1[SynchronousCompletionAsyncResult_1_T], right: SynchronousCompletionAsyncResult_1[SynchronousCompletionAsyncResult_1_T]) -> bool: ...
    def __ne__(self, left: SynchronousCompletionAsyncResult_1[SynchronousCompletionAsyncResult_1_T], right: SynchronousCompletionAsyncResult_1[SynchronousCompletionAsyncResult_1_T]) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup[SynchronousCompletionAsyncResult_1_T]
    Equals_MethodGroup_SynchronousCompletionAsyncResult_1_T = typing.TypeVar('Equals_MethodGroup_SynchronousCompletionAsyncResult_1_T')
    class Equals_MethodGroup(typing.Generic[Equals_MethodGroup_SynchronousCompletionAsyncResult_1_T]):
        Equals_MethodGroup_SynchronousCompletionAsyncResult_1_T = SynchronousCompletionAsyncResult_1.Equals_MethodGroup_SynchronousCompletionAsyncResult_1_T
        @typing.overload
        def __call__(self, other: SynchronousCompletionAsyncResult_1[Equals_MethodGroup_SynchronousCompletionAsyncResult_1_T]) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...


