import abc
from System.Collections.Generic import List_1
from JAStudio.Core.LanguageServices.JanomeEx.Tokenizing import IAnalysisToken, JNToken
from JAStudio.Core.LanguageServices.JamdictEx import DictLookupResult, DictLookup
from System.Collections.Frozen import FrozenSet_1
from JAStudio.Core.Note.Vocabulary import VocabNote
from JAStudio.Core.Note.Collection import VocabCollection

class DictionaryFormVerbSplitter(abc.ABC):
    @staticmethod
    def TrySplit(token: JNToken) -> List_1[IAnalysisToken]: ...


class DictWordInfoEntry(WordInfoEntry):
    def __init__(self, word: str, dictResult: DictLookupResult) -> None: ...
    @property
    def Answer(self) -> str: ...
    @property
    def IsGodan(self) -> bool: ...
    @property
    def IsIchidan(self) -> bool: ...
    @property
    def IsIntransitive(self) -> bool: ...
    @property
    def PartsOfSpeech(self) -> FrozenSet_1[str]: ...
    @property
    def Word(self) -> str: ...


class GodanImperativeSplitter(abc.ABC):
    @staticmethod
    def TrySplit(token: JNToken) -> List_1[IAnalysisToken]: ...


class IchidanGodanPotentialOrImperativeHybridSplitter(abc.ABC):
    @staticmethod
    def BaseFormHasGodanPotentialEnding(baseForm: str) -> bool: ...
    @staticmethod
    def IsIchidanHidingGodan(vocab: VocabNote) -> bool: ...
    @staticmethod
    def TryGetGodanHiddenByIchidan(vocab: VocabNote) -> WordInfoEntry: ...
    @staticmethod
    def TrySplit(token: JNToken, vocabs: VocabCollection, dictLookup: DictLookup) -> List_1[IAnalysisToken]: ...


class IchidanImperativeSplitter(abc.ABC):
    @staticmethod
    def TrySplit(token: JNToken) -> List_1[IAnalysisToken]: ...


class PreProcessingStage:
    def __init__(self, vocabs: VocabCollection, dictLookup: DictLookup) -> None: ...
    def PreProcess(self, tokens: List_1[JNToken]) -> List_1[IAnalysisToken]: ...


class VocabWordInfoEntry(WordInfoEntry):
    def __init__(self, word: str, vocab: VocabNote) -> None: ...
    @property
    def Answer(self) -> str: ...
    @property
    def IsGodan(self) -> bool: ...
    @property
    def IsIchidan(self) -> bool: ...
    @property
    def IsIntransitive(self) -> bool: ...
    @property
    def PartsOfSpeech(self) -> FrozenSet_1[str]: ...
    @property
    def Word(self) -> str: ...


class WordInfo(abc.ABC):
    @staticmethod
    def IsGodan(vocab: VocabCollection, dictLookup: DictLookup, word: str) -> bool: ...
    @staticmethod
    def IsIchidan(vocab: VocabCollection, dictLookup: DictLookup, word: str) -> bool: ...
    @staticmethod
    def Lookup(vocab: VocabCollection, dictLookup: DictLookup, word: str) -> WordInfoEntry: ...
    @staticmethod
    def LookupGodan(vocab: VocabCollection, dictLookup: DictLookup, word: str) -> WordInfoEntry: ...
    @staticmethod
    def LookupIchidan(vocab: VocabCollection, dictLookup: DictLookup, word: str) -> WordInfoEntry: ...


class WordInfoEntry(abc.ABC):
    @property
    def Answer(self) -> str: ...
    @property
    def IsGodan(self) -> bool: ...
    @property
    def IsIchidan(self) -> bool: ...
    @property
    def IsIntransitive(self) -> bool: ...
    @property
    def PartsOfSpeech(self) -> FrozenSet_1[str]: ...
    @property
    def Word(self) -> str: ...

