import typing, abc
from JAStudio.Core import IBackendDataLoader, BackendData, IEnvironmentPaths
from JAStudio.Core.TaskRunners import TaskRunner
from System.Collections.Generic import List_1, Dictionary_2, IReadOnlyList_1, IEnumerable_1
from JAStudio.Core.Note import NoteData, NoteId, ICardOperations, ExternalNoteIdMap, JPNote, KanjiNote
from System import IDisposable, Func_2, Guid
from Microsoft.Data.Sqlite import SqliteConnection
from JAStudio.Core.Note.Collection import CardStudyingStatus, VocabCollection, KanjiCollection
from JAStudio.Core.LanguageServices.JanomeEx import AnalysisServices
from JAStudio.Core.Note.Vocabulary import VocabNote

class AnkiBackendDataLoader(IBackendDataLoader):
    def __init__(self) -> None: ...
    def Load(self, taskRunner: TaskRunner) -> BackendData: ...


class AnkiBulkLoadResult:
    def __init__(self, notes: List_1[NoteData], ankiIdMap: Dictionary_2[int, NoteId]) -> None: ...
    @property
    def AnkiIdMap(self) -> Dictionary_2[int, NoteId]: ...
    @property
    def Notes(self) -> List_1[NoteData]: ...


class AnkiCardOperationsImpl(ICardOperations):
    def __init__(self, idMap: ExternalNoteIdMap) -> None: ...
    def SuspendAllCardsForNote(self, noteId: NoteId) -> None: ...
    def UnsuspendAllCardsForNote(self, noteId: NoteId) -> None: ...


class AnkiDatabase(IDisposable):
    @property
    def Connection(self) -> SqliteConnection: ...
    def Dispose(self) -> None: ...
    @staticmethod
    def OpenReadOnly(dbFilePath: str) -> AnkiDatabase: ...


class AnkiEnvironmentPaths(IEnvironmentPaths):
    def __init__(self) -> None: ...
    @property
    def AddonRootDir(self) -> str: ...
    @property
    def AnkiMediaDir(self) -> str: ...
    @property
    def DatabaseDir(self) -> str: ...
    @property
    def MediaDir(self) -> str: ...
    @property
    def MetadataDir(self) -> str: ...
    @property
    def UserFilesDir(self) -> str: ...


class AnkiFacade(abc.ABC):
    @staticmethod
    def GetAddonRootDir() -> str: ...
    @staticmethod
    def GetAnkiMediaDir() -> str: ...
    @staticmethod
    def GetNoteIdFromCardId(cardId: int) -> int: ...

    class Batches(abc.ABC):
        @staticmethod
        def ConvertImmersionKitSentences() -> None: ...
        @staticmethod
        def FlushAnkiNote(externalNoteId: int) -> None: ...


    class Browser(abc.ABC):
        @staticmethod
        def ExecuteLookup(query: str) -> None: ...
        @staticmethod
        def ExecuteLookupAndShowPreviewer(query: str) -> None: ...

        class MenuActions(abc.ABC):
            @staticmethod
            def PrioritizeCards(cardIds: IReadOnlyList_1[int]) -> None: ...
            @staticmethod
            def SpreadCardsOverDays(cardIds: IReadOnlyList_1[int], startDay: int, daysApart: int) -> None: ...



    class UIUtils(abc.ABC):
        @staticmethod
        def Refresh() -> None: ...
        @staticmethod
        def ShowTooltip(message: str, periodMs: int = ...) -> None: ...



class AnkiLifecycleEvent(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    ProfileOpened : AnkiLifecycleEvent # 0
    ProfileClosing : AnkiLifecycleEvent # 1
    SyncStarting : AnkiLifecycleEvent # 2
    SyncCompleted : AnkiLifecycleEvent # 3
    CollectionLoaded : AnkiLifecycleEvent # 4


class CardStudyingStatusLoader(abc.ABC):
    @staticmethod
    def FetchAll(dbFilePath: str) -> List_1[CardStudyingStatus]: ...


class NoteBulkLoader(abc.ABC):
    @staticmethod
    def LoadAllNotesOfType(dbFilePath: str, noteTypeName: str, idFactory: Func_2[Guid, NoteId]) -> AnkiBulkLoadResult: ...
    @staticmethod
    def LoadAnkiIdMaps(dbFilePath: str) -> Dictionary_2[int, NoteId]: ...


class QueryBuilder:
    def __init__(self, vocab: VocabCollection, kanji: KanjiCollection, analysisServices: AnalysisServices, externalNoteIdMap: ExternalNoteIdMap) -> None: ...
    def ExactMatches(self, question: str) -> str: ...
    def ExactMatchesNoSentencesReadingCards(self, question: str) -> str: ...
    def ImmersionKitSentences(self) -> str: ...
    def KanjiInString(self, text: str) -> str: ...
    def KanjiWithMeaning(self, search: str) -> str: ...
    def KanjiWithRadicalsInString(self, search: str) -> str: ...
    def KanjiWithReadingPart(self, readingPart: str) -> str: ...
    def NotesByIds(self, noteIds: IEnumerable_1[NoteId]) -> str: ...
    def NotesLookup(self, notes: IEnumerable_1[JPNote]) -> str: ...
    def OpenCardById(self, cardId: int) -> str: ...
    def PotentiallyMatchingSentencesForVocab(self, vocab: VocabNote) -> str: ...
    def SentenceSearch(self, word: str, exact: bool = ...) -> str: ...
    def SingleVocabByFormExact(self, form: str) -> str: ...
    def SingleVocabByFormExactReadCardOnly(self, form: str) -> str: ...
    def SingleVocabByQuestionReadingOrAnswerExact(self, search: str) -> str: ...
    def SingleVocabWildcard(self, form: str) -> str: ...
    def TextVocabLookup(self, text: str) -> str: ...
    def VocabDependenciesLookupQuery(self, vocab: VocabNote) -> str: ...
    def VocabsLookupStrings(self, words: IEnumerable_1[str]) -> str: ...
    def VocabsLookupStringsReadCard(self, words: IEnumerable_1[str]) -> str: ...
    def VocabWithKanji(self, kanji: KanjiNote) -> str: ...

