import typing
from Avalonia import AvaloniaObject, StyledProperty_1, AvaloniaProperty
from Avalonia.Data import IndexerDescriptor, IBinding
from Avalonia.Collections import AvaloniaList_1, ResetBehavior
from System import Action_1

class Animatable(AvaloniaObject):
    def __init__(self) -> None: ...
    TransitionsProperty : StyledProperty_1[Transitions]
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class IAnimation(typing.Protocol):
    pass


class ITransition(typing.Protocol):
    @property
    def Property(self) -> AvaloniaProperty: ...
    @Property.setter
    def Property(self, value: AvaloniaProperty) -> AvaloniaProperty: ...


class PlaybackDirection(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Normal : PlaybackDirection # 0
    Reverse : PlaybackDirection # 1
    Alternate : PlaybackDirection # 2
    AlternateReverse : PlaybackDirection # 3


class Transitions(AvaloniaList_1[ITransition]):
    def __init__(self) -> None: ...
    @property
    def Capacity(self) -> int: ...
    @Capacity.setter
    def Capacity(self, value: int) -> int: ...
    @property
    def Count(self) -> int: ...
    @property
    def ResetBehavior(self) -> ResetBehavior: ...
    @ResetBehavior.setter
    def ResetBehavior(self, value: ResetBehavior) -> ResetBehavior: ...
    @property
    def Validate(self) -> Action_1[ITransition]: ...
    @Validate.setter
    def Validate(self, value: Action_1[ITransition]) -> Action_1[ITransition]: ...
    def __getitem__(self, index: int) -> ITransition: ...
    def __setitem__(self, index: int, value: ITransition) -> None: ...

