import typing
from Avalonia.Controls import Control, Classes, ContextMenu, ITemplate_1, IResourceDictionary, Panel
from Avalonia import StyledProperty_1, Thickness, DirectProperty_2, CornerRadius, Rect, Size, StyledElement, RelativePoint, AvaloniaObject, AvaloniaProperty
from Avalonia.Media import IBrush, BackgroundSizing, BoxShadows, FontFamily, FontStretch, FontStyle, FontWeight, TextAlignment, TextTrimming, TextWrapping, Geometry, IEffect, FlowDirection, ITransform, DrawingContext
from Avalonia.Controls.Templates import IDataTemplate, DataTemplates
from Avalonia.Layout import HorizontalAlignment, VerticalAlignment
from Avalonia.Styling import ThemeVariant, Styles, ControlTheme
from Avalonia.Controls.Primitives import FlyoutBase, ILogicalScrollable
from Avalonia.Input import Cursor, KeyBinding
from Avalonia.Input.GestureRecognizers import GestureRecognizerCollection
from System.Collections.Generic import List_1
from Avalonia.Animation import Transitions
from Avalonia.Data import IndexerDescriptor, IBinding

class ContentPresenter(Control):
    def __init__(self) -> None: ...
    BackgroundProperty : StyledProperty_1[IBrush]
    BackgroundSizingProperty : StyledProperty_1[BackgroundSizing]
    BorderBrushProperty : StyledProperty_1[IBrush]
    BorderThicknessProperty : StyledProperty_1[Thickness]
    BoxShadowProperty : StyledProperty_1[BoxShadows]
    ChildProperty : DirectProperty_2[ContentPresenter, Control]
    ContentProperty : StyledProperty_1[typing.Any]
    ContentTemplateProperty : StyledProperty_1[IDataTemplate]
    CornerRadiusProperty : StyledProperty_1[CornerRadius]
    FontFamilyProperty : StyledProperty_1[FontFamily]
    FontSizeProperty : StyledProperty_1[float]
    FontStretchProperty : StyledProperty_1[FontStretch]
    FontStyleProperty : StyledProperty_1[FontStyle]
    FontWeightProperty : StyledProperty_1[FontWeight]
    ForegroundProperty : StyledProperty_1[IBrush]
    HorizontalContentAlignmentProperty : StyledProperty_1[HorizontalAlignment]
    LineHeightProperty : StyledProperty_1[float]
    MaxLinesProperty : StyledProperty_1[int]
    PaddingProperty : StyledProperty_1[Thickness]
    RecognizesAccessKeyProperty : StyledProperty_1[bool]
    TextAlignmentProperty : StyledProperty_1[TextAlignment]
    TextTrimmingProperty : StyledProperty_1[TextTrimming]
    TextWrappingProperty : StyledProperty_1[TextWrapping]
    VerticalContentAlignmentProperty : StyledProperty_1[VerticalAlignment]
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def Background(self) -> IBrush: ...
    @Background.setter
    def Background(self, value: IBrush) -> IBrush: ...
    @property
    def BackgroundSizing(self) -> BackgroundSizing: ...
    @BackgroundSizing.setter
    def BackgroundSizing(self, value: BackgroundSizing) -> BackgroundSizing: ...
    @property
    def BorderBrush(self) -> IBrush: ...
    @BorderBrush.setter
    def BorderBrush(self, value: IBrush) -> IBrush: ...
    @property
    def BorderThickness(self) -> Thickness: ...
    @BorderThickness.setter
    def BorderThickness(self, value: Thickness) -> Thickness: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def BoxShadow(self) -> BoxShadows: ...
    @BoxShadow.setter
    def BoxShadow(self, value: BoxShadows) -> BoxShadows: ...
    @property
    def Child(self) -> Control: ...
    @Child.setter
    def Child(self, value: Control) -> Control: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def Content(self) -> typing.Any: ...
    @Content.setter
    def Content(self, value: typing.Any) -> typing.Any: ...
    @property
    def ContentTemplate(self) -> IDataTemplate: ...
    @ContentTemplate.setter
    def ContentTemplate(self, value: IDataTemplate) -> IDataTemplate: ...
    @property
    def ContextFlyout(self) -> FlyoutBase: ...
    @ContextFlyout.setter
    def ContextFlyout(self, value: FlyoutBase) -> FlyoutBase: ...
    @property
    def ContextMenu(self) -> ContextMenu: ...
    @ContextMenu.setter
    def ContextMenu(self, value: ContextMenu) -> ContextMenu: ...
    @property
    def CornerRadius(self) -> CornerRadius: ...
    @CornerRadius.setter
    def CornerRadius(self, value: CornerRadius) -> CornerRadius: ...
    @property
    def Cursor(self) -> Cursor: ...
    @Cursor.setter
    def Cursor(self, value: Cursor) -> Cursor: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def DesiredSize(self) -> Size: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def Focusable(self) -> bool: ...
    @Focusable.setter
    def Focusable(self, value: bool) -> bool: ...
    @property
    def FocusAdorner(self) -> ITemplate_1[Control]: ...
    @FocusAdorner.setter
    def FocusAdorner(self, value: ITemplate_1[Control]) -> ITemplate_1[Control]: ...
    @property
    def FontFamily(self) -> FontFamily: ...
    @FontFamily.setter
    def FontFamily(self, value: FontFamily) -> FontFamily: ...
    @property
    def FontSize(self) -> float: ...
    @FontSize.setter
    def FontSize(self, value: float) -> float: ...
    @property
    def FontStretch(self) -> FontStretch: ...
    @FontStretch.setter
    def FontStretch(self, value: FontStretch) -> FontStretch: ...
    @property
    def FontStyle(self) -> FontStyle: ...
    @FontStyle.setter
    def FontStyle(self, value: FontStyle) -> FontStyle: ...
    @property
    def FontWeight(self) -> FontWeight: ...
    @FontWeight.setter
    def FontWeight(self, value: FontWeight) -> FontWeight: ...
    @property
    def Foreground(self) -> IBrush: ...
    @Foreground.setter
    def Foreground(self, value: IBrush) -> IBrush: ...
    @property
    def GestureRecognizers(self) -> GestureRecognizerCollection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def HorizontalContentAlignment(self) -> HorizontalAlignment: ...
    @HorizontalContentAlignment.setter
    def HorizontalContentAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @property
    def IsEffectivelyEnabled(self) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsFocused(self) -> bool: ...
    @property
    def IsHitTestVisible(self) -> bool: ...
    @IsHitTestVisible.setter
    def IsHitTestVisible(self, value: bool) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsKeyboardFocusWithin(self) -> bool: ...
    @IsKeyboardFocusWithin.setter
    def IsKeyboardFocusWithin(self, value: bool) -> bool: ...
    @property
    def IsLoaded(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @property
    def IsPointerOver(self) -> bool: ...
    @IsPointerOver.setter
    def IsPointerOver(self, value: bool) -> bool: ...
    @property
    def IsTabStop(self) -> bool: ...
    @IsTabStop.setter
    def IsTabStop(self, value: bool) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def KeyBindings(self) -> List_1[KeyBinding]: ...
    @property
    def LineHeight(self) -> float: ...
    @LineHeight.setter
    def LineHeight(self, value: float) -> float: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxLines(self) -> int: ...
    @MaxLines.setter
    def MaxLines(self, value: int) -> int: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Padding(self) -> Thickness: ...
    @Padding.setter
    def Padding(self, value: Thickness) -> Thickness: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def RecognizesAccessKey(self) -> bool: ...
    @RecognizesAccessKey.setter
    def RecognizesAccessKey(self, value: bool) -> bool: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def TabIndex(self) -> int: ...
    @TabIndex.setter
    def TabIndex(self, value: int) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def TextAlignment(self) -> TextAlignment: ...
    @TextAlignment.setter
    def TextAlignment(self, value: TextAlignment) -> TextAlignment: ...
    @property
    def TextTrimming(self) -> TextTrimming: ...
    @TextTrimming.setter
    def TextTrimming(self, value: TextTrimming) -> TextTrimming: ...
    @property
    def TextWrapping(self) -> TextWrapping: ...
    @TextWrapping.setter
    def TextWrapping(self, value: TextWrapping) -> TextWrapping: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def VerticalContentAlignment(self) -> VerticalAlignment: ...
    @VerticalContentAlignment.setter
    def VerticalContentAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    def ApplyTemplate(self) -> None: ...
    def Render(self, context: DrawingContext) -> None: ...
    def UpdateChild(self) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class ItemsPresenter(Control, ILogicalScrollable):
    def __init__(self) -> None: ...
    ItemsPanelProperty : StyledProperty_1[ITemplate_1[Panel]]
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def ContextFlyout(self) -> FlyoutBase: ...
    @ContextFlyout.setter
    def ContextFlyout(self, value: FlyoutBase) -> FlyoutBase: ...
    @property
    def ContextMenu(self) -> ContextMenu: ...
    @ContextMenu.setter
    def ContextMenu(self, value: ContextMenu) -> ContextMenu: ...
    @property
    def Cursor(self) -> Cursor: ...
    @Cursor.setter
    def Cursor(self, value: Cursor) -> Cursor: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def DesiredSize(self) -> Size: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def Focusable(self) -> bool: ...
    @Focusable.setter
    def Focusable(self, value: bool) -> bool: ...
    @property
    def FocusAdorner(self) -> ITemplate_1[Control]: ...
    @FocusAdorner.setter
    def FocusAdorner(self, value: ITemplate_1[Control]) -> ITemplate_1[Control]: ...
    @property
    def GestureRecognizers(self) -> GestureRecognizerCollection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @property
    def IsEffectivelyEnabled(self) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsFocused(self) -> bool: ...
    @property
    def IsHitTestVisible(self) -> bool: ...
    @IsHitTestVisible.setter
    def IsHitTestVisible(self, value: bool) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsKeyboardFocusWithin(self) -> bool: ...
    @IsKeyboardFocusWithin.setter
    def IsKeyboardFocusWithin(self, value: bool) -> bool: ...
    @property
    def IsLoaded(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @property
    def IsPointerOver(self) -> bool: ...
    @IsPointerOver.setter
    def IsPointerOver(self, value: bool) -> bool: ...
    @property
    def IsTabStop(self) -> bool: ...
    @IsTabStop.setter
    def IsTabStop(self, value: bool) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def ItemsPanel(self) -> ITemplate_1[Panel]: ...
    @ItemsPanel.setter
    def ItemsPanel(self, value: ITemplate_1[Panel]) -> ITemplate_1[Panel]: ...
    @property
    def KeyBindings(self) -> List_1[KeyBinding]: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Panel(self) -> Panel: ...
    @Panel.setter
    def Panel(self, value: Panel) -> Panel: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def TabIndex(self) -> int: ...
    @TabIndex.setter
    def TabIndex(self, value: int) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    def ApplyTemplate(self) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...

