import typing, abc
from MemoryPack import IMemoryPackFormatterRegister, IMemoryPackable_1
from System import Guid, Action
from System.Collections.Generic import List_1
from JAStudio.Core.Note import NoteData
from JAStudio.Core.Anki import AnkiKanjiNote, AnkiSentenceNote, AnkiVocabNote
from JAStudio.Core.Note.Sentences import SentenceConfiguration, ParsingResult

class CorpusDataBase(IMemoryPackFormatterRegister, abc.ABC):
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> Guid: ...
    @property
    def Tags(self) -> List_1[str]: ...
    @Tags.setter
    def Tags(self, value: List_1[str]) -> List_1[str]: ...
    def ToNoteData(self) -> NoteData: ...


class KanjiData(CorpusDataBase, IMemoryPackable_1[KanjiData]):
    def __init__(self) -> None: ...
    @property
    def ActiveAnswer(self) -> str: ...
    @ActiveAnswer.setter
    def ActiveAnswer(self, value: str) -> str: ...
    @property
    def Audio(self) -> str: ...
    @Audio.setter
    def Audio(self, value: str) -> str: ...
    @property
    def ConfusedWith(self) -> List_1[str]: ...
    @ConfusedWith.setter
    def ConfusedWith(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> Guid: ...
    @property
    def Image(self) -> str: ...
    @Image.setter
    def Image(self, value: str) -> str: ...
    @property
    def Kanji(self) -> str: ...
    @Kanji.setter
    def Kanji(self, value: str) -> str: ...
    @property
    def MeaningInfo(self) -> str: ...
    @MeaningInfo.setter
    def MeaningInfo(self, value: str) -> str: ...
    @property
    def PrimaryReadingsTtsAudio(self) -> str: ...
    @PrimaryReadingsTtsAudio.setter
    def PrimaryReadingsTtsAudio(self, value: str) -> str: ...
    @property
    def PrimaryVocab(self) -> List_1[str]: ...
    @PrimaryVocab.setter
    def PrimaryVocab(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def Radicals(self) -> List_1[str]: ...
    @Radicals.setter
    def Radicals(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def ReadingInfo(self) -> str: ...
    @ReadingInfo.setter
    def ReadingInfo(self, value: str) -> str: ...
    @property
    def ReadingKunHtml(self) -> str: ...
    @ReadingKunHtml.setter
    def ReadingKunHtml(self, value: str) -> str: ...
    @property
    def ReadingMnemonic(self) -> str: ...
    @ReadingMnemonic.setter
    def ReadingMnemonic(self, value: str) -> str: ...
    @property
    def ReadingNanHtml(self) -> str: ...
    @ReadingNanHtml.setter
    def ReadingNanHtml(self, value: str) -> str: ...
    @property
    def ReadingOnHtml(self) -> str: ...
    @ReadingOnHtml.setter
    def ReadingOnHtml(self, value: str) -> str: ...
    @property
    def References(self) -> str: ...
    @References.setter
    def References(self, value: str) -> str: ...
    @property
    def SimilarMeaning(self) -> List_1[str]: ...
    @SimilarMeaning.setter
    def SimilarMeaning(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def SourceAnswer(self) -> str: ...
    @SourceAnswer.setter
    def SourceAnswer(self, value: str) -> str: ...
    @property
    def SourceMeaningMnemonic(self) -> str: ...
    @SourceMeaningMnemonic.setter
    def SourceMeaningMnemonic(self, value: str) -> str: ...
    @property
    def Tags(self) -> List_1[str]: ...
    @Tags.setter
    def Tags(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def UserAnswer(self) -> str: ...
    @UserAnswer.setter
    def UserAnswer(self, value: str) -> str: ...
    @property
    def UserMnemonic(self) -> str: ...
    @UserMnemonic.setter
    def UserMnemonic(self, value: str) -> str: ...
    @staticmethod
    def FromAnki(anki: AnkiKanjiNote) -> KanjiData: ...
    @staticmethod
    def FromAnkiNoteData(data: NoteData) -> KanjiData: ...
    def MergeAnkiData(self, ankiData: NoteData) -> KanjiData: ...


class ParsedMatchSubData(IMemoryPackable_1[ParsedMatchSubData]):
    def __init__(self) -> None: ...
    @property
    def IsDisplayed(self) -> bool: ...
    @IsDisplayed.setter
    def IsDisplayed(self, value: bool) -> bool: ...
    @property
    def ParsedForm(self) -> str: ...
    @ParsedForm.setter
    def ParsedForm(self, value: str) -> str: ...
    @property
    def StartIndex(self) -> int: ...
    @StartIndex.setter
    def StartIndex(self, value: int) -> int: ...
    @property
    def Variant(self) -> str: ...
    @Variant.setter
    def Variant(self, value: str) -> str: ...
    @property
    def VocabId(self) -> typing.Optional[Guid]: ...
    @VocabId.setter
    def VocabId(self, value: typing.Optional[Guid]) -> typing.Optional[Guid]: ...


class SentenceConfigSubData(IMemoryPackable_1[SentenceConfigSubData]):
    def __init__(self) -> None: ...
    @property
    def HiddenMatches(self) -> List_1[WordExclusionSubData]: ...
    @HiddenMatches.setter
    def HiddenMatches(self, value: List_1[WordExclusionSubData]) -> List_1[WordExclusionSubData]: ...
    @property
    def HighlightedWords(self) -> List_1[str]: ...
    @HighlightedWords.setter
    def HighlightedWords(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def IncorrectMatches(self) -> List_1[WordExclusionSubData]: ...
    @IncorrectMatches.setter
    def IncorrectMatches(self, value: List_1[WordExclusionSubData]) -> List_1[WordExclusionSubData]: ...


class SentenceData(CorpusDataBase, IMemoryPackable_1[SentenceData]):
    def __init__(self) -> None: ...
    @property
    def ActiveAnswer(self) -> str: ...
    @ActiveAnswer.setter
    def ActiveAnswer(self, value: str) -> str: ...
    @property
    def ActiveQuestion(self) -> str: ...
    @ActiveQuestion.setter
    def ActiveQuestion(self, value: str) -> str: ...
    @property
    def Audio(self) -> str: ...
    @Audio.setter
    def Audio(self, value: str) -> str: ...
    @property
    def Configuration(self) -> SentenceConfigSubData: ...
    @Configuration.setter
    def Configuration(self, value: SentenceConfigSubData) -> SentenceConfigSubData: ...
    @property
    def ExternalId(self) -> str: ...
    @ExternalId.setter
    def ExternalId(self, value: str) -> str: ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> Guid: ...
    @property
    def JanomeTokens(self) -> str: ...
    @JanomeTokens.setter
    def JanomeTokens(self, value: str) -> str: ...
    @property
    def ParsingResult(self) -> SentenceParsingResultSubData: ...
    @ParsingResult.setter
    def ParsingResult(self, value: SentenceParsingResultSubData) -> SentenceParsingResultSubData: ...
    @property
    def Reading(self) -> str: ...
    @Reading.setter
    def Reading(self, value: str) -> str: ...
    @property
    def Screenshot(self) -> str: ...
    @Screenshot.setter
    def Screenshot(self, value: str) -> str: ...
    @property
    def SourceAnswer(self) -> str: ...
    @SourceAnswer.setter
    def SourceAnswer(self, value: str) -> str: ...
    @property
    def SourceComments(self) -> str: ...
    @SourceComments.setter
    def SourceComments(self, value: str) -> str: ...
    @property
    def SourceQuestion(self) -> str: ...
    @SourceQuestion.setter
    def SourceQuestion(self, value: str) -> str: ...
    @property
    def Tags(self) -> List_1[str]: ...
    @Tags.setter
    def Tags(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def UserAnswer(self) -> str: ...
    @UserAnswer.setter
    def UserAnswer(self, value: str) -> str: ...
    @property
    def UserComments(self) -> str: ...
    @UserComments.setter
    def UserComments(self, value: str) -> str: ...
    @property
    def UserQuestion(self) -> str: ...
    @UserQuestion.setter
    def UserQuestion(self, value: str) -> str: ...
    @staticmethod
    def CreateConfiguration(data: SentenceConfigSubData, saveCallback: Action) -> SentenceConfiguration: ...
    @staticmethod
    def CreateParsingResult(data: SentenceParsingResultSubData) -> ParsingResult: ...
    @staticmethod
    def FromAnki(anki: AnkiSentenceNote) -> SentenceData: ...
    @staticmethod
    def FromAnkiNoteData(data: NoteData) -> SentenceData: ...
    def MergeAnkiData(self, ankiData: NoteData) -> SentenceData: ...


class SentenceParsingResultSubData(IMemoryPackable_1[SentenceParsingResultSubData]):
    def __init__(self) -> None: ...
    @property
    def ParsedWords(self) -> List_1[ParsedMatchSubData]: ...
    @ParsedWords.setter
    def ParsedWords(self, value: List_1[ParsedMatchSubData]) -> List_1[ParsedMatchSubData]: ...
    @property
    def ParserVersion(self) -> str: ...
    @ParserVersion.setter
    def ParserVersion(self, value: str) -> str: ...
    @property
    def Sentence(self) -> str: ...
    @Sentence.setter
    def Sentence(self, value: str) -> str: ...


class VocabData(CorpusDataBase, IMemoryPackable_1[VocabData]):
    def __init__(self) -> None: ...
    @property
    def ActiveAnswer(self) -> str: ...
    @ActiveAnswer.setter
    def ActiveAnswer(self, value: str) -> str: ...
    @property
    def AudioB(self) -> str: ...
    @AudioB.setter
    def AudioB(self, value: str) -> str: ...
    @property
    def AudioG(self) -> str: ...
    @AudioG.setter
    def AudioG(self, value: str) -> str: ...
    @property
    def AudioTTS(self) -> str: ...
    @AudioTTS.setter
    def AudioTTS(self, value: str) -> str: ...
    @property
    def Forms(self) -> List_1[str]: ...
    @Forms.setter
    def Forms(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> Guid: ...
    @property
    def Image(self) -> str: ...
    @Image.setter
    def Image(self, value: str) -> str: ...
    @property
    def MatchingRules(self) -> VocabMatchingRulesSubData: ...
    @MatchingRules.setter
    def MatchingRules(self, value: VocabMatchingRulesSubData) -> VocabMatchingRulesSubData: ...
    @property
    def PartsOfSpeech(self) -> str: ...
    @PartsOfSpeech.setter
    def PartsOfSpeech(self, value: str) -> str: ...
    @property
    def Question(self) -> str: ...
    @Question.setter
    def Question(self, value: str) -> str: ...
    @property
    def Readings(self) -> List_1[str]: ...
    @Readings.setter
    def Readings(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def References(self) -> str: ...
    @References.setter
    def References(self, value: str) -> str: ...
    @property
    def RelatedVocab(self) -> VocabRelatedSubData: ...
    @RelatedVocab.setter
    def RelatedVocab(self, value: VocabRelatedSubData) -> VocabRelatedSubData: ...
    @property
    def SentenceCount(self) -> int: ...
    @SentenceCount.setter
    def SentenceCount(self, value: int) -> int: ...
    @property
    def SourceAnswer(self) -> str: ...
    @SourceAnswer.setter
    def SourceAnswer(self, value: str) -> str: ...
    @property
    def SourceMnemonic(self) -> str: ...
    @SourceMnemonic.setter
    def SourceMnemonic(self, value: str) -> str: ...
    @property
    def SourceReadingMnemonic(self) -> str: ...
    @SourceReadingMnemonic.setter
    def SourceReadingMnemonic(self, value: str) -> str: ...
    @property
    def Tags(self) -> List_1[str]: ...
    @Tags.setter
    def Tags(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def TechnicalNotes(self) -> str: ...
    @TechnicalNotes.setter
    def TechnicalNotes(self, value: str) -> str: ...
    @property
    def UserAnswer(self) -> str: ...
    @UserAnswer.setter
    def UserAnswer(self, value: str) -> str: ...
    @property
    def UserCompounds(self) -> List_1[str]: ...
    @UserCompounds.setter
    def UserCompounds(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def UserExplanation(self) -> str: ...
    @UserExplanation.setter
    def UserExplanation(self, value: str) -> str: ...
    @property
    def UserExplanationLong(self) -> str: ...
    @UserExplanationLong.setter
    def UserExplanationLong(self, value: str) -> str: ...
    @property
    def UserImage(self) -> str: ...
    @UserImage.setter
    def UserImage(self, value: str) -> str: ...
    @property
    def UserMnemonic(self) -> str: ...
    @UserMnemonic.setter
    def UserMnemonic(self, value: str) -> str: ...
    @staticmethod
    def FromAnki(anki: AnkiVocabNote) -> VocabData: ...
    @staticmethod
    def FromAnkiNoteData(data: NoteData) -> VocabData: ...
    def MergeAnkiData(self, ankiData: NoteData) -> VocabData: ...


class VocabMatchingRulesSubData(IMemoryPackable_1[VocabMatchingRulesSubData]):
    def __init__(self) -> None: ...
    @property
    def PrefixIsNot(self) -> List_1[str]: ...
    @PrefixIsNot.setter
    def PrefixIsNot(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def RequiredPrefix(self) -> List_1[str]: ...
    @RequiredPrefix.setter
    def RequiredPrefix(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def SuffixIsNot(self) -> List_1[str]: ...
    @SuffixIsNot.setter
    def SuffixIsNot(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def SurfaceIsNot(self) -> List_1[str]: ...
    @SurfaceIsNot.setter
    def SurfaceIsNot(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def YieldToSurface(self) -> List_1[str]: ...
    @YieldToSurface.setter
    def YieldToSurface(self, value: List_1[str]) -> List_1[str]: ...


class VocabRelatedSubData(IMemoryPackable_1[VocabRelatedSubData]):
    def __init__(self) -> None: ...
    @property
    def Antonyms(self) -> List_1[str]: ...
    @Antonyms.setter
    def Antonyms(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def ConfusedWith(self) -> List_1[str]: ...
    @ConfusedWith.setter
    def ConfusedWith(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def DerivedFrom(self) -> str: ...
    @DerivedFrom.setter
    def DerivedFrom(self, value: str) -> str: ...
    @property
    def ErgativeTwin(self) -> str: ...
    @ErgativeTwin.setter
    def ErgativeTwin(self, value: str) -> str: ...
    @property
    def PerfectSynonyms(self) -> List_1[str]: ...
    @PerfectSynonyms.setter
    def PerfectSynonyms(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def SeeAlso(self) -> List_1[str]: ...
    @SeeAlso.setter
    def SeeAlso(self, value: List_1[str]) -> List_1[str]: ...
    @property
    def Synonyms(self) -> List_1[str]: ...
    @Synonyms.setter
    def Synonyms(self, value: List_1[str]) -> List_1[str]: ...


class WordExclusionSubData(IMemoryPackable_1[WordExclusionSubData]):
    def __init__(self) -> None: ...
    @property
    def Index(self) -> int: ...
    @Index.setter
    def Index(self, value: int) -> int: ...
    @property
    def Word(self) -> str: ...
    @Word.setter
    def Word(self, value: str) -> str: ...

