import typing, abc
from Avalonia.Rendering.Composition.Animations import KeyFrameAnimation, AnimationDelayBehavior, ImplicitAnimationCollection, AnimationIterationBehavior, AnimationStopBehavior, CompositionAnimation, ICompositionAnimationBase, CompositionAnimationGroup, ExpressionAnimation
from System import TimeSpan, IDisposable, Array_1, Action, IAsyncDisposable
from Avalonia.Animation import PlaybackDirection
from Avalonia.Animation.Easings import IEasing
from Avalonia.Media import Color, IBrush, RenderOptions, ImmediateDrawingContext
from Avalonia import Vector, Vector3D, Rect
from System.Numerics import Quaternion, Vector2, Vector3, Vector4
from System.Threading.Tasks import Task, Task_1, ValueTask_1
from System.Collections.Generic import IList_1, List_1, IReadOnlyList_1
from Avalonia.Platform import IPlatformGraphics, IPlatformHandle, PlatformGraphicsExternalImageProperties
from Avalonia.Media.Imaging import Bitmap
from Avalonia.Rendering.Composition.Transport import CompositionBatch

class BooleanKeyFrameAnimation(KeyFrameAnimation):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    # Skipped InsertKeyFrame due to it being static, abstract and generic.

    InsertKeyFrame : InsertKeyFrame_MethodGroup
    class InsertKeyFrame_MethodGroup:
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: bool) -> None:...
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: bool, easingFunction: IEasing) -> None:...



class ColorKeyFrameAnimation(KeyFrameAnimation):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    # Skipped InsertKeyFrame due to it being static, abstract and generic.

    InsertKeyFrame : InsertKeyFrame_MethodGroup
    class InsertKeyFrame_MethodGroup:
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Color) -> None:...
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Color, easingFunction: IEasing) -> None:...



class CompositionContainerVisual(CompositionVisual):
    @property
    def AnchorPoint(self) -> Vector: ...
    @AnchorPoint.setter
    def AnchorPoint(self, value: Vector) -> Vector: ...
    @property
    def CenterPoint(self) -> Vector3D: ...
    @CenterPoint.setter
    def CenterPoint(self, value: Vector3D) -> Vector3D: ...
    @property
    def Children(self) -> CompositionVisualCollection: ...
    @Children.setter
    def Children(self, value: CompositionVisualCollection) -> CompositionVisualCollection: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Offset(self) -> Vector3D: ...
    @Offset.setter
    def Offset(self, value: Vector3D) -> Vector3D: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Orientation(self) -> Quaternion: ...
    @Orientation.setter
    def Orientation(self, value: Quaternion) -> Quaternion: ...
    @property
    def RenderOptions(self) -> RenderOptions: ...
    @RenderOptions.setter
    def RenderOptions(self, value: RenderOptions) -> RenderOptions: ...
    @property
    def RotationAngle(self) -> float: ...
    @RotationAngle.setter
    def RotationAngle(self, value: float) -> float: ...
    @property
    def Scale(self) -> Vector3D: ...
    @Scale.setter
    def Scale(self, value: Vector3D) -> Vector3D: ...
    @property
    def Size(self) -> Vector: ...
    @Size.setter
    def Size(self, value: Vector) -> Vector: ...
    @property
    def Visible(self) -> bool: ...
    @Visible.setter
    def Visible(self, value: bool) -> bool: ...


class CompositionCustomVisual(CompositionContainerVisual):
    @property
    def AnchorPoint(self) -> Vector: ...
    @AnchorPoint.setter
    def AnchorPoint(self, value: Vector) -> Vector: ...
    @property
    def CenterPoint(self) -> Vector3D: ...
    @CenterPoint.setter
    def CenterPoint(self, value: Vector3D) -> Vector3D: ...
    @property
    def Children(self) -> CompositionVisualCollection: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Offset(self) -> Vector3D: ...
    @Offset.setter
    def Offset(self, value: Vector3D) -> Vector3D: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Orientation(self) -> Quaternion: ...
    @Orientation.setter
    def Orientation(self, value: Quaternion) -> Quaternion: ...
    @property
    def RenderOptions(self) -> RenderOptions: ...
    @RenderOptions.setter
    def RenderOptions(self, value: RenderOptions) -> RenderOptions: ...
    @property
    def RotationAngle(self) -> float: ...
    @RotationAngle.setter
    def RotationAngle(self, value: float) -> float: ...
    @property
    def Scale(self) -> Vector3D: ...
    @Scale.setter
    def Scale(self, value: Vector3D) -> Vector3D: ...
    @property
    def Size(self) -> Vector: ...
    @Size.setter
    def Size(self, value: Vector) -> Vector: ...
    @property
    def Visible(self) -> bool: ...
    @Visible.setter
    def Visible(self, value: bool) -> bool: ...
    def SendHandlerMessage(self, message: typing.Any) -> None: ...


class CompositionCustomVisualHandler(abc.ABC):
    def GetRenderBounds(self) -> Rect: ...
    def OnAnimationFrameUpdate(self) -> None: ...
    def OnMessage(self, message: typing.Any) -> None: ...
    @abc.abstractmethod
    def OnRender(self, drawingContext: ImmediateDrawingContext) -> None: ...


class CompositionDrawingSurface(CompositionSurface, IDisposable):
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    def Dispose(self) -> None: ...
    def UpdateAsync(self, image: ICompositionImportedGpuImage) -> Task: ...
    def UpdateWithKeyedMutexAsync(self, image: ICompositionImportedGpuImage, acquireIndex: int, releaseIndex: int) -> Task: ...
    def UpdateWithSemaphoresAsync(self, image: ICompositionImportedGpuImage, waitForSemaphore: ICompositionImportedGpuSemaphore, signalSemaphore: ICompositionImportedGpuSemaphore) -> Task: ...


class CompositionGpuImportedImageSynchronizationCapabilities(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Semaphores : CompositionGpuImportedImageSynchronizationCapabilities # 1
    KeyedMutex : CompositionGpuImportedImageSynchronizationCapabilities # 2
    Automatic : CompositionGpuImportedImageSynchronizationCapabilities # 4


class CompositionObject(abc.ABC):
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @IsDisposed.setter
    def IsDisposed(self, value: bool) -> bool: ...
    def StartAnimation(self, propertyName: str, animation: CompositionAnimation) -> None: ...
    def StartAnimationGroup(self, grp: ICompositionAnimationBase) -> None: ...


class CompositionSolidColorVisual(CompositionContainerVisual):
    @property
    def AnchorPoint(self) -> Vector: ...
    @AnchorPoint.setter
    def AnchorPoint(self, value: Vector) -> Vector: ...
    @property
    def CenterPoint(self) -> Vector3D: ...
    @CenterPoint.setter
    def CenterPoint(self, value: Vector3D) -> Vector3D: ...
    @property
    def Children(self) -> CompositionVisualCollection: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def Color(self) -> Color: ...
    @Color.setter
    def Color(self, value: Color) -> Color: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Offset(self) -> Vector3D: ...
    @Offset.setter
    def Offset(self, value: Vector3D) -> Vector3D: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Orientation(self) -> Quaternion: ...
    @Orientation.setter
    def Orientation(self, value: Quaternion) -> Quaternion: ...
    @property
    def RenderOptions(self) -> RenderOptions: ...
    @RenderOptions.setter
    def RenderOptions(self, value: RenderOptions) -> RenderOptions: ...
    @property
    def RotationAngle(self) -> float: ...
    @RotationAngle.setter
    def RotationAngle(self, value: float) -> float: ...
    @property
    def Scale(self) -> Vector3D: ...
    @Scale.setter
    def Scale(self, value: Vector3D) -> Vector3D: ...
    @property
    def Size(self) -> Vector: ...
    @Size.setter
    def Size(self, value: Vector) -> Vector: ...
    @property
    def Visible(self) -> bool: ...
    @Visible.setter
    def Visible(self, value: bool) -> bool: ...


class CompositionSurface(CompositionObject):
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...


class CompositionSurfaceVisual(CompositionContainerVisual):
    @property
    def AnchorPoint(self) -> Vector: ...
    @AnchorPoint.setter
    def AnchorPoint(self, value: Vector) -> Vector: ...
    @property
    def CenterPoint(self) -> Vector3D: ...
    @CenterPoint.setter
    def CenterPoint(self, value: Vector3D) -> Vector3D: ...
    @property
    def Children(self) -> CompositionVisualCollection: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Offset(self) -> Vector3D: ...
    @Offset.setter
    def Offset(self, value: Vector3D) -> Vector3D: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Orientation(self) -> Quaternion: ...
    @Orientation.setter
    def Orientation(self, value: Quaternion) -> Quaternion: ...
    @property
    def RenderOptions(self) -> RenderOptions: ...
    @RenderOptions.setter
    def RenderOptions(self, value: RenderOptions) -> RenderOptions: ...
    @property
    def RotationAngle(self) -> float: ...
    @RotationAngle.setter
    def RotationAngle(self, value: float) -> float: ...
    @property
    def Scale(self) -> Vector3D: ...
    @Scale.setter
    def Scale(self, value: Vector3D) -> Vector3D: ...
    @property
    def Size(self) -> Vector: ...
    @Size.setter
    def Size(self, value: Vector) -> Vector: ...
    @property
    def Surface(self) -> CompositionSurface: ...
    @Surface.setter
    def Surface(self, value: CompositionSurface) -> CompositionSurface: ...
    @property
    def Visible(self) -> bool: ...
    @Visible.setter
    def Visible(self, value: bool) -> bool: ...


class CompositionVisual(CompositionObject):
    @property
    def AnchorPoint(self) -> Vector: ...
    @AnchorPoint.setter
    def AnchorPoint(self, value: Vector) -> Vector: ...
    @property
    def CenterPoint(self) -> Vector3D: ...
    @CenterPoint.setter
    def CenterPoint(self, value: Vector3D) -> Vector3D: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def Offset(self) -> Vector3D: ...
    @Offset.setter
    def Offset(self, value: Vector3D) -> Vector3D: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Orientation(self) -> Quaternion: ...
    @Orientation.setter
    def Orientation(self, value: Quaternion) -> Quaternion: ...
    @property
    def RenderOptions(self) -> RenderOptions: ...
    @RenderOptions.setter
    def RenderOptions(self, value: RenderOptions) -> RenderOptions: ...
    @property
    def RotationAngle(self) -> float: ...
    @RotationAngle.setter
    def RotationAngle(self, value: float) -> float: ...
    @property
    def Scale(self) -> Vector3D: ...
    @Scale.setter
    def Scale(self, value: Vector3D) -> Vector3D: ...
    @property
    def Size(self) -> Vector: ...
    @Size.setter
    def Size(self, value: Vector) -> Vector: ...
    @property
    def Visible(self) -> bool: ...
    @Visible.setter
    def Visible(self, value: bool) -> bool: ...


class CompositionVisualCollection(CompositionObject, IList_1[CompositionVisual]):
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def Count(self) -> int: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IsReadOnly(self) -> bool: ...
    def Add(self, item: CompositionVisual) -> None: ...
    def Clear(self) -> None: ...
    def Contains(self, item: CompositionVisual) -> bool: ...
    def CopyTo(self, array: Array_1[CompositionVisual], arrayIndex: int) -> None: ...
    def GetEnumerator(self) -> List_1.Enumerator_1[CompositionVisual]: ...
    def IndexOf(self, item: CompositionVisual) -> int: ...
    def Insert(self, index: int, item: CompositionVisual) -> None: ...
    def InsertAbove(self, newChild: CompositionVisual, sibling: CompositionVisual) -> None: ...
    def InsertAtBottom(self, newChild: CompositionVisual) -> None: ...
    def InsertAtTop(self, newChild: CompositionVisual) -> None: ...
    def InsertBelow(self, newChild: CompositionVisual, sibling: CompositionVisual) -> None: ...
    def Remove(self, item: CompositionVisual) -> bool: ...
    def RemoveAll(self) -> None: ...
    def RemoveAt(self, index: int) -> None: ...
    def __getitem__(self, index: int) -> CompositionVisual: ...
    def __setitem__(self, index: int, value: CompositionVisual) -> None: ...


class Compositor:
    def __init__(self, gpu: IPlatformGraphics, useUiThreadForSynchronousCommits: bool = ...) -> None: ...
    def CreateAnimationGroup(self) -> CompositionAnimationGroup: ...
    def CreateBooleanKeyFrameAnimation(self) -> BooleanKeyFrameAnimation: ...
    def CreateColorKeyFrameAnimation(self) -> ColorKeyFrameAnimation: ...
    def CreateCompositionVisualSnapshot(self, visual: CompositionVisual, scaling: float) -> Task_1[Bitmap]: ...
    def CreateContainerVisual(self) -> CompositionContainerVisual: ...
    def CreateCustomVisual(self, handler: CompositionCustomVisualHandler) -> CompositionCustomVisual: ...
    def CreateDoubleKeyFrameAnimation(self) -> DoubleKeyFrameAnimation: ...
    def CreateDrawingSurface(self) -> CompositionDrawingSurface: ...
    def CreateImplicitAnimationCollection(self) -> ImplicitAnimationCollection: ...
    def CreateQuaternionKeyFrameAnimation(self) -> QuaternionKeyFrameAnimation: ...
    def CreateScalarKeyFrameAnimation(self) -> ScalarKeyFrameAnimation: ...
    def CreateSolidColorVisual(self) -> CompositionSolidColorVisual: ...
    def CreateSurfaceVisual(self) -> CompositionSurfaceVisual: ...
    def CreateVector2KeyFrameAnimation(self) -> Vector2KeyFrameAnimation: ...
    def CreateVector3DKeyFrameAnimation(self) -> Vector3DKeyFrameAnimation: ...
    def CreateVector3KeyFrameAnimation(self) -> Vector3KeyFrameAnimation: ...
    def CreateVector4KeyFrameAnimation(self) -> Vector4KeyFrameAnimation: ...
    def CreateVectorKeyFrameAnimation(self) -> VectorKeyFrameAnimation: ...
    def RequestCommitAsync(self) -> Task: ...
    def RequestCompositionBatchCommitAsync(self) -> CompositionBatch: ...
    def RequestCompositionUpdate(self, action: Action) -> None: ...
    def TryGetCompositionGpuInterop(self) -> ValueTask_1[ICompositionGpuInterop]: ...
    @staticmethod
    def TryGetDefaultCompositor() -> Compositor: ...
    def TryGetRenderInterfaceFeature(self, featureType: typing.Type[typing.Any]) -> ValueTask_1[typing.Any]: ...
    # Skipped CreateExpressionAnimation due to it being static, abstract and generic.

    CreateExpressionAnimation : CreateExpressionAnimation_MethodGroup
    class CreateExpressionAnimation_MethodGroup:
        @typing.overload
        def __call__(self) -> ExpressionAnimation:...
        @typing.overload
        def __call__(self, expression: str) -> ExpressionAnimation:...



class DoubleKeyFrameAnimation(KeyFrameAnimation):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    # Skipped InsertKeyFrame due to it being static, abstract and generic.

    InsertKeyFrame : InsertKeyFrame_MethodGroup
    class InsertKeyFrame_MethodGroup:
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: float) -> None:...
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: float, easingFunction: IEasing) -> None:...



class ICompositionGpuImportedObject(IAsyncDisposable, typing.Protocol):
    @property
    def ImportCompeted(self) -> Task: ...
    @property
    def ImportCompleted(self) -> Task: ...
    @property
    def IsLost(self) -> bool: ...


class ICompositionGpuInterop(typing.Protocol):
    @property
    def DeviceLuid(self) -> Array_1[int]: ...
    @DeviceLuid.setter
    def DeviceLuid(self, value: Array_1[int]) -> Array_1[int]: ...
    @property
    def DeviceUuid(self) -> Array_1[int]: ...
    @DeviceUuid.setter
    def DeviceUuid(self, value: Array_1[int]) -> Array_1[int]: ...
    @property
    def IsLost(self) -> bool: ...
    @property
    def SupportedImageHandleTypes(self) -> IReadOnlyList_1[str]: ...
    @property
    def SupportedSemaphoreTypes(self) -> IReadOnlyList_1[str]: ...
    @abc.abstractmethod
    def GetSynchronizationCapabilities(self, imageHandleType: str) -> CompositionGpuImportedImageSynchronizationCapabilities: ...
    # Skipped ImportImage due to it being static, abstract and generic.

    ImportImage : ImportImage_MethodGroup
    class ImportImage_MethodGroup:
        @typing.overload
        def __call__(self, image: ICompositionImportableSharedGpuContextImage) -> ICompositionImportedGpuImage:...
        @typing.overload
        def __call__(self, handle: IPlatformHandle, properties: PlatformGraphicsExternalImageProperties) -> ICompositionImportedGpuImage:...

    # Skipped ImportSemaphore due to it being static, abstract and generic.

    ImportSemaphore : ImportSemaphore_MethodGroup
    class ImportSemaphore_MethodGroup:
        @typing.overload
        def __call__(self, image: ICompositionImportableSharedGpuContextSemaphore) -> ICompositionImportedGpuImage:...
        @typing.overload
        def __call__(self, handle: IPlatformHandle) -> ICompositionImportedGpuSemaphore:...



class ICompositionImportableSharedGpuContextImage(IDisposable, typing.Protocol):
    pass


class ICompositionImportableSharedGpuContextSemaphore(IDisposable, typing.Protocol):
    pass


class ICompositionImportedGpuImage(ICompositionGpuImportedObject, typing.Protocol):
    pass


class ICompositionImportedGpuSemaphore(ICompositionGpuImportedObject, typing.Protocol):
    pass


class QuaternionKeyFrameAnimation(KeyFrameAnimation):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    # Skipped InsertKeyFrame due to it being static, abstract and generic.

    InsertKeyFrame : InsertKeyFrame_MethodGroup
    class InsertKeyFrame_MethodGroup:
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Quaternion) -> None:...
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Quaternion, easingFunction: IEasing) -> None:...



class ScalarKeyFrameAnimation(KeyFrameAnimation):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    # Skipped InsertKeyFrame due to it being static, abstract and generic.

    InsertKeyFrame : InsertKeyFrame_MethodGroup
    class InsertKeyFrame_MethodGroup:
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: float) -> None:...
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: float, easingFunction: IEasing) -> None:...



class Vector2KeyFrameAnimation(KeyFrameAnimation):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    # Skipped InsertKeyFrame due to it being static, abstract and generic.

    InsertKeyFrame : InsertKeyFrame_MethodGroup
    class InsertKeyFrame_MethodGroup:
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Vector2) -> None:...
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Vector2, easingFunction: IEasing) -> None:...



class Vector3DKeyFrameAnimation(KeyFrameAnimation):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    # Skipped InsertKeyFrame due to it being static, abstract and generic.

    InsertKeyFrame : InsertKeyFrame_MethodGroup
    class InsertKeyFrame_MethodGroup:
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Vector3D) -> None:...
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Vector3D, easingFunction: IEasing) -> None:...



class Vector3KeyFrameAnimation(KeyFrameAnimation):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    # Skipped InsertKeyFrame due to it being static, abstract and generic.

    InsertKeyFrame : InsertKeyFrame_MethodGroup
    class InsertKeyFrame_MethodGroup:
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Vector3) -> None:...
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Vector3, easingFunction: IEasing) -> None:...



class Vector4KeyFrameAnimation(KeyFrameAnimation):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    # Skipped InsertKeyFrame due to it being static, abstract and generic.

    InsertKeyFrame : InsertKeyFrame_MethodGroup
    class InsertKeyFrame_MethodGroup:
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Vector4) -> None:...
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Vector4, easingFunction: IEasing) -> None:...



class VectorKeyFrameAnimation(KeyFrameAnimation):
    def __init__(self, compositor: Compositor) -> None: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DelayBehavior(self) -> AnimationDelayBehavior: ...
    @DelayBehavior.setter
    def DelayBehavior(self, value: AnimationDelayBehavior) -> AnimationDelayBehavior: ...
    @property
    def DelayTime(self) -> TimeSpan: ...
    @DelayTime.setter
    def DelayTime(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def Direction(self) -> PlaybackDirection: ...
    @Direction.setter
    def Direction(self, value: PlaybackDirection) -> PlaybackDirection: ...
    @property
    def Duration(self) -> TimeSpan: ...
    @Duration.setter
    def Duration(self, value: TimeSpan) -> TimeSpan: ...
    @property
    def ImplicitAnimations(self) -> ImplicitAnimationCollection: ...
    @ImplicitAnimations.setter
    def ImplicitAnimations(self, value: ImplicitAnimationCollection) -> ImplicitAnimationCollection: ...
    @property
    def IsDisposed(self) -> bool: ...
    @property
    def IterationBehavior(self) -> AnimationIterationBehavior: ...
    @IterationBehavior.setter
    def IterationBehavior(self, value: AnimationIterationBehavior) -> AnimationIterationBehavior: ...
    @property
    def IterationCount(self) -> int: ...
    @IterationCount.setter
    def IterationCount(self, value: int) -> int: ...
    @property
    def StopBehavior(self) -> AnimationStopBehavior: ...
    @StopBehavior.setter
    def StopBehavior(self, value: AnimationStopBehavior) -> AnimationStopBehavior: ...
    @property
    def Target(self) -> str: ...
    @Target.setter
    def Target(self, value: str) -> str: ...
    # Skipped InsertKeyFrame due to it being static, abstract and generic.

    InsertKeyFrame : InsertKeyFrame_MethodGroup
    class InsertKeyFrame_MethodGroup:
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Vector) -> None:...
        @typing.overload
        def __call__(self, normalizedProgressKey: float, value: Vector, easingFunction: IEasing) -> None:...


