namespace JAStudio.Core.Tests;

/// <summary>
/// Marker interface for test classes that were generated by AI rather than ported from Python.
/// This helps distinguish between ported test logic and newly created test coverage.
/// </summary>
public interface IAIGeneratedTestClass
{
}
