import abc
from JAStudio.Core.Note import VocabNote, SentenceNote
from System.Collections.Generic import List_1, HashSet_1
from JAStudio.Core.UI.Web import PreRenderingContentRenderer_1
from JAStudio.Core.Note.Sentences import ParsedMatch, ParsingResult

class CompoundPart:
    def __init__(self, vocabNote: VocabNote, depth: int = ...) -> None: ...
    @property
    def Depth(self) -> int: ...
    @Depth.setter
    def Depth(self, value: int) -> int: ...
    @property
    def VocabNote(self) -> VocabNote: ...
    @VocabNote.setter
    def VocabNote(self, value: VocabNote) -> VocabNote: ...


class CompoundPartsRenderer(abc.ABC):
    @staticmethod
    def GenerateCompounds(vocabNote: VocabNote) -> str: ...


class RelatedVocabsRenderer:
    @staticmethod
    def CreateClasses(vocab: VocabNote) -> str: ...
    @staticmethod
    def GenerateAntonymsMeaningHtmlList(vocabNote: VocabNote) -> str: ...
    def GenerateConfusedWithHtmlList(self, vocabNote: VocabNote) -> str: ...
    def GenerateDerivedFrom(self, vocabNote: VocabNote) -> str: ...
    def GenerateDerivedList(self, vocabNote: VocabNote) -> str: ...
    def GenerateErgativeTwinHtml(self, vocabNote: VocabNote) -> str: ...
    @staticmethod
    def GenerateFormsList(vocabNote: VocabNote) -> str: ...
    @staticmethod
    def GenerateHomophonesHtmlList(vocabNote: VocabNote) -> str: ...
    @staticmethod
    def GenerateInCompoundsList(vocabNote: VocabNote) -> str: ...
    @staticmethod
    def GenerateMetaTags(vocabNote: VocabNote) -> str: ...
    @staticmethod
    def GeneratePerfectSynonymsMeaningHtmlList(vocabNote: VocabNote) -> str: ...
    @staticmethod
    def GenerateSeeAlsoHtmlList(vocabNote: VocabNote) -> str: ...
    def GenerateStemInCompoundsList(self, vocabNote: VocabNote) -> str: ...
    def GenerateStemOfVocabs(self, vocabNote: VocabNote) -> str: ...
    @staticmethod
    def GenerateStemVocabs(vocabNote: VocabNote) -> str: ...
    @staticmethod
    def GenerateSynonymsMeaningHtmlList(vocabNote: VocabNote) -> str: ...


class VocabKanjiListRenderer:
    def RenderKanjiListFromKanji(self, kanjis: List_1[str]) -> str: ...
    def RenderVocabKanjiList(self, vocab: VocabNote) -> str: ...


class VocabNoteRenderer:
    def CreateRenderer(self) -> PreRenderingContentRenderer_1[VocabNote]: ...


class VocabSentenceMatchViewModel:
    def __init__(self, match: ParsedMatch, sentenceViewModel: VocabSentenceViewModel) -> None: ...
    @property
    def EndIndex(self) -> int: ...
    @property
    def IsDisplayed(self) -> bool: ...
    @property
    def Match(self) -> ParsedMatch: ...
    @property
    def SentenceViewModel(self) -> VocabSentenceViewModel: ...
    @property
    def ShadedBy(self) -> ParsedMatch: ...
    @property
    def StartIndex(self) -> int: ...
    @property
    def YieldsTo(self) -> ParsedMatch: ...
    def IsPrimaryFormOf(self, vocab: VocabNote) -> bool: ...
    def ToString(self) -> str: ...


class VocabSentencesRenderer(abc.ABC):
    @staticmethod
    def GenerateMarkedInvalidInListHtml(vocabNote: VocabNote) -> str: ...
    @staticmethod
    def GenerateValidInListHtml(vocabNote: VocabNote) -> str: ...


class VocabSentenceViewModel:
    def __init__(self, vocabNote: VocabNote, sentenceNote: SentenceNote) -> None: ...
    @property
    def DisplayedMatches(self) -> List_1[VocabSentenceMatchViewModel]: ...
    @property
    def HighlightedSentences(self) -> HashSet_1[SentenceNote]: ...
    @property
    def MatchedVocabIds(self) -> HashSet_1[int]: ...
    @property
    def Matches(self) -> List_1[VocabSentenceMatchViewModel]: ...
    @property
    def PrimaryMatch(self) -> VocabSentenceMatchViewModel: ...
    @property
    def Result(self) -> ParsingResult: ...
    @property
    def Sentence(self) -> SentenceNote: ...
    @property
    def ShadedMatches(self) -> List_1[VocabSentenceMatchViewModel]: ...
    @property
    def Vocab(self) -> VocabNote: ...
    @property
    def VocabIsDisplayed(self) -> bool: ...
    def ContainsPrimaryForm(self) -> bool: ...
    def FormatSentence(self) -> str: ...
    def IsHighlighted(self) -> bool: ...
    def SentenceClasses(self) -> str: ...

