from JAStudio.Core.UI.Web import AppendingPrerenderer_1
from JAStudio.Core.Note.Vocabulary import VocabNote
from JAStudio.Core.Note.Sentences import ParsedMatch, SentenceNote, ParsingResult
from System.Collections.Generic import List_1, HashSet_1
from JAStudio.Core.Note import NoteId

class VocabNoteRenderer:
    def __init__(self) -> None: ...
    def CreateRenderer(self) -> AppendingPrerenderer_1[VocabNote]: ...


class VocabSentenceMatchViewModel:
    def __init__(self, match: ParsedMatch, sentenceViewModel: VocabSentenceViewModel) -> None: ...
    @property
    def EndIndex(self) -> int: ...
    @property
    def IsDisplayed(self) -> bool: ...
    @property
    def Match(self) -> ParsedMatch: ...
    @property
    def SentenceViewModel(self) -> VocabSentenceViewModel: ...
    @property
    def ShadedBy(self) -> ParsedMatch: ...
    @property
    def StartIndex(self) -> int: ...
    @property
    def YieldsTo(self) -> ParsedMatch: ...
    def IsPrimaryFormOf(self, vocab: VocabNote) -> bool: ...
    def ToString(self) -> str: ...


class VocabSentenceViewModel:
    def __init__(self, vocabNote: VocabNote, sentenceNote: SentenceNote) -> None: ...
    @property
    def DisplayedMatches(self) -> List_1[VocabSentenceMatchViewModel]: ...
    @property
    def HighlightedSentences(self) -> HashSet_1[SentenceNote]: ...
    @property
    def MatchedVocabIds(self) -> HashSet_1[NoteId]: ...
    @property
    def Matches(self) -> List_1[VocabSentenceMatchViewModel]: ...
    @property
    def PrimaryMatch(self) -> VocabSentenceMatchViewModel: ...
    @property
    def Result(self) -> ParsingResult: ...
    @property
    def Sentence(self) -> SentenceNote: ...
    @property
    def ShadedMatches(self) -> List_1[VocabSentenceMatchViewModel]: ...
    @property
    def Vocab(self) -> VocabNote: ...
    @property
    def VocabIsDisplayed(self) -> bool: ...
    def ContainsPrimaryForm(self) -> bool: ...
    def FormatSentence(self) -> str: ...
    def IsHighlighted(self) -> bool: ...
    def SentenceClasses(self) -> str: ...

