import typing
from JAStudio.Core.TaskRunners import IScopePanel, TaskProgressScopeViewModel, ITaskProgressRunner, ThreadCount
from System.Collections.Generic import List_1, IReadOnlyList_1
from System import Func_2, Func_1
from System.Threading.Tasks import Task_1
from Avalonia.Controls import UserControl, Classes, ContextMenu, ITemplate_1, Control, IResourceDictionary, Window, WindowTransparencyLevel, WindowClosingBehavior, WindowIcon, WindowBase, Screens, SizeToContent, SystemDecorations, WindowStartupLocation, WindowState
from Avalonia.Styling import ThemeVariant, Styles, ControlTheme
from Avalonia.Media import IBrush, BackgroundSizing, Geometry, IEffect, FlowDirection, FontFamily, FontFeatureCollection, FontStretch, FontStyle, FontWeight, ITransform
from Avalonia import Thickness, Rect, CornerRadius, Size, StyledElement, RelativePoint, AvaloniaObject, AvaloniaProperty, PixelPoint
from Avalonia.Controls.Templates import IDataTemplate, DataTemplates, IControlTemplate
from Avalonia.Controls.Primitives import FlyoutBase
from Avalonia.Input import Cursor, KeyBinding, IFocusManager
from Avalonia.Input.GestureRecognizers import GestureRecognizerCollection
from Avalonia.Layout import HorizontalAlignment, VerticalAlignment
from Avalonia.Controls.Presenters import ContentPresenter
from Avalonia.Animation import Transitions
from Avalonia.Data import IndexerDescriptor, IBinding
from Avalonia.Input.Platform import IClipboard
from Avalonia.Platform import ExtendClientAreaChromeHints, IWindowImpl, IWindowBaseImpl, ITopLevelImpl, IPlatformSettings
from Avalonia.Controls.Platform import IInputPane, IInsetsManager
from Avalonia.Platform.Storage import ILauncher, IStorageProvider
from Avalonia.Rendering import RendererDiagnostics

class AvaloniaScopePanel(IScopePanel):
    def __init__(self, viewModel: TaskProgressScopeViewModel, panel: TaskProgressScopePanel) -> None: ...
    @property
    def ViewModel(self) -> TaskProgressScopeViewModel: ...
    def Dispose(self) -> None: ...


class AvaloniaTaskProgressRunner(ITaskProgressRunner):
    def __init__(self, scopeViewModel: TaskProgressScopeViewModel, labelText: str, allowCancel: bool) -> None: ...
    def Close(self) -> None: ...
    def Dispose(self) -> None: ...
    def IsHidden(self) -> bool: ...
    def SetLabelText(self, text: str) -> None: ...
    # Skipped RunBatch due to it being static, abstract and generic.

    RunBatch : RunBatch_MethodGroup
    class RunBatch_MethodGroup:
        def __getitem__(self, t:typing.Tuple[typing.Type[RunBatch_2_T1], typing.Type[RunBatch_2_T2]]) -> RunBatch_2[RunBatch_2_T1, RunBatch_2_T2]: ...

        RunBatch_2_T1 = typing.TypeVar('RunBatch_2_T1')
        RunBatch_2_T2 = typing.TypeVar('RunBatch_2_T2')
        class RunBatch_2(typing.Generic[RunBatch_2_T1, RunBatch_2_T2]):
            RunBatch_2_TInput = AvaloniaTaskProgressRunner.RunBatch_MethodGroup.RunBatch_2_T1
            RunBatch_2_TOutput = AvaloniaTaskProgressRunner.RunBatch_MethodGroup.RunBatch_2_T2
            def __call__(self, items: List_1[RunBatch_2_TInput], processItem: Func_2[RunBatch_2_TInput, RunBatch_2_TOutput], message: str, threads: ThreadCount) -> List_1[RunBatch_2_TOutput]:...


    # Skipped RunBatchAsync due to it being static, abstract and generic.

    RunBatchAsync : RunBatchAsync_MethodGroup
    class RunBatchAsync_MethodGroup:
        def __getitem__(self, t:typing.Tuple[typing.Type[RunBatchAsync_2_T1], typing.Type[RunBatchAsync_2_T2]]) -> RunBatchAsync_2[RunBatchAsync_2_T1, RunBatchAsync_2_T2]: ...

        RunBatchAsync_2_T1 = typing.TypeVar('RunBatchAsync_2_T1')
        RunBatchAsync_2_T2 = typing.TypeVar('RunBatchAsync_2_T2')
        class RunBatchAsync_2(typing.Generic[RunBatchAsync_2_T1, RunBatchAsync_2_T2]):
            RunBatchAsync_2_TInput = AvaloniaTaskProgressRunner.RunBatchAsync_MethodGroup.RunBatchAsync_2_T1
            RunBatchAsync_2_TOutput = AvaloniaTaskProgressRunner.RunBatchAsync_MethodGroup.RunBatchAsync_2_T2
            def __call__(self, items: List_1[RunBatchAsync_2_TInput], processItem: Func_2[RunBatchAsync_2_TInput, RunBatchAsync_2_TOutput], message: str, threads: ThreadCount) -> Task_1[List_1[RunBatchAsync_2_TOutput]]:...


    # Skipped RunIndeterminate due to it being static, abstract and generic.

    RunIndeterminate : RunIndeterminate_MethodGroup
    class RunIndeterminate_MethodGroup:
        def __getitem__(self, t:typing.Type[RunIndeterminate_1_T1]) -> RunIndeterminate_1[RunIndeterminate_1_T1]: ...

        RunIndeterminate_1_T1 = typing.TypeVar('RunIndeterminate_1_T1')
        class RunIndeterminate_1(typing.Generic[RunIndeterminate_1_T1]):
            RunIndeterminate_1_TResult = AvaloniaTaskProgressRunner.RunIndeterminate_MethodGroup.RunIndeterminate_1_T1
            def __call__(self, message: str, action: Func_1[RunIndeterminate_1_TResult]) -> RunIndeterminate_1_TResult:...


    # Skipped RunIndeterminateAsync due to it being static, abstract and generic.

    RunIndeterminateAsync : RunIndeterminateAsync_MethodGroup
    class RunIndeterminateAsync_MethodGroup:
        def __getitem__(self, t:typing.Type[RunIndeterminateAsync_1_T1]) -> RunIndeterminateAsync_1[RunIndeterminateAsync_1_T1]: ...

        RunIndeterminateAsync_1_T1 = typing.TypeVar('RunIndeterminateAsync_1_T1')
        class RunIndeterminateAsync_1(typing.Generic[RunIndeterminateAsync_1_T1]):
            RunIndeterminateAsync_1_TResult = AvaloniaTaskProgressRunner.RunIndeterminateAsync_MethodGroup.RunIndeterminateAsync_1_T1
            def __call__(self, message: str, action: Func_1[RunIndeterminateAsync_1_TResult]) -> Task_1[RunIndeterminateAsync_1_TResult]:...




class BatchTaskProgressPanel(UserControl):
    def __init__(self) -> None: ...
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def Background(self) -> IBrush: ...
    @Background.setter
    def Background(self, value: IBrush) -> IBrush: ...
    @property
    def BackgroundSizing(self) -> BackgroundSizing: ...
    @BackgroundSizing.setter
    def BackgroundSizing(self, value: BackgroundSizing) -> BackgroundSizing: ...
    @property
    def BorderBrush(self) -> IBrush: ...
    @BorderBrush.setter
    def BorderBrush(self, value: IBrush) -> IBrush: ...
    @property
    def BorderThickness(self) -> Thickness: ...
    @BorderThickness.setter
    def BorderThickness(self, value: Thickness) -> Thickness: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def Content(self) -> typing.Any: ...
    @Content.setter
    def Content(self, value: typing.Any) -> typing.Any: ...
    @property
    def ContentTemplate(self) -> IDataTemplate: ...
    @ContentTemplate.setter
    def ContentTemplate(self, value: IDataTemplate) -> IDataTemplate: ...
    @property
    def ContextFlyout(self) -> FlyoutBase: ...
    @ContextFlyout.setter
    def ContextFlyout(self, value: FlyoutBase) -> FlyoutBase: ...
    @property
    def ContextMenu(self) -> ContextMenu: ...
    @ContextMenu.setter
    def ContextMenu(self, value: ContextMenu) -> ContextMenu: ...
    @property
    def CornerRadius(self) -> CornerRadius: ...
    @CornerRadius.setter
    def CornerRadius(self, value: CornerRadius) -> CornerRadius: ...
    @property
    def Cursor(self) -> Cursor: ...
    @Cursor.setter
    def Cursor(self, value: Cursor) -> Cursor: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def DesiredSize(self) -> Size: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def Focusable(self) -> bool: ...
    @Focusable.setter
    def Focusable(self, value: bool) -> bool: ...
    @property
    def FocusAdorner(self) -> ITemplate_1[Control]: ...
    @FocusAdorner.setter
    def FocusAdorner(self, value: ITemplate_1[Control]) -> ITemplate_1[Control]: ...
    @property
    def FontFamily(self) -> FontFamily: ...
    @FontFamily.setter
    def FontFamily(self, value: FontFamily) -> FontFamily: ...
    @property
    def FontFeatures(self) -> FontFeatureCollection: ...
    @FontFeatures.setter
    def FontFeatures(self, value: FontFeatureCollection) -> FontFeatureCollection: ...
    @property
    def FontSize(self) -> float: ...
    @FontSize.setter
    def FontSize(self, value: float) -> float: ...
    @property
    def FontStretch(self) -> FontStretch: ...
    @FontStretch.setter
    def FontStretch(self, value: FontStretch) -> FontStretch: ...
    @property
    def FontStyle(self) -> FontStyle: ...
    @FontStyle.setter
    def FontStyle(self, value: FontStyle) -> FontStyle: ...
    @property
    def FontWeight(self) -> FontWeight: ...
    @FontWeight.setter
    def FontWeight(self, value: FontWeight) -> FontWeight: ...
    @property
    def Foreground(self) -> IBrush: ...
    @Foreground.setter
    def Foreground(self, value: IBrush) -> IBrush: ...
    @property
    def GestureRecognizers(self) -> GestureRecognizerCollection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def HorizontalContentAlignment(self) -> HorizontalAlignment: ...
    @HorizontalContentAlignment.setter
    def HorizontalContentAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @property
    def IsEffectivelyEnabled(self) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsFocused(self) -> bool: ...
    @property
    def IsHitTestVisible(self) -> bool: ...
    @IsHitTestVisible.setter
    def IsHitTestVisible(self, value: bool) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsKeyboardFocusWithin(self) -> bool: ...
    @IsKeyboardFocusWithin.setter
    def IsKeyboardFocusWithin(self, value: bool) -> bool: ...
    @property
    def IsLoaded(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @property
    def IsPointerOver(self) -> bool: ...
    @IsPointerOver.setter
    def IsPointerOver(self, value: bool) -> bool: ...
    @property
    def IsTabStop(self) -> bool: ...
    @IsTabStop.setter
    def IsTabStop(self, value: bool) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def KeyBindings(self) -> List_1[KeyBinding]: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Padding(self) -> Thickness: ...
    @Padding.setter
    def Padding(self, value: Thickness) -> Thickness: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def Presenter(self) -> ContentPresenter: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def TabIndex(self) -> int: ...
    @TabIndex.setter
    def TabIndex(self, value: int) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Template(self) -> IControlTemplate: ...
    @Template.setter
    def Template(self, value: IControlTemplate) -> IControlTemplate: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def VerticalContentAlignment(self) -> VerticalAlignment: ...
    @VerticalContentAlignment.setter
    def VerticalContentAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    def InitializeComponent(self, loadXaml: bool = ...) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class MultiTaskProgressDialog(Window):
    def __init__(self) -> None: ...
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def ActualTransparencyLevel(self) -> WindowTransparencyLevel: ...
    @property
    def Background(self) -> IBrush: ...
    @Background.setter
    def Background(self, value: IBrush) -> IBrush: ...
    @property
    def BackgroundSizing(self) -> BackgroundSizing: ...
    @BackgroundSizing.setter
    def BackgroundSizing(self, value: BackgroundSizing) -> BackgroundSizing: ...
    @property
    def BorderBrush(self) -> IBrush: ...
    @BorderBrush.setter
    def BorderBrush(self, value: IBrush) -> IBrush: ...
    @property
    def BorderThickness(self) -> Thickness: ...
    @BorderThickness.setter
    def BorderThickness(self, value: Thickness) -> Thickness: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def CanResize(self) -> bool: ...
    @CanResize.setter
    def CanResize(self, value: bool) -> bool: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def ClientSize(self) -> Size: ...
    @ClientSize.setter
    def ClientSize(self, value: Size) -> Size: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def Clipboard(self) -> IClipboard: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def ClosingBehavior(self) -> WindowClosingBehavior: ...
    @ClosingBehavior.setter
    def ClosingBehavior(self, value: WindowClosingBehavior) -> WindowClosingBehavior: ...
    @property
    def Content(self) -> typing.Any: ...
    @Content.setter
    def Content(self, value: typing.Any) -> typing.Any: ...
    @property
    def ContentTemplate(self) -> IDataTemplate: ...
    @ContentTemplate.setter
    def ContentTemplate(self, value: IDataTemplate) -> IDataTemplate: ...
    @property
    def ContextFlyout(self) -> FlyoutBase: ...
    @ContextFlyout.setter
    def ContextFlyout(self, value: FlyoutBase) -> FlyoutBase: ...
    @property
    def ContextMenu(self) -> ContextMenu: ...
    @ContextMenu.setter
    def ContextMenu(self, value: ContextMenu) -> ContextMenu: ...
    @property
    def CornerRadius(self) -> CornerRadius: ...
    @CornerRadius.setter
    def CornerRadius(self, value: CornerRadius) -> CornerRadius: ...
    @property
    def Cursor(self) -> Cursor: ...
    @Cursor.setter
    def Cursor(self, value: Cursor) -> Cursor: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def DesiredSize(self) -> Size: ...
    @property
    def DesktopScaling(self) -> float: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def ExtendClientAreaChromeHints(self) -> ExtendClientAreaChromeHints: ...
    @ExtendClientAreaChromeHints.setter
    def ExtendClientAreaChromeHints(self, value: ExtendClientAreaChromeHints) -> ExtendClientAreaChromeHints: ...
    @property
    def ExtendClientAreaTitleBarHeightHint(self) -> float: ...
    @ExtendClientAreaTitleBarHeightHint.setter
    def ExtendClientAreaTitleBarHeightHint(self, value: float) -> float: ...
    @property
    def ExtendClientAreaToDecorationsHint(self) -> bool: ...
    @ExtendClientAreaToDecorationsHint.setter
    def ExtendClientAreaToDecorationsHint(self, value: bool) -> bool: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def Focusable(self) -> bool: ...
    @Focusable.setter
    def Focusable(self, value: bool) -> bool: ...
    @property
    def FocusAdorner(self) -> ITemplate_1[Control]: ...
    @FocusAdorner.setter
    def FocusAdorner(self, value: ITemplate_1[Control]) -> ITemplate_1[Control]: ...
    @property
    def FocusManager(self) -> IFocusManager: ...
    @property
    def FontFamily(self) -> FontFamily: ...
    @FontFamily.setter
    def FontFamily(self, value: FontFamily) -> FontFamily: ...
    @property
    def FontFeatures(self) -> FontFeatureCollection: ...
    @FontFeatures.setter
    def FontFeatures(self, value: FontFeatureCollection) -> FontFeatureCollection: ...
    @property
    def FontSize(self) -> float: ...
    @FontSize.setter
    def FontSize(self, value: float) -> float: ...
    @property
    def FontStretch(self) -> FontStretch: ...
    @FontStretch.setter
    def FontStretch(self, value: FontStretch) -> FontStretch: ...
    @property
    def FontStyle(self) -> FontStyle: ...
    @FontStyle.setter
    def FontStyle(self, value: FontStyle) -> FontStyle: ...
    @property
    def FontWeight(self) -> FontWeight: ...
    @FontWeight.setter
    def FontWeight(self, value: FontWeight) -> FontWeight: ...
    @property
    def Foreground(self) -> IBrush: ...
    @Foreground.setter
    def Foreground(self, value: IBrush) -> IBrush: ...
    @property
    def FrameSize(self) -> typing.Optional[Size]: ...
    @FrameSize.setter
    def FrameSize(self, value: typing.Optional[Size]) -> typing.Optional[Size]: ...
    @property
    def GestureRecognizers(self) -> GestureRecognizerCollection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def HorizontalContentAlignment(self) -> HorizontalAlignment: ...
    @HorizontalContentAlignment.setter
    def HorizontalContentAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def Icon(self) -> WindowIcon: ...
    @Icon.setter
    def Icon(self, value: WindowIcon) -> WindowIcon: ...
    @property
    def InputPane(self) -> IInputPane: ...
    @property
    def InsetsManager(self) -> IInsetsManager: ...
    @property
    def IsActive(self) -> bool: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @property
    def IsEffectivelyEnabled(self) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsExtendedIntoWindowDecorations(self) -> bool: ...
    @property
    def IsFocused(self) -> bool: ...
    @property
    def IsHitTestVisible(self) -> bool: ...
    @IsHitTestVisible.setter
    def IsHitTestVisible(self, value: bool) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsKeyboardFocusWithin(self) -> bool: ...
    @IsKeyboardFocusWithin.setter
    def IsKeyboardFocusWithin(self, value: bool) -> bool: ...
    @property
    def IsLoaded(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @property
    def IsPointerOver(self) -> bool: ...
    @IsPointerOver.setter
    def IsPointerOver(self, value: bool) -> bool: ...
    @property
    def IsTabStop(self) -> bool: ...
    @IsTabStop.setter
    def IsTabStop(self, value: bool) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def KeyBindings(self) -> List_1[KeyBinding]: ...
    @property
    def Launcher(self) -> ILauncher: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def OffScreenMargin(self) -> Thickness: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def OwnedWindows(self) -> IReadOnlyList_1[Window]: ...
    @property
    def Owner(self) -> WindowBase: ...
    @Owner.setter
    def Owner(self, value: WindowBase) -> WindowBase: ...
    @property
    def Padding(self) -> Thickness: ...
    @Padding.setter
    def Padding(self, value: Thickness) -> Thickness: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def PlatformImpl(self) -> IWindowImpl: ...
    @property
    def PlatformImpl(self) -> IWindowBaseImpl: ...
    @property
    def PlatformImpl(self) -> ITopLevelImpl: ...
    @property
    def PlatformSettings(self) -> IPlatformSettings: ...
    @property
    def Position(self) -> PixelPoint: ...
    @Position.setter
    def Position(self, value: PixelPoint) -> PixelPoint: ...
    @property
    def Presenter(self) -> ContentPresenter: ...
    @property
    def RendererDiagnostics(self) -> RendererDiagnostics: ...
    @property
    def RenderScaling(self) -> float: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def RequestedThemeVariant(self) -> ThemeVariant: ...
    @RequestedThemeVariant.setter
    def RequestedThemeVariant(self, value: ThemeVariant) -> ThemeVariant: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def Screens(self) -> Screens: ...
    @property
    def ShowActivated(self) -> bool: ...
    @ShowActivated.setter
    def ShowActivated(self, value: bool) -> bool: ...
    @property
    def ShowInTaskbar(self) -> bool: ...
    @ShowInTaskbar.setter
    def ShowInTaskbar(self, value: bool) -> bool: ...
    @property
    def SizeToContent(self) -> SizeToContent: ...
    @SizeToContent.setter
    def SizeToContent(self, value: SizeToContent) -> SizeToContent: ...
    @property
    def StorageProvider(self) -> IStorageProvider: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def SystemDecorations(self) -> SystemDecorations: ...
    @SystemDecorations.setter
    def SystemDecorations(self, value: SystemDecorations) -> SystemDecorations: ...
    @property
    def TabIndex(self) -> int: ...
    @TabIndex.setter
    def TabIndex(self, value: int) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Template(self) -> IControlTemplate: ...
    @Template.setter
    def Template(self, value: IControlTemplate) -> IControlTemplate: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...
    @property
    def Topmost(self) -> bool: ...
    @Topmost.setter
    def Topmost(self, value: bool) -> bool: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def TransparencyBackgroundFallback(self) -> IBrush: ...
    @TransparencyBackgroundFallback.setter
    def TransparencyBackgroundFallback(self, value: IBrush) -> IBrush: ...
    @property
    def TransparencyLevelHint(self) -> IReadOnlyList_1[WindowTransparencyLevel]: ...
    @TransparencyLevelHint.setter
    def TransparencyLevelHint(self, value: IReadOnlyList_1[WindowTransparencyLevel]) -> IReadOnlyList_1[WindowTransparencyLevel]: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def VerticalContentAlignment(self) -> VerticalAlignment: ...
    @VerticalContentAlignment.setter
    def VerticalContentAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def WindowDecorationMargin(self) -> Thickness: ...
    @property
    def WindowStartupLocation(self) -> WindowStartupLocation: ...
    @WindowStartupLocation.setter
    def WindowStartupLocation(self, value: WindowStartupLocation) -> WindowStartupLocation: ...
    @property
    def WindowState(self) -> WindowState: ...
    @WindowState.setter
    def WindowState(self, value: WindowState) -> WindowState: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    @staticmethod
    def CreateScopePanel(viewModel: TaskProgressScopeViewModel, depth: int) -> TaskProgressScopePanel: ...
    @staticmethod
    def Hold() -> None: ...
    def InitializeComponent(self, loadXaml: bool = ...) -> None: ...
    @staticmethod
    def Release() -> None: ...
    @staticmethod
    def RemoveScopePanel(scopePanel: TaskProgressScopePanel) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class SpinnerProgressPanel(UserControl):
    def __init__(self) -> None: ...
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def Background(self) -> IBrush: ...
    @Background.setter
    def Background(self, value: IBrush) -> IBrush: ...
    @property
    def BackgroundSizing(self) -> BackgroundSizing: ...
    @BackgroundSizing.setter
    def BackgroundSizing(self, value: BackgroundSizing) -> BackgroundSizing: ...
    @property
    def BorderBrush(self) -> IBrush: ...
    @BorderBrush.setter
    def BorderBrush(self, value: IBrush) -> IBrush: ...
    @property
    def BorderThickness(self) -> Thickness: ...
    @BorderThickness.setter
    def BorderThickness(self, value: Thickness) -> Thickness: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def Content(self) -> typing.Any: ...
    @Content.setter
    def Content(self, value: typing.Any) -> typing.Any: ...
    @property
    def ContentTemplate(self) -> IDataTemplate: ...
    @ContentTemplate.setter
    def ContentTemplate(self, value: IDataTemplate) -> IDataTemplate: ...
    @property
    def ContextFlyout(self) -> FlyoutBase: ...
    @ContextFlyout.setter
    def ContextFlyout(self, value: FlyoutBase) -> FlyoutBase: ...
    @property
    def ContextMenu(self) -> ContextMenu: ...
    @ContextMenu.setter
    def ContextMenu(self, value: ContextMenu) -> ContextMenu: ...
    @property
    def CornerRadius(self) -> CornerRadius: ...
    @CornerRadius.setter
    def CornerRadius(self, value: CornerRadius) -> CornerRadius: ...
    @property
    def Cursor(self) -> Cursor: ...
    @Cursor.setter
    def Cursor(self, value: Cursor) -> Cursor: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def DesiredSize(self) -> Size: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def Focusable(self) -> bool: ...
    @Focusable.setter
    def Focusable(self, value: bool) -> bool: ...
    @property
    def FocusAdorner(self) -> ITemplate_1[Control]: ...
    @FocusAdorner.setter
    def FocusAdorner(self, value: ITemplate_1[Control]) -> ITemplate_1[Control]: ...
    @property
    def FontFamily(self) -> FontFamily: ...
    @FontFamily.setter
    def FontFamily(self, value: FontFamily) -> FontFamily: ...
    @property
    def FontFeatures(self) -> FontFeatureCollection: ...
    @FontFeatures.setter
    def FontFeatures(self, value: FontFeatureCollection) -> FontFeatureCollection: ...
    @property
    def FontSize(self) -> float: ...
    @FontSize.setter
    def FontSize(self, value: float) -> float: ...
    @property
    def FontStretch(self) -> FontStretch: ...
    @FontStretch.setter
    def FontStretch(self, value: FontStretch) -> FontStretch: ...
    @property
    def FontStyle(self) -> FontStyle: ...
    @FontStyle.setter
    def FontStyle(self, value: FontStyle) -> FontStyle: ...
    @property
    def FontWeight(self) -> FontWeight: ...
    @FontWeight.setter
    def FontWeight(self, value: FontWeight) -> FontWeight: ...
    @property
    def Foreground(self) -> IBrush: ...
    @Foreground.setter
    def Foreground(self, value: IBrush) -> IBrush: ...
    @property
    def GestureRecognizers(self) -> GestureRecognizerCollection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def HorizontalContentAlignment(self) -> HorizontalAlignment: ...
    @HorizontalContentAlignment.setter
    def HorizontalContentAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @property
    def IsEffectivelyEnabled(self) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsFocused(self) -> bool: ...
    @property
    def IsHitTestVisible(self) -> bool: ...
    @IsHitTestVisible.setter
    def IsHitTestVisible(self, value: bool) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsKeyboardFocusWithin(self) -> bool: ...
    @IsKeyboardFocusWithin.setter
    def IsKeyboardFocusWithin(self, value: bool) -> bool: ...
    @property
    def IsLoaded(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @property
    def IsPointerOver(self) -> bool: ...
    @IsPointerOver.setter
    def IsPointerOver(self, value: bool) -> bool: ...
    @property
    def IsTabStop(self) -> bool: ...
    @IsTabStop.setter
    def IsTabStop(self, value: bool) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def KeyBindings(self) -> List_1[KeyBinding]: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Padding(self) -> Thickness: ...
    @Padding.setter
    def Padding(self, value: Thickness) -> Thickness: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def Presenter(self) -> ContentPresenter: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def TabIndex(self) -> int: ...
    @TabIndex.setter
    def TabIndex(self, value: int) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Template(self) -> IControlTemplate: ...
    @Template.setter
    def Template(self, value: IControlTemplate) -> IControlTemplate: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def VerticalContentAlignment(self) -> VerticalAlignment: ...
    @VerticalContentAlignment.setter
    def VerticalContentAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    def InitializeComponent(self, loadXaml: bool = ...) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class TaskProgressDialog(Window):
    def __init__(self) -> None: ...
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def ActualTransparencyLevel(self) -> WindowTransparencyLevel: ...
    @property
    def Background(self) -> IBrush: ...
    @Background.setter
    def Background(self, value: IBrush) -> IBrush: ...
    @property
    def BackgroundSizing(self) -> BackgroundSizing: ...
    @BackgroundSizing.setter
    def BackgroundSizing(self, value: BackgroundSizing) -> BackgroundSizing: ...
    @property
    def BorderBrush(self) -> IBrush: ...
    @BorderBrush.setter
    def BorderBrush(self, value: IBrush) -> IBrush: ...
    @property
    def BorderThickness(self) -> Thickness: ...
    @BorderThickness.setter
    def BorderThickness(self, value: Thickness) -> Thickness: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def CanResize(self) -> bool: ...
    @CanResize.setter
    def CanResize(self, value: bool) -> bool: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def ClientSize(self) -> Size: ...
    @ClientSize.setter
    def ClientSize(self, value: Size) -> Size: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def Clipboard(self) -> IClipboard: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def ClosingBehavior(self) -> WindowClosingBehavior: ...
    @ClosingBehavior.setter
    def ClosingBehavior(self, value: WindowClosingBehavior) -> WindowClosingBehavior: ...
    @property
    def Content(self) -> typing.Any: ...
    @Content.setter
    def Content(self, value: typing.Any) -> typing.Any: ...
    @property
    def ContentTemplate(self) -> IDataTemplate: ...
    @ContentTemplate.setter
    def ContentTemplate(self, value: IDataTemplate) -> IDataTemplate: ...
    @property
    def ContextFlyout(self) -> FlyoutBase: ...
    @ContextFlyout.setter
    def ContextFlyout(self, value: FlyoutBase) -> FlyoutBase: ...
    @property
    def ContextMenu(self) -> ContextMenu: ...
    @ContextMenu.setter
    def ContextMenu(self, value: ContextMenu) -> ContextMenu: ...
    @property
    def CornerRadius(self) -> CornerRadius: ...
    @CornerRadius.setter
    def CornerRadius(self, value: CornerRadius) -> CornerRadius: ...
    @property
    def Cursor(self) -> Cursor: ...
    @Cursor.setter
    def Cursor(self, value: Cursor) -> Cursor: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def DesiredSize(self) -> Size: ...
    @property
    def DesktopScaling(self) -> float: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def ExtendClientAreaChromeHints(self) -> ExtendClientAreaChromeHints: ...
    @ExtendClientAreaChromeHints.setter
    def ExtendClientAreaChromeHints(self, value: ExtendClientAreaChromeHints) -> ExtendClientAreaChromeHints: ...
    @property
    def ExtendClientAreaTitleBarHeightHint(self) -> float: ...
    @ExtendClientAreaTitleBarHeightHint.setter
    def ExtendClientAreaTitleBarHeightHint(self, value: float) -> float: ...
    @property
    def ExtendClientAreaToDecorationsHint(self) -> bool: ...
    @ExtendClientAreaToDecorationsHint.setter
    def ExtendClientAreaToDecorationsHint(self, value: bool) -> bool: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def Focusable(self) -> bool: ...
    @Focusable.setter
    def Focusable(self, value: bool) -> bool: ...
    @property
    def FocusAdorner(self) -> ITemplate_1[Control]: ...
    @FocusAdorner.setter
    def FocusAdorner(self, value: ITemplate_1[Control]) -> ITemplate_1[Control]: ...
    @property
    def FocusManager(self) -> IFocusManager: ...
    @property
    def FontFamily(self) -> FontFamily: ...
    @FontFamily.setter
    def FontFamily(self, value: FontFamily) -> FontFamily: ...
    @property
    def FontFeatures(self) -> FontFeatureCollection: ...
    @FontFeatures.setter
    def FontFeatures(self, value: FontFeatureCollection) -> FontFeatureCollection: ...
    @property
    def FontSize(self) -> float: ...
    @FontSize.setter
    def FontSize(self, value: float) -> float: ...
    @property
    def FontStretch(self) -> FontStretch: ...
    @FontStretch.setter
    def FontStretch(self, value: FontStretch) -> FontStretch: ...
    @property
    def FontStyle(self) -> FontStyle: ...
    @FontStyle.setter
    def FontStyle(self, value: FontStyle) -> FontStyle: ...
    @property
    def FontWeight(self) -> FontWeight: ...
    @FontWeight.setter
    def FontWeight(self, value: FontWeight) -> FontWeight: ...
    @property
    def Foreground(self) -> IBrush: ...
    @Foreground.setter
    def Foreground(self, value: IBrush) -> IBrush: ...
    @property
    def FrameSize(self) -> typing.Optional[Size]: ...
    @FrameSize.setter
    def FrameSize(self, value: typing.Optional[Size]) -> typing.Optional[Size]: ...
    @property
    def GestureRecognizers(self) -> GestureRecognizerCollection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def HorizontalContentAlignment(self) -> HorizontalAlignment: ...
    @HorizontalContentAlignment.setter
    def HorizontalContentAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def Icon(self) -> WindowIcon: ...
    @Icon.setter
    def Icon(self, value: WindowIcon) -> WindowIcon: ...
    @property
    def InputPane(self) -> IInputPane: ...
    @property
    def InsetsManager(self) -> IInsetsManager: ...
    @property
    def IsActive(self) -> bool: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @property
    def IsEffectivelyEnabled(self) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsExtendedIntoWindowDecorations(self) -> bool: ...
    @property
    def IsFocused(self) -> bool: ...
    @property
    def IsHitTestVisible(self) -> bool: ...
    @IsHitTestVisible.setter
    def IsHitTestVisible(self, value: bool) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsKeyboardFocusWithin(self) -> bool: ...
    @IsKeyboardFocusWithin.setter
    def IsKeyboardFocusWithin(self, value: bool) -> bool: ...
    @property
    def IsLoaded(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @property
    def IsPointerOver(self) -> bool: ...
    @IsPointerOver.setter
    def IsPointerOver(self, value: bool) -> bool: ...
    @property
    def IsTabStop(self) -> bool: ...
    @IsTabStop.setter
    def IsTabStop(self, value: bool) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def KeyBindings(self) -> List_1[KeyBinding]: ...
    @property
    def Launcher(self) -> ILauncher: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def OffScreenMargin(self) -> Thickness: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def OwnedWindows(self) -> IReadOnlyList_1[Window]: ...
    @property
    def Owner(self) -> WindowBase: ...
    @Owner.setter
    def Owner(self, value: WindowBase) -> WindowBase: ...
    @property
    def Padding(self) -> Thickness: ...
    @Padding.setter
    def Padding(self, value: Thickness) -> Thickness: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def PlatformImpl(self) -> IWindowImpl: ...
    @property
    def PlatformImpl(self) -> IWindowBaseImpl: ...
    @property
    def PlatformImpl(self) -> ITopLevelImpl: ...
    @property
    def PlatformSettings(self) -> IPlatformSettings: ...
    @property
    def Position(self) -> PixelPoint: ...
    @Position.setter
    def Position(self, value: PixelPoint) -> PixelPoint: ...
    @property
    def Presenter(self) -> ContentPresenter: ...
    @property
    def RendererDiagnostics(self) -> RendererDiagnostics: ...
    @property
    def RenderScaling(self) -> float: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def RequestedThemeVariant(self) -> ThemeVariant: ...
    @RequestedThemeVariant.setter
    def RequestedThemeVariant(self, value: ThemeVariant) -> ThemeVariant: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def Screens(self) -> Screens: ...
    @property
    def ShowActivated(self) -> bool: ...
    @ShowActivated.setter
    def ShowActivated(self, value: bool) -> bool: ...
    @property
    def ShowInTaskbar(self) -> bool: ...
    @ShowInTaskbar.setter
    def ShowInTaskbar(self, value: bool) -> bool: ...
    @property
    def SizeToContent(self) -> SizeToContent: ...
    @SizeToContent.setter
    def SizeToContent(self, value: SizeToContent) -> SizeToContent: ...
    @property
    def StorageProvider(self) -> IStorageProvider: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def SystemDecorations(self) -> SystemDecorations: ...
    @SystemDecorations.setter
    def SystemDecorations(self, value: SystemDecorations) -> SystemDecorations: ...
    @property
    def TabIndex(self) -> int: ...
    @TabIndex.setter
    def TabIndex(self, value: int) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Template(self) -> IControlTemplate: ...
    @Template.setter
    def Template(self, value: IControlTemplate) -> IControlTemplate: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...
    @property
    def Topmost(self) -> bool: ...
    @Topmost.setter
    def Topmost(self, value: bool) -> bool: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def TransparencyBackgroundFallback(self) -> IBrush: ...
    @TransparencyBackgroundFallback.setter
    def TransparencyBackgroundFallback(self, value: IBrush) -> IBrush: ...
    @property
    def TransparencyLevelHint(self) -> IReadOnlyList_1[WindowTransparencyLevel]: ...
    @TransparencyLevelHint.setter
    def TransparencyLevelHint(self, value: IReadOnlyList_1[WindowTransparencyLevel]) -> IReadOnlyList_1[WindowTransparencyLevel]: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def VerticalContentAlignment(self) -> VerticalAlignment: ...
    @VerticalContentAlignment.setter
    def VerticalContentAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def WasCanceled(self) -> bool: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def WindowDecorationMargin(self) -> Thickness: ...
    @property
    def WindowStartupLocation(self) -> WindowStartupLocation: ...
    @WindowStartupLocation.setter
    def WindowStartupLocation(self, value: WindowStartupLocation) -> WindowStartupLocation: ...
    @property
    def WindowState(self) -> WindowState: ...
    @WindowState.setter
    def WindowState(self, value: WindowState) -> WindowState: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    def InitializeComponent(self, loadXaml: bool = ...) -> None: ...
    def SetIndeterminate(self, indeterminate: bool) -> None: ...
    def SetMessage(self, message: str) -> None: ...
    def SetProgress(self, current: int, total: int) -> None: ...
    def SetTitle(self, title: str) -> None: ...
    def ShowCancelButton(self, show: bool) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class TaskProgressScopePanel(UserControl):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, depth: int) -> None: ...
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def Background(self) -> IBrush: ...
    @Background.setter
    def Background(self, value: IBrush) -> IBrush: ...
    @property
    def BackgroundSizing(self) -> BackgroundSizing: ...
    @BackgroundSizing.setter
    def BackgroundSizing(self, value: BackgroundSizing) -> BackgroundSizing: ...
    @property
    def BorderBrush(self) -> IBrush: ...
    @BorderBrush.setter
    def BorderBrush(self, value: IBrush) -> IBrush: ...
    @property
    def BorderThickness(self) -> Thickness: ...
    @BorderThickness.setter
    def BorderThickness(self, value: Thickness) -> Thickness: ...
    @property
    def Bounds(self) -> Rect: ...
    @Bounds.setter
    def Bounds(self, value: Rect) -> Rect: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def Clip(self) -> Geometry: ...
    @Clip.setter
    def Clip(self, value: Geometry) -> Geometry: ...
    @property
    def ClipToBounds(self) -> bool: ...
    @ClipToBounds.setter
    def ClipToBounds(self, value: bool) -> bool: ...
    @property
    def Content(self) -> typing.Any: ...
    @Content.setter
    def Content(self, value: typing.Any) -> typing.Any: ...
    @property
    def ContentTemplate(self) -> IDataTemplate: ...
    @ContentTemplate.setter
    def ContentTemplate(self, value: IDataTemplate) -> IDataTemplate: ...
    @property
    def ContextFlyout(self) -> FlyoutBase: ...
    @ContextFlyout.setter
    def ContextFlyout(self, value: FlyoutBase) -> FlyoutBase: ...
    @property
    def ContextMenu(self) -> ContextMenu: ...
    @ContextMenu.setter
    def ContextMenu(self, value: ContextMenu) -> ContextMenu: ...
    @property
    def CornerRadius(self) -> CornerRadius: ...
    @CornerRadius.setter
    def CornerRadius(self, value: CornerRadius) -> CornerRadius: ...
    @property
    def Cursor(self) -> Cursor: ...
    @Cursor.setter
    def Cursor(self, value: Cursor) -> Cursor: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def DataTemplates(self) -> DataTemplates: ...
    @property
    def DesiredSize(self) -> Size: ...
    @property
    def Effect(self) -> IEffect: ...
    @Effect.setter
    def Effect(self, value: IEffect) -> IEffect: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @FlowDirection.setter
    def FlowDirection(self, value: FlowDirection) -> FlowDirection: ...
    @property
    def Focusable(self) -> bool: ...
    @Focusable.setter
    def Focusable(self, value: bool) -> bool: ...
    @property
    def FocusAdorner(self) -> ITemplate_1[Control]: ...
    @FocusAdorner.setter
    def FocusAdorner(self, value: ITemplate_1[Control]) -> ITemplate_1[Control]: ...
    @property
    def FontFamily(self) -> FontFamily: ...
    @FontFamily.setter
    def FontFamily(self, value: FontFamily) -> FontFamily: ...
    @property
    def FontFeatures(self) -> FontFeatureCollection: ...
    @FontFeatures.setter
    def FontFeatures(self, value: FontFeatureCollection) -> FontFeatureCollection: ...
    @property
    def FontSize(self) -> float: ...
    @FontSize.setter
    def FontSize(self, value: float) -> float: ...
    @property
    def FontStretch(self) -> FontStretch: ...
    @FontStretch.setter
    def FontStretch(self, value: FontStretch) -> FontStretch: ...
    @property
    def FontStyle(self) -> FontStyle: ...
    @FontStyle.setter
    def FontStyle(self, value: FontStyle) -> FontStyle: ...
    @property
    def FontWeight(self) -> FontWeight: ...
    @FontWeight.setter
    def FontWeight(self, value: FontWeight) -> FontWeight: ...
    @property
    def Foreground(self) -> IBrush: ...
    @Foreground.setter
    def Foreground(self, value: IBrush) -> IBrush: ...
    @property
    def GestureRecognizers(self) -> GestureRecognizerCollection: ...
    @property
    def HasMirrorTransform(self) -> bool: ...
    @HasMirrorTransform.setter
    def HasMirrorTransform(self, value: bool) -> bool: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> float: ...
    @property
    def HorizontalAlignment(self) -> HorizontalAlignment: ...
    @HorizontalAlignment.setter
    def HorizontalAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def HorizontalContentAlignment(self) -> HorizontalAlignment: ...
    @HorizontalContentAlignment.setter
    def HorizontalContentAlignment(self, value: HorizontalAlignment) -> HorizontalAlignment: ...
    @property
    def IsArrangeValid(self) -> bool: ...
    @property
    def IsEffectivelyEnabled(self) -> bool: ...
    @property
    def IsEffectivelyVisible(self) -> bool: ...
    @property
    def IsEnabled(self) -> bool: ...
    @IsEnabled.setter
    def IsEnabled(self, value: bool) -> bool: ...
    @property
    def IsFocused(self) -> bool: ...
    @property
    def IsHitTestVisible(self) -> bool: ...
    @IsHitTestVisible.setter
    def IsHitTestVisible(self, value: bool) -> bool: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def IsKeyboardFocusWithin(self) -> bool: ...
    @IsKeyboardFocusWithin.setter
    def IsKeyboardFocusWithin(self, value: bool) -> bool: ...
    @property
    def IsLoaded(self) -> bool: ...
    @property
    def IsMeasureValid(self) -> bool: ...
    @property
    def IsPointerOver(self) -> bool: ...
    @IsPointerOver.setter
    def IsPointerOver(self, value: bool) -> bool: ...
    @property
    def IsTabStop(self) -> bool: ...
    @IsTabStop.setter
    def IsTabStop(self, value: bool) -> bool: ...
    @property
    def IsVisible(self) -> bool: ...
    @IsVisible.setter
    def IsVisible(self, value: bool) -> bool: ...
    @property
    def KeyBindings(self) -> List_1[KeyBinding]: ...
    @property
    def Margin(self) -> Thickness: ...
    @Margin.setter
    def Margin(self, value: Thickness) -> Thickness: ...
    @property
    def MaxHeight(self) -> float: ...
    @MaxHeight.setter
    def MaxHeight(self, value: float) -> float: ...
    @property
    def MaxWidth(self) -> float: ...
    @MaxWidth.setter
    def MaxWidth(self, value: float) -> float: ...
    @property
    def MinHeight(self) -> float: ...
    @MinHeight.setter
    def MinHeight(self, value: float) -> float: ...
    @property
    def MinWidth(self) -> float: ...
    @MinWidth.setter
    def MinWidth(self, value: float) -> float: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> float: ...
    @property
    def OpacityMask(self) -> IBrush: ...
    @OpacityMask.setter
    def OpacityMask(self, value: IBrush) -> IBrush: ...
    @property
    def Padding(self) -> Thickness: ...
    @Padding.setter
    def Padding(self, value: Thickness) -> Thickness: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def Presenter(self) -> ContentPresenter: ...
    @property
    def RenderTransform(self) -> ITransform: ...
    @RenderTransform.setter
    def RenderTransform(self, value: ITransform) -> ITransform: ...
    @property
    def RenderTransformOrigin(self) -> RelativePoint: ...
    @RenderTransformOrigin.setter
    def RenderTransformOrigin(self, value: RelativePoint) -> RelativePoint: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def TabIndex(self) -> int: ...
    @TabIndex.setter
    def TabIndex(self, value: int) -> int: ...
    @property
    def Tag(self) -> typing.Any: ...
    @Tag.setter
    def Tag(self, value: typing.Any) -> typing.Any: ...
    @property
    def Template(self) -> IControlTemplate: ...
    @Template.setter
    def Template(self, value: IControlTemplate) -> IControlTemplate: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    @property
    def UseLayoutRounding(self) -> bool: ...
    @UseLayoutRounding.setter
    def UseLayoutRounding(self, value: bool) -> bool: ...
    @property
    def VerticalAlignment(self) -> VerticalAlignment: ...
    @VerticalAlignment.setter
    def VerticalAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def VerticalContentAlignment(self) -> VerticalAlignment: ...
    @VerticalContentAlignment.setter
    def VerticalContentAlignment(self, value: VerticalAlignment) -> VerticalAlignment: ...
    @property
    def Width(self) -> float: ...
    @Width.setter
    def Width(self, value: float) -> float: ...
    @property
    def ZIndex(self) -> int: ...
    @ZIndex.setter
    def ZIndex(self, value: int) -> int: ...
    def InitializeComponent(self, loadXaml: bool = ...) -> None: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...

