import typing, abc
from System.Collections.Generic import IEnumerable_1
from Avalonia import Visual, Point, Rect, Size, PixelPoint
from System import Func_2, IDisposable
from System.Threading.Tasks import ValueTask_1
from System.ComponentModel import INotifyPropertyChanged

class IHitTester(typing.Protocol):
    @abc.abstractmethod
    def HitTest(self, p: Point, root: Visual, filter: Func_2[Visual, bool]) -> IEnumerable_1[Visual]: ...
    @abc.abstractmethod
    def HitTestFirst(self, p: Point, root: Visual, filter: Func_2[Visual, bool]) -> Visual: ...


class IRenderer(IDisposable, typing.Protocol):
    @property
    def Diagnostics(self) -> RendererDiagnostics: ...
    @abc.abstractmethod
    def AddDirty(self, visual: Visual) -> None: ...
    @abc.abstractmethod
    def Paint(self, rect: Rect) -> None: ...
    @abc.abstractmethod
    def RecalculateChildren(self, visual: Visual) -> None: ...
    @abc.abstractmethod
    def Resized(self, size: Size) -> None: ...
    @abc.abstractmethod
    def Start(self) -> None: ...
    @abc.abstractmethod
    def Stop(self) -> None: ...
    @abc.abstractmethod
    def TryGetRenderInterfaceFeature(self, featureType: typing.Type[typing.Any]) -> ValueTask_1[typing.Any]: ...


class IRenderRoot(typing.Protocol):
    @property
    def ClientSize(self) -> Size: ...
    @property
    def HitTester(self) -> IHitTester: ...
    @property
    def Renderer(self) -> IRenderer: ...
    @property
    def RenderScaling(self) -> float: ...
    @abc.abstractmethod
    def PointToClient(self, point: PixelPoint) -> Point: ...
    @abc.abstractmethod
    def PointToScreen(self, point: Point) -> PixelPoint: ...


class RendererDebugOverlays(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : RendererDebugOverlays # 0
    Fps : RendererDebugOverlays # 1
    DirtyRects : RendererDebugOverlays # 2
    LayoutTimeGraph : RendererDebugOverlays # 4
    RenderTimeGraph : RendererDebugOverlays # 8


class RendererDiagnostics(INotifyPropertyChanged):
    def __init__(self) -> None: ...
    @property
    def DebugOverlays(self) -> RendererDebugOverlays: ...
    @DebugOverlays.setter
    def DebugOverlays(self, value: RendererDebugOverlays) -> RendererDebugOverlays: ...

