import typing
from System import IEquatable_1
from Avalonia.Media import IDashStyle, IPen, IImmutableBrush, PenLineCap, PenLineJoin, IBrush, ITransform
from System.Collections.Generic import IEnumerable_1, IReadOnlyList_1
from Avalonia import Matrix

class ImmutableDashStyle(IEquatable_1[IDashStyle], IDashStyle):
    def __init__(self, dashes: IEnumerable_1[float], offset: float) -> None: ...
    @property
    def Dashes(self) -> IReadOnlyList_1[float]: ...
    @property
    def Offset(self) -> float: ...
    def GetHashCode(self) -> int: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...
        @typing.overload
        def __call__(self, other: IDashStyle) -> bool:...



class ImmutablePen(IEquatable_1[IPen], IPen):
    @typing.overload
    def __init__(self, brush: IImmutableBrush, thickness: float = ..., dashStyle: ImmutableDashStyle = ..., lineCap: PenLineCap = ..., lineJoin: PenLineJoin = ..., miterLimit: float = ...) -> None: ...
    @typing.overload
    def __init__(self, color: int, thickness: float = ..., dashStyle: ImmutableDashStyle = ..., lineCap: PenLineCap = ..., lineJoin: PenLineJoin = ..., miterLimit: float = ...) -> None: ...
    @property
    def Brush(self) -> IBrush: ...
    @property
    def DashStyle(self) -> IDashStyle: ...
    @property
    def LineCap(self) -> PenLineCap: ...
    @property
    def LineJoin(self) -> PenLineJoin: ...
    @property
    def MiterLimit(self) -> float: ...
    @property
    def Thickness(self) -> float: ...
    def GetHashCode(self) -> int: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...
        @typing.overload
        def __call__(self, other: IPen) -> bool:...



class ImmutableTransform(ITransform):
    def __init__(self, matrix: Matrix) -> None: ...
    @property
    def Value(self) -> Matrix: ...

