"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from functools import lru_cache

logger = ...
handler = ...
formatter = ...
MODULE_FST_DATA = ...
MODULE_ENTRIES_EXTRA = ...
MODULE_ENTRIES_COMPACT = ...
MODULE_ENTRIES_BUCKETS = ...
MODULE_CONNECTIONS = ...
MODULE_CHARDEFS = ...
MODULE_UNKNOWNS = ...
FILE_USER_FST_DATA = ...
FILE_USER_ENTRIES_DATA = ...
def save_fstdata(data, dir, part=...): # -> None:
    ...

def start_save_entries(dir, bucket_idx, morph_offset): # -> None:
    ...

def end_save_entries(dir, bucket_idx): # -> None:
    ...

def save_entry(dir, bucket_idx, morph_id, entry): # -> None:
    ...

def save_entry_buckets(dir, buckets): # -> None:
    ...

def save_connections(connections, dir=...): # -> None:
    ...

def save_chardefs(chardefs, dir=...): # -> None:
    ...

def save_unknowns(unknowns, dir=...): # -> None:
    ...

class Dictionary(ABC):
    """
    Base dictionary class
    """
    @abstractmethod
    def lookup(self, s, matcher): # -> None:
        ...
    
    @abstractmethod
    def lookup_extra(self, num): # -> None:
        ...
    
    @abstractmethod
    def get_trans_cost(self, id1, id2): # -> None:
        ...
    


class RAMDictionary(Dictionary):
    """
    RAM dictionary class
    """
    def __init__(self, entries, connections) -> None:
        ...
    
    def lookup(self, s, matcher): # -> list[Any]:
        ...
    
    def lookup_extra(self, num):
        ...
    
    def get_trans_cost(self, id1, id2):
        ...
    


class MMapDictionary(Dictionary):
    """
    MMap dictionary class
    """
    def __init__(self, entries_compact, entries_extra, open_files, connections) -> None:
        ...
    
    def lookup(self, s, matcher): # -> list[Any]:
        ...
    
    @lru_cache(maxsize=1024)
    def lookup_extra(self, idx): # -> tuple[Any, Any, Any, Any, Any, Any]:
        ...
    
    def get_trans_cost(self, id1, id2):
        ...
    
    def __del__(self): # -> None:
        ...
    


class UnknownsDictionary:
    """
    Dictionary class for handling unknown words
    """
    def __init__(self, chardefs, unknowns) -> None:
        ...
    
    @lru_cache(maxsize=1024)
    def get_char_categories(self, c): # -> dict[str, list[Any]]:
        ...
    
    def unknown_invoked_always(self, cate): # -> Literal[False]:
        ...
    
    def unknown_grouping(self, cate): # -> Literal[False]:
        ...
    
    def unknown_length(self, cate): # -> Literal[-1]:
        ...
    


class UserDictionary(RAMDictionary):
    """
    User dictionary class (on-the-fly)
    """
    def __init__(self, user_dict, enc, type, connections, progress_handler=...) -> None:
        """
        Initialize user defined dictionary object.

        :param user_dict: user dictionary file (CSV format)
        :param enc: character encoding
        :param type: user dictionary type. supported types are 'ipadic' and 'simpledic'
        :param connections: connection cost matrix. expected value is SYS_DIC.connections
        :param progress_handler: handler mainly to indicate progress, implementation of ProgressHandler

        .. seealso:: http://mocobeta.github.io/janome/en/#use-with-user-defined-dictionary
        """
        ...
    
    def lookup(self, s): # -> list[Any]:
        ...
    
    @classmethod
    def line_to_entry_ipadic(cls, line): # -> tuple[Any, int, int, int, LiteralString, Any, Any, Any, Any, Any]:
        """Convert IPADIC formatted string to an user dictionary entry"""
        ...
    
    @classmethod
    def line_to_entry_simpledic(cls, line): # -> tuple[Any, Literal[0], Literal[0], Literal[-100000], LiteralString, Literal['*'], Literal['*'], Any, Any, Any]:
        """Convert simpledict formatted string to an user dictionary entry"""
        ...
    
    @classmethod
    def build_dic(cls, user_dict, enc, dict_type, progress_handler): # -> tuple[bytes, dict[Any, Any]]:
        ...
    
    def save(self, to_dir, compressionlevel=...): # -> None:
        """
        Save compressed compiled dictionary data.

        :param to_dir: directory to save dictionary data
        :compressionlevel: (Optional) gzip compression level. default is 9
        """
        ...
    


class CompiledUserDictionary(RAMDictionary):
    """
    User dictionary class (compiled)
    """
    def __init__(self, dic_dir, connections) -> None:
        ...
    
    def lookup(self, s): # -> list[Any]:
        ...
    
    @classmethod
    def load_dict(cls, dic_dir): # -> tuple[str | bytes | None, Any]:
        ...
    


class LoadingDictionaryError(Exception):
    def __init__(self) -> None:
        ...
    


