"""
This type stub file was generated by pyright.
"""

class NodeType:
    SYS_DICT = ...
    USER_DICT = ...
    UNKNOWN = ...


class Node:
    """
    Standard Node class
    """
    __slots__ = ...
    def __init__(self, dict_entry, node_type=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def node_label(self):
        ...
    


class SurfaceNode:
    """
    Node class with surface form only.
    """
    __slots__ = ...
    def __init__(self, dict_entry, node_type=...) -> None:
        ...
    
    def node_label(self):
        ...
    


class BOS:
    """
    BOS node
    """
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def node_label(self): # -> Literal['BOS']:
        ...
    


class EOS:
    """
    EOS node
    """
    __slots__ = ...
    def __init__(self, pos) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def node_label(self): # -> Literal['EOS']:
        ...
    


class Lattice:
    def __init__(self, size, dic) -> None:
        ...
    
    def add(self, node): # -> None:
        ...
    
    def forward(self): # -> int:
        ...
    
    def end(self): # -> None:
        ...
    
    def backward(self): # -> list[Any]:
        ...
    
    def generate_dotfile(self, filename=...): # -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


