"""
This type stub file was generated by pyright.
"""

from .dic import MMapDictionary, RAMDictionary, UnknownsDictionary

class SystemDictionary(RAMDictionary, UnknownsDictionary):
    """
    System dictionary class
    """
    __INSTANCE = ...
    __lock = ...
    @classmethod
    def instance(cls): # -> SystemDictionary:
        ...
    
    def __init__(self, entries, connections, chardefs, unknowns) -> None:
        ...
    


class MMapSystemDictionary(MMapDictionary, UnknownsDictionary):
    """
    MMap System dictionary class
    """
    __INSTANCE = ...
    __lock = ...
    @classmethod
    def instance(cls): # -> MMapSystemDictionary:
        ...
    
    def __init__(self, mmap_entries, connections, chardefs, unknowns) -> None:
        ...
    


