"""
This type stub file was generated by pyright.
"""

import os
import sys
from janome.dic import LoadingDictionaryError
from . import chardef, connections1, connections2, unknowns

base_dir = ...
connections = ...
__entries = ...
def entries(compact=...): # -> dict[int, tuple[str, int, int, int]]:
    ...

def mmap_entries(compact=...): # -> tuple[dict[Any, Any], dict[Any, Any] | None, list[Any]]:
    ...

def all_fstdata(): # -> list[Any]:
    ...

