from JAStudio.Core.Note.Vocabulary import VocabNote
from JAStudio.Core.Note import NoteGuard, NoteId
from System.Collections.Generic import List_1, HashSet_1
from JAStudio.Core.Note.CorpusData import VocabRelatedSubData
from JAStudio.Core.Note.NoteFields.AutoSaveWrappers import ValueWrapper_1
from JAStudio.Core.Note.NoteFields import IObjectSerializer_1

class Antonyms:
    def __init__(self, vocab: VocabNote, data: RelatedVocabData, guard: NoteGuard) -> None: ...
    def Add(self, antonym: str) -> None: ...
    def Notes(self) -> List_1[VocabNote]: ...
    def Remove(self, toRemove: str) -> None: ...
    def Strings(self) -> HashSet_1[str]: ...
    def ToString(self) -> str: ...


class ConfusedWithField:
    def __init__(self, data: RelatedVocabData, guard: NoteGuard) -> None: ...
    def Add(self, value: str) -> None: ...
    def Get(self) -> HashSet_1[str]: ...
    def Remove(self, value: str) -> None: ...
    def ToString(self) -> str: ...


class DerivedFromField:
    def __init__(self, data: RelatedVocabData, guard: NoteGuard) -> None: ...
    def Get(self) -> str: ...
    def Set(self, value: str) -> None: ...
    def ToString(self) -> str: ...


class ErgativeTwin:
    def __init__(self, vocab: VocabNote, data: RelatedVocabData, guard: NoteGuard) -> None: ...
    def Get(self) -> str: ...
    def Remove(self) -> None: ...
    def Set(self, value: str) -> None: ...


class PerfectSynonyms:
    def __init__(self, vocab: VocabNote, data: RelatedVocabData, guard: NoteGuard) -> None: ...
    def AddOverwritingTheAnswerOfTheAddedSynonym(self, addedQuestion: str) -> None: ...
    def Get(self) -> HashSet_1[str]: ...
    def Notes(self) -> List_1[VocabNote]: ...
    def PushAnswerToOtherSynonyms(self) -> None: ...
    def Remove(self, synonymToRemove: str) -> None: ...
    def ToString(self) -> str: ...


class RelatedVocab:
    def __init__(self, vocab: VocabNote, subData: VocabRelatedSubData, guard: NoteGuard) -> None: ...
    @property
    def Antonyms(self) -> Antonyms: ...
    @property
    def ConfusedWith(self) -> ConfusedWithField: ...
    @property
    def DerivedFrom(self) -> DerivedFromField: ...
    @property
    def ErgativeTwin(self) -> ErgativeTwin: ...
    @property
    def InCompoundIds(self) -> HashSet_1[NoteId]: ...
    @property
    def PerfectSynonyms(self) -> PerfectSynonyms: ...
    @property
    def RawJson(self) -> str: ...
    @RawJson.setter
    def RawJson(self, value: str) -> str: ...
    @property
    def SeeAlso(self) -> SeeAlso: ...
    @property
    def Synonyms(self) -> Synonyms: ...
    def HomophonesNotes(self) -> HashSet_1[VocabNote]: ...
    def InCompounds(self) -> List_1[VocabNote]: ...
    def StemsNotes(self) -> HashSet_1[VocabNote]: ...


class RelatedVocabData:
    def __init__(self, ergativeTwin: str, derivedFrom: ValueWrapper_1[str], perfectSynonyms: HashSet_1[str], similar: HashSet_1[str], antonyms: HashSet_1[str], confusedWith: HashSet_1[str], seeAlso: HashSet_1[str]) -> None: ...
    @property
    def Antonyms(self) -> HashSet_1[str]: ...
    @Antonyms.setter
    def Antonyms(self, value: HashSet_1[str]) -> HashSet_1[str]: ...
    @property
    def ConfusedWith(self) -> HashSet_1[str]: ...
    @ConfusedWith.setter
    def ConfusedWith(self, value: HashSet_1[str]) -> HashSet_1[str]: ...
    @property
    def DerivedFrom(self) -> ValueWrapper_1[str]: ...
    @DerivedFrom.setter
    def DerivedFrom(self, value: ValueWrapper_1[str]) -> ValueWrapper_1[str]: ...
    @property
    def ErgativeTwin(self) -> str: ...
    @ErgativeTwin.setter
    def ErgativeTwin(self, value: str) -> str: ...
    @property
    def PerfectSynonyms(self) -> HashSet_1[str]: ...
    @PerfectSynonyms.setter
    def PerfectSynonyms(self, value: HashSet_1[str]) -> HashSet_1[str]: ...
    @property
    def SeeAlso(self) -> HashSet_1[str]: ...
    @SeeAlso.setter
    def SeeAlso(self, value: HashSet_1[str]) -> HashSet_1[str]: ...
    @property
    def Synonyms(self) -> HashSet_1[str]: ...
    @Synonyms.setter
    def Synonyms(self, value: HashSet_1[str]) -> HashSet_1[str]: ...
    @staticmethod
    def Serializer() -> IObjectSerializer_1[RelatedVocabData]: ...
    def ToString(self) -> str: ...


class RelatedVocabDataSerializer(IObjectSerializer_1[RelatedVocabData]):
    def __init__(self) -> None: ...
    def Deserialize(self, serialized: str) -> RelatedVocabData: ...
    def Serialize(self, instance: RelatedVocabData) -> str: ...


class SeeAlso:
    def __init__(self, vocab: VocabNote, data: RelatedVocabData, guard: NoteGuard) -> None: ...
    def Add(self, toAdd: str) -> None: ...
    def Notes(self) -> List_1[VocabNote]: ...
    def Remove(self, toRemove: str) -> None: ...
    def Strings(self) -> HashSet_1[str]: ...
    def ToString(self) -> str: ...


class Synonyms:
    def __init__(self, vocab: VocabNote, data: RelatedVocabData, guard: NoteGuard) -> None: ...
    def Add(self, synonym: str) -> None: ...
    def AddTransitivelyOneLevel(self, synonym: str) -> None: ...
    def Notes(self) -> List_1[VocabNote]: ...
    def Remove(self, toRemove: str) -> None: ...
    def Strings(self) -> HashSet_1[str]: ...

