import typing, clr, abc
from System import Array_1, IDisposable, TimeSpan, Action, Action_1, Action_2, Func_2, Span_1, IEquatable_1
from Avalonia import Vector, PixelSize, Matrix, Rect, Point, RoundedRect, Size, PixelPoint, PixelRect, Thickness
from System.IO import Stream
from Avalonia.Media import Color, IBrush, IPen, BoxShadows, RenderOptions, IGlyphTypeface
from System.Collections.Generic import IReadOnlyList_1, IList_1, IEnumerable_1
from Avalonia.Input.Platform import PlatformHotkeyConfiguration
from Avalonia.Input import PointerType, IInputRoot, PointerPressedEventArgs
from Avalonia.Controls.Primitives.PopupPositioning import IPopupPositioner
from System.Threading.Tasks import Task_1
from Avalonia.Controls import AcrylicPlatformCompensationLevels, WindowResizeReason, WindowTransparencyLevel, WindowCloseReason, WindowState, WindowEdge, Window, SystemDecorations
from Avalonia.Rendering.Composition import Compositor
from Avalonia.Input.Raw import RawInputEventArgs

class AlphaFormat(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Premul : AlphaFormat # 0
    Unpremul : AlphaFormat # 1
    Opaque : AlphaFormat # 2


class ColorContrastPreference(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    NoPreference : ColorContrastPreference # 0
    High : ColorContrastPreference # 1


class ExtendClientAreaChromeHints(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    NoChrome : ExtendClientAreaChromeHints # 0
    SystemChrome : ExtendClientAreaChromeHints # 1
    Default : ExtendClientAreaChromeHints # 2
    PreferSystemChrome : ExtendClientAreaChromeHints # 2
    OSXThickTitleBar : ExtendClientAreaChromeHints # 8


class IApplicationPlatformEvents(typing.Protocol):
    @abc.abstractmethod
    def RaiseUrlsOpened(self, urls: Array_1[str]) -> None: ...


class IBitmapImpl(IDisposable, typing.Protocol):
    @property
    def Dpi(self) -> Vector: ...
    @property
    def PixelSize(self) -> PixelSize: ...
    @property
    def Version(self) -> int: ...
    # Skipped Save due to it being static, abstract and generic.

    Save : Save_MethodGroup
    class Save_MethodGroup:
        @typing.overload
        def __call__(self, fileName: str, quality: typing.Optional[int] = ...) -> None:...
        @typing.overload
        def __call__(self, stream: Stream, quality: typing.Optional[int] = ...) -> None:...



class ICursorImpl(IDisposable, typing.Protocol):
    pass


class IDrawingContextImpl(IDisposable, typing.Protocol):
    @property
    def Transform(self) -> Matrix: ...
    @Transform.setter
    def Transform(self, value: Matrix) -> Matrix: ...
    @abc.abstractmethod
    def Clear(self, color: Color) -> None: ...
    @abc.abstractmethod
    def CreateLayer(self, size: PixelSize) -> IDrawingContextLayerImpl: ...
    @abc.abstractmethod
    def DrawEllipse(self, brush: IBrush, pen: IPen, rect: Rect) -> None: ...
    @abc.abstractmethod
    def DrawGeometry(self, brush: IBrush, pen: IPen, geometry: IGeometryImpl) -> None: ...
    @abc.abstractmethod
    def DrawGlyphRun(self, foreground: IBrush, glyphRun: IGlyphRunImpl) -> None: ...
    @abc.abstractmethod
    def DrawLine(self, pen: IPen, p1: Point, p2: Point) -> None: ...
    @abc.abstractmethod
    def DrawRectangle(self, brush: IBrush, pen: IPen, rect: RoundedRect, boxShadows: BoxShadows = ...) -> None: ...
    @abc.abstractmethod
    def DrawRegion(self, brush: IBrush, pen: IPen, region: IPlatformRenderInterfaceRegion) -> None: ...
    @abc.abstractmethod
    def GetFeature(self, t: typing.Type[typing.Any]) -> typing.Any: ...
    @abc.abstractmethod
    def PopClip(self) -> None: ...
    @abc.abstractmethod
    def PopGeometryClip(self) -> None: ...
    @abc.abstractmethod
    def PopLayer(self) -> None: ...
    @abc.abstractmethod
    def PopOpacity(self) -> None: ...
    @abc.abstractmethod
    def PopOpacityMask(self) -> None: ...
    @abc.abstractmethod
    def PopRenderOptions(self) -> None: ...
    @abc.abstractmethod
    def PushGeometryClip(self, clip: IGeometryImpl) -> None: ...
    @abc.abstractmethod
    def PushLayer(self, bounds: Rect) -> None: ...
    @abc.abstractmethod
    def PushOpacity(self, opacity: float, bounds: typing.Optional[Rect]) -> None: ...
    @abc.abstractmethod
    def PushOpacityMask(self, mask: IBrush, bounds: Rect) -> None: ...
    @abc.abstractmethod
    def PushRenderOptions(self, renderOptions: RenderOptions) -> None: ...
    # Skipped DrawBitmap due to it being static, abstract and generic.

    DrawBitmap : DrawBitmap_MethodGroup
    class DrawBitmap_MethodGroup:
        @typing.overload
        def __call__(self, source: IBitmapImpl, opacity: float, sourceRect: Rect, destRect: Rect) -> None:...
        @typing.overload
        def __call__(self, source: IBitmapImpl, opacityMask: IBrush, opacityMaskRect: Rect, destRect: Rect) -> None:...

    # Skipped PushClip due to it being static, abstract and generic.

    PushClip : PushClip_MethodGroup
    class PushClip_MethodGroup:
        @typing.overload
        def __call__(self, clip: Rect) -> None:...
        @typing.overload
        def __call__(self, clip: RoundedRect) -> None:...
        @typing.overload
        def __call__(self, region: IPlatformRenderInterfaceRegion) -> None:...



class IDrawingContextLayerImpl(IRenderTargetBitmapImpl, typing.Protocol):
    @property
    def CanBlit(self) -> bool: ...
    @abc.abstractmethod
    def Blit(self, context: IDrawingContextImpl) -> None: ...


class IGeometryImpl(typing.Protocol):
    @property
    def Bounds(self) -> Rect: ...
    @property
    def ContourLength(self) -> float: ...
    @abc.abstractmethod
    def FillContains(self, point: Point) -> bool: ...
    @abc.abstractmethod
    def GetRenderBounds(self, pen: IPen) -> Rect: ...
    @abc.abstractmethod
    def GetWidenedGeometry(self, pen: IPen) -> IGeometryImpl: ...
    @abc.abstractmethod
    def Intersect(self, geometry: IGeometryImpl) -> IGeometryImpl: ...
    @abc.abstractmethod
    def StrokeContains(self, pen: IPen, point: Point) -> bool: ...
    @abc.abstractmethod
    def TryGetPointAndTangentAtDistance(self, distance: float, point: clr.Reference[Point], tangent: clr.Reference[Point]) -> bool: ...
    @abc.abstractmethod
    def TryGetPointAtDistance(self, distance: float, point: clr.Reference[Point]) -> bool: ...
    @abc.abstractmethod
    def TryGetSegment(self, startDistance: float, stopDistance: float, startOnBeginFigure: bool, segmentGeometry: clr.Reference[IGeometryImpl]) -> bool: ...
    @abc.abstractmethod
    def WithTransform(self, transform: Matrix) -> ITransformedGeometryImpl: ...


class IGlyphRunImpl(IDisposable, typing.Protocol):
    @property
    def BaselineOrigin(self) -> Point: ...
    @property
    def Bounds(self) -> Rect: ...
    @property
    def FontRenderingEmSize(self) -> float: ...
    @property
    def GlyphTypeface(self) -> IGlyphTypeface: ...
    @abc.abstractmethod
    def GetIntersections(self, lowerLimit: float, upperLimit: float) -> IReadOnlyList_1[float]: ...


class ILockedFramebuffer(IDisposable, typing.Protocol):
    @property
    def Address(self) -> int: ...
    @property
    def Dpi(self) -> Vector: ...
    @property
    def Format(self) -> PixelFormat: ...
    @property
    def RowBytes(self) -> int: ...
    @property
    def Size(self) -> PixelSize: ...


class IOptionalFeatureProvider(typing.Protocol):
    @abc.abstractmethod
    def TryGetFeature(self, featureType: typing.Type[typing.Any]) -> typing.Any: ...


class IPlatformGraphics(typing.Protocol):
    @property
    def UsesSharedContext(self) -> bool: ...
    @abc.abstractmethod
    def CreateContext(self) -> IPlatformGraphicsContext: ...
    @abc.abstractmethod
    def GetSharedContext(self) -> IPlatformGraphicsContext: ...


class IPlatformGraphicsContext(IOptionalFeatureProvider, IDisposable, typing.Protocol):
    @property
    def IsLost(self) -> bool: ...
    @abc.abstractmethod
    def EnsureCurrent(self) -> IDisposable: ...


class IPlatformHandle(typing.Protocol):
    @property
    def Handle(self) -> int: ...
    @property
    def HandleDescriptor(self) -> str: ...


class IPlatformRenderInterfaceRegion(IDisposable, typing.Protocol):
    @property
    def Bounds(self) -> LtrbPixelRect: ...
    @property
    def IsEmpty(self) -> bool: ...
    @property
    def Rects(self) -> IList_1[LtrbPixelRect]: ...
    @abc.abstractmethod
    def AddRect(self, rect: LtrbPixelRect) -> None: ...
    @abc.abstractmethod
    def Contains(self, pt: Point) -> bool: ...
    @abc.abstractmethod
    def Intersects(self, rect: LtrbRect) -> bool: ...
    @abc.abstractmethod
    def Reset(self) -> None: ...


class IPlatformSettings(typing.Protocol):
    @property
    def HoldWaitDuration(self) -> TimeSpan: ...
    @property
    def HotkeyConfiguration(self) -> PlatformHotkeyConfiguration: ...
    @abc.abstractmethod
    def GetColorValues(self) -> PlatformColorValues: ...
    @abc.abstractmethod
    def GetDoubleTapSize(self, type: PointerType) -> Size: ...
    @abc.abstractmethod
    def GetDoubleTapTime(self, type: PointerType) -> TimeSpan: ...
    @abc.abstractmethod
    def GetTapSize(self, type: PointerType) -> Size: ...


class IPopupImpl(IWindowBaseImpl, typing.Protocol):
    @property
    def PopupPositioner(self) -> IPopupPositioner: ...
    @abc.abstractmethod
    def SetWindowManagerAddShadowHint(self, enabled: bool) -> None: ...
    @abc.abstractmethod
    def TakeFocus(self) -> None: ...


class IRenderTarget(IDisposable, typing.Protocol):
    @property
    def IsCorrupted(self) -> bool: ...
    @abc.abstractmethod
    def CreateDrawingContext(self, useScaledDrawing: bool) -> IDrawingContextImpl: ...


class IRenderTargetBitmapImpl(IRenderTarget, IBitmapImpl, typing.Protocol):
    pass


class IScreenImpl(typing.Protocol):
    @property
    def AllScreens(self) -> IReadOnlyList_1[Screen]: ...
    @property
    def Changed(self) -> Action: ...
    @Changed.setter
    def Changed(self, value: Action) -> Action: ...
    @property
    def ScreenCount(self) -> int: ...
    @abc.abstractmethod
    def RequestScreenDetails(self) -> Task_1[bool]: ...
    @abc.abstractmethod
    def ScreenFromPoint(self, point: PixelPoint) -> Screen: ...
    @abc.abstractmethod
    def ScreenFromRect(self, rect: PixelRect) -> Screen: ...
    @abc.abstractmethod
    def ScreenFromTopLevel(self, topLevel: ITopLevelImpl) -> Screen: ...
    @abc.abstractmethod
    def ScreenFromWindow(self, window: IWindowBaseImpl) -> Screen: ...


class ITopLevelImpl(IDisposable, IOptionalFeatureProvider, typing.Protocol):
    @property
    def AcrylicCompensationLevels(self) -> AcrylicPlatformCompensationLevels: ...
    @property
    def ClientSize(self) -> Size: ...
    @property
    def Closed(self) -> Action: ...
    @Closed.setter
    def Closed(self, value: Action) -> Action: ...
    @property
    def Compositor(self) -> Compositor: ...
    @property
    def DesktopScaling(self) -> float: ...
    @property
    def Handle(self) -> IPlatformHandle: ...
    @property
    def Input(self) -> Action_1[RawInputEventArgs]: ...
    @Input.setter
    def Input(self, value: Action_1[RawInputEventArgs]) -> Action_1[RawInputEventArgs]: ...
    @property
    def LostFocus(self) -> Action: ...
    @LostFocus.setter
    def LostFocus(self, value: Action) -> Action: ...
    @property
    def Paint(self) -> Action_1[Rect]: ...
    @Paint.setter
    def Paint(self, value: Action_1[Rect]) -> Action_1[Rect]: ...
    @property
    def RenderScaling(self) -> float: ...
    @property
    def Resized(self) -> Action_2[Size, WindowResizeReason]: ...
    @Resized.setter
    def Resized(self, value: Action_2[Size, WindowResizeReason]) -> Action_2[Size, WindowResizeReason]: ...
    @property
    def ScalingChanged(self) -> Action_1[float]: ...
    @ScalingChanged.setter
    def ScalingChanged(self, value: Action_1[float]) -> Action_1[float]: ...
    @property
    def Surfaces(self) -> IEnumerable_1[typing.Any]: ...
    @property
    def TransparencyLevel(self) -> WindowTransparencyLevel: ...
    @property
    def TransparencyLevelChanged(self) -> Action_1[WindowTransparencyLevel]: ...
    @TransparencyLevelChanged.setter
    def TransparencyLevelChanged(self, value: Action_1[WindowTransparencyLevel]) -> Action_1[WindowTransparencyLevel]: ...
    @abc.abstractmethod
    def CreatePopup(self) -> IPopupImpl: ...
    @abc.abstractmethod
    def PointToClient(self, point: PixelPoint) -> Point: ...
    @abc.abstractmethod
    def PointToScreen(self, point: Point) -> PixelPoint: ...
    @abc.abstractmethod
    def SetCursor(self, cursor: ICursorImpl) -> None: ...
    @abc.abstractmethod
    def SetFrameThemeVariant(self, themeVariant: PlatformThemeVariant) -> None: ...
    @abc.abstractmethod
    def SetInputRoot(self, inputRoot: IInputRoot) -> None: ...
    @abc.abstractmethod
    def SetTransparencyLevelHint(self, transparencyLevels: IReadOnlyList_1[WindowTransparencyLevel]) -> None: ...


class ITransformedGeometryImpl(IGeometryImpl, typing.Protocol):
    @property
    def SourceGeometry(self) -> IGeometryImpl: ...
    @property
    def Transform(self) -> Matrix: ...


class IWindowBaseImpl(ITopLevelImpl, typing.Protocol):
    @property
    def Activated(self) -> Action: ...
    @Activated.setter
    def Activated(self, value: Action) -> Action: ...
    @property
    def Deactivated(self) -> Action: ...
    @Deactivated.setter
    def Deactivated(self, value: Action) -> Action: ...
    @property
    def FrameSize(self) -> typing.Optional[Size]: ...
    @property
    def MaxAutoSizeHint(self) -> Size: ...
    @property
    def Position(self) -> PixelPoint: ...
    @property
    def PositionChanged(self) -> Action_1[PixelPoint]: ...
    @PositionChanged.setter
    def PositionChanged(self, value: Action_1[PixelPoint]) -> Action_1[PixelPoint]: ...
    @abc.abstractmethod
    def Activate(self) -> None: ...
    @abc.abstractmethod
    def Hide(self) -> None: ...
    @abc.abstractmethod
    def SetTopmost(self, value: bool) -> None: ...
    @abc.abstractmethod
    def Show(self, activate: bool, isDialog: bool) -> None: ...


class IWindowIconImpl(typing.Protocol):
    @abc.abstractmethod
    def Save(self, outputStream: Stream) -> None: ...


class IWindowImpl(IWindowBaseImpl, typing.Protocol):
    @property
    def Closing(self) -> Func_2[WindowCloseReason, bool]: ...
    @Closing.setter
    def Closing(self, value: Func_2[WindowCloseReason, bool]) -> Func_2[WindowCloseReason, bool]: ...
    @property
    def ExtendClientAreaToDecorationsChanged(self) -> Action_1[bool]: ...
    @ExtendClientAreaToDecorationsChanged.setter
    def ExtendClientAreaToDecorationsChanged(self, value: Action_1[bool]) -> Action_1[bool]: ...
    @property
    def ExtendedMargins(self) -> Thickness: ...
    @property
    def GotInputWhenDisabled(self) -> Action: ...
    @GotInputWhenDisabled.setter
    def GotInputWhenDisabled(self, value: Action) -> Action: ...
    @property
    def IsClientAreaExtendedToDecorations(self) -> bool: ...
    @property
    def NeedsManagedDecorations(self) -> bool: ...
    @property
    def OffScreenMargin(self) -> Thickness: ...
    @property
    def WindowState(self) -> WindowState: ...
    @WindowState.setter
    def WindowState(self, value: WindowState) -> WindowState: ...
    @property
    def WindowStateChanged(self) -> Action_1[WindowState]: ...
    @WindowStateChanged.setter
    def WindowStateChanged(self, value: Action_1[WindowState]) -> Action_1[WindowState]: ...
    @abc.abstractmethod
    def BeginMoveDrag(self, e: PointerPressedEventArgs) -> None: ...
    @abc.abstractmethod
    def BeginResizeDrag(self, edge: WindowEdge, e: PointerPressedEventArgs) -> None: ...
    @abc.abstractmethod
    def CanResize(self, value: bool) -> None: ...
    @abc.abstractmethod
    def GetWindowsZOrder(self, windows: Span_1[Window], zOrder: Span_1[int]) -> None: ...
    @abc.abstractmethod
    def Move(self, point: PixelPoint) -> None: ...
    @abc.abstractmethod
    def Resize(self, clientSize: Size, reason: WindowResizeReason = ...) -> None: ...
    @abc.abstractmethod
    def SetEnabled(self, enable: bool) -> None: ...
    @abc.abstractmethod
    def SetExtendClientAreaChromeHints(self, hints: ExtendClientAreaChromeHints) -> None: ...
    @abc.abstractmethod
    def SetExtendClientAreaTitleBarHeightHint(self, titleBarHeight: float) -> None: ...
    @abc.abstractmethod
    def SetExtendClientAreaToDecorationsHint(self, extendIntoClientAreaHint: bool) -> None: ...
    @abc.abstractmethod
    def SetIcon(self, icon: IWindowIconImpl) -> None: ...
    @abc.abstractmethod
    def SetMinMaxSize(self, minSize: Size, maxSize: Size) -> None: ...
    @abc.abstractmethod
    def SetParent(self, parent: IWindowImpl) -> None: ...
    @abc.abstractmethod
    def SetSystemDecorations(self, enabled: SystemDecorations) -> None: ...
    @abc.abstractmethod
    def SetTitle(self, title: str) -> None: ...
    @abc.abstractmethod
    def ShowTaskbarIcon(self, value: bool) -> None: ...


class LtrbPixelRect:
    Bottom : int
    Left : int
    Right : int
    Top : int
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: LtrbPixelRect, right: LtrbPixelRect) -> bool: ...
    def __ne__(self, left: LtrbPixelRect, right: LtrbPixelRect) -> bool: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: LtrbPixelRect) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class LtrbRect:
    Bottom : float
    Left : float
    Right : float
    Top : float
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: LtrbRect, right: LtrbRect) -> bool: ...
    def __ne__(self, left: LtrbRect, right: LtrbRect) -> bool: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: LtrbRect) -> bool:...
        @typing.overload
        def __call__(self, other: clr.Reference[LtrbRect]) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class PixelFormat(IEquatable_1[PixelFormat]):
    @classmethod
    @property
    def Bgra8888(cls) -> PixelFormat: ...
    @property
    def BitsPerPixel(self) -> int: ...
    @classmethod
    @property
    def Rgb32(cls) -> PixelFormat: ...
    @classmethod
    @property
    def Rgb565(cls) -> PixelFormat: ...
    @classmethod
    @property
    def Rgba8888(cls) -> PixelFormat: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: PixelFormat, right: PixelFormat) -> bool: ...
    def __ne__(self, left: PixelFormat, right: PixelFormat) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: PixelFormat) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class PlatformColorValues(IEquatable_1[PlatformColorValues]):
    def __init__(self) -> None: ...
    @property
    def AccentColor1(self) -> Color: ...
    @AccentColor1.setter
    def AccentColor1(self, value: Color) -> Color: ...
    @property
    def AccentColor2(self) -> Color: ...
    @AccentColor2.setter
    def AccentColor2(self, value: Color) -> Color: ...
    @property
    def AccentColor3(self) -> Color: ...
    @AccentColor3.setter
    def AccentColor3(self, value: Color) -> Color: ...
    @property
    def ContrastPreference(self) -> ColorContrastPreference: ...
    @ContrastPreference.setter
    def ContrastPreference(self, value: ColorContrastPreference) -> ColorContrastPreference: ...
    @property
    def ThemeVariant(self) -> PlatformThemeVariant: ...
    @ThemeVariant.setter
    def ThemeVariant(self, value: PlatformThemeVariant) -> PlatformThemeVariant: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: PlatformColorValues, right: PlatformColorValues) -> bool: ...
    def __ne__(self, left: PlatformColorValues, right: PlatformColorValues) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: PlatformColorValues) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class PlatformGraphicsExternalImageFormat(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    R8G8B8A8UNorm : PlatformGraphicsExternalImageFormat # 0
    B8G8R8A8UNorm : PlatformGraphicsExternalImageFormat # 1


class PlatformGraphicsExternalImageProperties(IEquatable_1[PlatformGraphicsExternalImageProperties]):
    @property
    def Format(self) -> PlatformGraphicsExternalImageFormat: ...
    @Format.setter
    def Format(self, value: PlatformGraphicsExternalImageFormat) -> PlatformGraphicsExternalImageFormat: ...
    @property
    def Height(self) -> int: ...
    @Height.setter
    def Height(self, value: int) -> int: ...
    @property
    def MemoryOffset(self) -> int: ...
    @MemoryOffset.setter
    def MemoryOffset(self, value: int) -> int: ...
    @property
    def MemorySize(self) -> int: ...
    @MemorySize.setter
    def MemorySize(self, value: int) -> int: ...
    @property
    def TopLeftOrigin(self) -> bool: ...
    @TopLeftOrigin.setter
    def TopLeftOrigin(self, value: bool) -> bool: ...
    @property
    def Width(self) -> int: ...
    @Width.setter
    def Width(self, value: int) -> int: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: PlatformGraphicsExternalImageProperties, right: PlatformGraphicsExternalImageProperties) -> bool: ...
    def __ne__(self, left: PlatformGraphicsExternalImageProperties, right: PlatformGraphicsExternalImageProperties) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: PlatformGraphicsExternalImageProperties) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class PlatformThemeVariant(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Light : PlatformThemeVariant # 0
    Dark : PlatformThemeVariant # 1


class Screen(IEquatable_1[Screen]):
    def __init__(self, scaling: float, bounds: PixelRect, workingArea: PixelRect, isPrimary: bool) -> None: ...
    @property
    def Bounds(self) -> PixelRect: ...
    @Bounds.setter
    def Bounds(self, value: PixelRect) -> PixelRect: ...
    @property
    def CurrentOrientation(self) -> ScreenOrientation: ...
    @CurrentOrientation.setter
    def CurrentOrientation(self, value: ScreenOrientation) -> ScreenOrientation: ...
    @property
    def DisplayName(self) -> str: ...
    @DisplayName.setter
    def DisplayName(self, value: str) -> str: ...
    @property
    def IsPrimary(self) -> bool: ...
    @IsPrimary.setter
    def IsPrimary(self, value: bool) -> bool: ...
    @property
    def PixelDensity(self) -> float: ...
    @property
    def Primary(self) -> bool: ...
    @property
    def Scaling(self) -> float: ...
    @Scaling.setter
    def Scaling(self, value: float) -> float: ...
    @property
    def WorkingArea(self) -> PixelRect: ...
    @WorkingArea.setter
    def WorkingArea(self, value: PixelRect) -> PixelRect: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: Screen, right: Screen) -> bool: ...
    def __ne__(self, left: Screen, right: Screen) -> bool: ...
    def ToString(self) -> str: ...
    def TryGetPlatformHandle(self) -> IPlatformHandle: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: Screen) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class ScreenOrientation(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : ScreenOrientation # 0
    Landscape : ScreenOrientation # 1
    Portrait : ScreenOrientation # 2
    LandscapeFlipped : ScreenOrientation # 4
    PortraitFlipped : ScreenOrientation # 8

