from System import EventArgs
from Avalonia.Input import IInputDevice, IInputRoot

class RawInputEventArgs(EventArgs):
    def __init__(self, device: IInputDevice, timestamp: int, root: IInputRoot) -> None: ...
    @property
    def Device(self) -> IInputDevice: ...
    @property
    def Handled(self) -> bool: ...
    @Handled.setter
    def Handled(self, value: bool) -> bool: ...
    @property
    def Root(self) -> IInputRoot: ...
    @property
    def Timestamp(self) -> int: ...
    @Timestamp.setter
    def Timestamp(self, value: int) -> int: ...

