import typing
from System.Collections.Generic import List_1, IEnumerable_1, HashSet_1
from JAStudio.Core.Note.Vocabulary import VocabNote
from System.Collections.Frozen import FrozenSet_1

class DictEntry:
    def __init__(self, source: typing.Any) -> None: ...
    @property
    def KanaForms(self) -> List_1[KanaFormEX]: ...
    @property
    def KanjiForms(self) -> List_1[KanjiFormEX]: ...
    @property
    def Senses(self) -> List_1[SenseEX]: ...
    @staticmethod
    def Create(entries: IEnumerable_1[DictEntry]) -> List_1[DictEntry]: ...
    def FormatAnswer(self) -> str: ...
    def HasMatchingKanaForm(self, search: str) -> bool: ...
    def HasMatchingKanjiForm(self, search: str) -> bool: ...
    def IsIntransitiveVerb(self) -> bool: ...
    def IsKanaOnly(self) -> bool: ...
    def IsToBeVerb(self) -> bool: ...
    def IsTransitiveVerb(self) -> bool: ...
    def KanaFormsText(self) -> List_1[str]: ...
    def KanjiFormsText(self) -> List_1[str]: ...
    def PartsOfSpeech(self) -> HashSet_1[str]: ...
    def ValidForms(self, forceAllowKanaOnly: bool = ...) -> HashSet_1[str]: ...


class DictLookup:
    def EnsureLoadedIntoMemory(self) -> None: ...
    def IsDictionaryOrCollectionWord(self, word: str) -> bool: ...
    def IsWord(self, word: str) -> bool: ...
    def LookupName(self, word: str) -> DictLookupResult: ...
    def LookupVocabWordOrName(self, vocab: VocabNote) -> DictLookupResult: ...
    def LookupWord(self, word: str) -> DictLookupResult: ...
    def LookupWordOrName(self, word: str) -> DictLookupResult: ...
    def LookupWordOrNameWithMatchingReading(self, word: str, readings: List_1[str]) -> DictLookupResult: ...
    def MightBeEntry(self, word: str) -> bool: ...
    def MightBeName(self, word: str) -> bool: ...
    def MightBeWord(self, word: str) -> bool: ...
    @staticmethod
    def ShutDownJamdict() -> None: ...


class DictLookupResult:
    def __init__(self, entries: List_1[DictEntry], lookupWord: str, lookupReading: List_1[str]) -> None: ...
    @property
    def Entries(self) -> List_1[DictEntry]: ...
    @property
    def LookupReading(self) -> List_1[str]: ...
    @property
    def Word(self) -> str: ...
    @staticmethod
    def Failed() -> DictLookupResult: ...
    def FormatAnswer(self) -> str: ...
    def FoundWords(self) -> bool: ...
    def FoundWordsCount(self) -> int: ...
    def IsUk(self) -> bool: ...
    def PartsOfSpeech(self) -> HashSet_1[str]: ...
    def PrioritySpec(self) -> PrioritySpec: ...
    def Readings(self) -> List_1[str]: ...
    def ValidForms(self, forceAllowKanaOnly: bool = ...) -> HashSet_1[str]: ...


class KanaFormEX:
    def __init__(self, source: typing.Any) -> None: ...
    @property
    def PriorityTags(self) -> List_1[str]: ...
    @property
    def Text(self) -> str: ...


class KanjiFormEX:
    def __init__(self, source: typing.Any) -> None: ...
    @property
    def PriorityTags(self) -> List_1[str]: ...
    @property
    def Text(self) -> str: ...


class PrioritySpec:
    def __init__(self, tags: HashSet_1[str]) -> None: ...
    @property
    def Priority(self) -> int: ...
    @property
    def PriorityString(self) -> str: ...
    @property
    def Tags(self) -> HashSet_1[str]: ...


class SenseEX:
    def __init__(self, source: typing.Any) -> None: ...
    @property
    def Glosses(self) -> List_1[str]: ...
    @property
    def IsKanaOnly(self) -> bool: ...
    @property
    def Pos(self) -> FrozenSet_1[str]: ...
    def FormatGlosses(self) -> str: ...
    def IsIntransitiveVerb(self) -> bool: ...
    def IsToBeVerb(self) -> bool: ...
    def IsTransitiveVerb(self) -> bool: ...

