import typing, abc
from JAStudio.Core.Note import NoteData, NoteId, IBackendNoteCreator, NoteServices, JPNote, KanjiNote
from JAStudio.Core.Configuration import JapaneseConfig
from JAStudio.Core.Storage import INoteRepository
from JAStudio.Core.Storage.Media import MediaFileIndex
from JAStudio.Core import IBackendDataLoader
from JAStudio.Core.LanguageServices.JamdictEx import DictLookup
from JAStudio.Core.Note.Vocabulary import VocabNoteFactory, VocabNoteGeneratedData, VocabNote
from System.Collections.Generic import List_1, HashSet_1, IEnumerable_1
from JAStudio.Core.Note.Sentences import SentenceNote

class CardStudyingStatus:
    def __init__(self, externalNoteId: int, cardType: str, isSuspended: bool, noteTypeName: str) -> None: ...
    @property
    def CardType(self) -> str: ...
    @property
    def ExternalNoteId(self) -> int: ...
    @property
    def IsSuspended(self) -> bool: ...
    @property
    def NoteTypeName(self) -> str: ...


class IExternalNoteUpdateHandler(typing.Protocol):
    @abc.abstractmethod
    def ExternalNoteAdded(self, externalNoteId: int, data: NoteData) -> None: ...
    @abc.abstractmethod
    def ExternalNoteRemoved(self, externalNoteId: int) -> None: ...
    @abc.abstractmethod
    def ExternalNoteWillFlush(self, externalNoteId: int, data: NoteData) -> None: ...
    @abc.abstractmethod
    def GetExternalNoteId(self, noteId: NoteId) -> int: ...
    @abc.abstractmethod
    def OnNoteUpdated(self, listener: typing.Any) -> None: ...


class JPCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator, noteServices: NoteServices, config: JapaneseConfig, noteRepository: INoteRepository, mediaFileIndex: MediaFileIndex, backendDataLoader: IBackendDataLoader) -> None: ...
    @property
    def DictLookup(self) -> DictLookup: ...
    @property
    def Kanji(self) -> KanjiCollection: ...
    @property
    def NoteServices(self) -> NoteServices: ...
    @property
    def Sentences(self) -> SentenceCollection: ...
    @property
    def Vocab(self) -> VocabCollection: ...
    @property
    def VocabNoteFactory(self) -> VocabNoteFactory: ...
    @property
    def VocabNoteGeneratedData(self) -> VocabNoteGeneratedData: ...
    def ClearCaches(self) -> None: ...
    def GetExternalNoteId(self, noteId: NoteId) -> int: ...
    def NoteFromExternalId(self, externalNoteId: int) -> JPNote: ...
    def NoteFromNoteId(self, noteId: NoteId) -> JPNote: ...
    def ReloadFromBackend(self) -> None: ...
    def UpdateCardStudyingStatus(self, cardId: int) -> None: ...


class KanjiCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator, noteServices: NoteServices) -> None: ...
    @property
    def ExternalSyncHandler(self) -> IExternalNoteUpdateHandler: ...
    def Add(self, note: KanjiNote) -> None: ...
    def All(self) -> List_1[KanjiNote]: ...
    def ExternalIdToNoteId(self, externalNoteId: int) -> NoteId: ...
    def WithAnyKanjiIn(self, kanjiList: List_1[str]) -> List_1[KanjiNote]: ...
    def WithExternalIdOrNone(self, externalNoteId: int) -> KanjiNote: ...
    def WithIdOrNone(self, noteId: NoteId) -> KanjiNote: ...
    def WithKanji(self, kanji: str) -> KanjiNote: ...
    def WithRadical(self, radical: str) -> List_1[KanjiNote]: ...
    def WithReading(self, reading: str) -> HashSet_1[KanjiNote]: ...


class SentenceCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator, noteServices: NoteServices) -> None: ...
    @property
    def ExternalSyncHandler(self) -> IExternalNoteUpdateHandler: ...
    def Add(self, note: SentenceNote) -> None: ...
    def All(self) -> List_1[SentenceNote]: ...
    def ExternalIdToNoteId(self, externalNoteId: int) -> NoteId: ...
    def PotentiallyMatchingVocab(self, vocab: VocabNote) -> List_1[SentenceNote]: ...
    def SentencesWithSubstring(self, substring: str) -> List_1[SentenceNote]: ...
    def WithExternalIdOrNone(self, externalNoteId: int) -> SentenceNote: ...
    def WithForm(self, form: str) -> List_1[SentenceNote]: ...
    def WithHighlightedVocab(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...
    def WithIdOrNone(self, noteId: NoteId) -> SentenceNote: ...
    def WithQuestion(self, question: str) -> List_1[SentenceNote]: ...
    def WithUserHighlightedVocab(self, form: str) -> List_1[SentenceNote]: ...
    def WithUserMarkedInvalidVocab(self, form: str) -> List_1[SentenceNote]: ...
    def WithVocab(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...
    def WithVocabMarkedInvalid(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...
    def WithVocabOwnedForm(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...


class VocabCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator, noteServices: NoteServices) -> None: ...
    @property
    def ExternalSyncHandler(self) -> IExternalNoteUpdateHandler: ...
    def Add(self, note: VocabNote) -> None: ...
    def All(self) -> List_1[VocabNote]: ...
    def DerivedFrom(self, derivedFrom: str) -> List_1[VocabNote]: ...
    def ExternalIdToNoteId(self, externalNoteId: int) -> NoteId: ...
    def IsWord(self, form: str) -> bool: ...
    def WithAnyDisambiguationNameIn(self, questions: IEnumerable_1[str]) -> List_1[VocabNote]: ...
    def WithAnyFormIn(self, forms: List_1[str]) -> List_1[VocabNote]: ...
    def WithAnyFormInPreferDisambiguationNameOrExactMatch(self, forms: List_1[str]) -> List_1[VocabNote]: ...
    def WithCompoundPart(self, disambiguationName: str) -> List_1[VocabNote]: ...
    def WithDisambiguationName(self, name: str) -> List_1[VocabNote]: ...
    def WithExternalIdOrNone(self, externalNoteId: int) -> VocabNote: ...
    def WithForm(self, form: str) -> List_1[VocabNote]: ...
    def WithFormPreferDisambiguationNameOrExactMatch(self, form: str) -> List_1[VocabNote]: ...
    def WithIdOrNone(self, noteId: NoteId) -> VocabNote: ...
    def WithKanjiInAnyForm(self, kanji: KanjiNote) -> List_1[VocabNote]: ...
    def WithKanjiInMainForm(self, kanji: KanjiNote) -> List_1[VocabNote]: ...
    def WithQuestion(self, question: str) -> List_1[VocabNote]: ...
    def WithQuestionPreferDisambiguationName(self, question: str) -> IEnumerable_1[VocabNote]: ...
    def WithReading(self, reading: str) -> List_1[VocabNote]: ...
    def WithStem(self, stem: str) -> List_1[VocabNote]: ...

