import typing, abc
from JAStudio.Core.Note import JPNote, IBackendNoteCreator, NoteServices, KanjiNote, SentenceNote, VocabNote
from System.Collections.Generic import Dictionary_2, List_1, HashSet_1, IEnumerable_1
from System import Array_1
from System.Threading.Tasks import Task

class CachedNote:
    def __init__(self, note: JPNote) -> None: ...
    @property
    def Id(self) -> int: ...
    @property
    def Question(self) -> str: ...


class CardStudyingStatus:
    def __init__(self, noteId: int, cardType: str, isSuspended: bool, noteTypeName: str) -> None: ...
    @property
    def CardType(self) -> str: ...
    @property
    def IsSuspended(self) -> bool: ...
    @property
    def NoteId(self) -> int: ...
    @property
    def NoteTypeName(self) -> str: ...


class JPCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator) -> None: ...
    @property
    def Kanji(self) -> KanjiCollection: ...
    @property
    def Sentences(self) -> SentenceCollection: ...
    @property
    def Vocab(self) -> VocabCollection: ...
    def NoteFromNoteId(self, noteId: int) -> JPNote: ...
    def SetNoteServices(self, noteServices: NoteServices) -> None: ...
    def UpdateCardStudyingStatus(self, cardId: int) -> None: ...


class KanjiCache(NoteCache_2[KanjiNote, KanjiSnapshot]):
    def __init__(self) -> None: ...
    ByReading : Dictionary_2[str, List_1[KanjiNote]]
    def WithRadical(self, radical: str) -> List_1[KanjiNote]: ...


class KanjiCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator) -> None: ...
    def Add(self, note: KanjiNote) -> None: ...
    def All(self) -> List_1[KanjiNote]: ...
    def WithAnyKanjiIn(self, kanjiList: List_1[str]) -> List_1[KanjiNote]: ...
    def WithIdOrNone(self, noteId: int) -> KanjiNote: ...
    def WithKanji(self, kanji: str) -> KanjiNote: ...
    def WithRadical(self, radical: str) -> List_1[KanjiNote]: ...
    def WithReading(self, reading: str) -> HashSet_1[KanjiNote]: ...


class KanjiSnapshot(CachedNote):
    def __init__(self, note: KanjiNote) -> None: ...
    @property
    def Id(self) -> int: ...
    @property
    def Question(self) -> str: ...
    @property
    def Radicals(self) -> Array_1[str]: ...
    @property
    def Readings(self) -> Array_1[str]: ...


class NoteCache_GenericClasses(abc.ABCMeta):
    Generic_NoteCache_GenericClasses_NoteCache_2_TNote = typing.TypeVar('Generic_NoteCache_GenericClasses_NoteCache_2_TNote')
    Generic_NoteCache_GenericClasses_NoteCache_2_TSnapshot = typing.TypeVar('Generic_NoteCache_GenericClasses_NoteCache_2_TSnapshot')
    def __getitem__(self, types : typing.Tuple[typing.Type[Generic_NoteCache_GenericClasses_NoteCache_2_TNote], typing.Type[Generic_NoteCache_GenericClasses_NoteCache_2_TSnapshot]]) -> typing.Type[NoteCache_2[Generic_NoteCache_GenericClasses_NoteCache_2_TNote, Generic_NoteCache_GenericClasses_NoteCache_2_TSnapshot]]: ...

NoteCache : NoteCache_GenericClasses

NoteCache_2_TNote = typing.TypeVar('NoteCache_2_TNote')
NoteCache_2_TSnapshot = typing.TypeVar('NoteCache_2_TSnapshot')
class NoteCache_2(typing.Generic[NoteCache_2_TNote, NoteCache_2_TSnapshot], NoteCacheBase_1[NoteCache_2_TNote]):
    def AddToCache(self, note: NoteCache_2_TNote) -> None: ...
    def All(self) -> List_1[NoteCache_2_TNote]: ...
    def RemoveFromCache(self, note: NoteCache_2_TNote) -> None: ...
    def WithQuestion(self, question: str) -> List_1[NoteCache_2_TNote]: ...


class NoteCacheBase_GenericClasses(abc.ABCMeta):
    Generic_NoteCacheBase_GenericClasses_NoteCacheBase_1_TNote = typing.TypeVar('Generic_NoteCacheBase_GenericClasses_NoteCacheBase_1_TNote')
    def __getitem__(self, types : typing.Type[Generic_NoteCacheBase_GenericClasses_NoteCacheBase_1_TNote]) -> typing.Type[NoteCacheBase_1[Generic_NoteCacheBase_GenericClasses_NoteCacheBase_1_TNote]]: ...

NoteCacheBase : NoteCacheBase_GenericClasses

NoteCacheBase_1_TNote = typing.TypeVar('NoteCacheBase_1_TNote')
class NoteCacheBase_1(typing.Generic[NoteCacheBase_1_TNote], abc.ABC):
    @abc.abstractmethod
    def AddToCache(self, note: NoteCacheBase_1_TNote) -> None: ...
    def AnkiNoteUpdated(self, note: NoteCacheBase_1_TNote) -> None: ...
    def JpNoteUpdated(self, note: NoteCacheBase_1_TNote) -> None: ...
    def LoadAsync(self) -> Task: ...
    def OnNoteUpdated(self, listener: typing.Any) -> None: ...
    @abc.abstractmethod
    def RemoveFromCache(self, note: NoteCacheBase_1_TNote) -> None: ...
    def SetNoteServices(self, noteServices: NoteServices) -> None: ...
    def SetStudyingStatuses(self, cardStatuses: List_1[CardStudyingStatus]) -> None: ...
    def WithIdOrNone(self, noteId: int) -> NoteCacheBase_1_TNote: ...


class SentenceCache(NoteCache_2[SentenceNote, SentenceSnapshot]):
    def __init__(self) -> None: ...
    def WithUserHighlightedVocab(self, form: str) -> List_1[SentenceNote]: ...
    def WithUserMarkedInvalidVocab(self, form: str) -> List_1[SentenceNote]: ...
    def WithVocab(self, vocab: VocabNote) -> List_1[SentenceNote]: ...
    def WithVocabForm(self, form: str) -> List_1[SentenceNote]: ...


class SentenceCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator) -> None: ...
    def Add(self, note: SentenceNote) -> None: ...
    def All(self) -> List_1[SentenceNote]: ...
    def PotentiallyMatchingVocab(self, vocab: VocabNote) -> List_1[SentenceNote]: ...
    def SentencesWithSubstring(self, substring: str) -> List_1[SentenceNote]: ...
    def WithForm(self, form: str) -> List_1[SentenceNote]: ...
    def WithHighlightedVocab(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...
    def WithIdOrNone(self, noteId: int) -> SentenceNote: ...
    def WithQuestion(self, question: str) -> List_1[SentenceNote]: ...
    def WithUserHighlightedVocab(self, form: str) -> List_1[SentenceNote]: ...
    def WithUserMarkedInvalidVocab(self, form: str) -> List_1[SentenceNote]: ...
    def WithVocab(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...
    def WithVocabMarkedInvalid(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...
    def WithVocabOwnedForm(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...


class SentenceSnapshot(CachedNote):
    def __init__(self, note: SentenceNote) -> None: ...
    @property
    def DetectedVocab(self) -> Array_1[int]: ...
    @property
    def Id(self) -> int: ...
    @property
    def MarkedIncorrectVocab(self) -> Array_1[str]: ...
    @property
    def Question(self) -> str: ...
    @property
    def UserHighlightedVocab(self) -> Array_1[str]: ...
    @property
    def Words(self) -> Array_1[str]: ...


class VocabCache(NoteCache_2[VocabNote, VocabSnapshot]):
    def __init__(self) -> None: ...
    def DerivedFrom(self, form: str) -> List_1[VocabNote]: ...
    def WithCompoundPart(self, disambiguationName: str) -> List_1[VocabNote]: ...
    def WithDisambiguationName(self, form: str) -> IEnumerable_1[VocabNote]: ...
    def WithForm(self, form: str) -> IEnumerable_1[VocabNote]: ...
    def WithKanjiInAnyForm(self, kanji: str) -> List_1[VocabNote]: ...
    def WithKanjiInMainForm(self, kanji: str) -> List_1[VocabNote]: ...
    def WithReading(self, reading: str) -> List_1[VocabNote]: ...
    def WithStem(self, stem: str) -> List_1[VocabNote]: ...


class VocabCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator) -> None: ...
    def Add(self, note: VocabNote) -> None: ...
    def All(self) -> List_1[VocabNote]: ...
    def DerivedFrom(self, derivedFrom: str) -> List_1[VocabNote]: ...
    def IsWord(self, form: str) -> bool: ...
    def WithAnyDisambiguationNameIn(self, questions: IEnumerable_1[str]) -> List_1[VocabNote]: ...
    def WithAnyFormIn(self, forms: List_1[str]) -> List_1[VocabNote]: ...
    def WithAnyFormInPreferDisambiguationNameOrExactMatch(self, forms: List_1[str]) -> List_1[VocabNote]: ...
    def WithCompoundPart(self, disambiguationName: str) -> List_1[VocabNote]: ...
    def WithDisambiguationName(self, name: str) -> IEnumerable_1[VocabNote]: ...
    def WithForm(self, form: str) -> IEnumerable_1[VocabNote]: ...
    def WithFormPreferDisambiguationNameOrExactMatch(self, form: str) -> List_1[VocabNote]: ...
    def WithIdOrNone(self, noteId: int) -> VocabNote: ...
    def WithKanjiInAnyForm(self, kanji: KanjiNote) -> List_1[VocabNote]: ...
    def WithKanjiInMainForm(self, kanji: KanjiNote) -> List_1[VocabNote]: ...
    def WithQuestion(self, question: str) -> List_1[VocabNote]: ...
    def WithQuestionPreferDisambiguationName(self, question: str) -> IEnumerable_1[VocabNote]: ...
    def WithReading(self, reading: str) -> List_1[VocabNote]: ...
    def WithStem(self, stem: str) -> List_1[VocabNote]: ...


class VocabSnapshot(CachedNote):
    def __init__(self, note: VocabNote) -> None: ...
    @property
    def AllKanji(self) -> Array_1[str]: ...
    @property
    def CompoundParts(self) -> Array_1[str]: ...
    @property
    def DerivedFrom(self) -> str: ...
    @property
    def DisambiguationName(self) -> str: ...
    @property
    def Forms(self) -> Array_1[str]: ...
    @property
    def Id(self) -> int: ...
    @property
    def MainFormKanji(self) -> Array_1[str]: ...
    @property
    def Question(self) -> str: ...
    @property
    def Readings(self) -> Array_1[str]: ...
    @property
    def Stems(self) -> Array_1[str]: ...

