import typing, abc
from JAStudio.Core.Note import JPNote, NoteId, NoteData, IBackendNoteCreator, NoteServices, KanjiNote, SentenceNote, VocabNote
from JAStudio.Core.Configuration import JapaneseConfig
from JAStudio.Core.Storage import INoteRepository
from JAStudio.Core import IBackendDataLoader
from JAStudio.Core.LanguageServices.JamdictEx import DictLookup
from JAStudio.Core.Note.Vocabulary import VocabNoteFactory, VocabNoteGeneratedData
from System.Collections.Generic import List_1, HashSet_1, IEnumerable_1, Dictionary_2
from System import Array_1, Action_1

class CachedNote:
    def __init__(self, note: JPNote) -> None: ...
    @property
    def Id(self) -> NoteId: ...
    @property
    def Question(self) -> str: ...


class CardStudyingStatus:
    def __init__(self, externalNoteId: int, cardType: str, isSuspended: bool, noteTypeName: str) -> None: ...
    @property
    def CardType(self) -> str: ...
    @property
    def ExternalNoteId(self) -> int: ...
    @property
    def IsSuspended(self) -> bool: ...
    @property
    def NoteTypeName(self) -> str: ...


class IExternalNoteUpdateHandler(typing.Protocol):
    @abc.abstractmethod
    def ExternalNoteAdded(self, externalNoteId: int, data: NoteData) -> None: ...
    @abc.abstractmethod
    def ExternalNoteRemoved(self, externalNoteId: int) -> None: ...
    @abc.abstractmethod
    def ExternalNoteWillFlush(self, externalNoteId: int, data: NoteData) -> None: ...
    @abc.abstractmethod
    def GetExternalNoteId(self, noteId: NoteId) -> int: ...
    @abc.abstractmethod
    def OnNoteUpdated(self, listener: typing.Any) -> None: ...


class JPCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator, noteServices: NoteServices, config: JapaneseConfig, noteRepository: INoteRepository, backendDataLoader: IBackendDataLoader = ...) -> None: ...
    @property
    def DictLookup(self) -> DictLookup: ...
    @property
    def Kanji(self) -> KanjiCollection: ...
    @property
    def NoteServices(self) -> NoteServices: ...
    @property
    def Sentences(self) -> SentenceCollection: ...
    @property
    def Vocab(self) -> VocabCollection: ...
    @property
    def VocabNoteFactory(self) -> VocabNoteFactory: ...
    @property
    def VocabNoteGeneratedData(self) -> VocabNoteGeneratedData: ...
    def ClearCaches(self) -> None: ...
    def GetExternalNoteId(self, noteId: NoteId) -> int: ...
    def NoteFromExternalId(self, externalNoteId: int) -> JPNote: ...
    def NoteFromNoteId(self, noteId: NoteId) -> JPNote: ...
    def ReloadFromBackend(self) -> None: ...
    def UpdateCardStudyingStatus(self, cardId: int) -> None: ...


class KanjiCache(NoteCache_2[KanjiNote, KanjiSnapshot]):
    def __init__(self, noteServices: NoteServices) -> None: ...
    def WithRadical(self, radical: str) -> List_1[KanjiNote]: ...
    def WithReading(self, reading: str) -> HashSet_1[KanjiNote]: ...


class KanjiCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator, noteServices: NoteServices) -> None: ...
    @property
    def ExternalSyncHandler(self) -> IExternalNoteUpdateHandler: ...
    def Add(self, note: KanjiNote) -> None: ...
    def All(self) -> List_1[KanjiNote]: ...
    def ExternalIdToNoteId(self, externalNoteId: int) -> NoteId: ...
    def WithAnyKanjiIn(self, kanjiList: List_1[str]) -> List_1[KanjiNote]: ...
    def WithExternalIdOrNone(self, externalNoteId: int) -> KanjiNote: ...
    def WithIdOrNone(self, noteId: NoteId) -> KanjiNote: ...
    def WithKanji(self, kanji: str) -> KanjiNote: ...
    def WithRadical(self, radical: str) -> List_1[KanjiNote]: ...
    def WithReading(self, reading: str) -> HashSet_1[KanjiNote]: ...


class KanjiSnapshot(CachedNote):
    def __init__(self, note: KanjiNote) -> None: ...
    @property
    def Id(self) -> NoteId: ...
    @property
    def Question(self) -> str: ...
    @property
    def Radicals(self) -> Array_1[str]: ...
    @property
    def Readings(self) -> Array_1[str]: ...


class NoteCache_GenericClasses(abc.ABCMeta):
    Generic_NoteCache_GenericClasses_NoteCache_2_TNote = typing.TypeVar('Generic_NoteCache_GenericClasses_NoteCache_2_TNote')
    Generic_NoteCache_GenericClasses_NoteCache_2_TSnapshot = typing.TypeVar('Generic_NoteCache_GenericClasses_NoteCache_2_TSnapshot')
    def __getitem__(self, types : typing.Tuple[typing.Type[Generic_NoteCache_GenericClasses_NoteCache_2_TNote], typing.Type[Generic_NoteCache_GenericClasses_NoteCache_2_TSnapshot]]) -> typing.Type[NoteCache_2[Generic_NoteCache_GenericClasses_NoteCache_2_TNote, Generic_NoteCache_GenericClasses_NoteCache_2_TSnapshot]]: ...

NoteCache : NoteCache_GenericClasses

NoteCache_2_TNote = typing.TypeVar('NoteCache_2_TNote')
NoteCache_2_TSnapshot = typing.TypeVar('NoteCache_2_TSnapshot')
class NoteCache_2(typing.Generic[NoteCache_2_TNote, NoteCache_2_TSnapshot], NoteCacheBase_1[NoteCache_2_TNote]):
    def All(self) -> List_1[NoteCache_2_TNote]: ...
    def WithQuestion(self, question: str) -> List_1[NoteCache_2_TNote]: ...


class NoteCacheBase_GenericClasses(abc.ABCMeta):
    Generic_NoteCacheBase_GenericClasses_NoteCacheBase_1_TNote = typing.TypeVar('Generic_NoteCacheBase_GenericClasses_NoteCacheBase_1_TNote')
    def __getitem__(self, types : typing.Type[Generic_NoteCacheBase_GenericClasses_NoteCacheBase_1_TNote]) -> typing.Type[NoteCacheBase_1[Generic_NoteCacheBase_GenericClasses_NoteCacheBase_1_TNote]]: ...

NoteCacheBase : NoteCacheBase_GenericClasses

NoteCacheBase_1_TNote = typing.TypeVar('NoteCacheBase_1_TNote')
class NoteCacheBase_1(typing.Generic[NoteCacheBase_1_TNote], IExternalNoteUpdateHandler, abc.ABC):
    def AddAllToCache(self, notes: IEnumerable_1[NoteCacheBase_1_TNote]) -> None: ...
    def AddToCache(self, note: NoteCacheBase_1_TNote) -> None: ...
    def Clear(self) -> None: ...
    def ExternalIdToNoteId(self, externalNoteId: int) -> NoteId: ...
    def ExternalNoteAdded(self, externalNoteId: int, data: NoteData) -> None: ...
    def ExternalNoteRemoved(self, externalNoteId: int) -> None: ...
    def ExternalNoteWillFlush(self, externalNoteId: int, data: NoteData) -> None: ...
    def GetExternalNoteId(self, noteId: NoteId) -> int: ...
    def JpNoteUpdated(self, note: NoteCacheBase_1_TNote) -> None: ...
    def RemoveFromCache(self, note: NoteCacheBase_1_TNote) -> None: ...
    def SetStudyingStatuses(self, statusesByExternalId: Dictionary_2[int, List_1[CardStudyingStatus]]) -> None: ...
    def WithExternalIdOrNone(self, externalNoteId: int) -> NoteCacheBase_1_TNote: ...
    def WithIdOrNone(self, noteId: NoteId) -> NoteCacheBase_1_TNote: ...
    # Skipped OnNoteUpdated due to it being static, abstract and generic.

    OnNoteUpdated : OnNoteUpdated_MethodGroup[NoteCacheBase_1_TNote]
    OnNoteUpdated_MethodGroup_NoteCacheBase_1_TNote = typing.TypeVar('OnNoteUpdated_MethodGroup_NoteCacheBase_1_TNote')
    class OnNoteUpdated_MethodGroup(typing.Generic[OnNoteUpdated_MethodGroup_NoteCacheBase_1_TNote]):
        OnNoteUpdated_MethodGroup_NoteCacheBase_1_TNote = NoteCacheBase_1.OnNoteUpdated_MethodGroup_NoteCacheBase_1_TNote
        @typing.overload
        def __call__(self, listener: Action_1[OnNoteUpdated_MethodGroup_NoteCacheBase_1_TNote]) -> None:...
        @typing.overload
        def __call__(self, listener: typing.Any) -> None:...



class SentenceCache(NoteCache_2[SentenceNote, SentenceSnapshot]):
    def __init__(self, noteServices: NoteServices) -> None: ...
    def WithUserHighlightedVocab(self, form: str) -> List_1[SentenceNote]: ...
    def WithUserMarkedInvalidVocab(self, form: str) -> List_1[SentenceNote]: ...
    def WithVocab(self, vocab: VocabNote) -> List_1[SentenceNote]: ...
    def WithVocabForm(self, form: str) -> List_1[SentenceNote]: ...


class SentenceCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator, noteServices: NoteServices) -> None: ...
    @property
    def ExternalSyncHandler(self) -> IExternalNoteUpdateHandler: ...
    def Add(self, note: SentenceNote) -> None: ...
    def All(self) -> List_1[SentenceNote]: ...
    def ExternalIdToNoteId(self, externalNoteId: int) -> NoteId: ...
    def PotentiallyMatchingVocab(self, vocab: VocabNote) -> List_1[SentenceNote]: ...
    def SentencesWithSubstring(self, substring: str) -> List_1[SentenceNote]: ...
    def WithExternalIdOrNone(self, externalNoteId: int) -> SentenceNote: ...
    def WithForm(self, form: str) -> List_1[SentenceNote]: ...
    def WithHighlightedVocab(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...
    def WithIdOrNone(self, noteId: NoteId) -> SentenceNote: ...
    def WithQuestion(self, question: str) -> List_1[SentenceNote]: ...
    def WithUserHighlightedVocab(self, form: str) -> List_1[SentenceNote]: ...
    def WithUserMarkedInvalidVocab(self, form: str) -> List_1[SentenceNote]: ...
    def WithVocab(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...
    def WithVocabMarkedInvalid(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...
    def WithVocabOwnedForm(self, vocabNote: VocabNote) -> List_1[SentenceNote]: ...


class SentenceSnapshot(CachedNote):
    def __init__(self, note: SentenceNote) -> None: ...
    @property
    def DetectedVocab(self) -> Array_1[NoteId]: ...
    @property
    def Id(self) -> NoteId: ...
    @property
    def MarkedIncorrectVocab(self) -> Array_1[str]: ...
    @property
    def Question(self) -> str: ...
    @property
    def UserHighlightedVocab(self) -> Array_1[str]: ...
    @property
    def Words(self) -> Array_1[str]: ...


class VocabCache(NoteCache_2[VocabNote, VocabSnapshot]):
    def __init__(self, noteServices: NoteServices) -> None: ...
    def DerivedFrom(self, form: str) -> List_1[VocabNote]: ...
    def WithCompoundPart(self, disambiguationName: str) -> List_1[VocabNote]: ...
    def WithDisambiguationName(self, form: str) -> List_1[VocabNote]: ...
    def WithForm(self, form: str) -> List_1[VocabNote]: ...
    def WithKanjiInAnyForm(self, kanji: str) -> List_1[VocabNote]: ...
    def WithKanjiInMainForm(self, kanji: str) -> List_1[VocabNote]: ...
    def WithReading(self, reading: str) -> List_1[VocabNote]: ...
    def WithStem(self, stem: str) -> List_1[VocabNote]: ...


class VocabCollection:
    def __init__(self, backendNoteCreator: IBackendNoteCreator, noteServices: NoteServices) -> None: ...
    @property
    def ExternalSyncHandler(self) -> IExternalNoteUpdateHandler: ...
    def Add(self, note: VocabNote) -> None: ...
    def All(self) -> List_1[VocabNote]: ...
    def DerivedFrom(self, derivedFrom: str) -> List_1[VocabNote]: ...
    def ExternalIdToNoteId(self, externalNoteId: int) -> NoteId: ...
    def IsWord(self, form: str) -> bool: ...
    def WithAnyDisambiguationNameIn(self, questions: IEnumerable_1[str]) -> List_1[VocabNote]: ...
    def WithAnyFormIn(self, forms: List_1[str]) -> List_1[VocabNote]: ...
    def WithAnyFormInPreferDisambiguationNameOrExactMatch(self, forms: List_1[str]) -> List_1[VocabNote]: ...
    def WithCompoundPart(self, disambiguationName: str) -> List_1[VocabNote]: ...
    def WithDisambiguationName(self, name: str) -> List_1[VocabNote]: ...
    def WithExternalIdOrNone(self, externalNoteId: int) -> VocabNote: ...
    def WithForm(self, form: str) -> List_1[VocabNote]: ...
    def WithFormPreferDisambiguationNameOrExactMatch(self, form: str) -> List_1[VocabNote]: ...
    def WithIdOrNone(self, noteId: NoteId) -> VocabNote: ...
    def WithKanjiInAnyForm(self, kanji: KanjiNote) -> List_1[VocabNote]: ...
    def WithKanjiInMainForm(self, kanji: KanjiNote) -> List_1[VocabNote]: ...
    def WithQuestion(self, question: str) -> List_1[VocabNote]: ...
    def WithQuestionPreferDisambiguationName(self, question: str) -> IEnumerable_1[VocabNote]: ...
    def WithReading(self, reading: str) -> List_1[VocabNote]: ...
    def WithStem(self, stem: str) -> List_1[VocabNote]: ...


class VocabSnapshot(CachedNote):
    def __init__(self, note: VocabNote) -> None: ...
    @property
    def AllKanji(self) -> Array_1[str]: ...
    @property
    def CompoundParts(self) -> Array_1[str]: ...
    @property
    def DerivedFrom(self) -> str: ...
    @property
    def DisambiguationName(self) -> str: ...
    @property
    def Forms(self) -> Array_1[str]: ...
    @property
    def Id(self) -> NoteId: ...
    @property
    def MainFormKanji(self) -> Array_1[str]: ...
    @property
    def Question(self) -> str: ...
    @property
    def Readings(self) -> Array_1[str]: ...
    @property
    def Stems(self) -> Array_1[str]: ...

