import typing, abc
from System import IEquatable_1, MulticastDelegate, IAsyncResult, AsyncCallback
from Avalonia import Rect, Point, Size, Visual
from System.Reflection import MethodInfo
from Avalonia.Controls import PlacementMode

class CustomPopupPlacement(IEquatable_1[CustomPopupPlacement]):
    @property
    def Anchor(self) -> PopupAnchor: ...
    @Anchor.setter
    def Anchor(self, value: PopupAnchor) -> PopupAnchor: ...
    @property
    def AnchorRectangle(self) -> Rect: ...
    @AnchorRectangle.setter
    def AnchorRectangle(self, value: Rect) -> Rect: ...
    @property
    def ConstraintAdjustment(self) -> PopupPositionerConstraintAdjustment: ...
    @ConstraintAdjustment.setter
    def ConstraintAdjustment(self, value: PopupPositionerConstraintAdjustment) -> PopupPositionerConstraintAdjustment: ...
    @property
    def Gravity(self) -> PopupGravity: ...
    @Gravity.setter
    def Gravity(self, value: PopupGravity) -> PopupGravity: ...
    @property
    def Offset(self) -> Point: ...
    @Offset.setter
    def Offset(self, value: Point) -> Point: ...
    @property
    def PopupSize(self) -> Size: ...
    @property
    def Target(self) -> Visual: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: CustomPopupPlacement, right: CustomPopupPlacement) -> bool: ...
    def __ne__(self, left: CustomPopupPlacement, right: CustomPopupPlacement) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: CustomPopupPlacement) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class CustomPopupPlacementCallback(MulticastDelegate):
    def __init__(self, object: typing.Any, method: int) -> None: ...
    @property
    def Method(self) -> MethodInfo: ...
    @property
    def Target(self) -> typing.Any: ...
    def BeginInvoke(self, parameters: CustomPopupPlacement, callback: AsyncCallback, object: typing.Any) -> IAsyncResult: ...
    def EndInvoke(self, result: IAsyncResult) -> None: ...
    def Invoke(self, parameters: CustomPopupPlacement) -> None: ...


class IPopupPositioner(typing.Protocol):
    @abc.abstractmethod
    def Update(self, parameters: PopupPositionerParameters) -> None: ...


class PopupAnchor(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : PopupAnchor # 0
    Top : PopupAnchor # 1
    Bottom : PopupAnchor # 2
    VerticalMask : PopupAnchor # 3
    Left : PopupAnchor # 4
    TopLeft : PopupAnchor # 5
    BottomLeft : PopupAnchor # 6
    Right : PopupAnchor # 8
    TopRight : PopupAnchor # 9
    BottomRight : PopupAnchor # 10
    HorizontalMask : PopupAnchor # 12
    AllMask : PopupAnchor # 15


class PopupGravity(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : PopupGravity # 0
    Top : PopupGravity # 1
    Bottom : PopupGravity # 2
    Left : PopupGravity # 4
    TopLeft : PopupGravity # 5
    BottomLeft : PopupGravity # 6
    Right : PopupGravity # 8
    TopRight : PopupGravity # 9
    BottomRight : PopupGravity # 10


class PopupPositionerConstraintAdjustment(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : PopupPositionerConstraintAdjustment # 0
    SlideX : PopupPositionerConstraintAdjustment # 1
    SlideY : PopupPositionerConstraintAdjustment # 2
    FlipX : PopupPositionerConstraintAdjustment # 4
    FlipY : PopupPositionerConstraintAdjustment # 8
    ResizeX : PopupPositionerConstraintAdjustment # 16
    ResizeY : PopupPositionerConstraintAdjustment # 32
    All : PopupPositionerConstraintAdjustment # 63


class PopupPositionerParameters(IEquatable_1[PopupPositionerParameters]):
    @property
    def Anchor(self) -> PopupAnchor: ...
    @Anchor.setter
    def Anchor(self, value: PopupAnchor) -> PopupAnchor: ...
    @property
    def AnchorRectangle(self) -> Rect: ...
    @AnchorRectangle.setter
    def AnchorRectangle(self, value: Rect) -> Rect: ...
    @property
    def ConstraintAdjustment(self) -> PopupPositionerConstraintAdjustment: ...
    @ConstraintAdjustment.setter
    def ConstraintAdjustment(self, value: PopupPositionerConstraintAdjustment) -> PopupPositionerConstraintAdjustment: ...
    @property
    def Gravity(self) -> PopupGravity: ...
    @Gravity.setter
    def Gravity(self, value: PopupGravity) -> PopupGravity: ...
    @property
    def Offset(self) -> Point: ...
    @Offset.setter
    def Offset(self, value: Point) -> Point: ...
    @property
    def Size(self) -> Size: ...
    @Size.setter
    def Size(self, value: Size) -> Size: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: PopupPositionerParameters, right: PopupPositionerParameters) -> bool: ...
    def __ne__(self, left: PopupPositionerParameters, right: PopupPositionerParameters) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: PopupPositionerParameters) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class PopupPositionRequest:
    @property
    def Anchor(self) -> PopupAnchor: ...
    @property
    def AnchorRect(self) -> typing.Optional[Rect]: ...
    @property
    def ConstraintAdjustment(self) -> PopupPositionerConstraintAdjustment: ...
    @property
    def Gravity(self) -> PopupGravity: ...
    @property
    def Offset(self) -> Point: ...
    @property
    def Placement(self) -> PlacementMode: ...
    @property
    def PlacementCallback(self) -> CustomPopupPlacementCallback: ...
    @property
    def Target(self) -> Visual: ...

