import typing, clr, abc
from System.Collections.Generic import List_1
from System import Func_2, Action_2, Action, Func_1, IEquatable_1, Action_1
from Compze.Utilities.SystemCE import LazyCE_1
from JAStudio.Core.Note import JPNote, Tag

class AudioField:
    def __init__(self, field: MutableStringField) -> None: ...
    def AudioFilesPaths(self) -> List_1[str]: ...
    def FirstAudioFilePath(self) -> str: ...
    def GetMediaReferences(self) -> List_1[MediaReference]: ...
    def HasAudio(self) -> bool: ...
    def RawValue(self) -> str: ...
    def ToString(self) -> str: ...


class CachingMutableStringField:
    def __init__(self, fieldName: str, getter: Func_2[str, str], setter: Action_2[str, str]) -> None: ...
    @property
    def Value(self) -> str: ...
    def Empty(self) -> None: ...
    def HasValue(self) -> bool: ...
    def OnChange(self, callback: Action) -> None: ...
    def Set(self, value: str) -> None: ...
    def ToString(self) -> str: ...
    # Skipped LazyReader due to it being static, abstract and generic.

    LazyReader : LazyReader_MethodGroup
    class LazyReader_MethodGroup:
        def __getitem__(self, t:typing.Type[LazyReader_1_T1]) -> LazyReader_1[LazyReader_1_T1]: ...

        LazyReader_1_T1 = typing.TypeVar('LazyReader_1_T1')
        class LazyReader_1(typing.Generic[LazyReader_1_T1]):
            LazyReader_1_TValue = CachingMutableStringField.LazyReader_MethodGroup.LazyReader_1_T1
            def __call__(self, reader: Func_1[LazyReader_1_TValue]) -> LazyCE_1[LazyReader_1_TValue]:...




class FallbackStringField:
    def __init__(self, primaryField: IStringValue, fallbackField: IStringValue) -> None: ...
    def Get(self) -> str: ...


class ImageField:
    def __init__(self, field: MutableStringField) -> None: ...
    def GetMediaReferences(self) -> List_1[MediaReference]: ...
    def HasImage(self) -> bool: ...
    def ImageFilePaths(self) -> List_1[str]: ...
    def RawValue(self) -> str: ...
    def ToString(self) -> str: ...


class IntegerField:
    def __init__(self, field: MutableStringField) -> None: ...
    def Get(self) -> int: ...
    def Set(self, value: int) -> None: ...


class IObjectSerializer_GenericClasses(abc.ABCMeta):
    Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T = typing.TypeVar('Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T')
    def __getitem__(self, types : typing.Type[Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T]) -> typing.Type[IObjectSerializer_1[Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T]]: ...

IObjectSerializer : IObjectSerializer_GenericClasses

IObjectSerializer_1_T = typing.TypeVar('IObjectSerializer_1_T')
class IObjectSerializer_1(typing.Generic[IObjectSerializer_1_T], typing.Protocol):
    @abc.abstractmethod
    def Deserialize(self, serialized: str) -> IObjectSerializer_1_T: ...
    @abc.abstractmethod
    def Serialize(self, instance: IObjectSerializer_1_T) -> str: ...


class IStringValue(typing.Protocol):
    @property
    def Value(self) -> str: ...


class IWritableStringValue(IStringValue, typing.Protocol):
    @abc.abstractmethod
    def Empty(self) -> None: ...
    @abc.abstractmethod
    def HasValue(self) -> bool: ...
    @abc.abstractmethod
    def Set(self, value: str) -> None: ...


class MediaFieldParsing(abc.ABC):
    @staticmethod
    def ParseAudioReferences(rawValue: str) -> List_1[MediaReference]: ...
    @staticmethod
    def ParseImageReferences(rawValue: str) -> List_1[MediaReference]: ...


class MediaReference(IEquatable_1[MediaReference]):
    def __init__(self, FileName: str, Type: MediaType) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> str: ...
    @property
    def Type(self) -> MediaType: ...
    @Type.setter
    def Type(self, value: MediaType) -> MediaType: ...
    def Deconstruct(self, FileName: clr.Reference[str], Type: clr.Reference[MediaType]) -> None: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: MediaReference, right: MediaReference) -> bool: ...
    def __ne__(self, left: MediaReference, right: MediaReference) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: MediaReference) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class MediaType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Audio : MediaType # 0
    Image : MediaType # 1


class MutableCommaSeparatedStringsListField:
    def __init__(self, field: CachingMutableStringField) -> None: ...
    def Add(self, add: str) -> None: ...
    def Get(self) -> List_1[str]: ...
    def RawStringValue(self) -> str: ...
    def Remove(self, remove: str) -> None: ...
    def Set(self, value: List_1[str]) -> None: ...
    def ToString(self) -> str: ...
    # Skipped LazyReader due to it being static, abstract and generic.

    LazyReader : LazyReader_MethodGroup
    class LazyReader_MethodGroup:
        def __getitem__(self, t:typing.Type[LazyReader_1_T1]) -> LazyReader_1[LazyReader_1_T1]: ...

        LazyReader_1_T1 = typing.TypeVar('LazyReader_1_T1')
        class LazyReader_1(typing.Generic[LazyReader_1_T1]):
            LazyReader_1_TValue = MutableCommaSeparatedStringsListField.LazyReader_MethodGroup.LazyReader_1_T1
            def __call__(self, reader: Func_1[LazyReader_1_TValue]) -> LazyCE_1[LazyReader_1_TValue]:...




class MutableCommaSeparatedStringsListFieldDeDuplicated(MutableCommaSeparatedStringsListField):
    def __init__(self, field: CachingMutableStringField) -> None: ...
    def Set(self, value: List_1[str]) -> None: ...


class MutableSerializedObjectField_GenericClasses(abc.ABCMeta):
    Generic_MutableSerializedObjectField_GenericClasses_MutableSerializedObjectField_1_T = typing.TypeVar('Generic_MutableSerializedObjectField_GenericClasses_MutableSerializedObjectField_1_T')
    def __getitem__(self, types : typing.Type[Generic_MutableSerializedObjectField_GenericClasses_MutableSerializedObjectField_1_T]) -> typing.Type[MutableSerializedObjectField_1[Generic_MutableSerializedObjectField_GenericClasses_MutableSerializedObjectField_1_T]]: ...

MutableSerializedObjectField : MutableSerializedObjectField_GenericClasses

MutableSerializedObjectField_1_T = typing.TypeVar('MutableSerializedObjectField_1_T')
class MutableSerializedObjectField_1(typing.Generic[MutableSerializedObjectField_1_T]):
    def __init__(self, field: MutableStringField, serializer: IObjectSerializer_1[MutableSerializedObjectField_1_T]) -> None: ...
    @property
    def RawValue(self) -> str: ...
    @RawValue.setter
    def RawValue(self, value: str) -> str: ...
    def Get(self) -> MutableSerializedObjectField_1_T: ...
    def Save(self) -> None: ...
    def Set(self, value: MutableSerializedObjectField_1_T) -> None: ...
    def ToString(self) -> str: ...


class MutableStringField(IWritableStringValue):
    def __init__(self, fieldName: str, getter: Func_2[str, str], setter: Action_2[str, str]) -> None: ...
    @property
    def Value(self) -> str: ...
    def Empty(self) -> None: ...
    def GetImageReferences(self) -> List_1[MediaReference]: ...
    def HasValue(self) -> bool: ...
    def Set(self, value: str) -> None: ...
    def ToString(self) -> str: ...


class RequireForbidFlagField:
    def __init__(self, note: JPNote, requiredWeight: int, forbiddenWeight: int, requiredTag: Tag, forbiddenTag: Tag) -> None: ...
    @property
    def ForbiddenWeight(self) -> int: ...
    @property
    def IsActive(self) -> bool: ...
    @property
    def IsConfiguredForbidden(self) -> bool: ...
    @property
    def IsConfiguredRequired(self) -> bool: ...
    @property
    def IsForbidden(self) -> bool: ...
    @property
    def IsRequired(self) -> bool: ...
    @property
    def MatchWeight(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def RequiredWeight(self) -> int: ...
    def SetForbidden(self, value: bool) -> None: ...
    def SetRequired(self, value: bool) -> None: ...
    def ToString(self) -> str: ...


class SentenceQuestionField:
    def __init__(self, primaryField: IWritableStringValue, fallbackField: IWritableStringValue) -> None: ...
    WordBreakTag : str
    def SplitTokenWithWordBreakTag(self, section: str) -> None: ...
    def WithInvisibleSpace(self) -> str: ...
    def WithoutInvisibleSpace(self) -> str: ...


class StripHtmlOnReadFallbackStringField:
    def __init__(self, primaryField: IStringValue, fallbackField: IStringValue) -> None: ...
    def Get(self) -> str: ...


class TagFlagField:
    def __init__(self, note: JPNote, tag: Tag) -> None: ...
    Tag : Tag
    def IsSet(self) -> bool: ...
    def SetTo(self, set: bool) -> None: ...
    def ToString(self) -> str: ...


class WritableAudioField(AudioField):
    def __init__(self, field: MutableStringField) -> None: ...
    def SetRawValue(self, value: str) -> None: ...


class WritableImageField(ImageField):
    def __init__(self, field: MutableStringField) -> None: ...
    def SetRawValue(self, value: str) -> None: ...


class WritableStringValue(IWritableStringValue):
    def __init__(self, getValue: Func_1[str], setValue: Action_1[str]) -> None: ...
    @property
    def Value(self) -> str: ...
    def Empty(self) -> None: ...
    def HasValue(self) -> bool: ...
    def OnChange(self, callback: Action) -> None: ...
    def Set(self, value: str) -> None: ...
    def ToString(self) -> str: ...

