import typing, abc
from JAStudio.Core.Note import JPNote, Tag
from System.Collections.Generic import List_1
from System import Action, Func_1
from Compze.Utilities.SystemCE import LazyCE_1

class AudioField:
    def __init__(self, note: JPNote, fieldName: str) -> None: ...
    def AudioFilesPaths(self) -> List_1[str]: ...
    def FirstAudioFilePath(self) -> str: ...
    def HasAudio(self) -> bool: ...
    def RawValue(self) -> str: ...
    def ToString(self) -> str: ...


class CachingMutableStringField:
    def __init__(self, note: JPNote, fieldName: str) -> None: ...
    @property
    def Value(self) -> str: ...
    def Empty(self) -> None: ...
    def HasValue(self) -> bool: ...
    def OnChange(self, callback: Action) -> None: ...
    def Set(self, value: str) -> None: ...
    def ToString(self) -> str: ...


class FallbackStringField:
    def __init__(self, primaryField: MutableStringField, fallbackField: MutableStringField) -> None: ...
    def Get(self) -> str: ...


class IntegerField:
    def __init__(self, note: JPNote, fieldName: str) -> None: ...
    def Get(self) -> int: ...
    def Set(self, value: int) -> None: ...


class IObjectSerializer_GenericClasses(abc.ABCMeta):
    Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T = typing.TypeVar('Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T')
    def __getitem__(self, types : typing.Type[Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T]) -> typing.Type[IObjectSerializer_1[Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T]]: ...

IObjectSerializer : IObjectSerializer_GenericClasses

IObjectSerializer_1_T = typing.TypeVar('IObjectSerializer_1_T')
class IObjectSerializer_1(typing.Generic[IObjectSerializer_1_T], typing.Protocol):
    @abc.abstractmethod
    def Deserialize(self, serialized: str) -> IObjectSerializer_1_T: ...
    @abc.abstractmethod
    def Serialize(self, instance: IObjectSerializer_1_T) -> str: ...


class MutableCommaSeparatedStringsListField:
    def __init__(self, note: JPNote, fieldName: str) -> None: ...
    def Add(self, add: str) -> None: ...
    def Get(self) -> List_1[str]: ...
    def RawStringValue(self) -> str: ...
    def Remove(self, remove: str) -> None: ...
    def Set(self, value: List_1[str]) -> None: ...
    def ToString(self) -> str: ...
    # Skipped LazyReader due to it being static, abstract and generic.

    LazyReader : LazyReader_MethodGroup
    class LazyReader_MethodGroup:
        def __getitem__(self, t:typing.Type[LazyReader_1_T1]) -> LazyReader_1[LazyReader_1_T1]: ...

        LazyReader_1_T1 = typing.TypeVar('LazyReader_1_T1')
        class LazyReader_1(typing.Generic[LazyReader_1_T1]):
            LazyReader_1_TValue = MutableCommaSeparatedStringsListField.LazyReader_MethodGroup.LazyReader_1_T1
            def __call__(self, reader: Func_1[LazyReader_1_TValue]) -> LazyCE_1[LazyReader_1_TValue]:...




class MutableCommaSeparatedStringsListFieldDeDuplicated(MutableCommaSeparatedStringsListField):
    def __init__(self, note: JPNote, fieldName: str) -> None: ...
    def Set(self, value: List_1[str]) -> None: ...


class MutableSerializedObjectField_GenericClasses(abc.ABCMeta):
    Generic_MutableSerializedObjectField_GenericClasses_MutableSerializedObjectField_1_T = typing.TypeVar('Generic_MutableSerializedObjectField_GenericClasses_MutableSerializedObjectField_1_T')
    def __getitem__(self, types : typing.Type[Generic_MutableSerializedObjectField_GenericClasses_MutableSerializedObjectField_1_T]) -> typing.Type[MutableSerializedObjectField_1[Generic_MutableSerializedObjectField_GenericClasses_MutableSerializedObjectField_1_T]]: ...

MutableSerializedObjectField : MutableSerializedObjectField_GenericClasses

MutableSerializedObjectField_1_T = typing.TypeVar('MutableSerializedObjectField_1_T')
class MutableSerializedObjectField_1(typing.Generic[MutableSerializedObjectField_1_T]):
    def __init__(self, note: JPNote, fieldName: str, serializer: IObjectSerializer_1[MutableSerializedObjectField_1_T]) -> None: ...
    def Get(self) -> MutableSerializedObjectField_1_T: ...
    def Save(self) -> None: ...
    def Set(self, value: MutableSerializedObjectField_1_T) -> None: ...
    def ToString(self) -> str: ...


class MutableStringField:
    def __init__(self, note: JPNote, fieldName: str) -> None: ...
    @property
    def Value(self) -> str: ...
    def Empty(self) -> None: ...
    def HasValue(self) -> bool: ...
    def Set(self, value: str) -> None: ...
    def ToString(self) -> str: ...


class RequireForbidFlagField:
    def __init__(self, note: JPNote, requiredWeight: int, forbiddenWeight: int, requiredTag: Tag, forbiddenTag: Tag) -> None: ...
    @property
    def ForbiddenWeight(self) -> int: ...
    @property
    def IsActive(self) -> bool: ...
    @property
    def IsConfiguredForbidden(self) -> bool: ...
    @property
    def IsConfiguredRequired(self) -> bool: ...
    @property
    def IsForbidden(self) -> bool: ...
    @property
    def IsRequired(self) -> bool: ...
    @property
    def MatchWeight(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def RequiredWeight(self) -> int: ...
    def SetForbidden(self, value: bool) -> None: ...
    def SetRequired(self, value: bool) -> None: ...
    def ToString(self) -> str: ...


class SentenceQuestionField:
    def __init__(self, primaryField: MutableStringField, fallbackField: MutableStringField) -> None: ...
    WordBreakTag : str
    def SplitTokenWithWordBreakTag(self, section: str) -> None: ...
    def WithInvisibleSpace(self) -> str: ...
    def WithoutInvisibleSpace(self) -> str: ...


class StripHtmlOnReadFallbackStringField:
    def __init__(self, primaryField: MutableStringField, fallbackField: MutableStringField) -> None: ...
    def Get(self) -> str: ...


class TagFlagField:
    def __init__(self, note: JPNote, tag: Tag) -> None: ...
    Tag : Tag
    def IsSet(self) -> bool: ...
    def SetTo(self, set: bool) -> None: ...
    def ToString(self) -> str: ...


class WritableAudioField(AudioField):
    def __init__(self, note: JPNote, fieldName: str) -> None: ...
    def SetRawValue(self, value: str) -> None: ...

