import typing, clr, abc
from System.Collections.Generic import List_1
from System import IEquatable_1, IObservable_1, IDisposable, IObserver_1
from JAStudio.Core.Note import JPNote, Tag, NoteGuard

class IObjectSerializer_GenericClasses(abc.ABCMeta):
    Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T = typing.TypeVar('Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T')
    def __getitem__(self, types : typing.Type[Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T]) -> typing.Type[IObjectSerializer_1[Generic_IObjectSerializer_GenericClasses_IObjectSerializer_1_T]]: ...

IObjectSerializer : IObjectSerializer_GenericClasses

IObjectSerializer_1_T = typing.TypeVar('IObjectSerializer_1_T')
class IObjectSerializer_1(typing.Generic[IObjectSerializer_1_T], typing.Protocol):
    @abc.abstractmethod
    def Deserialize(self, serialized: str) -> IObjectSerializer_1_T: ...
    @abc.abstractmethod
    def Serialize(self, instance: IObjectSerializer_1_T) -> str: ...


class IStringValue(typing.Protocol):
    @property
    def Value(self) -> str: ...


class IWritableStringValue(IStringValue, typing.Protocol):
    @abc.abstractmethod
    def Empty(self) -> None: ...
    @abc.abstractmethod
    def HasValue(self) -> bool: ...
    @abc.abstractmethod
    def Set(self, value: str) -> None: ...


class MediaFieldParsing(abc.ABC):
    @staticmethod
    def ParseAudioReferences(rawValue: str) -> List_1[MediaReference]: ...
    @staticmethod
    def ParseImageReferences(rawValue: str) -> List_1[MediaReference]: ...


class MediaReference(IEquatable_1[MediaReference]):
    def __init__(self, FileName: str, Type: MediaType) -> None: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> str: ...
    @property
    def Type(self) -> MediaType: ...
    @Type.setter
    def Type(self, value: MediaType) -> MediaType: ...
    def Deconstruct(self, FileName: clr.Reference[str], Type: clr.Reference[MediaType]) -> None: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: MediaReference, right: MediaReference) -> bool: ...
    def __ne__(self, left: MediaReference, right: MediaReference) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: MediaReference) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class MediaType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Audio : MediaType # 0
    Image : MediaType # 1


class RequireForbidFlagField:
    def __init__(self, note: JPNote, requiredWeight: int, forbiddenWeight: int, requiredTag: Tag, forbiddenTag: Tag) -> None: ...
    @property
    def ForbiddenWeight(self) -> int: ...
    @property
    def IsActive(self) -> bool: ...
    @property
    def IsConfiguredForbidden(self) -> bool: ...
    @property
    def IsConfiguredRequired(self) -> bool: ...
    @property
    def IsForbidden(self) -> bool: ...
    @property
    def IsRequired(self) -> bool: ...
    @property
    def MatchWeight(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def RequiredWeight(self) -> int: ...
    def SetForbidden(self, value: bool) -> None: ...
    def SetRequired(self, value: bool) -> None: ...
    def ToString(self) -> str: ...


class SentenceQuestionField:
    def __init__(self, primaryField: IWritableStringValue, fallbackField: IWritableStringValue) -> None: ...
    WordBreakTag : str
    def SplitTokenWithWordBreakTag(self, section: str) -> None: ...
    def WithInvisibleSpace(self) -> str: ...
    def WithoutInvisibleSpace(self) -> str: ...


class StripHtmlOnReadFallbackStringField:
    def __init__(self, primaryField: IStringValue, fallbackField: IStringValue) -> None: ...
    def Get(self) -> str: ...


class TagFlagField:
    def __init__(self, note: JPNote, tag: Tag) -> None: ...
    Tag : Tag
    def IsSet(self) -> bool: ...
    def SetTo(self, set: bool) -> None: ...
    def ToString(self) -> str: ...


class WritableImageValue:
    def __init__(self, initialValue: str, guard: NoteGuard) -> None: ...
    def GetMediaReferences(self) -> List_1[MediaReference]: ...
    def HasImage(self) -> bool: ...
    def ImageFilePaths(self) -> List_1[str]: ...
    def RawValue(self) -> str: ...
    def SetRawValue(self, value: str) -> None: ...
    def ToString(self) -> str: ...


class WritableStringValue(IWritableStringValue, IObservable_1[str]):
    def __init__(self, initialValue: str, guard: NoteGuard) -> None: ...
    @property
    def Value(self) -> str: ...
    @Value.setter
    def Value(self, value: str) -> str: ...
    def Empty(self) -> None: ...
    def HasValue(self) -> bool: ...
    def Set(self, value: str) -> None: ...
    def Subscribe(self, observer: IObserver_1[str]) -> IDisposable: ...
    def ToString(self) -> str: ...

