from System.Collections.Generic import IEnumerable_1
from JAStudio.Core.Note import NoteId, JPNote, VocabNote, KanjiNote

class QueryBuilder:
    def ExactMatches(self, question: str) -> str: ...
    def ExactMatchesNoSentences(self, question: str) -> str: ...
    def ExactMatchesNoSentencesReadingCards(self, question: str) -> str: ...
    def ImmersionKitSentences(self) -> str: ...
    def KanjiInString(self, text: str) -> str: ...
    def KanjiWithMeaning(self, search: str) -> str: ...
    def KanjiWithRadicalsInString(self, search: str) -> str: ...
    def KanjiWithReadingPart(self, readingPart: str) -> str: ...
    def NotesByIds(self, noteIds: IEnumerable_1[NoteId]) -> str: ...
    def NotesLookup(self, notes: IEnumerable_1[JPNote]) -> str: ...
    def OpenCardById(self, cardId: int) -> str: ...
    def PotentiallyMatchingSentencesForVocab(self, vocab: VocabNote) -> str: ...
    def SentenceSearch(self, word: str, exact: bool = ...) -> str: ...
    def SingleVocabByFormExact(self, form: str) -> str: ...
    def SingleVocabByFormExactReadCardOnly(self, form: str) -> str: ...
    def SingleVocabByQuestionReadingOrAnswerExact(self, search: str) -> str: ...
    def SingleVocabWildcard(self, form: str) -> str: ...
    def TextVocabLookup(self, text: str) -> str: ...
    def VocabDependenciesLookupQuery(self, vocab: VocabNote) -> str: ...
    def VocabsLookup(self, dictionaryForms: IEnumerable_1[str]) -> str: ...
    def VocabsLookupStrings(self, words: IEnumerable_1[str]) -> str: ...
    def VocabsLookupStringsReadCard(self, words: IEnumerable_1[str]) -> str: ...
    def VocabWithKanji(self, kanji: KanjiNote) -> str: ...

