from System.Collections.Generic import IEnumerable_1
from JAStudio.Core.Note import JPNote, VocabNote, KanjiNote

class QueryBuilder:
    @staticmethod
    def ExactMatches(question: str) -> str: ...
    @staticmethod
    def ExactMatchesNoSentences(question: str) -> str: ...
    @staticmethod
    def ExactMatchesNoSentencesReadingCards(question: str) -> str: ...
    @staticmethod
    def ImmersionKitSentences() -> str: ...
    @staticmethod
    def KanjiInString(text: str) -> str: ...
    @staticmethod
    def KanjiWithMeaning(search: str) -> str: ...
    @staticmethod
    def KanjiWithRadicalsInString(search: str) -> str: ...
    @staticmethod
    def KanjiWithReadingPart(readingPart: str) -> str: ...
    @staticmethod
    def NotesByIds(noteIds: IEnumerable_1[int]) -> str: ...
    @staticmethod
    def NotesLookup(notes: IEnumerable_1[JPNote]) -> str: ...
    @staticmethod
    def OpenCardById(cardId: int) -> str: ...
    @staticmethod
    def PotentiallyMatchingSentencesForVocab(vocab: VocabNote) -> str: ...
    @staticmethod
    def SentenceSearch(word: str, exact: bool = ...) -> str: ...
    @staticmethod
    def SingleVocabByFormExact(form: str) -> str: ...
    @staticmethod
    def SingleVocabByFormExactReadCardOnly(form: str) -> str: ...
    @staticmethod
    def SingleVocabByQuestionReadingOrAnswerExact(search: str) -> str: ...
    @staticmethod
    def SingleVocabWildcard(form: str) -> str: ...
    @staticmethod
    def TextVocabLookup(text: str) -> str: ...
    @staticmethod
    def VocabDependenciesLookupQuery(vocab: VocabNote) -> str: ...
    @staticmethod
    def VocabsLookup(dictionaryForms: IEnumerable_1[str]) -> str: ...
    @staticmethod
    def VocabsLookupStrings(words: IEnumerable_1[str]) -> str: ...
    @staticmethod
    def VocabsLookupStringsReadCard(words: IEnumerable_1[str]) -> str: ...
    @staticmethod
    def VocabWithKanji(kanji: KanjiNote) -> str: ...

