import typing, abc
from System.Collections.Generic import HashSet_1
from JAStudio.Core.Note.NoteFields import MutableSerializedObjectField_1

class FieldSetWrapper_GenericClasses(abc.ABCMeta):
    Generic_FieldSetWrapper_GenericClasses_FieldSetWrapper_1_TValue = typing.TypeVar('Generic_FieldSetWrapper_GenericClasses_FieldSetWrapper_1_TValue')
    def __getitem__(self, types : typing.Type[Generic_FieldSetWrapper_GenericClasses_FieldSetWrapper_1_TValue]) -> typing.Type[FieldSetWrapper_1[Generic_FieldSetWrapper_GenericClasses_FieldSetWrapper_1_TValue]]: ...

FieldSetWrapper : FieldSetWrapper_GenericClasses

FieldSetWrapper_1_TValue = typing.TypeVar('FieldSetWrapper_1_TValue')
class FieldSetWrapper_1(typing.Generic[FieldSetWrapper_1_TValue]):
    def Add(self, value: FieldSetWrapper_1_TValue) -> None: ...
    def Any(self) -> bool: ...
    def Clear(self) -> None: ...
    def Discard(self, key: FieldSetWrapper_1_TValue) -> None: ...
    def Get(self) -> HashSet_1[FieldSetWrapper_1_TValue]: ...
    def None(self) -> bool: ...
    def OverwriteWith(self, other: FieldSetWrapper_1[FieldSetWrapper_1_TValue]) -> None: ...
    def Remove(self, key: FieldSetWrapper_1_TValue) -> None: ...
    def ToString(self) -> str: ...
    # Skipped ForJsonObjectField due to it being static, abstract and generic.

    ForJsonObjectField : ForJsonObjectField_MethodGroup[FieldSetWrapper_1_TValue]
    ForJsonObjectField_MethodGroup_FieldSetWrapper_1_TValue = typing.TypeVar('ForJsonObjectField_MethodGroup_FieldSetWrapper_1_TValue')
    class ForJsonObjectField_MethodGroup(typing.Generic[ForJsonObjectField_MethodGroup_FieldSetWrapper_1_TValue]):
        ForJsonObjectField_MethodGroup_FieldSetWrapper_1_TValue = FieldSetWrapper_1.ForJsonObjectField_MethodGroup_FieldSetWrapper_1_TValue
        def __getitem__(self, t:typing.Type[ForJsonObjectField_1_T1]) -> ForJsonObjectField_1[ForJsonObjectField_MethodGroup_FieldSetWrapper_1_TValue, ForJsonObjectField_1_T1]: ...

        ForJsonObjectField_1_FieldSetWrapper_1_TValue = typing.TypeVar('ForJsonObjectField_1_FieldSetWrapper_1_TValue')
        ForJsonObjectField_1_T1 = typing.TypeVar('ForJsonObjectField_1_T1')
        class ForJsonObjectField_1(typing.Generic[ForJsonObjectField_1_FieldSetWrapper_1_TValue, ForJsonObjectField_1_T1]):
            ForJsonObjectField_1_FieldSetWrapper_1_TValue = FieldSetWrapper_1.ForJsonObjectField_MethodGroup.ForJsonObjectField_1_FieldSetWrapper_1_TValue
            ForJsonObjectField_1_TWrapper = FieldSetWrapper_1.ForJsonObjectField_MethodGroup.ForJsonObjectField_1_T1
            def __call__(self, field: MutableSerializedObjectField_1[ForJsonObjectField_1_TWrapper], value: HashSet_1[ForJsonObjectField_1_FieldSetWrapper_1_TValue]) -> FieldSetWrapper_1[ForJsonObjectField_1_FieldSetWrapper_1_TValue]:...




class FieldWrapper_GenericClasses(abc.ABCMeta):
    Generic_FieldWrapper_GenericClasses_FieldWrapper_2_TValue = typing.TypeVar('Generic_FieldWrapper_GenericClasses_FieldWrapper_2_TValue')
    Generic_FieldWrapper_GenericClasses_FieldWrapper_2_TWrapper = typing.TypeVar('Generic_FieldWrapper_GenericClasses_FieldWrapper_2_TWrapper')
    def __getitem__(self, types : typing.Tuple[typing.Type[Generic_FieldWrapper_GenericClasses_FieldWrapper_2_TValue], typing.Type[Generic_FieldWrapper_GenericClasses_FieldWrapper_2_TWrapper]]) -> typing.Type[FieldWrapper_2[Generic_FieldWrapper_GenericClasses_FieldWrapper_2_TValue, Generic_FieldWrapper_GenericClasses_FieldWrapper_2_TWrapper]]: ...

FieldWrapper : FieldWrapper_GenericClasses

FieldWrapper_2_TValue = typing.TypeVar('FieldWrapper_2_TValue')
FieldWrapper_2_TWrapper = typing.TypeVar('FieldWrapper_2_TWrapper')
class FieldWrapper_2(typing.Generic[FieldWrapper_2_TValue, FieldWrapper_2_TWrapper]):
    def __init__(self, field: MutableSerializedObjectField_1[FieldWrapper_2_TWrapper], value: ValueWrapper_1[FieldWrapper_2_TValue]) -> None: ...
    def Get(self) -> FieldWrapper_2_TValue: ...
    def Set(self, value: FieldWrapper_2_TValue) -> None: ...
    def ToString(self) -> str: ...


class ValueWrapper_GenericClasses(abc.ABCMeta):
    Generic_ValueWrapper_GenericClasses_ValueWrapper_1_TValue = typing.TypeVar('Generic_ValueWrapper_GenericClasses_ValueWrapper_1_TValue')
    def __getitem__(self, types : typing.Type[Generic_ValueWrapper_GenericClasses_ValueWrapper_1_TValue]) -> typing.Type[ValueWrapper_1[Generic_ValueWrapper_GenericClasses_ValueWrapper_1_TValue]]: ...

ValueWrapper : ValueWrapper_GenericClasses

ValueWrapper_1_TValue = typing.TypeVar('ValueWrapper_1_TValue')
class ValueWrapper_1(typing.Generic[ValueWrapper_1_TValue]):
    def __init__(self, value: ValueWrapper_1_TValue) -> None: ...
    def Get(self) -> ValueWrapper_1_TValue: ...
    def Set(self, value: ValueWrapper_1_TValue) -> None: ...
    def ToString(self) -> str: ...

