import typing, abc

class ValueWrapper_GenericClasses(abc.ABCMeta):
    Generic_ValueWrapper_GenericClasses_ValueWrapper_1_TValue = typing.TypeVar('Generic_ValueWrapper_GenericClasses_ValueWrapper_1_TValue')
    def __getitem__(self, types : typing.Type[Generic_ValueWrapper_GenericClasses_ValueWrapper_1_TValue]) -> typing.Type[ValueWrapper_1[Generic_ValueWrapper_GenericClasses_ValueWrapper_1_TValue]]: ...

ValueWrapper : ValueWrapper_GenericClasses

ValueWrapper_1_TValue = typing.TypeVar('ValueWrapper_1_TValue')
class ValueWrapper_1(typing.Generic[ValueWrapper_1_TValue]):
    def __init__(self, value: ValueWrapper_1_TValue) -> None: ...
    def Get(self) -> ValueWrapper_1_TValue: ...
    def Set(self, value: ValueWrapper_1_TValue) -> None: ...
    def ToString(self) -> str: ...

