import typing, clr
from CommunityToolkit.Mvvm.ComponentModel import ObservableObject
from System.Collections.Generic import List_1
from CommunityToolkit.Mvvm.Input import IRelayCommand
from System import IEquatable_1
from JAStudio.Core.Note import NoteId

class EditableImportRule(ObservableObject):
    def __init__(self) -> None: ...
    @classmethod
    @property
    def CopyrightOptions(cls) -> List_1[str]: ...
    @property
    def IsValid(self) -> bool: ...
    @property
    def MatchCount(self) -> int: ...
    @MatchCount.setter
    def MatchCount(self, value: int) -> int: ...
    @property
    def RemoveSelfCommand(self) -> IRelayCommand: ...
    @RemoveSelfCommand.setter
    def RemoveSelfCommand(self, value: IRelayCommand) -> IRelayCommand: ...
    @property
    def SelectedCopyright(self) -> str: ...
    @SelectedCopyright.setter
    def SelectedCopyright(self, value: str) -> str: ...
    @property
    def SelectedField(self) -> str: ...
    @SelectedField.setter
    def SelectedField(self, value: str) -> str: ...
    @property
    def SourceTagPrefix(self) -> str: ...
    @SourceTagPrefix.setter
    def SourceTagPrefix(self, value: str) -> str: ...
    @property
    def TargetDirectory(self) -> str: ...
    @TargetDirectory.setter
    def TargetDirectory(self, value: str) -> str: ...


class MissingFileRow(IEquatable_1[MissingFileRow]):
    def __init__(self, Question: str, NoteIdDisplay: str, FieldName: str, FileName: str, NoteId: NoteId) -> None: ...
    @property
    def FieldName(self) -> str: ...
    @FieldName.setter
    def FieldName(self, value: str) -> str: ...
    @property
    def FileName(self) -> str: ...
    @FileName.setter
    def FileName(self, value: str) -> str: ...
    @property
    def NoteId(self) -> NoteId: ...
    @NoteId.setter
    def NoteId(self, value: NoteId) -> NoteId: ...
    @property
    def NoteIdDisplay(self) -> str: ...
    @NoteIdDisplay.setter
    def NoteIdDisplay(self, value: str) -> str: ...
    @property
    def Question(self) -> str: ...
    @Question.setter
    def Question(self, value: str) -> str: ...
    def Deconstruct(self, Question: clr.Reference[str], NoteIdDisplay: clr.Reference[str], FieldName: clr.Reference[str], FileName: clr.Reference[str], NoteId: clr.Reference[NoteId]) -> None: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: MissingFileRow, right: MissingFileRow) -> bool: ...
    def __ne__(self, left: MissingFileRow, right: MissingFileRow) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: MissingFileRow) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class UnmappedMediaGroup(IEquatable_1[UnmappedMediaGroup]):
    def __init__(self, SourcePrefix: str, FieldName: str, FileCount: int) -> None: ...
    @property
    def FieldName(self) -> str: ...
    @FieldName.setter
    def FieldName(self, value: str) -> str: ...
    @property
    def FileCount(self) -> int: ...
    @FileCount.setter
    def FileCount(self, value: int) -> int: ...
    @property
    def SourcePrefix(self) -> str: ...
    @SourcePrefix.setter
    def SourcePrefix(self, value: str) -> str: ...
    def Deconstruct(self, SourcePrefix: clr.Reference[str], FieldName: clr.Reference[str], FileCount: clr.Reference[int]) -> None: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: UnmappedMediaGroup, right: UnmappedMediaGroup) -> bool: ...
    def __ne__(self, left: UnmappedMediaGroup, right: UnmappedMediaGroup) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: UnmappedMediaGroup) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...


