from CommunityToolkit.Mvvm.ComponentModel import ObservableObject
from JAStudio.Core.Note import VocabNote
from CommunityToolkit.Mvvm.Input import IRelayCommand

class VocabFlagsViewModel(ObservableObject):
    def __init__(self, vocab: VocabNote) -> None: ...
    @property
    def Archaic(self) -> bool: ...
    @Archaic.setter
    def Archaic(self, value: bool) -> bool: ...
    @property
    def CancelCommand(self) -> IRelayCommand: ...
    @property
    def Childish(self) -> bool: ...
    @Childish.setter
    def Childish(self, value: bool) -> bool: ...
    @property
    def Derogatory(self) -> bool: ...
    @Derogatory.setter
    def Derogatory(self, value: bool) -> bool: ...
    @property
    def Formal(self) -> bool: ...
    @Formal.setter
    def Formal(self, value: bool) -> bool: ...
    @property
    def Honorific(self) -> bool: ...
    @Honorific.setter
    def Honorific(self, value: bool) -> bool: ...
    @property
    def Humble(self) -> bool: ...
    @Humble.setter
    def Humble(self, value: bool) -> bool: ...
    @property
    def Informal(self) -> bool: ...
    @Informal.setter
    def Informal(self, value: bool) -> bool: ...
    @property
    def IsCompositionallyTransparentCompound(self) -> bool: ...
    @IsCompositionallyTransparentCompound.setter
    def IsCompositionallyTransparentCompound(self, value: bool) -> bool: ...
    @property
    def IsInflectingWord(self) -> bool: ...
    @IsInflectingWord.setter
    def IsInflectingWord(self, value: bool) -> bool: ...
    @property
    def IsPoisonWord(self) -> bool: ...
    @IsPoisonWord.setter
    def IsPoisonWord(self, value: bool) -> bool: ...
    @property
    def Literary(self) -> bool: ...
    @Literary.setter
    def Literary(self, value: bool) -> bool: ...
    @property
    def MatchWithPrecedingVowel(self) -> bool: ...
    @MatchWithPrecedingVowel.setter
    def MatchWithPrecedingVowel(self, value: bool) -> bool: ...
    @property
    def Polite(self) -> bool: ...
    @Polite.setter
    def Polite(self, value: bool) -> bool: ...
    @property
    def QuestionOverridesForm(self) -> bool: ...
    @QuestionOverridesForm.setter
    def QuestionOverridesForm(self, value: bool) -> bool: ...
    @property
    def RoughMasculine(self) -> bool: ...
    @RoughMasculine.setter
    def RoughMasculine(self, value: bool) -> bool: ...
    @property
    def SaveCommand(self) -> IRelayCommand: ...
    @property
    def Sensitive(self) -> bool: ...
    @Sensitive.setter
    def Sensitive(self, value: bool) -> bool: ...
    @property
    def Slang(self) -> bool: ...
    @Slang.setter
    def Slang(self, value: bool) -> bool: ...
    @property
    def SoftFeminine(self) -> bool: ...
    @SoftFeminine.setter
    def SoftFeminine(self, value: bool) -> bool: ...
    @property
    def Title(self) -> str: ...
    @property
    def Vulgar(self) -> bool: ...
    @Vulgar.setter
    def Vulgar(self, value: bool) -> bool: ...

