import typing
from CommunityToolkit.Mvvm.ComponentModel import ObservableObject
from System.Collections.ObjectModel import ObservableCollection_1
from JAStudio.Core.Note import KanjiNote, JPNote, NoteId, SentenceNote, VocabNote
from CommunityToolkit.Mvvm.Input import IRelayCommand, AsyncRelayCommand, RelayCommand, IAsyncRelayCommand
from JAStudio.Core import TemporaryServiceCollection
from Avalonia.Controls import Window
from JAStudio.UI.Controls import RequireForbidControlViewModel, StringSetControlViewModel
from System.Threading.Tasks import Task

class EnglishWordResultViewModel:
    def __init__(self, word: str, definition: str) -> None: ...
    @property
    def Definition(self) -> str: ...
    @property
    def Word(self) -> str: ...


class EnglishWordSearchDialogViewModel(ObservableObject):
    def __init__(self) -> None: ...
    @property
    def Results(self) -> ObservableCollection_1[EnglishWordResultViewModel]: ...
    @property
    def SearchText(self) -> str: ...
    @SearchText.setter
    def SearchText(self, value: str) -> str: ...
    @property
    def SelectedResult(self) -> EnglishWordResultViewModel: ...
    @SelectedResult.setter
    def SelectedResult(self, value: EnglishWordResultViewModel) -> EnglishWordResultViewModel: ...
    def OpenInGoogle(self) -> None: ...
    def OpenInMerriamWebster(self) -> None: ...
    def OpenInOED(self) -> None: ...


class KanjiEditorViewModel(ObservableObject):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, kanji: KanjiNote) -> None: ...
    @property
    def CancelCommand(self) -> IRelayCommand: ...
    @CancelCommand.setter
    def CancelCommand(self, value: IRelayCommand) -> IRelayCommand: ...
    @property
    def ConfusedWith(self) -> str: ...
    @ConfusedWith.setter
    def ConfusedWith(self, value: str) -> str: ...
    @property
    def PrimaryVocab(self) -> str: ...
    @PrimaryVocab.setter
    def PrimaryVocab(self, value: str) -> str: ...
    @property
    def Question(self) -> str: ...
    @Question.setter
    def Question(self, value: str) -> str: ...
    @property
    def Radicals(self) -> str: ...
    @Radicals.setter
    def Radicals(self, value: str) -> str: ...
    @property
    def ReadingKun(self) -> str: ...
    @ReadingKun.setter
    def ReadingKun(self, value: str) -> str: ...
    @property
    def ReadingNan(self) -> str: ...
    @ReadingNan.setter
    def ReadingNan(self, value: str) -> str: ...
    @property
    def ReadingOn(self) -> str: ...
    @ReadingOn.setter
    def ReadingOn(self, value: str) -> str: ...
    @property
    def SaveCommand(self) -> IRelayCommand: ...
    @SaveCommand.setter
    def SaveCommand(self, value: IRelayCommand) -> IRelayCommand: ...
    @property
    def SimilarMeaning(self) -> str: ...
    @SimilarMeaning.setter
    def SimilarMeaning(self, value: str) -> str: ...
    @property
    def SourceAnswer(self) -> str: ...
    @SourceAnswer.setter
    def SourceAnswer(self, value: str) -> str: ...
    @property
    def SourceMeaningMnemonic(self) -> str: ...
    @SourceMeaningMnemonic.setter
    def SourceMeaningMnemonic(self, value: str) -> str: ...
    @property
    def Title(self) -> str: ...
    @property
    def UserAnswer(self) -> str: ...
    @UserAnswer.setter
    def UserAnswer(self, value: str) -> str: ...
    @property
    def UserMnemonic(self) -> str: ...
    @UserMnemonic.setter
    def UserMnemonic(self, value: str) -> str: ...
    def Save(self) -> None: ...


class NoteSearchDialogViewModel(ObservableObject):
    def __init__(self, services: TemporaryServiceCollection) -> None: ...
    @property
    def IsSearching(self) -> bool: ...
    @IsSearching.setter
    def IsSearching(self, value: bool) -> bool: ...
    @property
    def Results(self) -> ObservableCollection_1[NoteSearchResultViewModel]: ...
    @property
    def SearchCommand(self) -> AsyncRelayCommand: ...
    @property
    def SearchText(self) -> str: ...
    @SearchText.setter
    def SearchText(self, value: str) -> str: ...
    @property
    def SelectedResult(self) -> NoteSearchResultViewModel: ...
    @SelectedResult.setter
    def SelectedResult(self, value: NoteSearchResultViewModel) -> NoteSearchResultViewModel: ...
    @property
    def StatusText(self) -> str: ...
    @StatusText.setter
    def StatusText(self, value: str) -> str: ...
    def OpenSelectedNote(self) -> None: ...


class NoteSearchResultViewModel:
    def __init__(self, note: JPNote) -> None: ...
    @property
    def Answer(self) -> str: ...
    @property
    def NoteId(self) -> NoteId: ...
    @property
    def NoteType(self) -> str: ...
    @property
    def Question(self) -> str: ...


class OptionsDialogViewModel(ObservableObject):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, window: Window, services: TemporaryServiceCollection) -> None: ...
    @property
    def AnkiInternalFsrsSetEnableFsrsShortTermWithSteps(self) -> bool: ...
    @AnkiInternalFsrsSetEnableFsrsShortTermWithSteps.setter
    def AnkiInternalFsrsSetEnableFsrsShortTermWithSteps(self, value: bool) -> bool: ...
    @property
    def AutoadvanceSentenceHiraganaSeconds(self) -> float: ...
    @AutoadvanceSentenceHiraganaSeconds.setter
    def AutoadvanceSentenceHiraganaSeconds(self, value: float) -> float: ...
    @property
    def AutoadvanceSentenceKanjiSeconds(self) -> float: ...
    @AutoadvanceSentenceKanjiSeconds.setter
    def AutoadvanceSentenceKanjiSeconds(self, value: float) -> float: ...
    @property
    def AutoadvanceSentenceKatakanaSeconds(self) -> float: ...
    @AutoadvanceSentenceKatakanaSeconds.setter
    def AutoadvanceSentenceKatakanaSeconds(self, value: float) -> float: ...
    @property
    def AutoadvanceSentenceStartingSeconds(self) -> float: ...
    @AutoadvanceSentenceStartingSeconds.setter
    def AutoadvanceSentenceStartingSeconds(self, value: float) -> float: ...
    @property
    def AutoadvanceVocabHiraganaSeconds(self) -> float: ...
    @AutoadvanceVocabHiraganaSeconds.setter
    def AutoadvanceVocabHiraganaSeconds(self, value: float) -> float: ...
    @property
    def AutoadvanceVocabKanjiSeconds(self) -> float: ...
    @AutoadvanceVocabKanjiSeconds.setter
    def AutoadvanceVocabKanjiSeconds(self, value: float) -> float: ...
    @property
    def AutoadvanceVocabKatakanaSeconds(self) -> float: ...
    @AutoadvanceVocabKatakanaSeconds.setter
    def AutoadvanceVocabKatakanaSeconds(self, value: float) -> float: ...
    @property
    def AutoadvanceVocabStartingSeconds(self) -> float: ...
    @AutoadvanceVocabStartingSeconds.setter
    def AutoadvanceVocabStartingSeconds(self, value: float) -> float: ...
    @property
    def AutomaticallyYieldLastTokenInCausativeVerbCompoundsToOverlappingCompound(self) -> bool: ...
    @AutomaticallyYieldLastTokenInCausativeVerbCompoundsToOverlappingCompound.setter
    def AutomaticallyYieldLastTokenInCausativeVerbCompoundsToOverlappingCompound(self, value: bool) -> bool: ...
    @property
    def AutomaticallyYieldLastTokenInPassiveVerbCompoundsToOverlappingCompound(self) -> bool: ...
    @AutomaticallyYieldLastTokenInPassiveVerbCompoundsToOverlappingCompound.setter
    def AutomaticallyYieldLastTokenInPassiveVerbCompoundsToOverlappingCompound(self, value: bool) -> bool: ...
    @property
    def AutomaticallyYieldLastTokenInSuruVerbCompoundsToOverlappingCompound(self) -> bool: ...
    @AutomaticallyYieldLastTokenInSuruVerbCompoundsToOverlappingCompound.setter
    def AutomaticallyYieldLastTokenInSuruVerbCompoundsToOverlappingCompound(self, value: bool) -> bool: ...
    @property
    def BoostFailedCardAllowedTime(self) -> bool: ...
    @BoostFailedCardAllowedTime.setter
    def BoostFailedCardAllowedTime(self, value: bool) -> bool: ...
    @property
    def BoostFailedCardAllowedTimeByFactor(self) -> float: ...
    @BoostFailedCardAllowedTimeByFactor.setter
    def BoostFailedCardAllowedTimeByFactor(self, value: float) -> float: ...
    @property
    def CloseCommand(self) -> IRelayCommand: ...
    @property
    def DecreaseFailedCardIntervals(self) -> bool: ...
    @DecreaseFailedCardIntervals.setter
    def DecreaseFailedCardIntervals(self, value: bool) -> bool: ...
    @property
    def DecreaseFailedCardIntervalsInterval(self) -> int: ...
    @DecreaseFailedCardIntervalsInterval.setter
    def DecreaseFailedCardIntervalsInterval(self, value: int) -> int: ...
    @property
    def DisableAllAutomaticGarbageCollection(self) -> bool: ...
    @DisableAllAutomaticGarbageCollection.setter
    def DisableAllAutomaticGarbageCollection(self, value: bool) -> bool: ...
    @property
    def EnableAutomaticGarbageCollection(self) -> bool: ...
    @EnableAutomaticGarbageCollection.setter
    def EnableAutomaticGarbageCollection(self, value: bool) -> bool: ...
    @property
    def EnableGarbageCollectionDuringBatches(self) -> bool: ...
    @EnableGarbageCollectionDuringBatches.setter
    def EnableGarbageCollectionDuringBatches(self, value: bool) -> bool: ...
    @property
    def EnableTraceMalloc(self) -> bool: ...
    @EnableTraceMalloc.setter
    def EnableTraceMalloc(self, value: bool) -> bool: ...
    @property
    def HideAllCompounds(self) -> bool: ...
    @HideAllCompounds.setter
    def HideAllCompounds(self, value: bool) -> bool: ...
    @property
    def HideCompositionallyTransparentCompounds(self) -> bool: ...
    @HideCompositionallyTransparentCompounds.setter
    def HideCompositionallyTransparentCompounds(self, value: bool) -> bool: ...
    @property
    def LoadJamdictDbIntoMemory(self) -> bool: ...
    @LoadJamdictDbIntoMemory.setter
    def LoadJamdictDbIntoMemory(self, value: bool) -> bool: ...
    @property
    def LoadNotesFromFileSystem(self) -> bool: ...
    @LoadNotesFromFileSystem.setter
    def LoadNotesFromFileSystem(self, value: bool) -> bool: ...
    @property
    def LoadStudioInForeground(self) -> bool: ...
    @LoadStudioInForeground.setter
    def LoadStudioInForeground(self, value: bool) -> bool: ...
    @property
    def LogWhenFlushingNotes(self) -> bool: ...
    @LogWhenFlushingNotes.setter
    def LogWhenFlushingNotes(self, value: bool) -> bool: ...
    @property
    def MinimumTimeViewingAnswer(self) -> float: ...
    @MinimumTimeViewingAnswer.setter
    def MinimumTimeViewingAnswer(self, value: float) -> float: ...
    @property
    def MinimumTimeViewingQuestion(self) -> float: ...
    @MinimumTimeViewingQuestion.setter
    def MinimumTimeViewingQuestion(self, value: float) -> float: ...
    @property
    def PreCacheCardStudyingStatus(self) -> bool: ...
    @PreCacheCardStudyingStatus.setter
    def PreCacheCardStudyingStatus(self, value: bool) -> bool: ...
    @property
    def PreferDefaultMnemonicsToSourceMnemonics(self) -> bool: ...
    @PreferDefaultMnemonicsToSourceMnemonics.setter
    def PreferDefaultMnemonicsToSourceMnemonics(self, value: bool) -> bool: ...
    @property
    def PreventAnkiFromGarbageCollectingEveryTimeAWindowCloses(self) -> bool: ...
    @PreventAnkiFromGarbageCollectingEveryTimeAWindowCloses.setter
    def PreventAnkiFromGarbageCollectingEveryTimeAWindowCloses(self, value: bool) -> bool: ...
    @property
    def PreventDoubleClicks(self) -> bool: ...
    @PreventDoubleClicks.setter
    def PreventDoubleClicks(self, value: bool) -> bool: ...
    @property
    def ReanalysisThreads(self) -> int: ...
    @ReanalysisThreads.setter
    def ReanalysisThreads(self, value: int) -> int: ...
    @property
    def ShowCompoundPartsInSentenceBreakdown(self) -> bool: ...
    @ShowCompoundPartsInSentenceBreakdown.setter
    def ShowCompoundPartsInSentenceBreakdown(self, value: bool) -> bool: ...
    @property
    def ShowKanjiInSentenceBreakdown(self) -> bool: ...
    @ShowKanjiInSentenceBreakdown.setter
    def ShowKanjiInSentenceBreakdown(self, value: bool) -> bool: ...
    @property
    def ShowKanjiMnemonicsInSentenceBreakdown(self) -> bool: ...
    @ShowKanjiMnemonicsInSentenceBreakdown.setter
    def ShowKanjiMnemonicsInSentenceBreakdown(self, value: bool) -> bool: ...
    @property
    def ShowSentenceBreakdownInEditMode(self) -> bool: ...
    @ShowSentenceBreakdownInEditMode.setter
    def ShowSentenceBreakdownInEditMode(self, value: bool) -> bool: ...
    @property
    def TimeboxKanjiRead(self) -> int: ...
    @TimeboxKanjiRead.setter
    def TimeboxKanjiRead(self, value: int) -> int: ...
    @property
    def TimeboxSentenceListen(self) -> int: ...
    @TimeboxSentenceListen.setter
    def TimeboxSentenceListen(self, value: int) -> int: ...
    @property
    def TimeboxSentenceRead(self) -> int: ...
    @TimeboxSentenceRead.setter
    def TimeboxSentenceRead(self, value: int) -> int: ...
    @property
    def TimeboxVocabListen(self) -> int: ...
    @TimeboxVocabListen.setter
    def TimeboxVocabListen(self, value: int) -> int: ...
    @property
    def TimeboxVocabRead(self) -> int: ...
    @TimeboxVocabRead.setter
    def TimeboxVocabRead(self, value: int) -> int: ...
    @property
    def TrackInstancesInMemory(self) -> bool: ...
    @TrackInstancesInMemory.setter
    def TrackInstancesInMemory(self, value: bool) -> bool: ...
    @property
    def YomitanIntegrationCopyAnswerToClipboard(self) -> bool: ...
    @YomitanIntegrationCopyAnswerToClipboard.setter
    def YomitanIntegrationCopyAnswerToClipboard(self, value: bool) -> bool: ...


class ReadingsMappingsDialogViewModel(ObservableObject):
    def __init__(self, window: Window, services: TemporaryServiceCollection) -> None: ...
    @property
    def CancelCommand(self) -> RelayCommand: ...
    @property
    def MappingsText(self) -> str: ...
    @MappingsText.setter
    def MappingsText(self, value: str) -> str: ...
    @property
    def SaveCommand(self) -> RelayCommand: ...
    @property
    def SearchText(self) -> str: ...
    @SearchText.setter
    def SearchText(self, value: str) -> str: ...


class SentenceEditorViewModel(ObservableObject):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, sentence: SentenceNote) -> None: ...
    @property
    def CancelCommand(self) -> IRelayCommand: ...
    @CancelCommand.setter
    def CancelCommand(self, value: IRelayCommand) -> IRelayCommand: ...
    @property
    def Reading(self) -> str: ...
    @Reading.setter
    def Reading(self, value: str) -> str: ...
    @property
    def SaveCommand(self) -> IRelayCommand: ...
    @SaveCommand.setter
    def SaveCommand(self, value: IRelayCommand) -> IRelayCommand: ...
    @property
    def SourceAnswer(self) -> str: ...
    @SourceAnswer.setter
    def SourceAnswer(self, value: str) -> str: ...
    @property
    def SourceComments(self) -> str: ...
    @SourceComments.setter
    def SourceComments(self, value: str) -> str: ...
    @property
    def SourceQuestion(self) -> str: ...
    @SourceQuestion.setter
    def SourceQuestion(self, value: str) -> str: ...
    @property
    def Title(self) -> str: ...
    @property
    def UserAnswer(self) -> str: ...
    @UserAnswer.setter
    def UserAnswer(self, value: str) -> str: ...
    @property
    def UserComments(self) -> str: ...
    @UserComments.setter
    def UserComments(self, value: str) -> str: ...
    @property
    def UserQuestion(self) -> str: ...
    @UserQuestion.setter
    def UserQuestion(self, value: str) -> str: ...
    def Save(self) -> None: ...


class VocabEditorViewModel(ObservableObject):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, vocab: VocabNote) -> None: ...
    @property
    def CancelCommand(self) -> IRelayCommand: ...
    @CancelCommand.setter
    def CancelCommand(self, value: IRelayCommand) -> IRelayCommand: ...
    @property
    def Forms(self) -> str: ...
    @Forms.setter
    def Forms(self, value: str) -> str: ...
    @property
    def PartsOfSpeech(self) -> str: ...
    @PartsOfSpeech.setter
    def PartsOfSpeech(self, value: str) -> str: ...
    @property
    def Question(self) -> str: ...
    @Question.setter
    def Question(self, value: str) -> str: ...
    @property
    def Readings(self) -> str: ...
    @Readings.setter
    def Readings(self, value: str) -> str: ...
    @property
    def SaveCommand(self) -> IRelayCommand: ...
    @SaveCommand.setter
    def SaveCommand(self, value: IRelayCommand) -> IRelayCommand: ...
    @property
    def SourceAnswer(self) -> str: ...
    @SourceAnswer.setter
    def SourceAnswer(self, value: str) -> str: ...
    @property
    def SourceMnemonic(self) -> str: ...
    @SourceMnemonic.setter
    def SourceMnemonic(self, value: str) -> str: ...
    @property
    def SourceReadingMnemonic(self) -> str: ...
    @SourceReadingMnemonic.setter
    def SourceReadingMnemonic(self, value: str) -> str: ...
    @property
    def Title(self) -> str: ...
    @property
    def UserAnswer(self) -> str: ...
    @UserAnswer.setter
    def UserAnswer(self, value: str) -> str: ...
    @property
    def UserCompounds(self) -> str: ...
    @UserCompounds.setter
    def UserCompounds(self, value: str) -> str: ...
    @property
    def UserExplanation(self) -> str: ...
    @UserExplanation.setter
    def UserExplanation(self, value: str) -> str: ...
    @property
    def UserExplanationLong(self) -> str: ...
    @UserExplanationLong.setter
    def UserExplanationLong(self, value: str) -> str: ...
    @property
    def UserMnemonic(self) -> str: ...
    @UserMnemonic.setter
    def UserMnemonic(self, value: str) -> str: ...
    def Save(self) -> None: ...


class VocabFlagsViewModel(ObservableObject):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, vocab: VocabNote, services: TemporaryServiceCollection, parentWindow: Window = ...) -> None: ...
    @property
    def Archaic(self) -> bool: ...
    @Archaic.setter
    def Archaic(self, value: bool) -> bool: ...
    @property
    def CancelCommand(self) -> IRelayCommand: ...
    @CancelCommand.setter
    def CancelCommand(self, value: IRelayCommand) -> IRelayCommand: ...
    @property
    def Childish(self) -> bool: ...
    @Childish.setter
    def Childish(self, value: bool) -> bool: ...
    @property
    def Derogatory(self) -> bool: ...
    @Derogatory.setter
    def Derogatory(self, value: bool) -> bool: ...
    @property
    def DictionaryFormPrefix(self) -> RequireForbidControlViewModel: ...
    @DictionaryFormPrefix.setter
    def DictionaryFormPrefix(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def DictionaryFormStem(self) -> RequireForbidControlViewModel: ...
    @DictionaryFormStem.setter
    def DictionaryFormStem(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def Formal(self) -> bool: ...
    @Formal.setter
    def Formal(self, value: bool) -> bool: ...
    @property
    def Godan(self) -> RequireForbidControlViewModel: ...
    @Godan.setter
    def Godan(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def GodanImperative(self) -> RequireForbidControlViewModel: ...
    @GodanImperative.setter
    def GodanImperative(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def GodanImperativePrefix(self) -> RequireForbidControlViewModel: ...
    @GodanImperativePrefix.setter
    def GodanImperativePrefix(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def GodanPotential(self) -> RequireForbidControlViewModel: ...
    @GodanPotential.setter
    def GodanPotential(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def Honorific(self) -> bool: ...
    @Honorific.setter
    def Honorific(self, value: bool) -> bool: ...
    @property
    def Humble(self) -> bool: ...
    @Humble.setter
    def Humble(self, value: bool) -> bool: ...
    @property
    def Ichidan(self) -> RequireForbidControlViewModel: ...
    @Ichidan.setter
    def Ichidan(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def IchidanImperative(self) -> RequireForbidControlViewModel: ...
    @IchidanImperative.setter
    def IchidanImperative(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def Informal(self) -> bool: ...
    @Informal.setter
    def Informal(self, value: bool) -> bool: ...
    @property
    def Irrealis(self) -> RequireForbidControlViewModel: ...
    @Irrealis.setter
    def Irrealis(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def IsCompositionallyTransparentCompound(self) -> bool: ...
    @IsCompositionallyTransparentCompound.setter
    def IsCompositionallyTransparentCompound(self, value: bool) -> bool: ...
    @property
    def IsInflectingWord(self) -> bool: ...
    @IsInflectingWord.setter
    def IsInflectingWord(self, value: bool) -> bool: ...
    @property
    def IsPoisonWord(self) -> bool: ...
    @IsPoisonWord.setter
    def IsPoisonWord(self, value: bool) -> bool: ...
    @property
    def Literary(self) -> bool: ...
    @Literary.setter
    def Literary(self, value: bool) -> bool: ...
    @property
    def MasuStem(self) -> RequireForbidControlViewModel: ...
    @MasuStem.setter
    def MasuStem(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def MatchWithPrecedingVowel(self) -> bool: ...
    @MatchWithPrecedingVowel.setter
    def MatchWithPrecedingVowel(self, value: bool) -> bool: ...
    @property
    def PastTenseStem(self) -> RequireForbidControlViewModel: ...
    @PastTenseStem.setter
    def PastTenseStem(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def Polite(self) -> bool: ...
    @Polite.setter
    def Polite(self, value: bool) -> bool: ...
    @property
    def PrecedingAdverb(self) -> RequireForbidControlViewModel: ...
    @PrecedingAdverb.setter
    def PrecedingAdverb(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def PrefixIsNot(self) -> StringSetControlViewModel: ...
    @PrefixIsNot.setter
    def PrefixIsNot(self, value: StringSetControlViewModel) -> StringSetControlViewModel: ...
    @property
    def QuestionOverridesForm(self) -> bool: ...
    @QuestionOverridesForm.setter
    def QuestionOverridesForm(self, value: bool) -> bool: ...
    @property
    def RequiredPrefix(self) -> StringSetControlViewModel: ...
    @RequiredPrefix.setter
    def RequiredPrefix(self, value: StringSetControlViewModel) -> StringSetControlViewModel: ...
    @property
    def RoughMasculine(self) -> bool: ...
    @RoughMasculine.setter
    def RoughMasculine(self, value: bool) -> bool: ...
    @property
    def SaveCommand(self) -> IAsyncRelayCommand: ...
    @SaveCommand.setter
    def SaveCommand(self, value: IAsyncRelayCommand) -> IAsyncRelayCommand: ...
    @property
    def Sensitive(self) -> bool: ...
    @Sensitive.setter
    def Sensitive(self, value: bool) -> bool: ...
    @property
    def SentenceEnd(self) -> RequireForbidControlViewModel: ...
    @SentenceEnd.setter
    def SentenceEnd(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def SentenceStart(self) -> RequireForbidControlViewModel: ...
    @SentenceStart.setter
    def SentenceStart(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def SingleToken(self) -> RequireForbidControlViewModel: ...
    @SingleToken.setter
    def SingleToken(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def Slang(self) -> bool: ...
    @Slang.setter
    def Slang(self, value: bool) -> bool: ...
    @property
    def SoftFeminine(self) -> bool: ...
    @SoftFeminine.setter
    def SoftFeminine(self, value: bool) -> bool: ...
    @property
    def SuffixIsNot(self) -> StringSetControlViewModel: ...
    @SuffixIsNot.setter
    def SuffixIsNot(self, value: StringSetControlViewModel) -> StringSetControlViewModel: ...
    @property
    def Surface(self) -> RequireForbidControlViewModel: ...
    @Surface.setter
    def Surface(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def SurfaceIsNot(self) -> StringSetControlViewModel: ...
    @SurfaceIsNot.setter
    def SurfaceIsNot(self, value: StringSetControlViewModel) -> StringSetControlViewModel: ...
    @property
    def TeFormPrefix(self) -> RequireForbidControlViewModel: ...
    @TeFormPrefix.setter
    def TeFormPrefix(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def TeFormStem(self) -> RequireForbidControlViewModel: ...
    @TeFormStem.setter
    def TeFormStem(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def Title(self) -> str: ...
    @property
    def Vulgar(self) -> bool: ...
    @Vulgar.setter
    def Vulgar(self, value: bool) -> bool: ...
    @property
    def YieldLastToken(self) -> RequireForbidControlViewModel: ...
    @YieldLastToken.setter
    def YieldLastToken(self, value: RequireForbidControlViewModel) -> RequireForbidControlViewModel: ...
    @property
    def YieldToSurface(self) -> StringSetControlViewModel: ...
    @YieldToSurface.setter
    def YieldToSurface(self, value: StringSetControlViewModel) -> StringSetControlViewModel: ...
    def SaveAsync(self) -> Task: ...

