import typing, clr, abc

class SwiftError:
    def __init__(self, value: clr.Reference[None]) -> None: ...
    @property
    def Value(self) -> clr.Reference[None]: ...


class SwiftIndirectResult:
    def __init__(self, value: clr.Reference[None]) -> None: ...
    @property
    def Value(self) -> clr.Reference[None]: ...


class SwiftSelf_GenericClasses(abc.ABCMeta):
    Generic_SwiftSelf_GenericClasses_SwiftSelf_1_T = typing.TypeVar('Generic_SwiftSelf_GenericClasses_SwiftSelf_1_T')
    def __getitem__(self, types : typing.Type[Generic_SwiftSelf_GenericClasses_SwiftSelf_1_T]) -> typing.Type[SwiftSelf_1[Generic_SwiftSelf_GenericClasses_SwiftSelf_1_T]]: ...

class SwiftSelf(SwiftSelf_0, metaclass =SwiftSelf_GenericClasses): ...

class SwiftSelf_0:
    def __init__(self, value: clr.Reference[None]) -> None: ...
    @property
    def Value(self) -> clr.Reference[None]: ...


SwiftSelf_1_T = typing.TypeVar('SwiftSelf_1_T')
class SwiftSelf_1(typing.Generic[SwiftSelf_1_T]):
    def __init__(self, value: SwiftSelf_1_T) -> None: ...
    @property
    def Value(self) -> SwiftSelf_1_T: ...

