import typing, clr, abc
from System import IEquatable_1, Array_1, ReadOnlyMemory_1, IDisposable
from Avalonia import Vector, Rect, Point
from Avalonia.Media import FlowDirection, DrawingContext, CharacterHit, IBrush, BaselineAlignment, FontFeatureCollection, TextDecorationCollection, Typeface
from System.Collections.Generic import IList_1, IReadOnlyList_1
from System.Globalization import CultureInfo

class GlyphInfo(IEquatable_1[GlyphInfo]):
    def __init__(self, GlyphIndex: int, GlyphCluster: int, GlyphAdvance: float, GlyphOffset: Vector = ...) -> None: ...
    @property
    def GlyphAdvance(self) -> float: ...
    @property
    def GlyphCluster(self) -> int: ...
    @property
    def GlyphIndex(self) -> int: ...
    @property
    def GlyphOffset(self) -> Vector: ...
    def Deconstruct(self, GlyphIndex: clr.Reference[int], GlyphCluster: clr.Reference[int], GlyphAdvance: clr.Reference[float], GlyphOffset: clr.Reference[Vector]) -> None: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: GlyphInfo, right: GlyphInfo) -> bool: ...
    def __ne__(self, left: GlyphInfo, right: GlyphInfo) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: GlyphInfo) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class JustificationProperties(abc.ABC):
    @property
    def Width(self) -> float: ...
    @abc.abstractmethod
    def Justify(self, textLine: TextLine) -> None: ...


class TextBounds:
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @property
    def Rectangle(self) -> Rect: ...
    @Rectangle.setter
    def Rectangle(self, value: Rect) -> Rect: ...
    @property
    def TextRunBounds(self) -> IList_1[TextRunBounds]: ...


class TextCollapsingProperties(abc.ABC):
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @property
    def Symbol(self) -> TextRun: ...
    @property
    def Width(self) -> float: ...
    @abc.abstractmethod
    def Collapse(self, textLine: TextLine) -> Array_1[TextRun]: ...
    @staticmethod
    def CreateCollapsedRuns(textLine: TextLine, collapsedLength: int, flowDirection: FlowDirection, shapedSymbol: TextRun) -> Array_1[TextRun]: ...


class TextEndOfLine(TextRun):
    def __init__(self, textSourceLength: int = ...) -> None: ...
    @property
    def Length(self) -> int: ...
    @property
    def Properties(self) -> TextRunProperties: ...
    @property
    def Text(self) -> ReadOnlyMemory_1[str]: ...


class TextLine(IDisposable, abc.ABC):
    @property
    def Baseline(self) -> float: ...
    @property
    def Extent(self) -> float: ...
    @property
    def FirstTextSourceIndex(self) -> int: ...
    @property
    def HasCollapsed(self) -> bool: ...
    @property
    def HasOverflowed(self) -> bool: ...
    @property
    def Height(self) -> float: ...
    @property
    def Length(self) -> int: ...
    @property
    def NewLineLength(self) -> int: ...
    @property
    def OverhangAfter(self) -> float: ...
    @property
    def OverhangLeading(self) -> float: ...
    @property
    def OverhangTrailing(self) -> float: ...
    @property
    def Start(self) -> float: ...
    @property
    def TextLineBreak(self) -> TextLineBreak: ...
    @property
    def TextRuns(self) -> IReadOnlyList_1[TextRun]: ...
    @property
    def TrailingWhitespaceLength(self) -> int: ...
    @property
    def Width(self) -> float: ...
    @property
    def WidthIncludingTrailingWhitespace(self) -> float: ...
    @abc.abstractmethod
    def Collapse(self, collapsingPropertiesList: Array_1[TextCollapsingProperties]) -> TextLine: ...
    @abc.abstractmethod
    def Dispose(self) -> None: ...
    @abc.abstractmethod
    def Draw(self, drawingContext: DrawingContext, lineOrigin: Point) -> None: ...
    @abc.abstractmethod
    def GetBackspaceCaretCharacterHit(self, characterHit: CharacterHit) -> CharacterHit: ...
    @abc.abstractmethod
    def GetCharacterHitFromDistance(self, distance: float) -> CharacterHit: ...
    @abc.abstractmethod
    def GetDistanceFromCharacterHit(self, characterHit: CharacterHit) -> float: ...
    @abc.abstractmethod
    def GetNextCaretCharacterHit(self, characterHit: CharacterHit) -> CharacterHit: ...
    @abc.abstractmethod
    def GetPreviousCaretCharacterHit(self, characterHit: CharacterHit) -> CharacterHit: ...
    @abc.abstractmethod
    def GetTextBounds(self, firstTextSourceCharacterIndex: int, textLength: int) -> IReadOnlyList_1[TextBounds]: ...
    @abc.abstractmethod
    def Justify(self, justificationProperties: JustificationProperties) -> None: ...


class TextLineBreak:
    def __init__(self, textEndOfLine: TextEndOfLine = ..., flowDirection: FlowDirection = ..., isSplit: bool = ...) -> None: ...
    @property
    def FlowDirection(self) -> FlowDirection: ...
    @property
    def IsSplit(self) -> bool: ...
    @property
    def TextEndOfLine(self) -> TextEndOfLine: ...


class TextRun(abc.ABC):
    DefaultTextSourceLength : int
    @property
    def Length(self) -> int: ...
    @property
    def Properties(self) -> TextRunProperties: ...
    @property
    def Text(self) -> ReadOnlyMemory_1[str]: ...


class TextRunBounds(IEquatable_1[TextRunBounds]):
    @property
    def Length(self) -> int: ...
    @property
    def Rectangle(self) -> Rect: ...
    @property
    def TextRun(self) -> TextRun: ...
    @property
    def TextSourceCharacterIndex(self) -> int: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: TextRunBounds, right: TextRunBounds) -> bool: ...
    def __ne__(self, left: TextRunBounds, right: TextRunBounds) -> bool: ...
    def ToString(self) -> str: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: TextRunBounds) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...



class TextRunProperties(IEquatable_1[TextRunProperties], abc.ABC):
    @property
    def BackgroundBrush(self) -> IBrush: ...
    @property
    def BaselineAlignment(self) -> BaselineAlignment: ...
    @property
    def CultureInfo(self) -> CultureInfo: ...
    @property
    def FontFeatures(self) -> FontFeatureCollection: ...
    @property
    def FontRenderingEmSize(self) -> float: ...
    @property
    def ForegroundBrush(self) -> IBrush: ...
    @property
    def TextDecorations(self) -> TextDecorationCollection: ...
    @property
    def Typeface(self) -> Typeface: ...
    def GetHashCode(self) -> int: ...
    def __eq__(self, left: TextRunProperties, right: TextRunProperties) -> bool: ...
    def __ne__(self, left: TextRunProperties, right: TextRunProperties) -> bool: ...
    # Skipped Equals due to it being static, abstract and generic.

    Equals : Equals_MethodGroup
    class Equals_MethodGroup:
        @typing.overload
        def __call__(self, other: TextRunProperties) -> bool:...
        @typing.overload
        def __call__(self, obj: typing.Any) -> bool:...


