import typing, abc
from Avalonia import StyledElement, AvaloniaObject, AvaloniaProperty
from Avalonia.Styling import ThemeVariant, Styles, ControlTheme
from Avalonia.Controls import Classes, IResourceDictionary
from Avalonia.Animation import Transitions
from Avalonia.Data import IndexerDescriptor, IBinding
from System.Collections.Generic import IReadOnlyCollection_1, IEnumerator_1
from Avalonia.Input import IInputElement

class GestureRecognizer(StyledElement, abc.ABC):
    @property
    def ActualThemeVariant(self) -> ThemeVariant: ...
    @property
    def Classes(self) -> Classes: ...
    @property
    def DataContext(self) -> typing.Any: ...
    @DataContext.setter
    def DataContext(self, value: typing.Any) -> typing.Any: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def Parent(self) -> StyledElement: ...
    @property
    def Resources(self) -> IResourceDictionary: ...
    @Resources.setter
    def Resources(self, value: IResourceDictionary) -> IResourceDictionary: ...
    @property
    def StyleKey(self) -> typing.Type[typing.Any]: ...
    @property
    def Styles(self) -> Styles: ...
    @property
    def TemplatedParent(self) -> AvaloniaObject: ...
    @TemplatedParent.setter
    def TemplatedParent(self, value: AvaloniaObject) -> AvaloniaObject: ...
    @property
    def Theme(self) -> ControlTheme: ...
    @Theme.setter
    def Theme(self, value: ControlTheme) -> ControlTheme: ...
    @property
    def Transitions(self) -> Transitions: ...
    @Transitions.setter
    def Transitions(self, value: Transitions) -> Transitions: ...
    def __getitem__(self, property: AvaloniaProperty) -> typing.Any: ...
    def __setitem__(self, property: AvaloniaProperty, value: typing.Any) -> None: ...
    def __getitem__(self, binding: IndexerDescriptor) -> IBinding: ...
    def __setitem__(self, binding: IndexerDescriptor, value: IBinding) -> None: ...


class GestureRecognizerCollection(IReadOnlyCollection_1[GestureRecognizer]):
    def __init__(self, inputElement: IInputElement) -> None: ...
    @property
    def Count(self) -> int: ...
    def Add(self, recognizer: GestureRecognizer) -> None: ...
    def GetEnumerator(self) -> IEnumerator_1[GestureRecognizer]: ...

