import typing, abc
from System.Collections.Generic import IReadOnlyList_1, IAsyncEnumerable_1
from System.Threading.Tasks import Task_1, Task
from System import Uri, IDisposable, DateTimeOffset
from System.IO import Stream

class FilePickerFileType:
    def __init__(self, name: str) -> None: ...
    @property
    def AppleUniformTypeIdentifiers(self) -> IReadOnlyList_1[str]: ...
    @AppleUniformTypeIdentifiers.setter
    def AppleUniformTypeIdentifiers(self, value: IReadOnlyList_1[str]) -> IReadOnlyList_1[str]: ...
    @property
    def MimeTypes(self) -> IReadOnlyList_1[str]: ...
    @MimeTypes.setter
    def MimeTypes(self, value: IReadOnlyList_1[str]) -> IReadOnlyList_1[str]: ...
    @property
    def Name(self) -> str: ...
    @property
    def Patterns(self) -> IReadOnlyList_1[str]: ...
    @Patterns.setter
    def Patterns(self, value: IReadOnlyList_1[str]) -> IReadOnlyList_1[str]: ...


class FilePickerOpenOptions(PickerOptions):
    def __init__(self) -> None: ...
    @property
    def AllowMultiple(self) -> bool: ...
    @AllowMultiple.setter
    def AllowMultiple(self, value: bool) -> bool: ...
    @property
    def FileTypeFilter(self) -> IReadOnlyList_1[FilePickerFileType]: ...
    @FileTypeFilter.setter
    def FileTypeFilter(self, value: IReadOnlyList_1[FilePickerFileType]) -> IReadOnlyList_1[FilePickerFileType]: ...
    @property
    def SuggestedFileName(self) -> str: ...
    @SuggestedFileName.setter
    def SuggestedFileName(self, value: str) -> str: ...
    @property
    def SuggestedStartLocation(self) -> IStorageFolder: ...
    @SuggestedStartLocation.setter
    def SuggestedStartLocation(self, value: IStorageFolder) -> IStorageFolder: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...


class FilePickerSaveOptions(PickerOptions):
    def __init__(self) -> None: ...
    @property
    def DefaultExtension(self) -> str: ...
    @DefaultExtension.setter
    def DefaultExtension(self, value: str) -> str: ...
    @property
    def FileTypeChoices(self) -> IReadOnlyList_1[FilePickerFileType]: ...
    @FileTypeChoices.setter
    def FileTypeChoices(self, value: IReadOnlyList_1[FilePickerFileType]) -> IReadOnlyList_1[FilePickerFileType]: ...
    @property
    def ShowOverwritePrompt(self) -> typing.Optional[bool]: ...
    @ShowOverwritePrompt.setter
    def ShowOverwritePrompt(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def SuggestedFileName(self) -> str: ...
    @SuggestedFileName.setter
    def SuggestedFileName(self, value: str) -> str: ...
    @property
    def SuggestedStartLocation(self) -> IStorageFolder: ...
    @SuggestedStartLocation.setter
    def SuggestedStartLocation(self, value: IStorageFolder) -> IStorageFolder: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...


class FolderPickerOpenOptions(PickerOptions):
    def __init__(self) -> None: ...
    @property
    def AllowMultiple(self) -> bool: ...
    @AllowMultiple.setter
    def AllowMultiple(self, value: bool) -> bool: ...
    @property
    def SuggestedFileName(self) -> str: ...
    @SuggestedFileName.setter
    def SuggestedFileName(self, value: str) -> str: ...
    @property
    def SuggestedStartLocation(self) -> IStorageFolder: ...
    @SuggestedStartLocation.setter
    def SuggestedStartLocation(self, value: IStorageFolder) -> IStorageFolder: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...


class ILauncher(typing.Protocol):
    @abc.abstractmethod
    def LaunchFileAsync(self, storageItem: IStorageItem) -> Task_1[bool]: ...
    @abc.abstractmethod
    def LaunchUriAsync(self, uri: Uri) -> Task_1[bool]: ...


class IStorageBookmarkFile(IStorageBookmarkItem, IStorageFile, typing.Protocol):
    pass


class IStorageBookmarkFolder(IStorageBookmarkItem, IStorageFolder, typing.Protocol):
    pass


class IStorageBookmarkItem(IStorageItem, typing.Protocol):
    @abc.abstractmethod
    def ReleaseBookmarkAsync(self) -> Task: ...


class IStorageFile(IStorageItem, typing.Protocol):
    @abc.abstractmethod
    def OpenReadAsync(self) -> Task_1[Stream]: ...
    @abc.abstractmethod
    def OpenWriteAsync(self) -> Task_1[Stream]: ...


class IStorageFolder(IStorageItem, typing.Protocol):
    @abc.abstractmethod
    def CreateFileAsync(self, name: str) -> Task_1[IStorageFile]: ...
    @abc.abstractmethod
    def CreateFolderAsync(self, name: str) -> Task_1[IStorageFolder]: ...
    @abc.abstractmethod
    def GetItemsAsync(self) -> IAsyncEnumerable_1[IStorageItem]: ...


class IStorageItem(IDisposable, typing.Protocol):
    @property
    def CanBookmark(self) -> bool: ...
    @property
    def Name(self) -> str: ...
    @property
    def Path(self) -> Uri: ...
    @abc.abstractmethod
    def DeleteAsync(self) -> Task: ...
    @abc.abstractmethod
    def GetBasicPropertiesAsync(self) -> Task_1[StorageItemProperties]: ...
    @abc.abstractmethod
    def GetParentAsync(self) -> Task_1[IStorageFolder]: ...
    @abc.abstractmethod
    def MoveAsync(self, destination: IStorageFolder) -> Task_1[IStorageItem]: ...
    @abc.abstractmethod
    def SaveBookmarkAsync(self) -> Task_1[str]: ...


class IStorageProvider(typing.Protocol):
    @property
    def CanOpen(self) -> bool: ...
    @property
    def CanPickFolder(self) -> bool: ...
    @property
    def CanSave(self) -> bool: ...
    @abc.abstractmethod
    def OpenFileBookmarkAsync(self, bookmark: str) -> Task_1[IStorageBookmarkFile]: ...
    @abc.abstractmethod
    def OpenFilePickerAsync(self, options: FilePickerOpenOptions) -> Task_1[IReadOnlyList_1[IStorageFile]]: ...
    @abc.abstractmethod
    def OpenFolderBookmarkAsync(self, bookmark: str) -> Task_1[IStorageBookmarkFolder]: ...
    @abc.abstractmethod
    def OpenFolderPickerAsync(self, options: FolderPickerOpenOptions) -> Task_1[IReadOnlyList_1[IStorageFolder]]: ...
    @abc.abstractmethod
    def SaveFilePickerAsync(self, options: FilePickerSaveOptions) -> Task_1[IStorageFile]: ...
    @abc.abstractmethod
    def TryGetFileFromPathAsync(self, filePath: Uri) -> Task_1[IStorageFile]: ...
    @abc.abstractmethod
    def TryGetFolderFromPathAsync(self, folderPath: Uri) -> Task_1[IStorageFolder]: ...
    @abc.abstractmethod
    def TryGetWellKnownFolderAsync(self, wellKnownFolder: WellKnownFolder) -> Task_1[IStorageFolder]: ...


class PickerOptions:
    def __init__(self) -> None: ...
    @property
    def SuggestedFileName(self) -> str: ...
    @SuggestedFileName.setter
    def SuggestedFileName(self, value: str) -> str: ...
    @property
    def SuggestedStartLocation(self) -> IStorageFolder: ...
    @SuggestedStartLocation.setter
    def SuggestedStartLocation(self, value: IStorageFolder) -> IStorageFolder: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> str: ...


class StorageItemProperties:
    def __init__(self, size: typing.Optional[int] = ..., dateCreated: typing.Optional[DateTimeOffset] = ..., dateModified: typing.Optional[DateTimeOffset] = ...) -> None: ...
    @property
    def DateCreated(self) -> typing.Optional[DateTimeOffset]: ...
    @property
    def DateModified(self) -> typing.Optional[DateTimeOffset]: ...
    @property
    def Size(self) -> typing.Optional[int]: ...


class WellKnownFolder(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Desktop : WellKnownFolder # 0
    Documents : WellKnownFolder # 1
    Downloads : WellKnownFolder # 2
    Music : WellKnownFolder # 3
    Pictures : WellKnownFolder # 4
    Videos : WellKnownFolder # 5

