from JAStudio.Core.LanguageServices.JanomeEx.WordExtraction.Matches.Requirements import CustomForbidsNoCache, VocabMatchInspector

class ForbidsHasDisplayedOverlappingFollowingCompound(CustomForbidsNoCache):
    @property
    def Description(self) -> str: ...
    @property
    def FailureReason(self) -> str: ...
    @property
    def IsFulfilled(self) -> bool: ...
    @property
    def IsInState(self) -> bool: ...
    @staticmethod
    def ApplyTo(inspector: VocabMatchInspector) -> ForbidsHasDisplayedOverlappingFollowingCompound: ...

