import typing, abc
from JAStudio.Core.Note import IBackendNoteCreator, KanjiNote, NoteData
from System import Action, Action_1
from JAStudio.Core.Note.Sentences import SentenceNote
from JAStudio.Core.Note.Vocabulary import VocabNote
from JAStudio.UI import AnkiDialogs
from JAStudio.Core import TemporaryServiceCollection
from JAStudio.Anki import AnkiLifecycleEvent
from JAStudio.Core.Note.Collection import IExternalNoteUpdateHandler
from JAStudio.UI.Menus.UIAgnosticMenuStructure import SpecMenuItem
from JAStudio.UI.Menus import JapaneseMainMenu, NoteContextMenu

class AnkiBackendNoteCreator(IBackendNoteCreator):
    def __init__(self) -> None: ...
    def CreateKanji(self, note: KanjiNote, callback: Action) -> None: ...
    def CreateSentence(self, note: SentenceNote, callback: Action) -> None: ...
    def CreateVocab(self, note: VocabNote, callback: Action) -> None: ...


class JAStudioAnkiAppRoot:
    @property
    def Dialogs(self) -> AnkiDialogs: ...
    @property
    def IsInitialized(self) -> bool: ...
    @property
    def Menus(self) -> PythonAnkiMenus: ...
    @property
    def Services(self) -> TemporaryServiceCollection: ...
    def HandleAnkiLifecycleEvent(self, lifecycleEvent: AnkiLifecycleEvent) -> None: ...
    @staticmethod
    def Initialize(configJson: str, configUpdateCallback: Action_1[str]) -> JAStudioAnkiAppRoot: ...
    def ShutDown(self) -> None: ...


class NoteDataPythonAdapter(abc.ABC):
    @staticmethod
    def FromPython(item: typing.Any) -> NoteData: ...


class NoteUpdatePythonAdapter(abc.ABC):
    @staticmethod
    def Register(handler: IExternalNoteUpdateHandler, pythonCallback: typing.Any) -> None: ...


class PythonAnkiMenus:
    def BuildBrowserMenuSpec(self, selectedCardIds: typing.Any, selectedNoteIds: typing.Any) -> SpecMenuItem: ...
    def CreateJapaneseMainMenu(self) -> JapaneseMainMenu: ...
    def CreateNoteContextMenu(self) -> NoteContextMenu: ...
    def ShowContextMenuPopup(self, clipboardContent: str, selectionContent: str, x: int, y: int) -> None: ...

