from JAStudio.Core.LanguageServices.JanomeEx.WordExtraction.Matches.Requirements import MatchRequirement

class FailedMatchRequirement(MatchRequirement):
    @property
    def FailureReason(self) -> str: ...
    @property
    def IsFulfilled(self) -> bool: ...
    @property
    def Reason(self) -> str: ...
    @staticmethod
    def Forbids(message: str) -> FailedMatchRequirement: ...
    @staticmethod
    def Required(message: str) -> FailedMatchRequirement: ...

