"""
This type stub file was generated by pyright.
"""

import sys
import clr_loader
from pathlib import Path
from typing import Any, Dict, Optional, Union

"""Python.NET runtime loading and configuration"""
__all__ = ["set_runtime", "set_runtime_from_env", "load", "unload", "get_runtime_info"]
_RUNTIME: Optional[clr_loader.Runtime] = ...
_LOADER_ASSEMBLY: Optional[clr_loader.Assembly] = ...
_LOADED: bool = ...
def set_runtime(runtime: Union[clr_loader.Runtime, str], **params: str) -> None:
    """Set up a clr_loader runtime without loading it

    :param runtime:
        Either an already initialised `clr_loader` runtime, or one of netfx,
        coreclr, mono, or default. If a string parameter is given, the runtime
        will be created.
    """
    ...

def get_runtime_info() -> Optional[clr_loader.RuntimeInfo]:
    """Retrieve information on the configured runtime"""
    ...

def set_runtime_from_env() -> None:
    """Set up the runtime using the environment

    This will use the environment variable PYTHONNET_RUNTIME to decide the
    runtime to use, which may be one of netfx, coreclr or mono. The parameters
    of the respective clr_loader.get_<runtime> functions can also be given as
    environment variables, named `PYTHONNET_<RUNTIME>_<PARAM_NAME>`. In
    particular, to use `PYTHONNET_RUNTIME=coreclr`, the variable
    `PYTHONNET_CORECLR_RUNTIME_CONFIG` has to be set to a valid
    `.runtimeconfig.json`.

    If no environment variable is specified, a globally installed Mono is used
    for all environments but Windows, on Windows the legacy .NET Framework is
    used.
    """
    ...

def load(runtime: Union[clr_loader.Runtime, str, None] = ..., **params: str) -> None:
    """Load Python.NET in the specified runtime

    The same parameters as for `set_runtime` can be used. By default,
    `set_default_runtime` is called if no environment has been set yet and no
    parameters are passed.

    After a successful call, further invocations will return immediately."""
    ...

def unload() -> None:
    """Explicitly unload a loaded runtime and shut down Python.NET"""
    ...

