import abc
from JAStudio.Core.LanguageServices.JanomeEx.WordExtraction.Matches import Match, VocabMatch
from JAStudio.Core.Note.Sentences import SentenceConfiguration
from JAStudio.Core.LanguageServices.JanomeEx.WordExtraction import TextAnalysisLocation, CandidateWordVariant, CandidateWord
from JAStudio.Core.Note.Vocabulary import VocabMatchingRulesConfigurationRequiresForbidsFlags

class CustomForbidsNoCache(MatchRequirement):
    @property
    def Description(self) -> str: ...
    @property
    def FailureReason(self) -> str: ...
    @property
    def IsFulfilled(self) -> bool: ...
    @property
    def IsInState(self) -> bool: ...


class MatchInspector:
    def __init__(self, match: Match) -> None: ...
    @property
    def CompoundLocationsAllHaveValidNonCompoundMatches(self) -> bool: ...
    @property
    def Configuration(self) -> SentenceConfiguration: ...
    @property
    def EndLocation(self) -> TextAnalysisLocation: ...
    @property
    def HasGodanImperativePart(self) -> bool: ...
    @property
    def HasGodanPotentialEnding(self) -> bool: ...
    @property
    def HasGodanPotentialStart(self) -> bool: ...
    @property
    def HasMasuStem(self) -> bool: ...
    @property
    def HasPrecedingAdverb(self) -> bool: ...
    @property
    def HasTeFormPrefix(self) -> bool: ...
    @property
    def HasTeFormStem(self) -> bool: ...
    @property
    def IsBase(self) -> bool: ...
    @property
    def IsCompoundEndingOnDictionaryFormWhereSurfaceDiffersFromBase(self) -> bool: ...
    @property
    def IsEndOfStatement(self) -> bool: ...
    @property
    def IsIchidanCoveringGodanPotential(self) -> bool: ...
    @property
    def IsVerbDictionaryFormCompound(self) -> bool: ...
    @property
    def Match(self) -> Match: ...
    @property
    def NextLocation(self) -> TextAnalysisLocation: ...
    @property
    def Prefix(self) -> str: ...
    @property
    def PreviousLocation(self) -> TextAnalysisLocation: ...
    @property
    def StartLocation(self) -> TextAnalysisLocation: ...
    @property
    def StartLocationIsDictionaryVerbInflection(self) -> bool: ...
    @property
    def Suffix(self) -> str: ...
    @property
    def SurfaceVariant(self) -> CandidateWordVariant: ...
    @property
    def Variant(self) -> CandidateWordVariant: ...
    @property
    def Word(self) -> CandidateWord: ...


class MatchRequirement(abc.ABC):
    @property
    def FailureReason(self) -> str: ...
    @property
    def IsFulfilled(self) -> bool: ...
    def ToString(self) -> str: ...


class VocabMatchInspector(MatchInspector):
    def __init__(self, match: VocabMatch) -> None: ...
    @property
    def BaseEqualsSurface(self) -> bool: ...
    @property
    def CompoundLocationsAllHaveValidNonCompoundMatches(self) -> bool: ...
    @property
    def Configuration(self) -> SentenceConfiguration: ...
    @property
    def EndLocation(self) -> TextAnalysisLocation: ...
    @property
    def HasGodanImperativePart(self) -> bool: ...
    @property
    def HasGodanPotentialEnding(self) -> bool: ...
    @property
    def HasGodanPotentialStart(self) -> bool: ...
    @property
    def HasMasuStem(self) -> bool: ...
    @property
    def HasPrecedingAdverb(self) -> bool: ...
    @property
    def HasTeFormPrefix(self) -> bool: ...
    @property
    def HasTeFormStem(self) -> bool: ...
    @property
    def IsBase(self) -> bool: ...
    @property
    def IsCompoundEndingOnDictionaryFormWhereSurfaceDiffersFromBase(self) -> bool: ...
    @property
    def IsEndOfStatement(self) -> bool: ...
    @property
    def IsIchidanCoveringGodanPotential(self) -> bool: ...
    @property
    def IsVerbDictionaryFormCompound(self) -> bool: ...
    @property
    def Match(self) -> VocabMatch: ...
    @property
    def Match(self) -> Match: ...
    @property
    def NextLocation(self) -> TextAnalysisLocation: ...
    @property
    def Prefix(self) -> str: ...
    @property
    def PreviousLocation(self) -> TextAnalysisLocation: ...
    @property
    def PreviousLocationIsGodan(self) -> bool: ...
    @property
    def PreviousLocationIsIchidan(self) -> bool: ...
    @property
    def PreviousLocationIsIrrealis(self) -> bool: ...
    @property
    def RequiresForbids(self) -> VocabMatchingRulesConfigurationRequiresForbidsFlags: ...
    @property
    def StartLocation(self) -> TextAnalysisLocation: ...
    @property
    def StartLocationIsDictionaryVerbInflection(self) -> bool: ...
    @property
    def Suffix(self) -> str: ...
    @property
    def SurfaceVariant(self) -> CandidateWordVariant: ...
    @property
    def Variant(self) -> CandidateWordVariant: ...
    @property
    def Word(self) -> CandidateWord: ...

