from JAStudio.Core.Note.Sentences import ParsedMatch, ParsingResult, SentenceConfiguration
from JAStudio.Core.Note.NoteFields import IObjectSerializer_1
from System import Action

class ParsedWordSerializer:
    def __init__(self) -> None: ...
    @staticmethod
    def FromRow(serialized: str) -> ParsedMatch: ...
    @staticmethod
    def ToRow(parsedWord: ParsedMatch) -> str: ...


class ParsingResultSerializer(IObjectSerializer_1[ParsingResult]):
    def __init__(self) -> None: ...
    def Deserialize(self, serialized: str) -> ParsingResult: ...
    def Serialize(self, instance: ParsingResult) -> str: ...


class SentenceConfigurationSerializer:
    @classmethod
    @property
    def Instance(cls) -> SentenceConfigurationSerializer: ...
    def Deserialize(self, json: str, saveCallback: Action) -> SentenceConfiguration: ...
    def Serialize(self, config: SentenceConfiguration) -> str: ...

