from JAStudio.Core.Note.Sentences import ParsedMatch, SentenceConfiguration
from System import Action

class ParsedWordSerializer:
    def __init__(self) -> None: ...
    @staticmethod
    def FromRow(serialized: str) -> ParsedMatch: ...
    @staticmethod
    def ToRow(parsedWord: ParsedMatch) -> str: ...


class SentenceConfigurationSerializer:
    @classmethod
    @property
    def Instance(cls) -> SentenceConfigurationSerializer: ...
    def Deserialize(self, json: str, saveCallback: Action) -> SentenceConfiguration: ...
    def Serialize(self, config: SentenceConfiguration) -> str: ...

